### PR TITLE
fix(components): [carousel] special case `activeIndex` is inaccurate

### LINKED ISSUE #21735: [Component] [carousel] For two carouselItems, activeIndex should not be the subscript of the additional carouselItem
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.18`
- Element Plus Version: `2.10.7`
- Browser / OS: `*`
- Build Tool: `Vite`

### Related Component

- `el-carousel`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiYmxvY2sgdGV4dC1jZW50ZXJcIj5cbiAgICA8ZWwtY2Fyb3VzZWwgcmVmPVwiY2Fyb3VzZWxSZWZcIiA6YXV0b3BsYXk9XCJmYWxzZVwiIGhlaWdodD1cIjE1MHB4XCI+XG4gICAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gMlwiIDprZXk9XCJpdGVtXCI+XG4gICAgICAgIDxoMyBjbGFzcz1cInNtYWxsIGp1c3RpZnktY2VudGVyXCIgdGV4dD1cIjJ4bFwiPnt7IGl0ZW0gfX08L2gzPlxuICAgICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICAgIDwvZWwtY2Fyb3VzZWw+XG4gICAge3sgY2Fyb3VzZWxBY3RpdmVJbmRleCB9fVxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlZiwgY29tcHV0ZWR9IGZyb20gJ3Z1ZSdcblxuY29uc3QgY2Fyb3VzZWxSZWYgPSByZWYoJycpXG5cbmNvbnN0IGNhcm91c2VsQWN0aXZlSW5kZXggPSBjb21wdXRlZCgoKSA9PiB7XG4gIHJldHVybiBjYXJvdXNlbFJlZi52YWx1ZT8uYWN0aXZlSW5kZXggfHwgMFxufSlcblxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtb25zdHJhdGlvbiB7XG4gIGNvbG9yOiB2YXIoLS1lbC10ZXh0LWNvbG9yLXNlY29uZGFyeSk7XG59XG5cbi5lbC1jYXJvdXNlbF9faXRlbSBoMyB7XG4gIGNvbG9yOiAjNDc1NjY5O1xuICBvcGFjaXR5OiAwLjc1O1xuICBsaW5lLWhlaWdodDogMTUwcHg7XG4gIG1hcmdpbjogMDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xufVxuXG4uZWwtY2Fyb3VzZWxfX2l0ZW06bnRoLWNoaWxkKDJuKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICM5OWE5YmY7XG59XG5cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4gKyAxKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNkM2RjZTY7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC43L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTAuNy90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjUuMTgvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQDMuNS4xOC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC43L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC43L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InZ1ZVZlcnNpb24iOiIzLjUuMTgiLCJlcFZlcnNpb24iOiIyLjEwLjcifX0=)

### Steps to reproduce

Click the Next button twice in a row

### What is Expected?

The first time you click on the next picture, the activeIndex is normally 1. The second time you click on the next picture, the activeIndex should return to 0 according to user usage.

### What is actually happening?

Because when the length of carouselItem is 2, two additional carouselItem elements are added inside the carousel, causing activeIndex exception

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by jevin98**
Please make sure these boxes are checked before submitting your PR, thank you!
fix https://github.com/element-plus/element-plus/issues/21735

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
This will cause the smooth transition effect to be lost when clicking the right button all the way.

**Comment by btea** [comment]
https://github.com/element-plus/element-plus/blob/25c7ea2b3c54415862e56de3f4f3e467ad3a340c/packages/components/carousel/src/carousel.vue#L178

I think we should make some changes here..
```ts
const _activeIndex  = computed({
  get() {
    if (isTwoLengthShow.value) {
      return activeIndex.value % 2
    }
    return activeIndex.value
  },
  set(val) {
    activeIndex.value = val
  }
})
...
activeIndex: _activeIndex,
```

**Comment by jevin98** [comment]
@btea Thanks for your suggestion. done

File: packages/components/carousel/src/use-carousel.ts [hunk 1]
```diff
@@ -255,6 +255,14 @@ export const useCarousel = (
       }
     }
   )
+
+  const exposeActiveIndex = computed(() => {
+    if (isItemsTwoLength.value) {
+      return activeIndex.value % 2
+    }
+    return activeIndex.value
+  })
```
Comment (btea) [inline packages/components/carousel/src/use-carousel.ts]:
```suggestion
  const exposeActiveIndex = computed({
    get: () => {
      if (isItemsTwoLength.value) {
        return activeIndex.value % 2
      }
      return activeIndex.value
    },
    set: (value) => {
      activeIndex.value = value
    }
  })
```
The current activeIndex seems to support assignment, so we should keep the behavior consistent.

**Comment by jevin98** [comment]
@btea done.  Sorry, forgot to expose external may change

**Review by btea — APPROVED** [review]
Thanks!

**Review by warmthsea — APPROVED** [review]
LGTM, Thanks!
