### PR TITLE
fix(components): [el-input-number] model:value not required

### LINKED ISSUE #3047: [bug report] parameter type warning occurs when the model value of El input number component is undefined
### Element Plus version
1.1.0-beta.4

### OS/Browsers version
chrome 92.0.4515.159

### Vue version
3.2.6

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-ub1gk?file=/src/App.vue

### Steps to reproduce
1. <el-input-number v-model="num"></el-input-number>
2. 当 num 的值是 undefined 是，控制台出现警告

### What is Expected?
el-input-number 组件 model-value 的值允许为 undefined

### What is actually happening?
el-input-number 组件 model-value 的值允许为 undefined 时，会出现警告

### PR DESCRIPTION
**Pull request by msidolphin**
fix #3047

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by adaex — APPROVED** [review]

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
You might get the same effect by making `required` equal to `false`.

File: packages/components/input-number/src/index.vue [hunk 1]
```diff
@@ -102,7 +102,9 @@ export default defineComponent({
     },
     modelValue: {
       required: true,
```
Comment (sxzz) [inline packages/components/input-number/src/index.vue]:
```
required: false,
```

**Comment by msidolphin** [comment]
LGTM

> You might get the same effect by making `required` equal to `false`.

done

**Review by sxzz — APPROVED** [review]
