### PR TITLE
fix(components): [tree-v2] update expanded state when defaultExpandedKeys change

### LINKED ISSUE #23546: [Component] [tree-v2] tree-v2 设置 defaultExpandedKeys 后节点展开但是图标还是收起的状态
Bug Type: **`Component`**

## Environment

- Vue Version: `3.6.0-beta.4`
- Element Plus Version: `2.13.1`
- Browser / OS: `Chrome 135.0.7049.96`
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6aGVpZ2h0PVwiMjAwXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cImRlZmF1bHRDaGVja2VkS2V5c1wiXG4gICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cImRlZmF1bHRFeHBhbmRlZEtleXNcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBnZXRLZXkgPSAocHJlZml4OiBzdHJpbmcsIGlkOiBudW1iZXIpID0+IHtcbiAgcmV0dXJuIGAke3ByZWZpeH0tJHtpZH1gXG59XG5cbmNvbnN0IGNyZWF0ZURhdGEgPSAoXG4gIG1heERlZXA6IG51bWJlcixcbiAgbWF4Q2hpbGRyZW46IG51bWJlcixcbiAgbWluTm9kZXNOdW1iZXI6IG51bWJlcixcbiAgZGVlcCA9IDEsXG4gIGtleSA9ICdub2RlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuY29uc3QgY2hlY2tlZEtleXM6IHN0cmluZ1tdID0gW11cbmNvbnN0IGV4cGFuZWRLZXlzOiBzdHJpbmdbXSA9IFtdXG5mb3IgKGNvbnN0IGRhdHVtIG9mIGRhdGEpIHtcbiAgY29uc3QgY2hpbGRyZW4gPSBkYXR1bS5jaGlsZHJlblxuICBpZiAoY2hpbGRyZW4pIHtcbiAgICBleHBhbmVkS2V5cy5wdXNoKGRhdHVtLmlkKVxuICAgIGNoZWNrZWRLZXlzLnB1c2goY2hpbGRyZW5bMF0uaWQpXG4gICAgYnJlYWtcbiAgfVxufVxuXG5jb25zdCBkZWZhdWx0Q2hlY2tlZEtleXMgPSByZWYoY2hlY2tlZEtleXMpXG5jb25zdCBkZWZhdWx0RXhwYW5kZWRLZXlzID0gcmVmKFtdKVxub25Nb3VudGVkKCgpID0+IHtcbiAgZGVmYXVsdEV4cGFuZGVkS2V5cy52YWx1ZSA9IGV4cGFuZWRLZXlzXG59KVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点开链接即可看到 node-1 展开了，但是 node-1 的图标还是收起的状态

### What is Expected?

node-1 图标变为展开状态

### What is actually happening?

node-1 图标仍为收起状态

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by hellomrbigshot**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #23546

## Release Notes

* **Tests**
  * Added tests validating Virtual Tree expand/collapse icon state updates when defaultExpandedKeys change dynamically.
  * Added tests ensuring parent nodes properly expand when child node keys are specified.

* **Bug Fixes**
  * Improved node collapse handling to prevent errors with missing nodes.
  * Ensured expansion state properly reapplies following tree data updates.

### CODE REVIEW

**Comment by hellomrbigshot** [comment]
Fix https://github.com/element-plus/element-plus/issues/23546

**Comment by hellomrbigshot** [comment]
@keeplearning66 I reopen a pr and add a test case.

**Review by keeplearning66 — COMMENTED** [review]
There is an issue: when `defaultExpandedKeys` is passed the key of a child node, its parent node is not expanded. [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6aGVpZ2h0PVwiMjAwXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cImRlZmF1bHRDaGVja2VkS2V5c1wiXG4gICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cImRlZmF1bHRFeHBhbmRlZEtleXNcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBnZXRLZXkgPSAocHJlZml4OiBzdHJpbmcsIGlkOiBudW1iZXIpID0+IHtcbiAgcmV0dXJuIGAke3ByZWZpeH0tJHtpZH1gXG59XG5cbmNvbnN0IGNyZWF0ZURhdGEgPSAoXG4gIG1heERlZXA6IG51bWJlcixcbiAgbWF4Q2hpbGRyZW46IG51bWJlcixcbiAgbWluTm9kZXNOdW1iZXI6IG51bWJlcixcbiAgZGVlcCA9IDEsXG4gIGtleSA9ICdub2RlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuY29uc3QgY2hlY2tlZEtleXM6IHN0cmluZ1tdID0gW11cbmNvbnN0IGV4cGFuZWRLZXlzOiBzdHJpbmdbXSA9IFtdXG5mb3IgKGNvbnN0IGRhdHVtIG9mIGRhdGEpIHtcbiAgY29uc3QgY2hpbGRyZW4gPSBkYXR1bS5jaGlsZHJlblxuICBpZiAoY2hpbGRyZW4pIHtcbiAgICBleHBhbmVkS2V5cy5wdXNoKGNoaWxkcmVuWzBdLmlkKVxuICAgIGNoZWNrZWRLZXlzLnB1c2goY2hpbGRyZW5bMF0uaWQpXG4gICAgYnJlYWtcbiAgfVxufVxuXG5jb25zdCBkZWZhdWx0Q2hlY2tlZEtleXMgPSByZWYoY2hlY2tlZEtleXMpXG5jb25zdCBkZWZhdWx0RXhwYW5kZWRLZXlzID0gcmVmKFtdKVxub25Nb3VudGVkKCgpID0+IHtcbiAgZGVmYXVsdEV4cGFuZGVkS2V5cy52YWx1ZSA9IGV4cGFuZWRLZXlzXG59KVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==)

**Comment by hellomrbigshot** [comment]
> There is an issue: when `defaultExpandedKeys` is passed the key of a child node, its parent node is not expanded. [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6aGVpZ2h0PVwiMjAwXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgc2hvdy1jaGVja2JveFxuICAgIDpkZWZhdWx0LWNoZWNrZWQta2V5cz1cImRlZmF1bHRDaGVja2VkS2V5c1wiXG4gICAgOmRlZmF1bHQtZXhwYW5kZWQta2V5cz1cImRlZmF1bHRFeHBhbmRlZEtleXNcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBnZXRLZXkgPSAocHJlZml4OiBzdHJpbmcsIGlkOiBudW1iZXIpID0+IHtcbiAgcmV0dXJuIGAke3ByZWZpeH0tJHtpZH1gXG59XG5cbmNvbnN0IGNyZWF0ZURhdGEgPSAoXG4gIG1heERlZXA6IG51bWJlcixcbiAgbWF4Q2hpbGRyZW46IG51bWJlcixcbiAgbWluTm9kZXNOdW1iZXI6IG51bWJlcixcbiAgZGVlcCA9IDEsXG4gIGtleSA9ICdub2RlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuY29uc3QgY2hlY2tlZEtleXM6IHN0cmluZ1tdID0gW11cbmNvbnN0IGV4cGFuZWRLZXlzOiBzdHJpbmdbXSA9IFtdXG5mb3IgKGNvbnN0IGRhdHVtIG9mIGRhdGEpIHtcbiAgY29uc3QgY2hpbGRyZW4gPSBkYXR1bS5jaGlsZHJlblxuICBpZiAoY2hpbGRyZW4pIHtcbiAgICBleHBhbmVkS2V5cy5wdXNoKGNoaWxkcmVuWzBdLmlkKVxuICAgIGNoZWNrZWRLZXlzLnB1c2goY2hpbGRyZW5bMF0uaWQpXG4gICAgYnJlYWtcbiAgfVxufVxuXG5jb25zdCBkZWZhdWx0Q2hlY2tlZEtleXMgPSByZWYoY2hlY2tlZEtleXMpXG5jb25zdCBkZWZhdWx0RXhwYW5kZWRLZXlzID0gcmVmKFtdKVxub25Nb3VudGVkKCgpID0+IHtcbiAgZGVmYXVsdEV4cGFuZGVkS2V5cy52YWx1ZSA9IGV4cGFuZWRLZXlzXG59KVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjM1NTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==)

Yeah! I will open another PR to fix it

**Comment by patienry** [comment]
> Yeah! I will open another PR to fix it

You can continue to submit your changes in the current PR. 😃 @hellomrbigshot

**Comment by hellomrbigshot** [comment]
> > Yeah! I will open another PR to fix it
> 
> You can continue to submit your changes in the current PR. 😃 @hellomrbigshot

The issue has been resolved for now.

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 1]
```diff
@@ -313,14 +316,22 @@ export function useTree(
...
     },
     {
       immediate: true,
     }
   )
 
+  function isExpanded(node: TreeNode) {
+    return expandedKeySet.value.has(node.key)
+  }
+
```
Comment (patienry) [inline packages/components/tree-v2/src/composables/useTree.ts]: We can first ensure the minimum changes. The `setExpandedKeys` method will set the node's `expanded` state, so the newly added `isExpanded` method is not necessary.

File: packages/components/tree-v2/__tests__/tree.test.ts [hunk 2]
```diff
@@ -864,6 +864,86 @@ describe('Virtual Tree', () => {
...
+              id: '2',
+              label: 'node-2',
+            },
+          ],
+          defaultExpandedKeys,
+        }
+      },
+    })
+    await nextTick()
+    // Collapsed by default; the expand icon of the first node should not have the expanded class
```
Comment (patienry) [inline packages/components/tree-v2/__tests__/tree.test.ts]: The meaning expressed by the code in the two new test cases is very clear, so these comments can be removed.

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 3]
```diff
@@ -283,6 +282,10 @@ export function useTree(
 
   function setData(data: TreeData) {
     tree.value = createTree(data)
+    // When the defaultExpandedKeys array includes a child node, all ancestor nodes of that child shall be expanded automatically
+    if (props.defaultExpandedKeys?.length) {
+      setExpandedKeys(props.defaultExpandedKeys)
+    }
```
Comment (patienry) [inline packages/components/tree-v2/src/composables/useTree.ts]: Are there other ways to avoid adding logic here? 🤔

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 4]
```diff
@@ -313,8 +312,12 @@ export function useTree(
...
   watch(
     () => props.defaultExpandedKeys,
-    (key) => {
-      expandedKeySet.value = new Set<TreeKey>(key)
+    (keys) => {
+      if (tree.value) {
+        setExpandedKeys(keys || [])
+      } else {
+        expandedKeySet.value = new Set<TreeKey>(keys || [])
+      }
```
Comment (patienry) [inline packages/components/tree-v2/src/composables/useTree.ts]: This `else` branch seems unnecessary. 🤔

**Review by keeplearning66 — APPROVED** [review]
Thank you!

**Review by keeplearning66 — CHANGES_REQUESTED** [review]
I feel that we can move the `watch` for `props.data` before the `watch` for `props.defaultExpandedKeys`, so that no additional logic is needed in the `watch` for `props.data`. WDYT? 🤔

**Comment by patienry** [comment]
> I feel that we can move the `watch` for `props.data` before the `watch` for `props.defaultExpandedKeys`, so that no additional logic is needed in the `watch` for `props.data`. WDYT? 🤔

I thought about it again. In certain cases, `expanded` state of the node still needs to be updated after `data` changes.

**Review by keeplearning66 — APPROVED** [review]
Thank you!

**Review by btea — APPROVED** [review]

**Comment by hepengju** [comment]
PixPin_2026-03-27_17-23-10
当我使用2.13.5时，树形节点新增一个键，当前打开的节点还是保持打开状态（满足需求）。但升级2.13.6后（似乎是因为这个升级），添加一个子节点后，所有展开的节点都自动闭合了。
