### PR TITLE
fix(components): [input] fix formatter and parse problem

### LINKED ISSUE #12613: [Component] [input] input格式化
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Chrome/109.0.0.0`
- Build Tool: `Vue CLI`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICBAY2hhbmdlPVwiYWFcIlxuICAgIHYtbW9kZWw9XCJpbnB1dFwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAgIDpmb3JtYXR0ZXI9XCIodmFsdWUpID0+IGAkICR7dmFsdWV9YC5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCAnLCcpXCJcbiAgICA6cGFyc2VyPVwiKHZhbHVlKSA9PiBjaGFuZ2VGb3JtbWF0ZXIodmFsdWUpXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJylcbmZ1bmN0aW9uIGFhKHZhbCl7XG4gIFx0Y29uc29sZS5sb2codmFsLGlucHV0LnZhbHVlKVxufVxuICBmdW5jdGlvbiBjaGFuZ2VGb3JtbWF0ZXIodmFsdWUpe1xuICAgIGNvbnNvbGUubG9nKCdwYXJzZTonLHZhbHVlLnJlcGxhY2UoL1xcJFxccz98KCwqKS9nLCAnJykpXG4gICAgcmV0dXJuIHZhbHVlLnJlcGxhY2UoL1xcJFxccz98KCwqKS9nLCAnJylcbiAgfVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1

### What is Expected?

2

### What is actually happening?

3

### Additional comments

input框格式化用formmater加千分位   parse解析后v-model绑定的值实际还是加,的  所以parse有什么用呢

### PR DESCRIPTION
**Pull request by wzc520pyfm**
closed #12613

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by wzc520pyfm** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICBAY2hhbmdlPVwiYWFcIlxuICAgIHYtbW9kZWw9XCJpbnB1dFwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIlxuICAgIDpmb3JtYXR0ZXI9XCIodmFsdWUpID0+IGAkICR7dmFsdWV9YC5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCAnLCcpXCJcbiAgICA6cGFyc2VyPVwiKHZhbHVlKSA9PiBjaGFuZ2VGb3JtbWF0ZXIodmFsdWUpXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnB1dCA9IHJlZignJylcbmZ1bmN0aW9uIGFhKHZhbCl7XG4gIFx0Y29uc29sZS5sb2codmFsLGlucHV0LnZhbHVlKVxufVxuICBmdW5jdGlvbiBjaGFuZ2VGb3JtbWF0ZXIodmFsdWUpe1xuICAgIGNvbnNvbGUubG9nKCdwYXJzZTonLHZhbHVlLnJlcGxhY2UoL1xcJFxccz98KCwqKS9nLCAnJykpXG4gICAgcmV0dXJuIHZhbHVlLnJlcGxhY2UoL1xcJFxccz98KCwqKS9nLCAnJylcbiAgfVxuPC9zY3JpcHQ+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTI2MjItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMjYyMi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMjYyMi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMjYyMi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

As I understand it, this PR solves #12613.
The `formatter` formats the input value and parses the input value to the moduleValue using `parse`

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -371,18 +371,22 @@ const onceInitSizeTextarea = createOnceInitResize(resizeTextarea)
...
 const handleInput = async (event: Event) => {
   recordCursor()
 
   let { value } = event.target as TargetElement
 
+  const parseValue = props.parser ? props.parser(value) : value
+
   if (props.formatter) {
-    value = props.parser ? props.parser(value) : value
-    value = props.formatter(value)
```
Comment (chenxch) [inline packages/components/input/src/input.vue:385]: Regarding handleInput, I think that as long as this line of code is deleted, the values returned by the two emit events should be the same.

Comment (chenxch) [reply packages/components/input/src/input.vue:385]: It should be to restore this handleInput, and then delete `value = props.parser ? props.parser(value) : value`.
Your current existence should be a problem, because the precondition of the parser is formatter, and you have done the processing of the parser first.

**Comment by chenxch** [comment]
Problem solved by just deleting one line of code. . .

**Comment by wzc520pyfm** [comment]
sorry, I just saw your latest message. I'm finishing the changes.

**Comment by chenxch** [comment]
```diff
const handleInput = async (event: Event) => {
  recordCursor()
  let { value } = event.target as TargetElement
  if (props.formatter) {
    value = props.parser ? props.parser(value) : value
-    value = props.formatter(value)
  }
  // should not emit input during composition
  // see: https://github.com/ElemeFE/element/issues/10516
  if (isComposing.value) return
  // hack for https://github.com/ElemeFE/element/issues/8548
  // should remove the following line when we don't support IE
  if (value === nativeInputValue.value) {
    setNativeInputValue()
    return
  }
  emit(UPDATE_MODEL_EVENT, value)
  emit('input', value)
  // ensure native input value is controlled
  // see: https://github.com/ElemeFE/element/issues/12850
  await nextTick()
  setNativeInputValue()
  setCursor()
}
```

File: packages/components/input/src/input.vue (hunk 1 above)
Comment (wzc520pyfm) [reply packages/components/input/src/input.vue:385]: I have finished. But failing of 'PR Docs Build / Build windows-latest LTS (pull_request)' ?

**Comment by chenxch** [comment]
> sorry, I just saw your latest message. I'm finishing the changes.

re-running

**Comment by chenxch** [comment]
There is no problem in function, would you mind adding a test case to verify the correctness of the two-way binding value after the value is entered in the input box in the formatting scenario.

**Comment by chenxch** [comment]
I provide some code that simulates the input.
```
const event = new Event('input', { bubbles: true })
vm.$el.querySelector('input').value = "1,000,000"
vm.$el.querySelector('input').dispatchEvent(event)
```

**Comment by wzc520pyfm** [comment]
@chenxch 
I have added the test case, thank you for your guidance, please review again.

**Review by chenxch — APPROVED** [review]
LGTM.  👍

**Review by tolking — APPROVED** [review]
