### PR TITLE
fix(components): [table] parent-child selection mismatch in tree data

### LINKED ISSUE #7101: [Bug Report] [Component] [table, table-column] 表格树形数据选择
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome  102.0.4987.0`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Link](http://5l8.cn/CGOZ1)

### Steps to reproduce

点击全选/反选

### What is Expected?

选择表格的所有项或反选表格所有项

### What is actually happening?

选择表格的一级项或反选表格一级项，嵌套数据children 没有选择与反选事件

### Additional comments

_(empty)_

### LINKED ISSUE #7920: [Bug Report] [Component] [table] el-table树形数据内使用type="selection"不能全选
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `版本 99.0.4844.84（正式版本）`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMTAwJTsgbWFyZ2luLWJvdHRvbTogMjBweFwiXG4gICAgICByb3cta2V5PVwiaWRcIlxuICAgICAgYm9yZGVyXG4gICAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICA+IFxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJkYXRlMVwiIHNvcnRhYmxlIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiBzb3J0YWJsZSB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPC9lbC10YWJsZT5cblxuICAgIDxlbC10YWJsZVxuICAgICAgOmRhdGE9XCJ0YWJsZURhdGExXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgIGJvcmRlclxuICAgICAgbGF6eVxuICAgICAgOmxvYWQ9XCJsb2FkXCJcbiAgICAgIDp0cmVlLXByb3BzPVwieyBjaGlsZHJlbjogJ2NoaWxkcmVuJywgaGFzQ2hpbGRyZW46ICdoYXNDaGlsZHJlbicgfVwiXG4gICAgPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IG51bWJlclxuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGhhc0NoaWxkcmVuPzogYm9vbGVhblxuICBjaGlsZHJlbj86IFVzZXJbXVxufVxuXG5jb25zdCBsb2FkID0gKFxuICByb3c6IFVzZXIsXG4gIHRyZWVOb2RlOiB1bmtub3duLFxuICByZXNvbHZlOiAoZGF0ZTogVXNlcltdKSA9PiB2b2lkXG4pID0+IHtcbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgcmVzb2x2ZShbXG4gICAgICB7XG4gICAgICAgIGlkOiAzMSxcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgfSxcbiAgICBdKVxuICB9LCAxMDAwKVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMyLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG5dXG5cbmNvbnN0IHRhYmxlRGF0YTE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

点击左上角的选中全部，children内数据没有被选中

### What is Expected?

children内数据应该被选中

### What is actually happening?

children内数据未选中

### Additional comments

_(empty)_

### LINKED ISSUE #14585: [Component] [table, table-column] el-table有展开项 el-table-column单选框当设置了selectable 子选项禁用时 父选项勾选后会把子项的禁用框也勾选上，全选也会
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.4`
- Browser / OS: `Chrome 版本 118.0.5993.71（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDEwMCU7IG1hcmdpbi1ib3R0b206IDIwcHhcIlxuICAgICAgcm93LWtleT1cImlkXCJcbiAgICAgIGJvcmRlclxuICAgICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4ga2V5PVwic2VsZWN0aW9uXCIgdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTBcIiA6c2VsZWN0YWJsZT1cInNlbGVjdGFibGVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHNvcnRhYmxlIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgc29ydGFibGUgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiBzb3J0YWJsZSAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBudW1iZXJcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhZGRyZXNzOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVXNlcltdXG59XG5jb25zdCBzZWxlY3RhYmxlPShyb3cpPT57XG5pZihyb3cuZGF0ZT09PScyMDE2LTA1LTAxJyl7cmV0dXJuIGZhbHNlfWVsc2V7cmV0dXJuIHRydWV9XG59XG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiAzMixcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cblxuXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

<template>
  <div>
    <el-table
      :data="tableData"
      style="width: 100%; margin-bottom: 20px"
      row-key="id"
      border
      default-expand-all
    >
    <el-table-column key="selection" type="selection" width="50" :selectable="selectable" />
      <el-table-column prop="date" label="Date" sortable />
      <el-table-column prop="name" label="Name" sortable />
      <el-table-column prop="address" label="Address" sortable />
    </el-table>
  </div>
</template>
<script lang="ts" setup>
interface User {
  id: number
  date: string
  name: string
  address: string
  hasChildren?: boolean
  children?: User[]
}
const selectable=(row)=>{
if(row.date==='2016-05-01'){return false}else{return true}
}
const tableData: User[] = [
  {
    id: 1,
    date: '2016-05-02',
    name: 'wangxiaohu',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    id: 2,
    date: '2016-05-04',
    name: 'wangxiaohu',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    id: 3,
    date: '2016-05-02',
    name: 'wangxiaohu',
    address: 'No. 189, Grove St, Los Angeles',
    children: [
      {
        id: 31,
        date: '2016-05-01',
        name: 'wangxiaohu',
        address: 'No. 189, Grove St, Los Angeles',
      },
      {
        id: 32,
        date: '2016-05-03',
        name: 'wangxiaohu',
        address: 'No. 189, Grove St, Los Angeles',
      },
    ],
  },
  {
    id: 4,
    date: '2016-05-03',
    name: 'wangxiaohu',
    address: 'No. 189, Grove St, Los Angeles',
  },
]

</script>

### What is Expected?

当子选项禁用后 选择全选或者勾选父选项的时候  禁用项不能再勾选

### What is actually happening?

当子选项禁用后 选择全选或者勾选父选项的时候  禁用项被勾选

### Additional comments

_(empty)_

### LINKED ISSUE #18177: [Component] [table] The tree data that can be selected in the el-table, after selecting each child node one by one, the parent node cannot automatically select when all are selected
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.1`
- Element Plus Version: `2.8.1`
- Browser / OS: `Chrome/127.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInRyZWVQcm9wcy5jaGVja1N0cmljdGx5XCI+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6dmFsdWU9XCJ0cnVlXCIgbGFiZWw9XCJ0cnVlXCIgLz5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIDp2YWx1ZT1cImZhbHNlXCIgbGFiZWw9XCJmYWxzZVwiIC8+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDxlbC10YWJsZVxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICA6dHJlZS1wcm9wcz1cInRyZWVQcm9wc1wiXG4gICAgcm93LWtleT1cImlkXCJcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIi8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IG51bWJlclxuICBkYXRlOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFkZHJlc3M6IHN0cmluZ1xuICBoYXNDaGlsZHJlbj86IGJvb2xlYW5cbiAgY2hpbGRyZW4/OiBVc2VyW11cbn1cblxuY29uc3QgdHJlZVByb3BzID0gcmVhY3RpdmUoe1xuICBjaGVja1N0cmljdGx5OiBmYWxzZSxcbn0pXG5cbmNvbnN0IHNlbGVjdGFibGUgPSAocm93OiBVc2VyKSA9PiAhWzEsIDMxXS5pbmNsdWRlcyhyb3cuaWQpXG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIGRhdGU6ICcyMDE2LTA1LTA0JyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAzMSxcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMyLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBpZDogNCxcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

Remove the 'selectable' column from the checkbox table in the case and select each child node one by one. When all child nodes are selected, the parent node cannot be automatically selected

### What is Expected?

Select child nodes one by one, and when all child nodes are selected, the parent node can automatically select them

### What is actually happening?

Select child nodes one by one, and when all child nodes are selected, the parent node can automatically select them

### Additional comments

_(empty)_

### LINKED ISSUE #18203: [Component] [table] [Component] [el-table] Table 表格树形懒加载和selection多选共用，多选框不联动
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.38`
- Element Plus Version: `2.8.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgcm93LWtleT1cImlkXCJcbiAgICBsYXp5XG4gICAgOmxvYWQ9XCJsb2FkXCJcbiAgICA6dHJlZS1wcm9wcz1cInsgY2hpbGRyZW46ICdjaGlsZHJlbicsIGhhc0NoaWxkcmVuOiAnaGFzQ2hpbGRyZW4nIH1cIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYWRkcmVzc1wiIGxhYmVsPVwiQWRkcmVzc1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBsb2FkID0gKHJvdywgdHJlZU5vZGVuLCByZXNvbHZlKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnN0IGNoaWxkcmVuID0gW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6IFwiMjAxNi0wNS0wMVwiLFxuICAgICAgICBuYW1lOiBcIndhbmd4aWFvaHVcIixcbiAgICAgICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiAzMixcbiAgICAgICAgZGF0ZTogXCIyMDE2LTA1LTAxXCIsXG4gICAgICAgIG5hbWU6IFwid2FuZ3hpYW9odVwiLFxuICAgICAgICBhZGRyZXNzOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiLFxuICAgICAgfSxcbiAgICBdO1xuXG4gICAgcm93LmNoaWxkcmVuID0gY2hpbGRyZW47XG4gICAgLy8gcm93Lmhhc0NoaWxkcmVuID0gZmFsc2VcbiAgICBkZWxldGUgcm93Lmhhc0NoaWxkcmVuXG5cbiAgICAvLyDpgJrov4cgcmVzb2x2ZSDkvKDpgJLlrZDoioLngrnmlbDmja5cbiAgICByZXNvbHZlKGNoaWxkcmVuKTtcbiAgfSwgMTAwMCk7XG59O1xuXG5zZXRJbnRlcnZhbCgoKT0+e1xuICBjb25zb2xlLmxvZyh0YWJsZURhdGEudmFsdWUpXG59LCAyMDAwKVxuXG5jb25zdCB0YWJsZURhdGEgPSByZWYoW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgZGF0ZTogXCIyMDE2LTA1LTAyXCIsXG4gICAgbmFtZTogXCJ3YW5neGlhb2h1XCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIGRhdGU6IFwiMjAxNi0wNS0wNFwiLFxuICAgIG5hbWU6IFwid2FuZ3hpYW9odVwiLFxuICAgIGFkZHJlc3M6IFwiTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzXCIsXG4gIH0sXG4gIHtcbiAgICBpZDogMyxcbiAgICBkYXRlOiBcIjIwMTYtMDUtMDFcIixcbiAgICBuYW1lOiBcIndhbmd4aWFvaHVcIixcbiAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgICBhZGRyZXNzOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgZGF0ZTogXCIyMDE2LTA1LTAzXCIsXG4gICAgbmFtZTogXCJ3YW5neGlhb2h1XCIsXG4gICAgYWRkcmVzczogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgfSxcbl0pO1xuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击table表格左侧选择框和展开树形节点，父子节点选择框不联动

### What is Expected?

正常运行

### What is actually happening?

父子节点选择框不联动

### Additional comments

_(empty)_

### LINKED ISSUE #21397: [Component] [table] parent node did not show indeterminate status when checkStrictly is false
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.17`
- Element Plus Version: `2.10.4`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInRyZWVQcm9wcy5jaGVja1N0cmljdGx5XCI+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6dmFsdWU9XCJ0cnVlXCIgbGFiZWw9XCJ0cnVlXCIgLz5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIDp2YWx1ZT1cImZhbHNlXCIgbGFiZWw9XCJmYWxzZVwiIC8+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDxlbC10YWJsZVxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICA6dHJlZS1wcm9wcz1cInRyZWVQcm9wc1wiXG4gICAgcm93LWtleT1cImlkXCJcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIHdpZHRoPVwiNTVcIiA6c2VsZWN0YWJsZT1cInNlbGVjdGFibGVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBudW1iZXJcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhZGRyZXNzOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVXNlcltdXG59XG5cbmNvbnN0IHRyZWVQcm9wcyA9IHJlYWN0aXZlKHtcbiAgY2hlY2tTdHJpY3RseTogZmFsc2UsXG59KVxuXG5jb25zdCBzZWxlY3RhYmxlID0gKHJvdzogVXNlcikgPT4gIVsxLCAzMV0uaW5jbHVkZXMocm93LmlkKVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogMzEsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGlkOiAzMixcbiAgICAgICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgICAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgaWQ6IDQsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

as shown in doc.

### What is Expected?

parent node should be indeterminate when partial child nodes checked

### What is actually happening?

parent node is not checked

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by zhixiaotong**
Please make sure these boxes are checked before submitting your PR, thank you!

rel https://github.com/element-plus/element-plus/discussions/23560

fix #21397
fix #18177
fix #7920
fix #18203
fix #7101
fix #14585

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

## Summary by CodeRabbit

* **New Features**
  * Table selection shows indeterminate (half-selected) states for parent rows in tree/hierarchical data.
* **Behavior Changes**
  * Parent selection now respects non-selectable children, lazy-loaded children, and updates correctly when strict/non-strict linkage is toggled.
* **Tests**
  * Added test coverage for tree selection linkage, lazy-loading behavior, indeterminate states, and strict vs non-strict behavior.
* **Documentation**
  * Example table data updated with an additional nested child row.

### CODE REVIEW

**Comment by zhixiaotong** [comment]
## before


https://github.com/user-attachments/assets/5f328538-6f3e-4ac4-a97f-fc42a6724b14


## after

https://github.com/user-attachments/assets/86e0a2b1-d809-49a3-8a6b-c0407cbd5952

**Comment by zhixiaotong** [comment]
Is there anyone here who can help with reviews or offer other suggestions? @btea @rzzf

**Comment by rzzf** [comment]
This seems to be the same as #22054, where you can find some related [discussions](https://github.com/element-plus/element-plus/pull/22054#issuecomment-3644031901) for reference. However, considering that the author has been inactive for two months, we can continue the discussion here instead.

File: packages/components/table/src/config.ts [hunk 1]
```diff
@@ -81,6 +81,9 @@ export const cellForced = {
         },
         onClick: (event: Event) => event.stopPropagation(),
         modelValue: store.isSelected(row),
+        indeterminate: store.getRowIndeterminate
+          ? store.getRowIndeterminate(row)
+          : false,
```
Comment (Dsaquel) [inline packages/components/table/src/config.ts]: Is there a situation where `store.getRowIndeterminate` is undefined ?
```suggestion
        indeterminate: store.getRowIndeterminate(row)
```

File: packages/components/table/src/store/index.ts [hunk 2]
```diff
@@ -65,6 +65,7 @@ function useStore<T extends DefaultRow>() {
           instance.store.cleanSelection()
         }
       }
+      instance.store.updateSelectionByChildren?.({ emitChange: false })
```
Comment (Dsaquel) [inline packages/components/table/src/store/index.ts]:
```suggestion
      instance.store.updateSelectionByChildren({ emitChange: false })
```

**Review by Dsaquel — COMMENTED** [review]
Your solution looks more correct 👍 , there is just a lack of the lazy support, [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJ0YWJsZVJlZlwiXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIDp0cmVlLXByb3BzPVwidHJlZVByb3BzXCJcbiAgICByb3cta2V5PVwiaWRcIlxuICAgIGxhenlcbiAgICA6bG9hZD1cImxvYWRcIlxuICAgIEBzZWxlY3Rpb24tY2hhbmdlPVwib25TZWxlY3Rpb25DaGFuZ2VcIlxuICA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB0eXBlPVwic2VsZWN0aW9uXCIgd2lkdGg9XCI1NVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cIklEXCIgd2lkdGg9XCI4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibm90ZVwiIGxhYmVsPVwiTm90ZVwiIC8+XG4gIDwvZWwtdGFibGU+XG5cbiAgPHByZT5cbiAgICBTZWxlY3RlZCBJRHM6IHt7IHNlbGVjdGVkSWRzIH19XG4gIDwvcHJlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5cbmludGVyZmFjZSBSb3cge1xuICBpZDogbnVtYmVyXG4gIG5hbWU6IHN0cmluZ1xuICBub3RlOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogUm93W11cbn1cblxuY29uc3Qgc2VsZWN0ZWRJZHMgPSByZWY8bnVtYmVyW10+KFtdKVxuXG5jb25zdCB0cmVlUHJvcHMgPSByZWFjdGl2ZSh7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBoYXNDaGlsZHJlbjogJ2hhc0NoaWxkcmVuJyxcbn0pXG5cbmNvbnN0IG9uU2VsZWN0aW9uQ2hhbmdlID0gKHJvd3M6IFJvd1tdKSA9PiB7XG4gIHNlbGVjdGVkSWRzLnZhbHVlID0gcm93cy5tYXAoKHIpID0+IHIuaWQpXG59XG5cbmNvbnN0IGxvYWQgPSAoXG4gIHJvdzogUm93LFxuICBfdHJlZU5vZGU6IHVua25vd24sXG4gIHJlc29sdmU6IChkYXRhOiBSb3dbXSkgPT4gdm9pZFxuKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGlmIChyb3cuaWQgPT09IDIpIHtcbiAgICAgIHJlc29sdmUoW1xuICAgICAgICB7IGlkOiAyMSwgbmFtZTogJ0xhenkgY2hpbGQgMi0xJywgbm90ZTogJ2xvYWRlZCB2aWEgbG9hZCgpJyB9LFxuICAgICAgICB7IGlkOiAyMiwgbmFtZTogJ0xhenkgY2hpbGQgMi0yJywgbm90ZTogJ2xvYWRlZCB2aWEgbG9hZCgpJyB9LFxuICAgICAgXSlcbiAgICB9IGVsc2UgaWYgKHJvdy5pZCA9PT0gMzIpIHtcbiAgICAgIHJlc29sdmUoW1xuICAgICAgICB7IGlkOiAzMjEsIG5hbWU6ICdMYXp5IGdyYW5kY2hpbGQgMy0yLTEnLCBub3RlOiAnZGVlcCBsYXp5JyB9LFxuICAgICAgICB7IGlkOiAzMjIsIG5hbWU6ICdMYXp5IGdyYW5kY2hpbGQgMy0yLTInLCBub3RlOiAnZGVlcCBsYXp5JyB9LFxuICAgICAgXSlcbiAgICB9IGVsc2Uge1xuICAgICAgcmVzb2x2ZShbXSlcbiAgICB9XG4gIH0sIDMwMClcbn1cblxuY29uc3QgdGFibGVEYXRhOiBSb3dbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIG5hbWU6ICdSb3cgMSAobGVhZiknLFxuICAgIG5vdGU6ICdObyBjaGlsZHJlbicsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBuYW1lOiAnUm93IDIgKGxhenkgcGFyZW50KScsXG4gICAgbm90ZTogJ2hhc0NoaWxkcmVuIC0tIGNoaWxkcmVuIGxvYWRlZCBvbiBleHBhbmQnLFxuICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgbmFtZTogJ1JvdyAzIChlYWdlciBwYXJlbnQsIG1peGVkIG5lc3RpbmcpJyxcbiAgICBub3RlOiAnSW5saW5lIGNoaWxkcmVuLCBjaGlsZCAzMiBoYXMgbGF6eSBncmFuZGNoaWxkcmVuJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAgeyBpZDogMzEsIG5hbWU6ICdFYWdlciBjaGlsZCAzLTEnLCBub3RlOiAnaW5saW5lJyB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIG5hbWU6ICdDaGlsZCAzLTIgKGxhenkgZ3JhbmRwYXJlbnQpJyxcbiAgICAgICAgbm90ZTogJ2hhc0NoaWxkcmVuIC0tIGdyYW5kY2hpbGRyZW4gbG9hZGVkIG9uIGV4cGFuZCcsXG4gICAgICAgIGhhc0NoaWxkcmVuOiB0cnVlLFxuICAgICAgfSxcbiAgICAgIHsgaWQ6IDMzLCBuYW1lOiAnRWFnZXIgY2hpbGQgMy0zJywgbm90ZTogJ2lubGluZScgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjM1OTYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjM1OTYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjM1OTYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjM1OTYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==).

<details>
<summary>You can find here a fix of it (AI generation).</summary>

```diff
diff --git a/packages/components/table/src/store/watcher.ts b/packages/components/table/src/store/watcher.ts
index 8842ff1abe..2dd0590aa8 100644
--- a/packages/components/table/src/store/watcher.ts
+++ b/packages/components/table/src/store/watcher.ts
@@ -355,6 +355,45 @@ function useWatcher<T extends DefaultRow>() {
     return (selection.value || []).slice()
   }

+  // Cascade selection to lazy-loaded children that toggleRowStatus can't reach.
+  // toggleRowStatus only cascades via row[children] (inline), so lazy children
+  // in lazyTreeNodeMap are missed. This also recurses through inline children
+  // to find lazy grandchildren deeper in the tree.
+  const cascadeToLazyChildren = (row: T, selected: boolean) => {
+    if (!rowKey.value || treeStates.checkStrictly.value) return
+    const id = getRowIdentity(row, rowKey.value)
+    const { lazyTreeNodeMap, childrenColumnName } = instance.store.states
+    const lazyChildren = lazyTreeNodeMap.value?.[id]
+    const inlineChildren = row[childrenColumnName.value]
+
+    // If row has lazy children (no inline), cascade selection into them
+    if (lazyChildren?.length && !isArray(inlineChildren)) {
+      const treeProps = {
+        children: childrenColumnName.value,
+        checkStrictly: false,
+      }
+      lazyChildren.forEach((child: T) => {
+        toggleRowStatus(
+          selection.value,
+          child,
+          selected,
+          treeProps,
+          selectable.value,
+          0,
+          rowKey.value
+        )
+        cascadeToLazyChildren(child, selected)
+      })
+    }
+
+    // Also recurse into inline children to find lazy grandchildren
+    if (isArray(inlineChildren)) {
+      inlineChildren.forEach((child: T) => {
+        cascadeToLazyChildren(child, selected)
+      })
+    }
+  }
+
   const toggleRowSelection = (
     row: T,
     selected?: boolean,
@@ -375,6 +414,7 @@ function useWatcher<T extends DefaultRow>() {
       rowKey.value
     )
     if (changed) {
+      cascadeToLazyChildren(row, selected ?? isSelected(row))
       updateSelectionByChildren({ emitChange: false })
       const newSelection = (selection.value || []).slice()
       // 调用 API 修改选中值，不触发 select 事件
@@ -420,6 +460,23 @@ function useWatcher<T extends DefaultRow>() {
       childrenCount += getChildrenCount(getRowIdentity(row, rowKey))
     })

+    // Also cascade to lazy-loaded children that toggleRowStatus couldn't reach
+    const { lazyTreeNodeMap } = instance.store.states
+    Object.values(lazyTreeNodeMap.value).forEach((lazyRows) => {
+      ;(lazyRows as T[]).forEach((child) => {
+        toggleRowStatus(
+          selection.value,
+          child,
+          value,
+          treeProps,
+          selectable.value,
+          0,
+          rowKey
+        )
+        cascadeToLazyChildren(child, value)
+      })
+    })
+
     updateSelectionByChildren({ emitChange: false })

     if (selectionChanged) {
@@ -669,6 +726,42 @@ function useWatcher<T extends DefaultRow>() {
     }
   )

+  // When lazy children arrive, cascade selection from already-selected parents
+  // to the newly loaded children, then recompute indeterminate state.
+  watch(
+    () => treeStates.lazyTreeNodeMap.value,
+    () => {
+      if (!treeStates.checkStrictly.value && rowKey.value) {
+        const { lazyTreeNodeMap, childrenColumnName } = instance.store.states
+        const treeProps = {
+          children: childrenColumnName.value,
+          checkStrictly: false,
+        }
+        Object.entries(lazyTreeNodeMap.value).forEach(
+          ([parentId, lazyRows]) => {
+            if (selectedMap.value?.[parentId]) {
+              ;(lazyRows as T[]).forEach((child) => {
+                toggleRowStatus(
+                  selection.value,
+                  child,
+                  true,
+                  treeProps,
+                  selectable.value,
+                  0,
+                  rowKey.value
+                )
+                cascadeToLazyChildren(child, true)
+              })
+            }
+          }
+        )
+      }
+      updateSelectionByChildren()
+      updateAllSelected()
+    },
+    { deep: true }
+  )
+
   return {
     assertRowKey,
     updateColumns,
```

</details>

**Comment by zhixiaotong** [comment]
@Dsaquel Thanks for the review.
I'm back home for Chinese New Year and didn't bring my computer with me.
I'll handle this after the holiday.
 
By the way, wish you all a happy Chinese New Year!

**Comment by Dsaquel** [comment]
Happy Chinese New Year to you too, enjoy the holiday and no rush on the review!

File: packages/components/table/src/config.ts (hunk 1 above)
Comment (zhixiaotong) [reply packages/components/table/src/config.ts]: 这里不需要三元表达式，我改一下

**Comment by zhixiaotong** [comment]
@Dsaquel Thank you for your review. I have fixed and supplemented the associated selection code under lazy tree and added test cases. Please take a look when you have time.

**Comment by Dsaquel** [comment]
It fixes a lot of issues thanks for jumping into this fix,
I'll double check the change tomorrow or saturday :smiley: .

**Review by Dsaquel — APPROVED** [review]
I think the coverage is pretty good.

**Comment by zhixiaotong** [comment]
@btea Sorry to bother you, but this PR has been going on for too long...

**Comment by btea** [comment]
Sorry, I was too busy with other things and forgot. The logic of the table component is quite complex, and there are many changes to this PR. I'll take a closer look at it later.

File: packages/components/table/src/store/watcher.ts [hunk 3]
```diff
@@ -198,10 +203,119 @@ function useWatcher<T extends DefaultRow>() {
...
+  ) => {
+    const { emitChange = true } = options
+    if (treeStates.checkStrictly.value) {
+      selectionIndeterminate.value = {}
+      return
+    }
+    if (!rowKey.value) {
+      selectionIndeterminate.value = {}
+      return
+    }
```
Comment (btea) [inline packages/components/table/src/store/watcher.ts:236]: The interruption results here are consistent, so the two conditions can be combined.

File: packages/components/table/src/store/watcher.ts [hunk 4]
```diff
@@ -226,14 +352,52 @@ function useWatcher<T extends DefaultRow>() {
         (item) => !deleted.includes(item)
       )
       selection.value = newSelection
-      instance.emit('selection-change', newSelection.slice())
+      updateSelectionByChildren({ emitChange: false })
+      instance.emit('selection-change', selection.value.slice())
```
Comment (btea) [inline packages/components/table/src/store/watcher.ts]: The logic in this line doesn't seem to need to be changed.

**Comment by btea** [comment]
I've done some code refactoring, and so far it seems fine. However, I'm unsure if I've missed any scenarios. Could you take a look? @zhixiaotong

File: packages/components/table/src/store/watcher.ts [hunk 5]
```diff
@@ -213,6 +337,18 @@ function useWatcher<T extends DefaultRow>() {
...
+      if (lazyTreeNodeMap.value) {
+        Object.values(lazyTreeNodeMap.value).forEach((lazyRows) => {
+          ;(lazyRows as T[]).forEach((row) => {
+            const id = getRowIdentity(row, rowKey.value)
+            if (!dataMap[id]) {
+              dataMap[id] = { row, index: -1 }
+            }
+          })
+        })
+      }
```
Comment (rzzf) [inline packages/components/table/src/store/watcher.ts]: There appears to be a bug in `lazy` mode. [repro](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlcHJvZHVjZVwiPnJlcHJvZHVjZTwvZWwtYnV0dG9uPlxuICA8ZGl2PnNlbGVjdGlvbjoge3sgc2VsZWN0ZWRJZHMgfX08L2Rpdj5cblxuICA8ZWwtdGFibGVcbiAgICByZWY9XCJ0YWJsZVJlZlwiXG4gICAgOmRhdGE9XCJ0YWJsZURhdGFcIlxuICAgIHJvdy1rZXk9XCJpZFwiXG4gICAgbGF6eVxuICAgIDpsb2FkPVwibG9hZFwiXG4gICAgOnRyZWUtcHJvcHM9XCJ7IGNoaWxkcmVuOiAnY2hpbGRyZW4nLCBoYXNDaGlsZHJlbjogJ2hhc0NoaWxkcmVuJyB9XCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cImlkXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJuYW1lXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBFbFRhYmxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG50eXBlIFJvdyA9IHtcbiAgaWQ6IG51bWJlclxuICBuYW1lOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG59XG5cbmNvbnN0IHRhYmxlUmVmID0gcmVmPEluc3RhbmNlVHlwZTx0eXBlb2YgRWxUYWJsZT4+KClcbmNvbnN0IHRhYmxlRGF0YSA9IHJlZjxSb3dbXT4oW1xuICB7IGlkOiAxLCBuYW1lOiAncGFyZW50JywgaGFzQ2hpbGRyZW46IHRydWUgfSxcbiAgeyBpZDogMiwgbmFtZTogJ3NpYmxpbmcnIH0sXG5dKVxuY29uc3Qgc2VsZWN0ZWRJZHMgPSByZWY8bnVtYmVyW10+KFtdKVxuXG5jb25zdCBsb2FkID0gKHJvdzogUm93LCBfdHJlZU5vZGU6IHVua25vd24sIHJlc29sdmU6IChkYXRhOiBSb3dbXSkgPT4gdm9pZCkgPT4ge1xuICByZXNvbHZlKHJvdy5pZCA9PT0gMSA/IFt7IGlkOiAxMSwgbmFtZTogJ2NoaWxkJyB9XSA6IFtdKVxufVxuXG5jb25zdCBzeW5jU2VsZWN0aW9uID0gKCkgPT4ge1xuICBzZWxlY3RlZElkcy52YWx1ZSA9XG4gICAgdGFibGVSZWYudmFsdWU/LmdldFNlbGVjdGlvblJvd3MoKS5tYXAoKHJvdzogUm93KSA9PiByb3cuaWQpID8/IFtdXG59XG5cbmNvbnN0IHJlcHJvZHVjZSA9IGFzeW5jICgpID0+IHtcbiAgdGFibGVSZWYudmFsdWU/LnRvZ2dsZVJvd1NlbGVjdGlvbih0YWJsZURhdGEudmFsdWVbMF0sIHRydWUpXG4gIHRhYmxlUmVmLnZhbHVlPy50b2dnbGVSb3dFeHBhbnNpb24odGFibGVEYXRhLnZhbHVlWzBdLCB0cnVlKVxuICBhd2FpdCBuZXh0VGljaygpXG4gIGF3YWl0IG5leHRUaWNrKClcbiAgdGFibGVEYXRhLnZhbHVlLnNwbGljZSgwLCAxKVxuICBhd2FpdCBuZXh0VGljaygpXG4gIGF3YWl0IG5leHRUaWNrKClcbiAgc3luY1NlbGVjdGlvbigpXG59XG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM1OTYvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzU5Ni90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM1OTYvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL3Jhdy5lc20uc2gvcHIvZWxlbWVudC1wbHVzQDIzNTk2L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM1OTYvZGlzdC9pbmRleC5jc3MifX0=)



<details>
<summary>
Test case
</summary>

```ts
it('cleanSelection removes lazy children when parent is removed', async () => {
      wrapper = mount({
        components: {
          ElTable,
          ElTableColumn,
        },
        template: `
          <el-table
            ref="table"
            :data="testData"
            row-key="id"
            lazy
            :load="load"
            :tree-props="treeProps"
          >
            <el-table-column type="selection" />
            <el-table-column prop="name" label="name" />
          </el-table>
        `,
        data() {
          return {
            treeProps: {
              children: 'children',
              hasChildren: 'hasChildren',
              checkStrictly: false,
            },
            testData: [
              { id: 1, name: 'parent', hasChildren: true },
              { id: 2, name: 'sibling' },
            ],
          }
        },
        methods: {
          load(row, treeNode, resolve) {
            if (row.id === 1) {
              resolve([{ id: 11, name: 'child-1' }])
              return
            }
            resolve([])
          },
        },
      })
      await doubleWait()
      const tableRef = wrapper.findComponent({ ref: 'table' })
      const parentCheckbox = wrapper.findAll('.el-table__body .el-checkbox')[0]
      await parentCheckbox.trigger('click')
      await doubleWait()
      const expandIcons = wrapper.findAll('.el-table__expand-icon')
      await expandIcons[0].trigger('click')
      await doubleWait()
      const selectedBefore = (tableRef.vm as any)
        .getSelectionRows()
        .map((row: any) => row.id)
      expect(selectedBefore).toContain(1)
      expect(selectedBefore).toContain(11)
      const vm = wrapper.vm as any
      vm.testData.splice(0, 1)
      await doubleWait()
      await doubleWait()

      const selectedAfter = (tableRef.vm as any)
        .getSelectionRows()
        .map((row: any) => row.id)
      expect(selectedAfter).not.toContain(1)
      expect(selectedAfter).not.toContain(11)
    })
```
</details>

File: packages/components/table/src/store/index.ts [hunk 6]
```diff
@@ -65,6 +65,7 @@ function useStore<T extends DefaultRow>() {
           instance.store.cleanSelection()
         }
       }
+      instance.store.updateSelectionByChildren({ emitChange: false })
```
Comment (rzzf) [inline packages/components/table/src/store/index.ts:68]: Why isn’t the event triggered after the data changes? Is this what was expected?
[repro](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlcHJvZHVjZVwiPnJlcHJvZHVjZTwvZWwtYnV0dG9uPlxuICA8ZGl2PmdldFNlbGVjdGlvblJvd3M6IHt7IGludGVybmFsU2VsZWN0ZWRJZHMgfX08L2Rpdj5cbiAgPGRpdj5zZWxlY3Rpb24tY2hhbmdlOiB7eyBldmVudFNlbGVjdGVkSWRzIH19PC9kaXY+XG5cbiAgPGVsLXRhYmxlXG4gICAgcmVmPVwidGFibGVSZWZcIlxuICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICByb3cta2V5PVwiaWRcIlxuICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgIDp0cmVlLXByb3BzPVwieyBjaGlsZHJlbjogJ2NoaWxkcmVuJyB9XCJcbiAgICBAc2VsZWN0aW9uLWNoYW5nZT1cIm9uU2VsZWN0aW9uQ2hhbmdlXCJcbiAgPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gdHlwZT1cInNlbGVjdGlvblwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiaWRcIiBsYWJlbD1cImlkXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJuYW1lXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVmIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHR5cGUgeyBFbFRhYmxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG50eXBlIFJvdyA9IHtcbiAgaWQ6IG51bWJlclxuICBuYW1lOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBSb3dbXVxufVxuXG5jb25zdCB0YWJsZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVGFibGU+PigpXG5jb25zdCB0YWJsZURhdGEgPSByZWY8Um93W10+KFtcbiAge1xuICAgIGlkOiAxLFxuICAgIG5hbWU6ICdwYXJlbnQnLFxuICAgIGNoaWxkcmVuOiBbeyBpZDogMTEsIG5hbWU6ICdjaGlsZC0xJyB9XSxcbiAgfSxcbl0pXG5jb25zdCBpbnRlcm5hbFNlbGVjdGVkSWRzID0gcmVmPG51bWJlcltdPihbXSlcbmNvbnN0IGV2ZW50U2VsZWN0ZWRJZHMgPSByZWY8bnVtYmVyW10+KFtdKVxuXG5jb25zdCBzeW5jU2VsZWN0aW9uID0gKCkgPT4ge1xuICBpbnRlcm5hbFNlbGVjdGVkSWRzLnZhbHVlID1cbiAgICB0YWJsZVJlZi52YWx1ZT8uZ2V0U2VsZWN0aW9uUm93cygpLm1hcCgocm93OiBSb3cpID0+IHJvdy5pZCkgPz8gW11cbn1cblxuY29uc3Qgb25TZWxlY3Rpb25DaGFuZ2UgPSAocm93czogUm93W10pID0+IHtcbiAgZXZlbnRTZWxlY3RlZElkcy52YWx1ZSA9IHJvd3MubWFwKChyb3cpID0+IHJvdy5pZClcbiAgc3luY1NlbGVjdGlvbigpXG59XG5cbmNvbnN0IHJlcHJvZHVjZSA9IGFzeW5jICgpID0+IHtcbiAgdGFibGVSZWYudmFsdWU/LnRvZ2dsZVJvd1NlbGVjdGlvbih0YWJsZURhdGEudmFsdWVbMF0sIHRydWUpXG4gIGF3YWl0IG5leHRUaWNrKClcbiAgdGFibGVEYXRhLnZhbHVlWzBdLmNoaWxkcmVuPy5wdXNoKHsgaWQ6IDEyLCBuYW1lOiAnY2hpbGQtMicgfSlcbiAgYXdhaXQgbmV4dFRpY2soKVxuICBhd2FpdCBuZXh0VGljaygpXG4gIHN5bmNTZWxlY3Rpb24oKVxufVxuPC9zY3JpcHQ+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzU5Ni9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3Jhdy5lc20uc2gvcHIvZWxlbWVudC1wbHVzQDIzNTk2L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzU5Ni9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM1OTYvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzU5Ni9kaXN0L2luZGV4LmNzcyJ9fQ==)

Comment (zhixiaotong) [reply packages/components/table/src/store/index.ts:68]: 有意为之，内部状态无需同步。

- 懒加载子节点加载完成后，父节点之前已经选中了，需要把选中状态同步给新加载的子节点
- 数据刷新后，需要重新计算父节点的选中状态

File: packages/components/table/src/store/watcher.ts (hunk 5 above)
Comment (zhixiaotong) [reply packages/components/table/src/store/watcher.ts]: 谢谢提供这个test，我看一下问题

Comment (zhixiaotong) [reply packages/components/table/src/store/watcher.ts]: 问题在于没有考虑父节点是否在 `dataMap`,我把你的这个test补上了

**Comment by zhixiaotong** [comment]
@btea After running the review using the superpowers `/review` and ECC `/code-review` capabilities, I've addressed some potential performance issues with Claude Code's quick fixes, and no other problems have been found for now.

File: packages/components/table/src/store/watcher.ts [hunk 7]
```diff
@@ -526,6 +750,52 @@ function useWatcher<T extends DefaultRow>() {
...
+
+      const cascadeChanged = selection.value.length !== prevLen
+      updateSelectionByChildren({
+        emitChange: !cascadeChanged,
+        rowIndexMap: rowIndexMapVal,
+      })
+      updateAllSelected()
+      if (cascadeChanged) {
+        instance.emit('selection-change', selection.value.slice())
```
Comment (rzzf) [inline packages/components/table/src/store/watcher.ts]:
```suggestion
        instance.emit('selection-change', [...selection.value])
```

**Review by rzzf — APPROVED** [review]
lgtm

**Review by btea — APPROVED** [review]
