### PR TITLE
fix(components): [select-v2] scrollbar resets to top after select item

### LINKED ISSUE #21225: [Component] [select-v2] el-select-v2 滚动后选中选项之后会返回到顶部第一个
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.14`
- Element Plus Version: `2.10.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgbXVsdGlwbGVcbiAgICBmaWx0ZXJhYmxlXG4gICAgcmVtb3RlXG4gICAgOnJlbW90ZS1tZXRob2Q9XCJrZXl3b3JkPT5yZW1vdGVNZXRob2Qoa2V5d29yZCwndGVzdCcpXCJcbiAgICBjbGVhcmFibGVcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIDpsb2FkaW5nPVwibG9hZGluZ1wiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgZW50ZXIgYSBrZXl3b3JkXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHN0YXRlcyA9IFtcbiAgJ0FsYWJhbWEnLFxuICAnQWxhc2thJyxcbiAgJ0FyaXpvbmEnLFxuICAnQXJrYW5zYXMnLFxuICAnQ2FsaWZvcm5pYScsXG4gICdDb2xvcmFkbycsXG4gICdDb25uZWN0aWN1dCcsXG4gICdEZWxhd2FyZScsXG4gICdGbG9yaWRhJyxcbiAgJ0dlb3JnaWEnLFxuICAnSGF3YWlpJyxcbiAgJ0lkYWhvJyxcbiAgJ0lsbGlub2lzJyxcbiAgJ0luZGlhbmEnLFxuICAnSW93YScsXG4gICdLYW5zYXMnLFxuICAnS2VudHVja3knLFxuICAnTG91aXNpYW5hJyxcbiAgJ01haW5lJyxcbiAgJ01hcnlsYW5kJyxcbiAgJ01hc3NhY2h1c2V0dHMnLFxuICAnTWljaGlnYW4nLFxuICAnTWlubmVzb3RhJyxcbiAgJ01pc3Npc3NpcHBpJyxcbiAgJ01pc3NvdXJpJyxcbiAgJ01vbnRhbmEnLFxuICAnTmVicmFza2EnLFxuICAnTmV2YWRhJyxcbiAgJ05ldyBIYW1wc2hpcmUnLFxuICAnTmV3IEplcnNleScsXG4gICdOZXcgTWV4aWNvJyxcbiAgJ05ldyBZb3JrJyxcbiAgJ05vcnRoIENhcm9saW5hJyxcbiAgJ05vcnRoIERha290YScsXG4gICdPaGlvJyxcbiAgJ09rbGFob21hJyxcbiAgJ09yZWdvbicsXG4gICdQZW5uc3lsdmFuaWEnLFxuICAnUmhvZGUgSXNsYW5kJyxcbiAgJ1NvdXRoIENhcm9saW5hJyxcbiAgJ1NvdXRoIERha290YScsXG4gICdUZW5uZXNzZWUnLFxuICAnVGV4YXMnLFxuICAnVXRhaCcsXG4gICdWZXJtb250JyxcbiAgJ1ZpcmdpbmlhJyxcbiAgJ1dhc2hpbmd0b24nLFxuICAnV2VzdCBWaXJnaW5pYScsXG4gICdXaXNjb25zaW4nLFxuICAnV3lvbWluZycsXG5dXG5jb25zdCBsaXN0ID0gc3RhdGVzLm1hcCgoaXRlbSk6IExpc3RJdGVtID0+IHtcbiAgcmV0dXJuIHsgdmFsdWU6IGB2YWx1ZToke2l0ZW19YCwgbGFiZWw6IGBsYWJlbDoke2l0ZW19YCB9XG59KVxuXG5pbnRlcmZhY2UgTGlzdEl0ZW0ge1xuICB2YWx1ZTogc3RyaW5nXG4gIGxhYmVsOiBzdHJpbmdcbn1cblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gcmVmPExpc3RJdGVtW10+KFtdKVxuY29uc3QgbG9hZGluZyA9IHJlZihmYWxzZSlcblxuY29uc3QgcmVtb3RlTWV0aG9kID0gKHF1ZXJ5OiBzdHJpbmcsa2V5OnN0cmluZykgPT4ge1xuICBjb25zb2xlLmxvZyhxdWVyeSxrZXksJys+Jyk7XG4gIGlmIChxdWVyeSAhPT0gJycpIHtcbiAgICBsb2FkaW5nLnZhbHVlID0gdHJ1ZVxuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgICBvcHRpb25zLnZhbHVlID0gbGlzdC5maWx0ZXIoKGl0ZW0pID0+IHtcbiAgICAgICAgcmV0dXJuIGl0ZW0ubGFiZWwudG9Mb3dlckNhc2UoKS5pbmNsdWRlcyhxdWVyeS50b0xvd2VyQ2FzZSgpKVxuICAgICAgfSlcbiAgICB9LCAyMDApXG4gIH0gZWxzZSB7XG4gICAgb3B0aW9ucy52YWx1ZSA9IFtdXG4gIH1cbn1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
      <el-select-v2
        v-model="searchForm[item.columnName]"
        :options="searchOptions"
        multiple
        filterable
        remote
        :remote-method="keyword => searchByKeyword(item.columnName, keyword)"
        :collapse-tags="true"
        :loading="loading"
        :collapse-tags-tooltip="true"
        tag-type="primary"
      ></el-select-v2>
```
只要在remote-method传入自定义参数，便会触发

### What is Expected?

滚动条保留在当前位置

### What is actually happening?

每次选择完一个选项后，下拉列表会触发重新渲染，滚动条会滚动到顶部

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by SpanManX**
fix #21225

### Before
动画

### After
动画1

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by SpanManX** [comment]
Adding `&& isFunction(props.remoteMethod)` inside the `filterOptions` function causes `watchEffect` to trigger multiple times. After removing `&& isFunction(props.remoteMethod)`, it behaves normally. Changing it to use a `typeof` check still triggers `watchEffect`. I haven't figured out the exact trigger logic yet, so for now, I've reverted the code back to `isValidOption`.

> 在`filterOptions `函数下添加`&& isFunction(props.remoteMethod)`就会多次触发`watchEffect`，删除`&& isFunction(props.remoteMethod)` 后正常。改为 `typof` 判断也还是会触发watchEffect，目前没搞懂它的触发逻辑，所以把代码改回到`isValidOption`下。

```
const filterOptions = (query: string) => {
    const isRemoteMethodValid = props.filterable && props.remote && isFunction(props.remoteMethod)
}
```

**Review by warmthsea — COMMENTED** [review]
This problem seems to have returned. 🤔 

- https://github.com/element-plus/element-plus/issues/19964

**Comment by SpanManX** [comment]
> This problem seems to have returned. 🤔
> 
> * #19964

我知道是什么问题了，`:remote-method="(keyword) => remoteMethod(keyword)"`每次触发remote-method都会创建一个新的箭头函数，所以导致`watchEffect `的执行。也解释了为什么去掉`isFunction(props.remoteMethod)`就正常了。`:remote-method="remoteMethod"`这种方法使用就没有问题。

**Comment by SpanManX** [comment]
> This problem seems to have returned. 🤔
> 
> * #19964

The code has been updated. Wrapping it in a function resolves the issue of `props.remoteMethod` triggering `watchEffect`.

File: packages/components/select-v2/src/useSelect.ts [hunk 1]
```diff
@@ -204,10 +204,10 @@ const useSelect = (props: SelectV2Props, emit: SelectV2EmitFn) => {
     const regexp = new RegExp(escapeStringRegexp(query), 'i')
     const isFilterMethodValid =
       props.filterable && isFunction(props.filterMethod)
-    const isRemoteMethodValid =
+    const isRemoteMethodValid = () =>
       props.filterable && props.remote && isFunction(props.remoteMethod)
     const isValidOption = (o: Option): boolean => {
-      if (isFilterMethodValid || isRemoteMethodValid) return true
+      if (isFilterMethodValid || isRemoteMethodValid()) return true
```
Comment (Dsaquel) [inline packages/components/select-v2/src/useSelect.ts]: There is indeed extra trigger because of `remoteMethod`:
Calling `onTrigger` in the `watchEffect` debug option will print the key `remoteMethod`, (maybe vue can't check the old-new changes of this type (?))

There is also the same issue with `filterMethod`, we can make the same change as `remoteMethod`.
Consider using `toRaw` to understand what's going on:
```suggestion
props.filterable && isFunction(toRaw(props).filterMethod)
    const isRemoteMethodValid =
props.filterable && props.remote && isFunction(toRaw(props).remoteMethod)
const isValidOption = (o: Option): boolean => {
      if (isFilterMethodValid || isRemoteMethodValid) return true
```

Comment (Dsaquel) [reply packages/components/select-v2/src/useSelect.ts]: Also it keep the performance with https://github.com/element-plus/element-plus/pull/19970 more or less (local + no throttle)
image

With functions:
image

Comment (SpanManX) [reply packages/components/select-v2/src/useSelect.ts]: Change to toRaw
image

**Review by Dsaquel — APPROVED** [review]
nice :+1:

**Review by warmthsea — APPROVED** [review]
👍

**Review by btea — APPROVED** [review]
Thanks!

**Comment by Muspcn** [comment]
不是修复了吗为什么删除了

**Comment by btea** [comment]
参考 #21419，目前的表现应该是正常的。
