### PR TITLE
fix(components): [tooltip] avoid repeated onBeforeEnter execution

### LINKED ISSUE #20975: [Component] [popover] 组件设置persistent为false时会导致beforeenter钩子触发两遍
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.10.1`
- Browser / OS: `any`
- Build Tool: `Vite`

### Related Component

- `el-popover`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/popover.html)

### Steps to reproduce

只要把persistent为false就一定复现
<el-popover
          :persistent="false"
          @before-enter="beforeEnter"
        >
          <template #reference>
            <el-button type="primary">custom 1</el-button>
          </template>
        </el-popover>

### What is Expected?

before-enter 正常触发一次

### What is actually happening?

before-enter 异常触发两次

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #20975

### CODE REVIEW

**Comment by rzzf** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgcGVyc2lzdGVudCA9IHJlZihmYWxzZSlcbmNvbnN0IG9uQmVmb3JlRW50ZXIgPSAoY29tcE5hbWU6IHN0cmluZykgPT4ge1xuICBjb25zb2xlLmxvZyhgWyR7Y29tcE5hbWV9XTogYmVmb3JlIGVudGVyYClcbn1cbmNvbnN0IG9uQmVmb3JlTGVhdmUgPSAoY29tcE5hbWU6IHN0cmluZykgPT4ge1xuICBjb25zb2xlLmxvZyhgWyR7Y29tcE5hbWV9XTogYmVmb3JlIGxlYXZlYClcbn1cbmNvbnN0IG9uQWZ0ZXJFbnRlciA9IChjb21wTmFtZTogc3RyaW5nKSA9PiB7XG4gIGNvbnNvbGUubG9nKGBbJHtjb21wTmFtZX1dOiBhZnRlciBlbnRlcmApXG59XG5jb25zdCBvbkFmdGVyTGVhdmUgPSAoY29tcE5hbWU6IHN0cmluZykgPT4ge1xuICBjb25zb2xlLmxvZyhgWyR7Y29tcE5hbWV9XTogYWZ0ZXIgbGVhdmVgKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRvb2x0aXBcbiAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICBjb250ZW50PVwiVG9wIExlZnQgcHJvbXB0cyBpbmZvXCJcbiAgICBwbGFjZW1lbnQ9XCJ0b3Atc3RhcnRcIlxuICAgIDpwZXJzaXN0ZW50PVwicGVyc2lzdGVudFwiXG4gICAgQGJlZm9yZVNob3c9XCJvbkJlZm9yZUVudGVyKCd0b29sdGlwJylcIlxuICAgIEBiZWZvcmVIaWRlPVwib25CZWZvcmVMZWF2ZSgndG9vbHRpcCcpXCJcbiAgICBAc2hvdz1cIm9uQWZ0ZXJFbnRlcigndG9vbHRpcCcpXCJcbiAgICBAaGlkZT1cIm9uQWZ0ZXJMZWF2ZSgndG9vbHRpcCcpXCJcbiAgPlxuICAgIDxlbC1idXR0b24+dG9wLXN0YXJ0PC9lbC1idXR0b24+XG4gIDwvZWwtdG9vbHRpcD5cbiAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJ0b3Atc3RhcnRcIlxuICAgIHRpdGxlPVwiVGl0bGVcIlxuICAgIDp3aWR0aD1cIjIwMFwiXG4gICAgdHJpZ2dlcj1cImhvdmVyXCJcbiAgICA6cGVyc2lzdGVudD1cInBlcnNpc3RlbnRcIlxuICAgIGNvbnRlbnQ9XCJ0aGlzIGlzIGNvbnRlbnQsIHRoaXMgaXMgY29udGVudCwgdGhpcyBpcyBjb250ZW50XCJcbiAgICBAYmVmb3JlRW50ZXI9XCJvbkJlZm9yZUVudGVyKCdwb3BvdmVyJylcIlxuICAgIEBiZWZvcmVMZWF2ZT1cIm9uQmVmb3JlTGVhdmUoJ3BvcG92ZXInKVwiXG4gICAgQGFmdGVyRW50ZXI9XCJvbkFmdGVyRW50ZXIoJ3BvcG92ZXInKVwiXG4gICAgQGFmdGVyTGVhdmU9XCJvbkFmdGVyTGVhdmUoJ3BvcG92ZXInKVwiXG4gID5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJtLTJcIj5Ib3ZlciB0byBhY3RpdmF0ZTwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cblxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInBlcnNpc3RlbnQgPSAhcGVyc2lzdGVudFwiPnRvZ2dsZSBwZXJzaXN0ZW50IDwvZWwtYnV0dG9uPlxuXG4gIDxwPnBlcnNpc3RlbnQ6IHt7IHBlcnNpc3RlbnQgfX08L3A+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTIwOTgzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTIwOTgzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTIwOTgzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTIwOTgzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvZGlzdC9pbmRleC5jc3MifX0=)

File: packages/components/tooltip/src/content.vue [hunk 1]
```diff
@@ -1,14 +1,15 @@
 <template>
   <el-teleport :disabled="!teleported" :to="appendTo">
     <transition
+      v-if="shouldRender || !ariaHidden"
```
Comment (Dsaquel) [inline packages/components/tooltip/src/content.vue:4]: I was aware of the extra `|| !ariaHidden` but it make sense because we wait until the transition end.

**Review by Dsaquel — APPROVED** [review]
LGTM

**Comment by btea** [comment]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden#:~:text=should%20not%20be%20added%20when

As I understand it, when the tooltip is closed, we either destroy the tag structure directly or hide the content through `display:none`. It seems unnecessary to add aria-hidden. 🤔

**Comment by rzzf** [comment]
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden#:~:text=should%20not%20be%20added%20when
> 
> As I understand it, when the tooltip is closed, we either destroy the tag structure directly or hide the content through `display:none`. It seems unnecessary to add aria-hidden. 🤔

@btea Thank you for your review! You made a very good point, in most cases, hiding the tooltip using display: none or unmounting the component directly would indeed make aria-hidden seem unnecessary.

But, when `persistentRef: false`, `shouldRender` is set to `false` before `ariaHidden`. If we rely only on `shouldRender`, the component may be destroyed before the transition completes, which can prevent lifecycle hooks like `beforeLeave` and `afterLeave` from being properly triggered.

As @Dsaquel pointed out, we need to wait until the transition has finished before unmounting the component.
In this case, `ariaHidden` is used more like a flag to indicate whether the transition has completed. That said, if the naming causes confusion, perhaps we could consider introducing a separate variable to make its purpose clearer?

**Comment by rzzf** [comment]
> > https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-hidden#:~:text=should%20not%20be%20added%20when
> > As I understand it, when the tooltip is closed, we either destroy the tag structure directly or hide the content through `display:none`. It seems unnecessary to add aria-hidden. 🤔
> 
> @btea Thank you for your review! You made a very good point, in most cases, hiding the tooltip using display: none or unmounting the component directly would indeed make aria-hidden seem unnecessary.
> 
> But, when `persistentRef: false`, `shouldRender` is set to `false` before `ariaHidden`. If we rely only on `shouldRender`, the component may be destroyed before the transition completes, which can prevent lifecycle hooks like `beforeLeave` and `afterLeave` from being properly triggered.
> 
> As @Dsaquel pointed out, we need to wait until the transition has finished before unmounting the component. In this case, `ariaHidden` is used more like a flag to indicate whether the transition has completed. That said, if the naming causes confusion, perhaps we could consider introducing a separate variable to make its purpose clearer?


https://github.com/user-attachments/assets/1990b9d2-e51a-4870-993b-fefcf9bc24c4

**Review by btea — APPROVED** [review]
Thanks!
