### PR TITLE
fix(cascader-panel): should not re-init when props's value not change

### LINKED ISSUE #1871: [bug report] when multi select is used for El cascade panel, after binding V-model value, the sub node in the panel will be selected and the panel will return to its original position
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
win10 edge 90.0.818.39 

### Vue version
3.0.11

### Reproduction Link
https://codesandbox.io/s/beautiful-blackwell-p9fxn?file=/src/App.vue

### Steps to reproduce
选择 组件->form->form单选框

### What is Expected?
面板应该保持 选择时 的展开状态

### What is actually happening?
选择完后直接跳到最初状态

### LINKED ISSUE #2317: [Bug Report] Cascader `lazyLoad` triggers on every re-render
### Element Plus version
1.0.2-beta.51

### OS/Browsers version
Windows 10
Chrome v91

### Vue version
3.1.2

### Reproduction Link
https://github.com/wenfangdu/cascader-lazy-load-repro

### Steps to reproduce
Please use the repro link.

### What is Expected?
`props` are checked by content, e.g. using `lodash`'s `isEqual`, if it indeed changed, then run `lazyLoad`.

### What is actually happening?
`lazyLoad` triggers on every re-rerender.

### PR DESCRIPTION
**Pull request by SimonaliaChen**
fix #2317 #1871

--------
Edit by Jeremy:
- fix #2317 
- fix #1871 

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/utils/util.ts [hunk 1]
```diff
@@ -236,3 +238,18 @@ export function addUnit(value: string | number) {
...
+ * @param obj The value to compare
+ * @param other The other value to compare
+ * @returns Returns `true` if the values are equivalent, else `false`.
+ * @example
+ *  lodash.isEqual(() => 1, () => 1)      // false
+ *  isEqualWith(() => 1, () => 1)         // true
+ */
+export function isEqualWithFunction (obj: any, other: any) {
+  return isEqualWith(obj, other, (objVal, otherVal) => {
+    return isFunction(objVal) && isFunction(otherVal) ? `${objVal}` === `${otherVal}`  : undefined
```
Comment (JeremyWuuuuu) [inline packages/utils/util.ts:253]: You have added an extra space after `${otherVal}`

**Review by jw-foss — APPROVED** [review]

File: packages/utils/util.ts (hunk 1 above)
Comment (SimonaliaChen) [reply packages/utils/util.ts]: Well spotted!! Fixed

**Comment by SimonaliaChen** [comment]
@wenfangdu @jinrongni This fix has some side effects see https://github.com/element-plus/element-plus/issues/2837 for detail. After our discussions, we decided to rollback this pr and strongly recommend not take object literal values as props but wrap it with memo to prevent such issues. Thanks for your understanding.
