### PR TITLE
fix(components): [table] ensure tooltip works correctly in tree table

### LINKED ISSUE #18519: [Component] [table, table-column] When the Table component uses a tree-like list and has the "show-overflow-tooltip" prop set to true, the child list may display abnormally.
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.11`
- Element Plus Version: `2.8.4`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuXG4gICAgPGVsLXRhYmxlXG4gICAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tYm90dG9tOiAyMHB4XCJcbiAgICAgIHJvdy1rZXk9XCJpZFwiXG4gICAgICBib3JkZXJcbiAgICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgID5cbiAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gIGNsYXNzLW5hbWU9XCJpbmRleC1jZWxsXCIgYWxpZ249XCJyaWdodFwiIHdpZHRoPVwiNjBcIiBsYWJlbD1cIuihjOWPt1wiICA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwidHJ1ZVwiPlxuICAgICAgPHRlbXBsYXRlIHYtc2xvdD1cInNjb3BlXCI+XG4gICAgICAgIDxzcGFuID48L3NwYW4+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHNvcnRhYmxlIC8+XG4gICAgPC9lbC10YWJsZT5cblxuXG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBudW1iZXJcbiAgZGF0ZTogc3RyaW5nXG4gIG5hbWU6IHN0cmluZ1xuICBhZGRyZXNzOiBzdHJpbmdcbiAgaGFzQ2hpbGRyZW4/OiBib29sZWFuXG4gIGNoaWxkcmVuPzogVXNlcltdXG59XG5cbmNvbnN0IGxvYWQgPSAoXG4gIHJvdzogVXNlcixcbiAgdHJlZU5vZGU6IHVua25vd24sXG4gIHJlc29sdmU6IChkYXRhOiBVc2VyW10pID0+IHZvaWRcbikgPT4ge1xuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICByZXNvbHZlKFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMxLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICAgIH0sXG4gICAgXSlcbiAgfSwgMTAwMClcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBpZDogMSxcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgaWQ6IDIsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDQnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMxLFxuICAgICAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICAgICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBpZDogMzIsXG4gICAgICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICAgICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgICAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG5cbmNvbnN0IHRhYmxlRGF0YTE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAxLFxuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBpZDogMixcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ3dhbmd4aWFvaHUnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICB9LFxuICB7XG4gICAgaWQ6IDMsXG4gICAgZGF0ZTogJzIwMTYtMDUtMDEnLFxuICAgIG5hbWU6ICd3YW5neGlhb2h1JyxcbiAgICBoYXNDaGlsZHJlbjogdHJ1ZSxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGlkOiA0LFxuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnd2FuZ3hpYW9odScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Simply place the mouse over the sub-item to reproduce it. 鼠标放在子项即可复现

### What is Expected?

A tooltip cannot appear if the conditions for overflow are not met.

### What is actually happening?

No matter what happened

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by xuhuaiyu24**
Fixes #18519
Please make sure these boxes are checked before submitting your PR, thank you!

- [ x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x ] Make sure you are merging your commits to `dev` branch.
- [x ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/table/src/table-body/events-helper.ts [hunk 1]
```diff
@@ -138,7 +138,8 @@ function useEvents<T extends DefaultRow>(props: Partial<TableBodyProps<T>>) {
     if (
       !(
         hasClass(cellChild, `${namespace}-tooltip`) &&
-        cellChild.childNodes.length
+        cellChild.childNodes.length &&
+        cellChild.textContent.trim() !== ''
```
Comment (btea) [inline packages/components/table/src/table-body/events-helper.ts]:
```suggestion
        cellChild.textContent?.trim()
```

**Comment by xuhuaiyu24** [comment]
@btea I have made the modifications as you suggested.

File: packages/components/table/__tests__/table.test.ts [hunk 2]
```diff
@@ -2387,6 +2387,120 @@ describe('Table.vue', () => {
...
+        return {
+          testData,
+        }
+      },
+    })
+    await doubleWait()
+    const existingPopper = document.querySelector('.el-popper')
+    if (existingPopper) {
+      existingPopper.remove()
+    }
```
Comment (rzzf) [inline packages/components/table/__tests__/table.test.ts]:
```suggestion
```

File: packages/components/table/__tests__/table.test.ts [hunk 3]
```diff
@@ -2387,6 +2387,120 @@ describe('Table.vue', () => {
...
+      expect(cellElement.exists()).toBe(true)
+      const mockCellRect = vi
+        .spyOn(cellElement.element, 'getBoundingClientRect')
+        .mockReturnValue({
+          width: 100,
+          height: 30,
+        } as DOMRect)
+      await cell.trigger('mouseenter')
+      await rAF()
+      expect(document.querySelector('.el-popper')).toBeNull()
```
Comment (rzzf) [inline packages/components/table/__tests__/table.test.ts]:
```suggestion
      expect(wrapper.find('.el-popper').exists()).toBeFalsy()
```

**Comment by xuhuaiyu24** [comment]
@rzzf  I have made the modifications as you suggested.

**Review by rzzf — APPROVED** [review]
LGTM.

**Review by btea — APPROVED** [review]
Thanks!

**Review by warmthsea — APPROVED** [review]
LGTM

**Comment by xuhuaiyu24** [comment]
@btea @warmthsea @rzzf Thanks very much
