### PR TITLE
fix(components): [el-table] cannot scroll when tableLayout is auto

### LINKED ISSUE #6771: [Bug Report] [Component] [table] el-table 设置 table-layout 为 "auto"，超出容器不能滚动
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.4`
- Browser / OS: `Firefox 98.0 Windows 10 x64`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuXG4gIFxuY29uc3QgbGlzdCA9IHJlZihBcnJheS5mcm9tKHtsZW5ndGg6MTB9LCAoXywgaSkgPT4gKHthOiBpfSkgKSlcbiBcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PHNwYW4+dGFibGUtbGF5b3V0PSdmaXhlZCcg5Y+v5Lul5rua5YqoPC9zcGFuPlxuXHQ8ZGl2IGNsYXNzPVwiYm94XCI+XG4gICAgPGVsLXRhYmxlIDpkYXRhPVwibGlzdFwiIGhlaWdodD1cImF1dG9cIiB0YWJsZS1sYXlvdXQ9XCJmaXhlZFwiPlxuICAgIFx0PGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYVwiIGxhYmVsPVwiYVwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG4gIFxuICA8c3Bhbj50YWJsZS1sYXlvdXQ9J2F1dG8nIOS4jeiDvea7muWKqDwvc3Bhbj5cbiAgPGRpdiBjbGFzcz1cImJveFwiPlxuICAgIDxlbC10YWJsZSA6ZGF0YT1cImxpc3RcIiBoZWlnaHQ9XCJhdXRvXCIgdGFibGUtbGF5b3V0PVwiYXV0b1wiPlxuICAgIFx0PGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYVwiIGxhYmVsPVwiYVwiIC8+XG4gICAgPC9lbC10YWJsZT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG5cbjxzdHlsZT5cbiAgLmgtZ3JvdyB7XG4gICAgaGVpZ2h0OiAwO1xuICAgIGZsZXgtZ3JvdzogMTtcbiAgfVxuICAuYm94IHtcbiAgICBoZWlnaHQ6MzAwcHg7IFxuICAgIHdpZHRoOiAzMDBweDtcbiAgICBiYWNrZ3JvdW5kOmJsYWNrO1xuICAgIGRpc3BsYXk6ZmxleDtcbiAgICBmbGV4LWRpcmN0aW9uOmNvbHVtbjtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

设置`el-table`的`table-layout`属性为`auto`

### What is Expected?

和`fixed`一样，超出可以滚动

### What is actually happening?

无法滚动

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by msidolphin**
fix #6771

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/table/src/table/style-helper.ts [hunk 1]
```diff
@@ -261,6 +261,7 @@ function useStyle<T>(
     const headerHeight = layout.headerHeight.value || 0
     const bodyHeight = layout.bodyHeight.value
     const footerHeight = layout.footerHeight.value || 0
+    console.log(props.height, bodyHeight)
```
Comment (btea) [inline packages/components/table/src/table/style-helper.ts:264]: This line should be removed

**Review by btea — APPROVED** [review]

File: packages/components/table/src/table-layout.ts [hunk 2]
```diff
@@ -148,18 +148,21 @@ class TableLayout<T> {
...
 
     const headerHeight = (this.headerHeight.value = !this.showHeader
       ? 0
-      : headerWrapper.offsetHeight)
+      : headerWrapper?.offsetHeight || 0)
     if (
       this.showHeader &&
       !noneHeader &&
-      headerWrapper.offsetWidth > 0 &&
+      headerWrapper?.offsetWidth > 0 &&
```
Comment (JeremyWuuuuu) [inline packages/components/table/src/table-layout.ts:165]: **Question:** since the `headerWrapper?.offsetWidth` might be `undefined`, can we do something like:

```ts
const headerWrapperOffsetHeight = headerWrapper?.offsetHeight || 0
// Use this variable for operations
```

**Review by jw-foss — COMMENTED** [review]
@msidolphin I left a comment for you to consider ;>

**Comment by msidolphin** [comment]
@JeremyWuuuuu done

**Review by jw-foss — APPROVED** [review]
