### PR TITLE
fix(components): [date-picker] the time panel is closed without losing focus

### LINKED ISSUE #14728: [Component] [date-picker]el-date-picker(type="datetime")点击时间选择框后点击其他日期，时间选择框还是被选中状态，且点击时间选择框不会出现下拉框
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.34`
- Browser / OS: `Chrome 119.0.6045.105 / Windows 11`
- Build Tool: `Vue CLI`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tZGF0ZXRpbWUtcGlja2VyXCI+XG4gICAgPGRpdiBjbGFzcz1cImJsb2NrXCI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRlbW9uc3RyYXRpb25cIj5EZWZhdWx0PC9zcGFuPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTFcIlxuICAgICAgICB0eXBlPVwiZGF0ZXRpbWVcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdCBkYXRlIGFuZCB0aW1lXCJcbiAgICAgIC8+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUxID0gcmVmKCcnKVxuY29uc3QgZGVmYXVsdFRpbWUgPSBuZXcgRGF0ZSgyMDAwLCAxLCAxLCAxMiwgMCwgMClcblxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

点击面板中的时间选择框，出现时间下拉框后点击其他日期，此时时间选择框仍然是选择，且点击时间选择框不会出现下拉框
（Click the time selection box in the panel. After the time drop-down list box is displayed, click another date. In this case, the time selection box is still selected, and no drop-down list box is displayed when you click the time selection box.）
1.
image
2.
image

### What is Expected?

点击面板中的时间选择框，出现时间下拉框后点击其他日期，时间选择框会失焦，不再是选中状态，且点击时间选择框时会出现下拉框
（Click the time selection box on the panel. After the time drop-down list box is displayed, click another date. The time selection box is out of focus and is no longer selected. In addition, a drop-down list box is displayed when you click the time selection box.）

### What is actually happening?

点击面板中的时间选择框，出现时间下拉框后点击其他日期，时间选择框不会失焦，是选中状态，且点击时间选择框时不会出现下拉框
（Click the time selection box on the panel. After the time drop-down list box is displayed, click another date. The time selection box does not lose focus and is selected. In addition, no drop-down list box is displayed when you click the time selection box.）

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by CherishTheYouth**
Please make sure these boxes are checked before submitting your PR, thank you!

- [X] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [X] Make sure you are merging your commits to `dev` branch.
- [X] Add some descriptions and refer to relative issues for your PR.

## Description

Blur the timePickerInput when time-pick-panel is closed.

## Related Issue

Fixes #14728 

## Explanation of Changes

Watch ref timePickerVisible, when it is false, blur the timePickerInput el-input

### CODE REVIEW

File: packages/components/date-picker/src/date-picker-com/panel-date-pick.vue [hunk 1]
```diff
@@ -762,6 +764,13 @@ watch(
   { immediate: true }
 )
 
+// When close time-pick-panel, blur the timePickerInput
+watch(timePickerVisible, (newValue) => {
+  if (!newValue) {
+    timePickerInputRef.value?.blur()
+  }
+})
+
```
Comment (btea) [inline packages/components/date-picker/src/date-picker-com/panel-date-pick.vue:773]: Perhaps it would be better to execute `timePickerInputRef.value?.blur()` inside the `handleTimePickClose` function.

**Review by btea — APPROVED** [review]
LGTM

**Review by tolking — APPROVED** [review]
LGTM

**Comment by runaway-h** [comment]
Hello, which version is planned to be released?

**Comment by btea** [comment]
It should be released this afternoon.
