### PR TITLE
fix(components): inline style doesn't use the custom sass setting value

### LINKED ISSUE #14038: [Component] [select] select has inline style let custom sass setting invalid
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Chrome 115.0.5790.170 / MacOS 13.4.1`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgcmVhY3RpdmUsIGNvbXB1dGVkLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxudHlwZSBTaXplID0gXCJzbWFsbFwiIHwgXCJkZWZhdWx0XCIgfCBcImxhcmdlXCJcbmNvbnN0IHNpemUgPSByZWY8U2l6ZT4oJ2RlZmF1bHQnKVxuXG5jb25zdCBmb3JtID0gcmVhY3RpdmUoe1xuICByZWdpb246ICcnLFxufSlcblxuLyoqIFRoZSBmb2xsb3dpbmcgaXMgdGhlIHNldHRpbmcgSSBwdXQgaW4gaW5kZXguc2Nzc1xuQHVzZSAnc2FzczptYXAnO1xuQHVzZSAnZWxlbWVudC1wbHVzL3RoZW1lLWNoYWxrL3NyYy9taXhpbnMvZnVuY3Rpb24uc2NzcycgYXMgKjtcblxuQGZvcndhcmQgJ2VsZW1lbnQtcGx1cy90aGVtZS1jaGFsay9zcmMvY29tbW9uL3Zhci5zY3NzJyB3aXRoIChcbiAgJGNvbW1vbi1jb21wb25lbnQtc2l6ZTogKFxuICAgICdsYXJnZSc6IDUwcHgsXG4gICAgJ2RlZmF1bHQnOiAzMHB4LFxuICAgICdzbWFsbCc6IDEwcHgsXG4gICksXG4pO1xuKi9cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L2gxPlxuIDxlbC1kaXZpZGVyPjwvZWwtZGl2aWRlcj5cbiAgPHA+Q09NUE9ORU5UIE9QVElPTlM8L3A+XG4gIDxlbC1mb3JtIGxhYmVsLXdpZHRoPVwiODBweFwiPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJTaXplXCIgY2xhc3M9XCJmbGV4IGl0ZW1zLWNlbnRlclwiPlxuICAgICAgPGVsLXJhZGlvLWdyb3VwIHYtbW9kZWw9XCJzaXplXCI+XG4gICAgICAgIDxlbC1yYWRpbyBsYWJlbD1cInNtYWxsXCI+U21hbGw8L2VsLXJhZGlvPlxuICAgICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJkZWZhdWx0XCI+RGVmYXVsdDwvZWwtcmFkaW8+XG4gICAgICAgIDxlbC1yYWRpbyBsYWJlbD1cImxhcmdlXCI+TGFyZ2U8L2VsLXJhZGlvPlxuICAgICAgPC9lbC1yYWRpby1ncm91cD5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuICA8ZWwtZGl2aWRlcj48L2VsLWRpdmlkZXI+XG4gIDxwPkdpdmUgc2l6ZSBieSBlbC1mb3JtLjwvcD5cbiAgPGVsLWZvcm1cbiAgICA6bW9kZWw9XCJmb3JtXCJcbiAgICBsYWJlbC13aWR0aD1cIjE2MHB4XCJcbiAgICA6c2l6ZT1cInNpemVcIlxuICA+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFjdGl2aXR5IHpvbmVcIj5cbiAgICAgIDxlbC1zZWxlY3Qgdi1tb2RlbD1cImZvcm0ucmVnaW9uXCIgcGxhY2Vob2xkZXI9XCJwbGVhc2Ugc2VsZWN0IHlvdXIgem9uZVwiPlxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIlpvbmUgdHdvXCIgdmFsdWU9XCJiZWlqaW5nXCIgLz5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIDxlbC1kaXZpZGVyPjwvZWwtZGl2aWRlcj5cbiAgPHA+R2l2ZSBzaXplIGJ5IGVsLWZvcm0taXRlbS48L3A+XG4gIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJBY3Rpdml0eSB6b25lXCIgOnNpemU9XCJzaXplXCI+XG4gICAgPGVsLXNlbGVjdCB2LW1vZGVsPVwiZm9ybS5yZWdpb25cIiBwbGFjZWhvbGRlcj1cInBsZWFzZSBzZWxlY3QgeW91ciB6b25lXCI+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJab25lIHR3b1wiIHZhbHVlPVwiYmVpamluZ1wiIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZWwtZm9ybS1pdGVtPlxuICA8ZWwtZGl2aWRlcj48L2VsLWRpdmlkZXI+XG4gIDxwPkdpdmUgc2l6ZSBieSBlbC1zZWxlY3QuPC9wPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiIHBsYWNlaG9sZGVyPVwicGxlYXNlIHNlbGVjdCB5b3VyIHpvbmVcIiA6c2l6ZT1cInNpemVcIj5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSBvbmVcIiB2YWx1ZT1cInNoYW5naGFpXCIgLz5cbiAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiWm9uZSB0d29cIiB2YWx1ZT1cImJlaWppbmdcIiAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

- Use the recommended way to set your custom height for select in index.scss file. e.g. small is 10px, default is 30px, large is 50px.
- Change component size by options.

### What is Expected?

select component could change the size by the custom setting in index.scss file.

### What is actually happening?

Custom setting will be overwritten by inline style but not the custom setting.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by kamesan012**
closed #14038

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at db75662</samp>

Improve select component's size adaptation by using CSS variable `--el-input-height` as a fallback. Update `useSelect.ts` to implement this logic.

## Related Issue

Fixes #14038.

### <samp>🤖 Generated by Copilot at db75662</samp>

* Add fallback logic to get select size from CSS variable ([link](https://github.com/element-plus/element-plus/pull/14117/files?diff=unified&w=0#diff-ae55c3efc549b49d40b3f5b535ac2fc1572374d9309b6439f8d529b06edb1368L410-R414))

### CODE REVIEW

**Comment by zhao1995chen** [comment]
@HeftyKoo @btea @tolking 
Hi, is it possible to have a review for this PR?
If it still has something else needs to be done before the review, please inform me.
Really appreciate!

**Comment by btea** [comment]
@zhao1995chen Maybe you can directly overwrite the old value with the new css variable. I think this should be more convenient. Here is an [example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiBjbGFzcz1cIm0tMlwiIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgc2l6ZT1cImxhcmdlXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG48c3R5bGU+XG4ubS0yLmVsLXNlbGVjdCAuZWwtaW5wdXRfX2lubmVyIHtcbiAgLS1lbC1pbnB1dC1pbm5lci1oZWlnaHQ6IDYwcHg7ICBcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319).

**Comment by zhao1995chen** [comment]
@btea Please take a look at the discussion under #14038.
The discussion gives several examples explaining how to reproduce and the overwrite doesn't work.
That's why I opened an issue to ask for a fix.

**Comment by btea** [comment]
I see, and I roughly understand the problem you are encountering.

File: packages/components/select/src/useSelect.ts [hunk 1]
```diff
@@ -407,7 +407,11 @@ export const useSelect = (props, states: States, ctx) => {
         originClientHeight ||
         (input.clientHeight > 0 ? input.clientHeight + 2 : 0)
       const _tags = tags.value
-      const gotSize = getComponentSize(selectSize.value || form?.size)
+      const cssVarOfSelectSize =
+        getComputedStyle(input).getPropertyValue('--el-input-height')
+      const gotSize = cssVarOfSelectSize
+        ? cssVarOfSelectSize
+        : getComponentSize(selectSize.value || form?.size)
```
Comment (btea) [inline packages/components/select/src/useSelect.ts:414]:
```suggestion
       const gotSize = cssVarOfSelectSize || getComponentSize(selectSize.value || form?.size)
```

Comment (btea) [reply packages/components/select/src/useSelect.ts]: @kamesan012  You cannot directly commit this line of modification, and the above two lines of code should also be deleted.

Comment (kamesan012) [reply packages/components/select/src/useSelect.ts]: Thanks.

**Review by btea — APPROVED** [review]

**Comment by kamesan012** [comment]
@tolking
Can you review this PR? Thanks.

File: packages/components/select/src/useSelect.ts [hunk 2]
```diff
@@ -407,7 +407,10 @@ export const useSelect = (props, states: States, ctx) => {
         originClientHeight ||
         (input.clientHeight > 0 ? input.clientHeight + 2 : 0)
       const _tags = tags.value
-      const gotSize = getComponentSize(selectSize.value || form?.size)
+      const cssVarOfSelectSize =
+        getComputedStyle(input).getPropertyValue('--el-input-height')
```
Comment (tolking) [inline packages/components/select/src/useSelect.ts:411]: We also need to handle the [namespace](https://element-plus.org/en-US/guide/namespace.html) attribute here.

Comment (tolking) [reply packages/components/select/src/useSelect.ts:411]: '--el-input-height' -> `ns.cssVarName('input-height')`

**Review by tolking — APPROVED** [review]
