### PR TITLE
fix(components): [el-pagination] jumper prohibit decimal

### LINKED ISSUE #5509: [Bug Report] 分页器的jumper如果输入带小数的数字会导致格式化错误
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
Google Chrome 97.0.4692.71（正式版本） （64 位）

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/royalscome/pen/OJxYryB?editors=1111

### Steps to reproduce
1.引入el-pagination并使用jumper;
2.在jumper的输入框中输入带小数的数字回车，需要确保输入的数字不大于最大页码；

### What is Expected?
希望输入带小数的数字后可以自动格式化为整数，类似element ui的el-pagination

### What is actually happening?
因为这个bug导致我们在自定义table的index的时候index变成了小数

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #5509

### CODE REVIEW

File: packages/components/pagination/src/components/jumper.vue [hunk 1]
```diff
@@ -39,6 +39,7 @@ export default defineComponent({
     }
 
     function handleChange(val: number | string) {
+      val = parseInt(`${val}`, 10)
```
Comment (sxzz) [inline packages/components/pagination/src/components/jumper.vue:42]: prefer `Math.trunc`

Comment (btea) [reply packages/components/pagination/src/components/jumper.vue]: Updated.

**Review by sxzz — APPROVED** [review]
