### PR TITLE
fix(components): [watermark] content not fully displayed

### LINKED ISSUE #20336: [Style] [watermark] water remark is not displaying correctly
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.7`
- Browser / OS: `chrome 135.0.7049.42 （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-watermark`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyByZWYscmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGZvbnQgPSByZWFjdGl2ZSh7XG4gIGNvbG9yOiAncmdiYSgwLCAwLCAwLCAuMTUpJyxcbn0pXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC13YXRlcm1hcmsgOmZvbnQ9XCJmb250XCIgOmNvbnRlbnQ9XCJbJ2FkbWluJywgJ2FkbWluJ11cIj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6IDEwMHZ3O2hlaWdodDogMTAwdmg7XCIgLz5cbiAgPC9lbC13YXRlcm1hcms+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi45LjcvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi45LjcvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy41LjEwL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjUuMTAvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOS43L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi45LjcvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsidnVlVmVyc2lvbiI6IjMuNS4xMCIsImVwVmVyc2lvbiI6IjIuOS43In19)

### Steps to reproduce

In the Playground example, the text has two lines. "admin" is on the first line, and the "a" in the first line is cut off

### What is Expected?

text admin displaying correctly 

### What is actually happening?

text admin a word is cutoff 

### Additional comments

Image

### PR DESCRIPTION
**Pull request by betavs**
Please make sure these boxes are checked before submitting your PR, thank you!

close #20336

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/watermark/src/watermark.vue [hunk 1]
```diff
@@ -111,29 +111,44 @@ const appendWatermark = (base64Url: string, markWidth: number) => {
...
+      const {
+        width,
+        fontBoundingBoxAscent,
+        fontBoundingBoxDescent,
+        actualBoundingBoxAscent,
+        actualBoundingBoxDescent,
+      } = ctx.measureText(item!)
+      // Using `actualBoundingBoxAscent` to be compatible with lower version browsers (eg: Firefox < 116)
+      const height =
+        fontBoundingBoxAscent !== undefined
```
Comment (btea) [inline packages/components/watermark/src/watermark.vue:134]:
```suggestion
        !isUndefined(fontBoundingBoxAscent)
```

File: packages/components/watermark/src/watermark.vue [hunk 2]
```diff
@@ -111,29 +111,44 @@ const appendWatermark = (base64Url: string, markWidth: number) => {
...
-    defaultWidth = Math.ceil(Math.max(...sizes.map((size) => size[0])))
+
+    defaultWidth = maxWidth
     defaultHeight =
-      Math.ceil(Math.max(...sizes.map((size) => size[1]))) * contents.length +
-      (contents.length - 1) * FontGap
+      maxHeight * contents.length + (contents.length - 1) * FontGap
+
+    const angle = (Math.PI / 180) * Number(rotate)
+    const space = Math.ceil(Math.abs(Math.sin(angle) * defaultHeight) / 2)
```
Comment (btea) [inline packages/components/watermark/src/watermark.vue:147]: As far as I understand, the length of the text will not change even after ctx is rotated, so there seems no need to calculate it based on the rotation angle. 🤔

Comment (betavs) [reply packages/components/watermark/src/watermark.vue:147]: The text length does not change, but the character display is incomplete due to rotation.

**Review by btea — APPROVED** [review]
Thanks!

**Review by warmthsea — APPROVED** [review]
