### PR TITLE
fix(components): [input] use v-if throw exception

### LINKED ISSUE #11186: [Component] [input] use v-if at el-input[textarea] will cause error
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.28`
- Browser / OS: `chrome`
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IGJvb2wgPSByZWYoZmFsc2UpXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBib29sLnZhbHVlID0gdHJ1ZVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8c2VjdGlvbj5cbiAgICA8ZWwtaW5wdXQgdi1pZj1cImJvb2xcIiB0eXBlPVwidGV4dGFyZWFcIiB2LW1vZGVsPVwibXNnXCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAyLCBtYXhSb3dzOiAzIH1cIiAvPlxuICA8L3NlY3Rpb24+XG4gIDxzZWN0aW9uPlxuICAgIDxlbC1pbnB1dCB2LWlmPVwiIWJvb2xcIiB0eXBlPVwidGV4dGFyZWFcIiB2LW1vZGVsPVwibXNnXCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAyLCBtYXhSb3dzOiAzIH1cIiAvPlxuICA8L3NlY3Rpb24+XG4gIFxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

just open the link

### What is Expected?

not throw error

### What is actually happening?

throw error

### Additional comments

https://github.com/element-plus/element-plus/blob/dev/packages/components/input/src/input.vue#L492

### PR DESCRIPTION
**Pull request by acyza**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

see issue #11186 
close #11186

### CODE REVIEW

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -327,7 +327,7 @@ useResizeObserver(textarea, (entries) => {
 const resizeTextarea = () => {
   const { type, autosize } = props
 
-  if (!isClient || type !== 'textarea') return
+  if (!isClient || type !== 'textarea' || !textarea.value) return
```
Comment (btea) [inline packages/components/input/src/input.vue:330]: The judgment of `textarea.value` is added here, and the non-null assertion in lines 336 and 340 can be removed.

Comment (btea) [inline packages/components/input/src/input.vue:330]: The judgment of textarea.value is added here, and the non-null assertion in lines 336 and 340 can be removed.

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]
