### PR TITLE
fix(components): [image-viewer] Fix crossorigin

### LINKED ISSUE #15468: [Component] [image] Image 跨域问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.3`
- Element Plus Version: `2.5.1`
- Browser / OS: `Chrome/120.0.6099.216`
- Build Tool: `Nuxt`

### Related Component

- `el-image`

### Reproduction Link

[Github Repo](https://github.com/besscroft/kamera/blob/f2f63d8c8bbb664c7873f33dac52e5d01aea28cb/pages/index.vue#L91)

### Steps to reproduce

我把 element-plus 从 2.4.4 升级到 2.5.1 之后出现的问题，然后查看 releases 发现，新增了 crossorigin 属性。我单独对 crossorigin 和 referrerpolicy 属性，以及同时使用的各种值的排列组合进行了测试，依旧会出现跨域问题，所以来求助看看。项目中使用其他方式而非 el-image 的图片能够正常加载。

谢谢！

### What is Expected?

图片正常加载

### What is actually happening?

No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by kooriookami**
closed #15468

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/image-viewer/src/image-viewer.ts [hunk 1]
```diff
@@ -83,7 +83,6 @@ export const imageViewerProps = buildProps({
    */
   crossorigin: {
     type: definePropType<'anonymous' | 'use-credentials' | ''>(String),
-    default: 'anonymous',
```
Comment (chenxch) [inline packages/components/image-viewer/src/image-viewer.ts:86]: Maybe default  `''` ？

Comment (chenxch) [reply packages/components/image-viewer/src/image-viewer.ts:86]: Get.

**Review by chenxch — APPROVED** [review]
