### PR TITLE
fix(components): [tabs] incorrect boundary detection when container size is a float number

### LINKED ISSUE #23773: [Style] [tab-pane, tabs] el-tabs nav-next arrow not disabled at end when tab widths are fractional
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.30`
- Element Plus Version: `2.13.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tab-pane`
- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBUYWJQYW5lTmFtZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgeyBuZXh0VGljayB9IGZyb20gJ3Z1ZSc7XG5cbmxldCB0YWJJbmRleCA9IDJcbmNvbnN0IGVkaXRhYmxlVGFic1ZhbHVlID0gcmVmKCcyJylcbmNvbnN0IGVkaXRhYmxlVGFicyA9IHJlZihbXSk7XG5cbmNvbnN0IGFkZEVsZW1lbnRzID0gKCkgPT4geyBcbiAgZm9yIChsZXQgaSA9IDA7IGkgPD0gMjA7IGkrKykge1xuICAgIGVkaXRhYmxlVGFicy52YWx1ZS5wdXNoKHtcbiAgICB0aXRsZTogYDFUYWIgJHtpKzF9YCxcbiAgICBuYW1lOiBpKzEsXG4gICAgY29udGVudDogYFRhYiAke2krMX0gY29udGVudGAsXG4gIH0pO1xuICB9OyBcbn1cbmNvbnN0IGhhbmRsZVRhYnNFZGl0ID0gKFxuICB0YXJnZXROYW1lOiBUYWJQYW5lTmFtZSB8IHVuZGVmaW5lZCxcbiAgYWN0aW9uOiAncmVtb3ZlJyB8ICdhZGQnXG4pID0+IHtcbiAgaWYgKGFjdGlvbiA9PT0gJ2FkZCcpIHtcbiAgICBjb25zdCBuZXdUYWJOYW1lID0gYCR7Kyt0YWJJbmRleH1gXG4gICAgZWRpdGFibGVUYWJzLnZhbHVlLnB1c2goe1xuICAgICAgdGl0bGU6ICdOZXcgVGFiJyxcbiAgICAgIG5hbWU6IG5ld1RhYk5hbWUsXG4gICAgICBjb250ZW50OiAnTmV3IFRhYiBjb250ZW50JyxcbiAgICB9KVxuICAgIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gbmV3VGFiTmFtZVxuICB9IGVsc2UgaWYgKGFjdGlvbiA9PT0gJ3JlbW92ZScpIHtcbiAgICBjb25zdCB0YWJzID0gZWRpdGFibGVUYWJzLnZhbHVlXG4gICAgbGV0IGFjdGl2ZU5hbWUgPSBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZVxuICAgIGlmIChhY3RpdmVOYW1lID09PSB0YXJnZXROYW1lKSB7XG4gICAgICB0YWJzLmZvckVhY2goKHRhYiwgaW5kZXgpID0+IHtcbiAgICAgICAgaWYgKHRhYi5uYW1lID09PSB0YXJnZXROYW1lKSB7XG4gICAgICAgICAgY29uc3QgbmV4dFRhYiA9IHRhYnNbaW5kZXggKyAxXSB8fCB0YWJzW2luZGV4IC0gMV1cbiAgICAgICAgICBpZiAobmV4dFRhYikge1xuICAgICAgICAgICAgYWN0aXZlTmFtZSA9IG5leHRUYWIubmFtZVxuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfSlcbiAgICB9XG5cbiAgICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IGFjdGl2ZU5hbWVcbiAgICBlZGl0YWJsZVRhYnMudmFsdWUgPSB0YWJzLmZpbHRlcigodGFiKSA9PiB0YWIubmFtZSAhPT0gdGFyZ2V0TmFtZSlcbiAgfVxufVxub25Nb3VudGVkKCgpID0+IHtcbiAgYWRkRWxlbWVudHMoKTtcbiAgbmV4dFRpY2soKCkgPT4ge1xuICAgIGNvbnN0IHRhYjFFbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyN0YWItMScpO1xuICAgIHRhYjFFbC5zdHlsZS53aWR0aCA9ICcyMDAuM3B4JztcbiAgfSlcbn0pXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy41LjMwL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjUuMzAvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJ2dWVWZXJzaW9uIjoiMy41LjMwIn19)

### Steps to reproduce

1. Open the Element Plus Tabs playground (the scrollable tabs example with type="card" or type="border-card" and enough tabs to overflow).

2. Make one tab’s width fractional. For example, in the demo:
Give one tab a class, e.g. id="tab-1", and in style: width: 123.45px;
(Any way of ending up with a non-integer total nav width works.)

3. Add enough tabs so that the header is horizontally scrollable.

4. Use a trackpad / mouse wheel to scroll horizontally to the far right (do not click the arrow yet).

Inspect the nav element (.el-tabs__nav):

You’ll see an inline transform like translateX(-1036.69px).
The next arrow is still enabled.
Click the next arrow once:

The transform becomes an integer, e.g. translateX(-1037px).
The next arrow is now disabled and stays disabled, which matches the visual state.

### What is Expected?

When the user scrolls to the far right (via wheel/trackpad), the header should be treated as “at the end”, and the next arrow should be disabled immediately (no extra click needed).
In other words, “within a tiny floating‑point epsilon of the max offset” should be considered “at the end”.

### What is actually happening?

After wheel/trackpad scroll to the right:
The nav transform is a fractional negative value (e.g. -1036.69px).
The next arrow remains enabled, even though visually you are at the end.
Only after clicking next once more (which snaps navOffset to navSize - containerSize, an integer) does the arrow become disabled.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
fix #23773

The fix in #23774 is incomplete. 🤡
The issue can still be reproduced by adjusting the decimal part of `tab1El.style.width`. An epsilon is now introduced to snap the nav to the boundary.

[repro](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBUYWJQYW5lTmFtZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5sZXQgdGFiSW5kZXggPSAyXG5jb25zdCBlZGl0YWJsZVRhYnNWYWx1ZSA9IHJlZignMicpXG5jb25zdCBlZGl0YWJsZVRhYnMgPSByZWYoW10pXG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGFkZEVsZW1lbnRzKClcbiAgbmV4dFRpY2soKCkgPT4ge1xuICAgIGNvbnN0IHRhYjFFbCA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJyN0YWItMScpXG5cbiAgICAvLyBBZGp1c3QgaGVyZVxuICAgIHRhYjFFbC5zdHlsZS53aWR0aCA9ICcyMDAuOHB4J1xuICB9KVxufSlcblxuY29uc3QgYWRkRWxlbWVudHMgPSAoKSA9PiB7XG4gIGZvciAobGV0IGkgPSAwOyBpIDw9IDIwOyBpKyspIHtcbiAgICBlZGl0YWJsZVRhYnMudmFsdWUucHVzaCh7XG4gICAgICB0aXRsZTogYDFUYWIgJHtpICsgMX1gLFxuICAgICAgbmFtZTogaSArIDEsXG4gICAgICBjb250ZW50OiBgVGFiICR7aSArIDF9IGNvbnRlbnRgLFxuICAgIH0pXG4gIH1cbn1cbmNvbnN0IGhhbmRsZVRhYnNFZGl0ID0gKFxuICB0YXJnZXROYW1lOiBUYWJQYW5lTmFtZSB8IHVuZGVmaW5lZCxcbiAgYWN0aW9uOiAncmVtb3ZlJyB8ICdhZGQnXG4pID0+IHtcbiAgaWYgKGFjdGlvbiA9PT0gJ2FkZCcpIHtcbiAgICBjb25zdCBuZXdUYWJOYW1lID0gYCR7Kyt0YWJJbmRleH1gXG4gICAgZWRpdGFibGVUYWJzLnZhbHVlLnB1c2goe1xuICAgICAgdGl0bGU6ICdOZXcgVGFiJyxcbiAgICAgIG5hbWU6IG5ld1RhYk5hbWUsXG4gICAgICBjb250ZW50OiAnTmV3IFRhYiBjb250ZW50JyxcbiAgICB9KVxuICAgIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gbmV3VGFiTmFtZVxuICB9IGVsc2UgaWYgKGFjdGlvbiA9PT0gJ3JlbW92ZScpIHtcbiAgICBjb25zdCB0YWJzID0gZWRpdGFibGVUYWJzLnZhbHVlXG4gICAgbGV0IGFjdGl2ZU5hbWUgPSBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZVxuICAgIGlmIChhY3RpdmVOYW1lID09PSB0YXJnZXROYW1lKSB7XG4gICAgICB0YWJzLmZvckVhY2goKHRhYiwgaW5kZXgpID0+IHtcbiAgICAgICAgaWYgKHRhYi5uYW1lID09PSB0YXJnZXROYW1lKSB7XG4gICAgICAgICAgY29uc3QgbmV4dFRhYiA9IHRhYnNbaW5kZXggKyAxXSB8fCB0YWJzW2luZGV4IC0gMV1cbiAgICAgICAgICBpZiAobmV4dFRhYikge1xuICAgICAgICAgICAgYWN0aXZlTmFtZSA9IG5leHRUYWIubmFtZVxuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgfSlcbiAgICB9XG5cbiAgICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IGFjdGl2ZU5hbWVcbiAgICBlZGl0YWJsZVRhYnMudmFsdWUgPSB0YWJzLmZpbHRlcigodGFiKSA9PiB0YWIubmFtZSAhPT0gdGFyZ2V0TmFtZSlcbiAgfVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5kZW1vLXRhYnMgPiAuZWwtdGFic19fY29udGVudCB7XG4gIHBhZGRpbmc6IDMycHg7XG4gIGNvbG9yOiAjNmI3NzhjO1xuICBmb250LXNpemU6IDMycHg7XG4gIGZvbnQtd2VpZ2h0OiA2MDA7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzc3NC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3Jhdy5lc20uc2gvcHIvZWxlbWVudC1wbHVzQDIzNzc0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzc3NC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM3NzQvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzc3NC9kaXN0L2luZGV4LmNzcyJ9fQ==)

## Summary by CodeRabbit

* **Refactor**
  * Consolidated numeric comparison utilities for consistency across components.
  * Switched measurement logic to more precise positioning values to improve layout calculations.

* **Bug Fixes / UX**
  * Improved tab scrolling and active-tab positioning for smoother navigation.
  * Enhanced table event handling precision to reduce edge-case layout/scroll glitches.

* **Chore**
  * Re-exported numeric utilities to make them broadly available.

### CODE REVIEW

**Review by btea — APPROVED** [review]
The precision issue has been handled multiple times in the table's tooltip boundary judgment logic.

**Comment by btea** [comment]
https://github.com/element-plus/element-plus/blob/370153a2421567c5273c6d6bf4b7ba39c3aa0084/packages/components/table/src/table-body/events-helper.ts#L17-L19

**Comment by rzzf** [comment]
> https://github.com/element-plus/element-plus/blob/370153a2421567c5273c6d6bf4b7ba39c3aa0084/packages/components/table/src/table-body/events-helper.ts#L17-L19

Nice!

**Comment by patienry** [comment]
I think the change is reasonable, but I could not reproduce the issue described in #23773 on Windows.

02585EBE-E827-4649-8F1B-81E5461454C6

https://github.com/user-attachments/assets/8a4b0025-473a-4077-9fb7-c3bdb24a11e7

**Review by keeplearning66 — COMMENTED** [review]
Since `isGreaterThan` is used in both `table` and `tabs`, is it necessary to extract it into a common method? 🤔

**Comment by rzzf** [comment]
> I think the change is reasonable, but I could not reproduce the issue described in #23773 on Windows.


This may be affected by float number precision. You can try modifying the decimal part to reproduce the issue.

<details><summary>Videos</summary>

Before:


https://github.com/user-attachments/assets/9af525ee-2b21-404a-ab69-470bb2265fda

After:


https://github.com/user-attachments/assets/85267609-20d7-4cd0-be42-5d3bfb1e28f2



</details>

File: packages/utils/numbers.ts [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export function isGreaterThan(a: number, b: number, epsilon = 0.03) {
```
Comment (btea) [inline packages/utils/numbers.ts:6]: It would be best to add a note explaining this, such as: "Due to browser rendering and calculation precision loss issues, boundary checks cannot be based solely on value equality; a certain range of fluctuation is permissible."

Comment (rzzf) [reply packages/utils/numbers.ts:6]: done

File: packages/components/tabs/src/tab-nav.tsx [hunk 2]
```diff
@@ -201,20 +201,22 @@ const TabNav = defineComponent({
 
       const activeTabBounding = activeTab.getBoundingClientRect()
       const navScrollBounding = navScroll.getBoundingClientRect()
+      // nav has a 1px border width
+      const navScrollLeft = navScrollBounding.left + 1
+      const navScrollRight = navScrollBounding.right - 1
+      const navBounding = nav.getBoundingClientRect()
```
Comment (rzzf) [inline packages/components/tabs/src/tab-nav.tsx:207]: [repro](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFic1xuICAgIHYtbW9kZWw9XCJlZGl0YWJsZVRhYnNWYWx1ZVwiXG4gICAgdHlwZT1cImNhcmRcIlxuICAgIGVkaXRhYmxlXG4gICAgY2xhc3M9XCJkZW1vLXRhYnNcIlxuICAgIEBlZGl0PVwiaGFuZGxlVGFic0VkaXRcIlxuICA+XG4gICAgPGVsLXRhYi1wYW5lXG4gICAgICB2LWZvcj1cIml0ZW0gaW4gZWRpdGFibGVUYWJzXCJcbiAgICAgIDprZXk9XCJpdGVtLm5hbWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS50aXRsZVwiXG4gICAgICA6bmFtZT1cIml0ZW0ubmFtZVwiXG4gICAgPlxuICAgICAge3sgaXRlbS5jb250ZW50IH19XG4gICAgPC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuXG4gIDxkaXY+Rmlyc3QgY2xpY2sgdGhlIE5leHQgYnV0dG9uLCB0aGVuIGNsaWNrIHRoZSBnb1RvRmlyc3RUYWIgYnV0dG9uLjwvZGl2PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImdvdG9GaXJzdFRhYlwiPmdvdG9GaXJzdFRhYjwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuaW1wb3J0IHR5cGUgeyBUYWJQYW5lTmFtZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZWRpdGFibGVUYWJzVmFsdWUgPSByZWYoJzInKVxuY29uc3QgZWRpdGFibGVUYWJzID0gcmVmKFtdKVxuXG5jb25zdCBnb3RvRmlyc3RUYWIgPSAoKSA9PiB7XG4gIGVkaXRhYmxlVGFic1ZhbHVlLnZhbHVlID0gJzEnXG59XG5cbmNvbnN0IGFkZEVsZW1lbnRzID0gKCkgPT4ge1xuICBmb3IgKGxldCBpID0gMDsgaSA8PSAxMDsgaSsrKSB7XG4gICAgZWRpdGFibGVUYWJzLnZhbHVlLnB1c2goe1xuICAgICAgdGl0bGU6IGAxVGFiICR7aSArIDF9YCxcbiAgICAgIG5hbWU6IGAke2kgKyAxfWAsXG4gICAgICBjb250ZW50OiBgVGFiICR7aSArIDF9IGNvbnRlbnRgLFxuICAgIH0pXG4gIH1cbn1cbmNvbnN0IGhhbmRsZVRhYnNFZGl0ID0gKFxuICB0YXJnZXROYW1lOiBUYWJQYW5lTmFtZSB8IHVuZGVmaW5lZCxcbiAgYWN0aW9uOiAncmVtb3ZlJyB8ICdhZGQnXG4pID0+IHtcbiAgaWYgKGFjdGlvbiA9PT0gJ2FkZCcpIHtcbiAgICBjb25zdCBsZW4gPSBlZGl0YWJsZVRhYnMudmFsdWUubGVuZ3RoXG4gICAgY29uc3QgbmV3VGFiTmFtZSA9IGAke2xlbiArIDF9YFxuICAgIGVkaXRhYmxlVGFicy52YWx1ZS5wdXNoKHtcbiAgICAgIHRpdGxlOiAnTmV3IFRhYicsXG4gICAgICBuYW1lOiBuZXdUYWJOYW1lLFxuICAgICAgY29udGVudDogJ05ldyBUYWIgY29udGVudCcsXG4gICAgfSlcbiAgICBlZGl0YWJsZVRhYnNWYWx1ZS52YWx1ZSA9IG5ld1RhYk5hbWVcbiAgfSBlbHNlIGlmIChhY3Rpb24gPT09ICdyZW1vdmUnKSB7XG4gICAgY29uc3QgdGFicyA9IGVkaXRhYmxlVGFicy52YWx1ZVxuICAgIGxldCBhY3RpdmVOYW1lID0gZWRpdGFibGVUYWJzVmFsdWUudmFsdWVcbiAgICBpZiAoYWN0aXZlTmFtZSA9PT0gdGFyZ2V0TmFtZSkge1xuICAgICAgdGFicy5mb3JFYWNoKCh0YWIsIGluZGV4KSA9PiB7XG4gICAgICAgIGlmICh0YWIubmFtZSA9PT0gdGFyZ2V0TmFtZSkge1xuICAgICAgICAgIGNvbnN0IG5leHRUYWIgPSB0YWJzW2luZGV4ICsgMV0gfHwgdGFic1tpbmRleCAtIDFdXG4gICAgICAgICAgaWYgKG5leHRUYWIpIHtcbiAgICAgICAgICAgIGFjdGl2ZU5hbWUgPSBuZXh0VGFiLm5hbWVcbiAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICAgIH0pXG4gICAgfVxuXG4gICAgZWRpdGFibGVUYWJzVmFsdWUudmFsdWUgPSBhY3RpdmVOYW1lXG4gICAgZWRpdGFibGVUYWJzLnZhbHVlID0gdGFicy5maWx0ZXIoKHRhYikgPT4gdGFiLm5hbWUgIT09IHRhcmdldE5hbWUpXG4gIH1cbn1cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGFkZEVsZW1lbnRzKClcbn0pXG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cblxuYm9keSB7XG4gIG1hcmdpbjogMDtcbn1cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

**Review by keeplearning66 — APPROVED** [review]
👍
