### PR TITLE
fix(components): [el-dropdown-menu] adjust html tag

### LINKED ISSUE #6227: [Bug Report] Dropdown component generates invalid HMTL
### Element Plus version
2.0.2

### OS/Browsers version
Irrelevant

### Vue version
3.2.31

### Reproduction Link
https://jsfiddle.net/okdw9atq/1/

### Steps to reproduce
Bug is present in the doc: [https://element-plus.org/en-US/component/dropdown.html#basic-usage](Dropdown Component)

### What is Expected?
A valid HTML is expected:

```
    <div class="el-scrollbar__view el-dropdown__list" style="">
      <ul
        class="el-dropdown-menu el-dropdown-menu--default"
        tabindex="-1"
        role="menu"
        style="outline: none;"
      >
        <!--v-if--><li
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 1
        </li><!--v-if--><li
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 2
        </li><!--v-if--><li
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 3
        </li>
      </ul>
    </div>
```

### What is actually happening?
Generated HTML is:

```
    <ul class="el-scrollbar__view el-dropdown__list" style="">
      <ul
        class="el-dropdown-menu el-dropdown-menu--default"
        tabindex="-1"
        role="menu"
        style="outline: none;"
      >
        <!--v-if--><div
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 1
        </div><!--v-if--><div
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 2
        </div><!--v-if--><div
          data-el-collection-item=""
          aria-disabled="false"
          class="el-dropdown-menu__item"
          tabindex="-1"
          role="menuitem"
        >
          <!--v-if-->Action 3
        </div>
      </ul>
    </ul>
```

Two nested `ul`, no `li`.

### PR DESCRIPTION
**Pull request by msidolphin**
fix #6227

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/dropdown/src/dropdown-item-impl.vue [hunk 1]
```diff
@@ -1,10 +1,10 @@
 <template>
-  <div
+  <li
     v-if="divided"
     :class="ns.bem('menu', 'item', 'divided')"
     v-bind="$attrs"
-  ></div>
-  <div
+  ></li>
```
Comment (JeremyWuuuuu) [inline packages/components/dropdown/src/dropdown-item-impl.vue:6]: Maybe we should keep the original `div` but add `role="separator"` to it.

Comment (msidolphin) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: > Maybe we should keep the original `div` but add `role="separator"` to it.

But div should not be child element of ul, right?

Comment (amaury-hanser) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: Yes, `div` can't be a child of `ul`.  
See: [\<ul\>: The Unordered List element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul)

> Permitted content [of ul] | Zero or more \<li\>, \<script\> and \<template\> elements.

Comment (JeremyWuuuuu) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: > Yes, div can't be a child of ul.
See: [<ul>: The Unordered List element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul)

I see, should we add `role="separator"` for the `li` element?

Comment (amaury-hanser) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: I don't think that it's needed as a `li` is already a semantic element and will be declared as an item.

In the `<el-dropdown-item>`, there is an *attribute* `divider`, but I'm not sure to understand why it would be needed as it seems to do nothing when I test it in the fiddle.

I'm pretty new to *element+* so it might be interesting to wait for a more experienced opinion.

**Review by jw-foss — APPROVED** [review]
