### PR TITLE
fix(time-picker): model-value should sync when disable-attrs was updated

### LINKED ISSUE #2452: [Bug Report] `el-time-picker` does not emit `change` event if internal value is changed due to `disabledHours/Minutes/Seconds`
### Element Plus version
1.0.2-beta.54

### OS/Browsers version
macOS 11.4

### Vue version
3.1.4

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-2qfmn?file=/src/App.vue

### Steps to reproduce
1. Open the time-picker and increase hour to 9.
2. The outer modelValue is changed properly.
3. Increase the number-input to 10.
4. The time-picker is updated, but the outer modelValue is NOT changed,

### What is Expected?
The outer modelValue is 2000-01-01T0**2**:00:00.000Z.

### What is actually happening?
The outer modelValue is 2000-01-01T0**1**:00:00.000Z.

### PR DESCRIPTION
**Pull request by msidolphin**
Please make sure these boxes are checked before submitting your PR, thank you!

fix: #2452 

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]

File: packages/time-picker/src/common/picker.vue [hunk 1]
```diff
@@ -139,6 +139,7 @@ import { EVENT_CODE } from '@element-plus/utils/aria'
 import { useGlobalConfig, isEmpty } from '@element-plus/utils/util'
 import { elFormKey, elFormItemKey } from '@element-plus/form'
 import { defaultProps } from './props'
+import isEqual from 'lodash/isEqual'
```
Comment (JeremyWuuuuu) [inline packages/time-picker/src/common/picker.vue:142]: Minor: put this line below line#134

**Comment by JeremyWuuuuu** [comment]
Please address the only comment I left, or we can open a follow up issue to do that.

**Comment by msidolphin** [comment]
> Please address the only comment I left, or we can open a follow up issue to do that.

done
