### PR TITLE
fix(components): [watermark] mutationObserver should work

### LINKED ISSUE #14819: [Component] [watermark] 水印组件 MutationObserver 未生效无法做到防止篡改水印
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.2`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-watermark`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbFdhdGVybWFyayB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IHdhdGVybWFya1JlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsV2F0ZXJtYXJrPiB8IG51bGw+KG51bGwpXG5cbmNvbnN0IHJlbW92ZURvbSA9ICgpID0+IHtcbiAgY29uc3QgZGl2ID0gd2F0ZXJtYXJrUmVmLnZhbHVlIS4kZWwucXVlcnlTZWxlY3RvckFsbCgnZGl2JylbMV1cbiAgZGl2Py5yZW1vdmUoKVxufVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtd2F0ZXJtYXJrIHJlZj1cIndhdGVybWFya1JlZlwiPlxuICAgIDxkaXYgc3R5bGU9XCJoZWlnaHQ6IDUwMHB4XCIgLz5cbiAgPC9lbC13YXRlcm1hcms+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwicmVtb3ZlRG9tXCI+XG4gICAg5Yig6Zmk5rC05Y2wXG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

查看复现链接, 点击删除水印按钮

### What is Expected?

删除水印后，水印能自动重新生成

### What is actually happening?

删除水印后，水印无法自动重新生成

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Fuphoenixes**
closed #14819

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 7b8a093</samp>

Enhance watermark component to handle dynamic elements. Add `subtree` and `childList` options to `MutationObserver` in `watermark.vue`.

## Related Issue

Fixes #14819 .

### <samp>🤖 Generated by Copilot at 7b8a093</samp>

* Add two options to the MutationObserver constructor to monitor dynamic changes in the target container ([link](https://github.com/element-plus/element-plus/pull/14822/files?diff=unified&w=0#diff-c6c90c95997cf2bd5412dcad208a28a43a70addb4960c01a4a22440228b0a315R228-R229))

### CODE REVIEW

**Review by ryuhangyeong — APPROVED** [review]
@TomatoDroid 

Could you consider this review?

**Review by btea — APPROVED** [review]

**Comment by Fuphoenixes** [comment]
这个pr可以合了吗？水印组件无法防篡改应该算是这个组件比较严重的问题

File: packages/components/watermark/src/watermark.vue [hunk 1]
```diff
@@ -225,5 +225,7 @@ const onMutate = (mutations: MutationRecord[]) => {
 
 useMutationObserver(containerRef, onMutate, {
   attributes: true,
+  subtree: true,
```
Comment (tolking) [inline packages/components/watermark/src/watermark.vue:228]:
```suggestion
```

The `watermarkRef` is always on the next level nodes of `containerRef`. So the `subtree` attribute looks like redundant.

Comment (Fuphoenixes) [reply packages/components/watermark/src/watermark.vue:228]: 你好，我试过了，如果去掉`subtree`，则不能监听`watermarkRef`节点的属性修改了，`childList`仅仅只能监听子节点是否被删除了。也就是说，可以通过控制台去掉`background-image`样式，来做到删除水印的效果了。
image
image
image

Comment (tolking) [reply packages/components/watermark/src/watermark.vue:228]: You are right

**Review by tolking — APPROVED** [review]

**Comment by tenglongwentian** [comment]
为什么图片和文字水印不能组合使用？当图片水印存在的时候，文字水印就看不到。无法共存
