### PR TITLE
fix(components): [mention] the input event is not be triggered when selecting a mention

### LINKED ISSUE #20548: [Component] [mention] The input event is not triggered after selecting a mention
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.7`
- Element Plus Version: `2.9.8`
- Browser / OS: `Chrome 135.0.7049.96`
- Build Tool: `Vite`

### Related Component

- `el-mention`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtbWVudGlvblxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBAaW5wdXQ9XCJoYW5kbGVJbnB1dFwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMzIwcHhcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCcnKVxuXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAge1xuICAgIGxhYmVsOiAnRnVwaG9lbml4ZXMnLFxuICAgIHZhbHVlOiAnRnVwaG9lbml4ZXMnLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdrb29yaW9va2FtaScsXG4gICAgdmFsdWU6ICdrb29yaW9va2FtaScsXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0plcmVteScsXG4gICAgdmFsdWU6ICdKZXJlbXknLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdidGVhJyxcbiAgICB2YWx1ZTogJ2J0ZWEnLFxuICB9LFxuXSlcblxuY29uc3QgaGFuZGxlSW5wdXQgPSAodmFsOnN0cmluZykgPT4ge1xuICBjb25zb2xlLmxvZygnaW5wdXQnLCB2YWwpXG59XG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

When we type the '@' symbol and then select a mention, the input event is not triggered. Clearly, this does not meet our expectations.

### What is Expected?

The input event is triggered when selecting a mention.

### What is actually happening?

The input event is not triggered when selecting a mention.

### Additional comments

related to [#20527](https://github.com/element-plus/element-plus/issues/20527)

### PR DESCRIPTION
**Pull request by w2xi**
fix #20548

related to ##20527

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by Fuphoenixes — APPROVED** [review]

**Review by warmthsea — APPROVED** [review]
LGTM

File: packages/components/mention/src/mention.vue [hunk 1]
```diff
@@ -122,6 +126,7 @@ const hoveringId = computed(() => {
 
 const handleInputChange = (value: string) => {
   emit(UPDATE_MODEL_EVENT, value)
+  emit(INPUT_EVENT, value)
   syncAfterCursorMove()
 }
```
Comment (btea) [inline packages/components/mention/src/mention.vue:131]: The input event is directly bound to the `el-input` component through $attrs, so `handleInputChange` will not be triggered and may be removed.

https://github.com/element-plus/element-plus/blob/0589201ad44a9110a516cd123cfe68e666a16454/packages/components/mention/src/mention.vue#L4

Comment (w2xi) [reply packages/components/mention/src/mention.vue:131]: [attrs#nested-component-inheritance]https://vuejs.org/guide/components/attrs.html#nested-component-inheritance

> Forwarded attributes do not include any attributes that are declared as props, or v-on listeners of declared events by <MyButton> - in other words, the declared props and listeners have been "consumed" by <MyButton>.

As mentioned above, since we already declared the input event listener on the mention component, `$attrs` will not include the input event. So it works.

Comment (w2xi) [reply packages/components/mention/src/mention.vue:131]: There's a demo available for testing.
[Demo](https://play.vuejs.org/#eNp9UsFO4zAQ/ZWRtVJSqZscdk9sWi1UPcABEHDDHEIyTd06dmQ7pSjKvzN22lAJ6CmZee+Nnz2vY5dNk+xaZBcss4URjQOLrm3mXIm60cbBYi1kCSuja4iSNFReEHHFVaGVdbDOVSlxIUWxhRnEE5jNoeMKwMNaYiJ1FUeFx6MJV/0XJX0qPCcNhIM2Swef5JAKh3Ujc4dUAWSD1//hqBlnJ8Y4o3YY89kPJQEpibP0ZBKbMmfJwUpUycZqRY8TTHFW6LoREs1d4wQ55OxisOuxXEr9dhN6zrQ4PfaLNRbbb/obu/c9zu4NWjQ7sjJiLjcVugFePt7inv5HsNZlK4l9BnxAer3WexxoV62/sTnhBbfXYcVCVU92uXeo7PFS3qhn9oHPGS18cebqn3b/JH+DjlZFrzim5ed4ddBavHTOWOgPKfPp+ue3m6ZQ4kooXNbC2fj5kKEXCsKQoDEhxxnRdBwXT4h2JixdB3evGyxcssV3G//KvWgCfYgnZakUO9j9fhWqpMQMKGfzLKX+l7z0H9vXG1U=)

Comment (btea) [reply packages/components/mention/src/mention.vue:131]: The previous code did not declare input emit, so the internally bound `handleInputChange` should be useless. It will take effect only after you add input emit. 👍

**Review by btea — APPROVED** [review]
