### PR TITLE
fix(components): [form-item] do not validate without `prop` property

### LINKED ISSUE #9885: [Component] [form-item] Implicit required validation rule auto-creation based on "required" prop
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.39`
- Element Plus Version: `2.2.17`
- Browser / OS: `Firefox 105 / Windows 10`
- Build Tool: `Vue CLI`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJycpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZm9ybT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPSdsYWJlbCcgcmVxdWlyZWQ+XG4gIFx0XHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<el-form-item label="label" required><el-input v-model="msg" /></el-form-item>
```
We use backend validation and "required" prop on form-item for visualization purposes only (asterisk).
So "prop" is not set intentionally.

### What is Expected?

No required validation when "prop" is undefined

### What is actually happening?

"is required" validation error is always shown on such form items

### Additional comments

Now the only way to disable unneeded required validation is to set :validate-event="false" on every(!) input on the form.This is very inconvenient. Please add check for prop !== undefined in form-item.vue:200

In Element-UI required prop on form-item worked as expected.

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #9885

### CODE REVIEW

**Review by ryuhangyeong — APPROVED** [review]

**Comment by holazz** [comment]
I think that if the prop is not passed, the validation can be skipped without going through the validation logic. Like this:

```ts
const validate: FormItemContext['validate'] = async (trigger, callback) => {
  if (!props.prop) return false
  ...
}
```

This will be consistent with ElementUI. WDYT?

**Comment by btea** [comment]
Maybe I can modify it here
https://github.com/element-plus/element-plus/blob/268d87a03bbf5865d49f6177f2868018614c15a5/packages/components/form/src/form-item.vue#L185-L187

```ts
if (props.rules && prop) {
  rules.push(...ensureArray(props.rules))
}
```

**Comment by holazz** [comment]
> Maybe I can modify it here
> 
> https://github.com/element-plus/element-plus/blob/268d87a03bbf5865d49f6177f2868018614c15a5/packages/components/form/src/form-item.vue#L185-L187
> 
> ```ts
> if (props.rules && prop) {
>   rules.push(...ensureArray(props.rules))
> }
> ```

Changing here also seems to execute the entire validation process. IMO, there is no need to execute the rest of the logic in the `validate` function when the `prop` is `undefined`. Or am I missing something? 🤔

**Comment by btea** [comment]
Oops, maybe I misunderstood what you meant, the advice above is great, I'll update it 😅

File: packages/components/form/src/form-item.vue [hunk 1]
```diff
@@ -178,26 +178,26 @@ const fieldValue = computed(() => {
 })
 
 const normalizedRules = computed(() => {
-  const { required } = props
+  const { required, prop } = props
 
   const rules: FormItemRule[] = []
 
-  if (props.rules) {
+  if (props.rules && prop) {
```
Comment (holazz) [inline packages/components/form/src/form-item.vue:185]: Maybe there is no need to add extra conditions because the `prop` here must not be `undefined`.

File: packages/components/form/src/form-item.vue [hunk 2]
```diff
@@ -178,26 +178,26 @@ const fieldValue = computed(() => {
...
     rules.push(...ensureArray(props.rules))
   }
 
   const formRules = formContext?.rules
-  if (formRules && props.prop) {
+  if (formRules && prop) {
```
Comment (holazz) [inline packages/components/form/src/form-item.vue:190]: Same here.

File: packages/components/form/src/form-item.vue [hunk 3]
```diff
@@ -178,26 +178,26 @@ const fieldValue = computed(() => {
...
-      props.prop
+      prop
     ).value
     if (_rules) {
       rules.push(...ensureArray(_rules))
     }
   }
 
-  if (required !== undefined) {
+  if (required !== undefined && prop !== undefined) {
```
Comment (holazz) [inline packages/components/form/src/form-item.vue:200]: Same here.

File: packages/components/form/src/form-item.vue (hunk 1 above)
Comment (btea) [reply packages/components/form/src/form-item.vue]: Done.

**Comment by holazz** [comment]
Based on the changes now, the `&& props.prop` on line#190 doesn't seem to be needed either.

**Comment by btea** [comment]
If `&& props.prop` is removed, then line 193 should be changed to `props.prop || ''`, otherwise there will be a ts error, so I think it's okay to keep the status quo, what do you think? 🤔

**Comment by holazz** [comment]
> If `&& props.prop` is removed, then line 193 should be changed to `props.prop || ''`, otherwise there will be a ts error, so I think it's okay to keep the status quo, what do you think? 🤔

I feel like it's possible to use a non-null assertion in line 193: `props.prop!`.

**Review by holazz — APPROVED** [review]

**Comment by btea** [comment]
@holazz Thanks for your review
