### PR TITLE
fix(table): get global config

### LINKED ISSUE #992: Global config of size not working with table
### Version
element-plus: 1.0.1-beta.8
vue: 3.0.4

### Environment
macOS 10.15.7

### Step to reproduce

1. app.use(ElementPlus, { size: 'small', zIndex: 3000 });
2. Use table in vue file
3. The size of the table is always as medium

### What is expected?
Global config of size working with table and other components

### What is actually happening?
Global config of size just working with button

### PR DESCRIPTION
**Pull request by justwiner**
* [table] fix #992

### CODE REVIEW

File: packages/table/src/table/style-helper.ts [hunk 1]
```diff
@@ -174,7 +187,7 @@ function useStyle(
     }
   }
   const tableSize = computed(() => {
-    return props.size
+    return props.size || getConfig('size')
```
Comment (JeremyWuuuuu) [inline packages/table/src/table/style-helper.ts:190]: use `useGlobalConfig` in `@element-plus/utils/util` instead

**Review by jw-foss — APPROVED** [review]
