### PR TITLE
fix(components): [loading] namespace config

### LINKED ISSUE #11954: [Style] [loading] Use the namespace set by el-config-provider="ep", and the class name of v-loading/el-loading is still the class name of el -
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 110.0.5481.178 / Win 10`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Github Repo](https://github.com/vela666/demo2)

### Steps to reproduce

Use v-loading/el-loading after setting namespace

### What is Expected?

className true

### What is actually happening?

className error

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #11954

### CODE REVIEW

File: packages/components/loading/src/loading.ts [hunk 1]
```diff
@@ -77,7 +78,8 @@ export function createLoadingComponent(options: LoadingOptionsResolved) {
   const elLoadingComponent = defineComponent({
     name: 'ElLoading',
     setup(_, { expose }) {
-      const ns = useNamespace('loading')
+      const namespace = useGlobalConfig('namespace')
+      const ns = useNamespace('loading', namespace)
```
Comment (jw-foss) [inline packages/components/loading/src/loading.ts:82]:
```ts
import { useGlobalComponentSettings } from '@element-plus/components/config-provider'

const { ns } = useGlobalComponentSettings('loading')
```

**Review by jw-foss — APPROVED** [review]
