### PR TITLE
fix(components): [tree-v2] call `collapseNode/expandNode` `expand/collapse` icon status error

### LINKED ISSUE #22196: [Component] [tree-v2] el-tree-v2中的collapseNode和expandNode方法展开和收起时图标不动，递归调用collapseNode收起所有节点也不能生效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.17`
- Element Plus Version: `2.11.2`
- Browser / OS: `Chrome/133.0.0.0 `
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNvbGxhcHNlQWxsTm9kZVwiPuaUtui1t+aJgOaciTwvZWwtYnV0dG9uPlxuICA8ZWwtdHJlZS12MiA6ZGF0YT1cInRyZWVEYXRhXCIgaGlnaGxpZ2h0LWN1cnJlbnQgOmV4cGFuZC1vbi1jbGljay1ub2RlPVwiZmFsc2VcIiByZWY9XCJyZWZUcmVlXCI+XG4gICAgPHRlbXBsYXRlICNkZWZhdWx0PVwieyBub2RlIH1cIj5cbiAgICAgIDxkaXYgQGRibGNsaWNrPVwidG9nZ2xlRXhwYW5kKG5vZGUpXCI+e3sgbm9kZS5sYWJlbCB9fTwvZGl2PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtdHJlZS12Mj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWFjdGl2ZSwgdXNlVGVtcGxhdGVSZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRyZWVEYXRhID0gcmVhY3RpdmUoW1xuICB7XG4gICAgaWQ6ICcxJyxcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBpZDogJzEtMScsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMSdcbiAgICAgIH1cbiAgICBdXG4gIH1cbl0pXG5cbmNvbnN0IHJlZlRyZWUgPSB1c2VUZW1wbGF0ZVJlZigncmVmVHJlZScpXG5mdW5jdGlvbiB0b2dnbGVFeHBhbmQobm9kZSkge1xuICBpZiAobm9kZS5leHBhbmRlZCkge1xuICAgIHJlZlRyZWUudmFsdWUuY29sbGFwc2VOb2RlKG5vZGUpXG4gIH0gZWxzZSB7XG4gICAgcmVmVHJlZS52YWx1ZS5leHBhbmROb2RlKG5vZGUpXG4gIH1cbn1cblxuZnVuY3Rpb24gY29sbGFwc2VBbGxOb2RlKCkge1xuIGNvbnN0IHJvb3ROb2RlID0gcmVmVHJlZS52YWx1ZS5nZXROb2RlKCcxJylcbiBjb2xsYXBzZUFsbChbcm9vdE5vZGVdKVxufVxuXG4vLyDpgJLlvZLmlLbotbfmiYDmnInlsZXlvIDnmoToioLngrlcbmZ1bmN0aW9uIGNvbGxhcHNlQWxsKG5vZGVzKSB7XG4gIG5vZGVzLmZvckVhY2gobm9kZSA9PiB7XG4gICAgaWYgKG5vZGUuZXhwYW5kZWQpIHtcbiAgICAgIHJlZlRyZWUudmFsdWUuY29sbGFwc2VOb2RlKG5vZGUpXG4gICAgfVxuICAgIC8vIOmAkuW9kuWkhOeQhuWtkOiKgueCuVxuICAgIGlmIChub2RlLmNoaWxkcmVuPy5sZW5ndGggPiAwKSB7XG4gICAgICBjb2xsYXBzZUFsbChub2RlLmNoaWxkcmVuKVxuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkIGxhbmc9XCJzY3NzXCI+PC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTEuMi9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjExLjIvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTEuMi9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTEuMi9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJlcFZlcnNpb24iOiIyLjExLjIifX0=)

### Steps to reproduce

关掉expand-on-click-node以后，手动实现双击展开，调用collapseNode和expandNode这二个方法，展开时，节点左侧箭头没有动，只是把节点展开了（单击左侧箭头展开和收起，箭头方向可以跟着动）。
如果是点箭头展开，点击上面的【收起所有】按钮，可以正常收起，所有展开节点，如果是双击通过expandNode方法展开的，点【收起所有】按钮无法收起所有节点。

### What is Expected?

通过collapseNode和expandNode这二个方法调用展开和收起的逻辑能与点击箭头的逻辑保持一致

### What is actually happening?

collapseNode和expandNode这2个方法与点击箭头展开逻辑不一致，导致展开后通过collapseNode收起无效。

### Additional comments

_(empty)_

Image

Image

### PR DESCRIPTION
**Pull request by jevin98**
fix #22196

### CODE REVIEW

File: packages/components/tree-v2/src/tree-node.vue [hunk 1]
```diff
@@ -50,7 +50,7 @@
         @change="handleCheckChange"
         @click.stop
       />
-      <el-node-content :node="{ ...node, expanded }" />
+      <el-node-content :node="contentNode" />
```
Comment (rzzf) [inline packages/components/tree-v2/src/tree-node.vue]:
```suggestion
      <el-node-content :node="node" />
```

The `node` already contains the correct `expanded` property.

https://github.com/element-plus/element-plus/blob/a228b3a514106bf6d9025615349fbe0de626cefb/packages/components/tree-v2/src/tree.vue#L21-L22

File: packages/components/tree-v2/src/tree-node.vue [hunk 2]
```diff
@@ -86,6 +86,10 @@ const ns = useNamespace('tree')
 const indent = computed(() => tree?.props.indent ?? 16)
 const icon = computed(() => tree?.props.icon ?? CaretRight)
 
+const contentNode = computed(() => {
+  return Object.assign(props.node, { expanded: props.expanded })
+})
+
```
Comment (rzzf) [inline packages/components/tree-v2/src/tree-node.vue]:
```suggestion
```

**Comment by rzzf** [comment]
It seems to be related to #21066.

**Comment by jevin98** [comment]
@cszhjh done

**Comment by jevin98** [comment]
> It seems to be related to #21066.

The problem is that `<el-node-content :node="{ ...node, expanded }" />` assigns a new object here, which causes the `node` modified inside the `refTree.value.expandNode(node)` function to be different from the `node` in the original data source.

**Review by rzzf — APPROVED** [review]
LGTM.

**Comment by btea** [comment]
This modification will cause problems with dynamic rendering icons. [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgOmhlaWdodD1cIjIwMFwiXG4gID5cbiAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IG5vZGUgfVwiPlxuICAgICAgPGVsLWljb24gY2xhc3M9XCJlbC1pY29uLS1sZWZ0XCI+XG4gICAgICAgIDxEb2N1bWVudCB2LWlmPVwibm9kZS5pc0xlYWZcIiAvPlxuICAgICAgICA8Rm9sZGVyIHYtZWxzZS1pZj1cIiFub2RlLmV4cGFuZGVkXCIgLz5cbiAgICAgICAgPEZvbGRlck9wZW5lZCB2LWVsc2UgLz5cbiAgICAgIDwvZWwtaWNvbj5cbiAgICAgIDxzcGFuIGNsYXNzPVwicHJlZml4XCIgOmNsYXNzPVwieyAnaXMtbGVhZic6IG5vZGUuaXNMZWFmIH1cIlxuICAgICAgICA+W0VsZW1lbnRQbHVzXTwvc3BhblxuICAgICAgPlxuICAgICAgPHNwYW4+e3sgbm9kZS5sYWJlbCB9fTwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXRyZWUtdjI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgRG9jdW1lbnQsIEZvbGRlciwgRm9sZGVyT3BlbmVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmludGVyZmFjZSBUcmVlIHtcbiAgaWQ6IHN0cmluZ1xuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGdldEtleSA9IChwcmVmaXg6IHN0cmluZywgaWQ6IG51bWJlcikgPT4ge1xuICByZXR1cm4gYCR7cHJlZml4fS0ke2lkfWBcbn1cblxuY29uc3QgY3JlYXRlRGF0YSA9IChcbiAgbWF4RGVlcDogbnVtYmVyLFxuICBtYXhDaGlsZHJlbjogbnVtYmVyLFxuICBtaW5Ob2Rlc051bWJlcjogbnVtYmVyLFxuICBkZWVwID0gMSxcbiAga2V5ID0gJ25vZGUnXG4pOiBUcmVlW10gPT4ge1xuICBsZXQgaWQgPSAwXG4gIHJldHVybiBBcnJheS5mcm9tKHsgbGVuZ3RoOiBtaW5Ob2Rlc051bWJlciB9KVxuICAgIC5maWxsKGRlZXApXG4gICAgLm1hcCgoKSA9PiB7XG4gICAgICBjb25zdCBjaGlsZHJlbk51bWJlciA9XG4gICAgICAgIGRlZXAgPT09IG1heERlZXAgPyAwIDogTWF0aC5yb3VuZChNYXRoLnJhbmRvbSgpICogbWF4Q2hpbGRyZW4pXG4gICAgICBjb25zdCBub2RlS2V5ID0gZ2V0S2V5KGtleSwgKytpZClcbiAgICAgIHJldHVybiB7XG4gICAgICAgIGlkOiBub2RlS2V5LFxuICAgICAgICBsYWJlbDogbm9kZUtleSxcbiAgICAgICAgY2hpbGRyZW46IGNoaWxkcmVuTnVtYmVyXG4gICAgICAgICAgPyBjcmVhdGVEYXRhKG1heERlZXAsIG1heENoaWxkcmVuLCBjaGlsZHJlbk51bWJlciwgZGVlcCArIDEsIG5vZGVLZXkpXG4gICAgICAgICAgOiB1bmRlZmluZWQsXG4gICAgICB9XG4gICAgfSlcbn1cblxuY29uc3QgcHJvcHMgPSB7XG4gIHZhbHVlOiAnaWQnLFxuICBsYWJlbDogJ2xhYmVsJyxcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG59XG5jb25zdCBkYXRhID0gY3JlYXRlRGF0YSg0LCAzMCwgNDApXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5wcmVmaXgge1xuICBjb2xvcjogdmFyKC0tZWwtY29sb3ItcHJpbWFyeSk7XG4gIG1hcmdpbi1yaWdodDogMTBweDtcbn1cbi5wcmVmaXguaXMtbGVhZiB7XG4gIGNvbG9yOiB2YXIoLS1lbC1jb2xvci1zdWNjZXNzKTtcbn1cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjIyMDUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjIyMDUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjIyMDUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjIyMDUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==)

**Comment by rzzf** [comment]
I noticed that with the current changes, `el-tree-node` rerenders when `expanded` changes, but `el-node-content` doesn’t, interesting🤔.

How about trying to manually force the `el-node-content` to rerender?

Alternatively, we could modify the original object directly within `expandNode` / `collapseNode`.
```ts
const _node = tree.value?.treeNodeMap.get(node.key)
 _node && (_node.expanded = true)
```

**Comment by jevin98** [comment]
It seems that the reason here is that `tree` in `useTree` is a `shallowRef`. If `<el-node-content :node="{ ...node, expanded: node.expanded }" />` is changed to `<el-node-content :node="node" />`, `el-node-content`'s `node` is not a responsive object. Please correct me if I am wrong.

**Comment by jevin98** [comment]
> I noticed that with the current changes, `el-tree-node` rerenders when `expanded` changes, but `el-node-content` doesn’t, interesting🤔.
> 
> How about trying to manually force the `el-node-content` to rerender?
> 
> Alternatively, we could modify the original object directly within `expandNode` / `collapseNode`.
> 
> ```ts
> const _node = tree.value?.treeNodeMap.get(node.key)
>  _node && (_node.expanded = true)
> ```

I think this is a good solution.

The problem here was originally

> > It seems to be related to #21066.
> 
> The problem is that `<el-node-content :node="{ ...node, expanded }" />` assigns a new object here, which causes the `node` modified inside the `refTree.value.expandNode(node)` function to be different from the `node` in the original data source.

It is better to ensure that the modified `node` is the internal data source

**Review by btea — APPROVED** [review]
Thanks!

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 3]
```diff
@@ -243,13 +243,15 @@ export function useTree(
       })
     }
     keySet.add(node.key)
-    node.expanded = true
+    const _node = getNode(node.key)
+    _node && (_node.expanded = true)
     emit(NODE_EXPAND, node.data, node)
```
Comment (rzzf) [inline packages/components/tree-v2/src/composables/useTree.ts]: This fixes the issue with the expanded state, but I wonder whether we should respect the user's changes if the developer modifies node or data when this function is triggered?

[example](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNvbGxhcHNlQWxsTm9kZVwiPuaUtui1t+aJgOaciTwvZWwtYnV0dG9uPlxuICA8ZWwtdHJlZS12MlxuICAgIDpkYXRhPVwidHJlZURhdGFcIlxuICAgIGhpZ2hsaWdodC1jdXJyZW50XG4gICAgOmV4cGFuZC1vbi1jbGljay1ub2RlPVwiZmFsc2VcIlxuICAgIHJlZj1cInJlZlRyZWVcIlxuICAgIEBub2RlLWV4cGFuZD1cInRvZ2dsZUV4cGFuZGVkXCJcbiAgICBAbm9kZS1jb2xsYXBzZT1cInRvZ2dsZUV4cGFuZGVkXCJcbiAgPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD1cInsgbm9kZSB9XCI+XG4gICAgICA8ZGl2IEBkYmxjbGljaz1cInRvZ2dsZUV4cGFuZChub2RlKVwiPnt7IG5vZGUubGFiZWwgfX08L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXRyZWUtdjI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdHJlZURhdGEgPSByZWFjdGl2ZShbXG4gIHtcbiAgICBpZDogJzEnLFxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGlkOiAnMS0xJyxcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl0pXG5cbmNvbnN0IHRvZ2dsZUV4cGFuZGVkID0gKGRhdGEsIG5vZGUpID0+IHtcbiAgY29uc29sZS5sb2coZGF0YSwgbm9kZSlcbn1cblxuY29uc3QgcmVmVHJlZSA9IHJlZigpXG5mdW5jdGlvbiB0b2dnbGVFeHBhbmQobm9kZSkge1xuICBpZiAobm9kZS5leHBhbmRlZCkge1xuICAgIHJlZlRyZWUudmFsdWUuY29sbGFwc2VOb2RlKG5vZGUpXG4gIH0gZWxzZSB7XG4gICAgcmVmVHJlZS52YWx1ZS5leHBhbmROb2RlKHsuLi5ub2RlLCBkYXRhOiB7Li4ubm9kZS5kYXRhLCBhOiAndGVzdCd9fSlcbiAgfVxufVxuXG5mdW5jdGlvbiBjb2xsYXBzZUFsbE5vZGUoKSB7XG4gIGNvbnN0IHJvb3ROb2RlID0gcmVmVHJlZS52YWx1ZS5nZXROb2RlKCcxJylcbiAgY29sbGFwc2VBbGwoW3Jvb3ROb2RlXSlcbn1cblxuLy8g6YCS5b2S5pS26LW35omA5pyJ5bGV5byA55qE6IqC54K5XG5mdW5jdGlvbiBjb2xsYXBzZUFsbChub2Rlcykge1xuICBub2Rlcy5mb3JFYWNoKChub2RlKSA9PiB7XG4gICAgaWYgKG5vZGUuZXhwYW5kZWQpIHtcbiAgICAgIHJlZlRyZWUudmFsdWUuY29sbGFwc2VOb2RlKG5vZGUpXG4gICAgfVxuICAgIC8vIOmAkuW9kuWkhOeQhuWtkOiKgueCuVxuICAgIGlmIChub2RlLmNoaWxkcmVuPy5sZW5ndGggPiAwKSB7XG4gICAgICBjb2xsYXBzZUFsbChub2RlLmNoaWxkcmVuKVxuICAgIH1cbiAgfSlcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkIGxhbmc9XCJzY3NzXCI+PC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTAuMy9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjMvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTAuMy9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTAuMy9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJlcFZlcnNpb24iOiIyLjEwLjMifX0=)

At the very least, the latest expanded state needs to be emitted.

Comment (jevin98) [reply packages/components/tree-v2/src/composables/useTree.ts]: This issue seems unrelated to the current pull request and should be handled in a separate pull request.

My personal opinion: It's pointless for users to modify `node/node.data` in this way. `emit node-expand/node-collapse` should only return the data from the data source. If it's necessary for users to modify `node.data`, they should modify the `data source` instead.

Comment (rzzf) [reply packages/components/tree-v2/src/composables/useTree.ts]: Alright, but I think `node.expanded` in emit should stay in sync with `_node.expanded`, otherwise the `node-expand` and `node-collapse` events will receive an outdated state.

WDYT?

image

Comment (jevin98) [reply packages/components/tree-v2/src/composables/useTree.ts]: In that case, it seems like simply changing it to:
```
const _node = getNode(node.key)
_node && (_node.expanded = true)
emit(NODE_EXPAND, _node.data, _node)
```
is a good approach. However, if I make the following adjustments here, 

> This issue seems unrelated to the current pull request and should be handled in a separate pull request.
> 
> My personal opinion: It's pointless for users to modify `node/node.data` in this way. `emit node-expand/node-collapse` should only return the data from the data source. If it's necessary for users to modify `node.data`, they should modify the `data source` instead.

do we need to consult with other members?

Comment (rzzf) [reply packages/components/tree-v2/src/composables/useTree.ts]: No, I mean we should keep the original `node.expanded = true`.

Just like:
```ts
node.expanded = true
const _node = getNode(node.key)
_node && (_node.expanded = true)
```

Comment (jevin98) [reply packages/components/tree-v2/src/composables/useTree.ts]: But it feels like repetitive stuff.

Comment (rzzf) [reply packages/components/tree-v2/src/composables/useTree.ts]: > ```
> const _node = getNode(node.key)
> _node && (_node.expanded = true)
> emit(NODE_EXPAND, _node.data, _node)
> ```

Sorry, I misread it earlier. This works for me too.

Comment (jevin98) [reply packages/components/tree-v2/src/composables/useTree.ts]: done

**Review by rzzf — APPROVED** [review]

**Comment by rzzf** [comment]
Hi, @btea do you have any other suggestions for changes?

**Comment by btea** [comment]
No, it looks great. 👍
