### PR TITLE
fix(components): [el-date-picker]make defaultValue be reactive

### LINKED ISSUE #4720: [Bug Report] ElDatePicker prop 'default-value' is not reactive
### Element Plus version
1.2.0-beta.5

### OS/Browsers version
Chrome

### Vue version
3.2.24

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-6lljl?file=/src/App.vue

### Steps to reproduce
set input value and clear after 2000ms.

### What is Expected?
'defaultValue' in picker expect to change,but not.

### What is actually happening?
'defaultValue' seems lose reactivity when destructure

imgae

### PR DESCRIPTION
**Pull request by Alanscut**
fix: #4720
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/date-picker/src/date-picker-com/panel-date-range.vue [hunk 1]
```diff
@@ -481,10 +481,10 @@ export default defineComponent({
 
     const formatEmit = (emitDayjs: Dayjs, index?) => {
       if (!emitDayjs) return
-      if (defaultTime) {
-        const defaultTimeD = dayjs(defaultTime[index] || defaultTime).locale(
-          lang.value
-        )
+      if (defaultTime.value) {
```
Comment (msidolphin) [inline packages/components/date-picker/src/date-picker-com/panel-date-range.vue:484]: I think we should try to avoid redundant dependency collection, same for other places

```js
const defaultTimeValue = defaultTime.value
const defaultTimeD = dayjs(defaultTimeValue[index] || defaultTimeValue).locale(lang.value)
```

Comment (Alanscut) [reply packages/components/date-picker/src/date-picker-com/panel-date-range.vue:484]: fine

File: packages/components/date-picker/__tests__/date-picker.spec.ts [hunk 2]
```diff
@@ -129,6 +129,46 @@ describe('DatePicker', () => {
...
+      () => ({
+        value: '',
+        defaultValue: new Date(2011, 10, 1),
+      })
+    )
+    const input = wrapper.find('input')
+    input.trigger('blur')
+    input.trigger('focus')
+    await nextTick()
+    ;(document.querySelector('td.available') as HTMLElement).click()
```
Comment (btea) [inline packages/components/date-picker/__tests__/date-picker.spec.ts:147]:
```suggestion
    document.querySelector<HTMLElement>('td.available').click()
```

File: packages/components/date-picker/__tests__/date-picker.spec.ts [hunk 3]
```diff
@@ -129,6 +129,46 @@ describe('DatePicker', () => {
...
+    await nextTick()
+    const vm = wrapper.vm as any
+    expect(vm.value).toBeDefined()
+    expect(vm.value.getFullYear()).toBe(2011)
+    expect(vm.value.getMonth()).toBe(10)
+    expect(vm.value.getDate()).toBe(1)
+    const picker = wrapper.findComponent(CommonPicker)
+    ;(picker.vm as any).showClose = true
+    await nextTick()
+    ;(document.querySelector('.clear-icon') as HTMLElement).click()
```
Comment (btea) [inline packages/components/date-picker/__tests__/date-picker.spec.ts:157]: Same as above

**Review by btea — APPROVED** [review]

**Review by jw-foss — APPROVED** [review]
