### PR TITLE
fix(components): [checkbox] label is object in group

### LINKED ISSUE #9266: [Component] [checkbox, checkbox-group] 在多选框组el-checkbox-group中，若其中的el-checkbox的label为对象类型，进行多选时，其多选选中态会失效（只会有一个选中态）。
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome  104.0.5112.79/macOS 12.4`
- Build Tool: `Vite`

### Related Component

- `el-checkbox`
- `el-checkbox-group`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuY29uc3QgY2hlY2tMaXN0ID0gcmVmKFtdKTtcbmNvbnN0IGNoZWNrTGlzdGVkID0gcmVmKFtdKTtcbmNvbnN0IE9wdGlvbjEgPSB7XG4gIGlkOiAxLFxuICBuYW1lOiAnMScsXG59O1xuY29uc3QgT3B0aW9uMiA9IHtcbiAgaWQ6IDIsXG4gIG5hbWU6ICcyJyxcbn07XG5jb25zdCBPcHRpb24zID0ge1xuICBpZDogMyxcbiAgbmFtZTogJzMnLFxufTtcbiAgY29uc3QgT3B0aW9uID0gW1xuICB7IGlkOiAxLCBuYW1lOiAnT3B0aW9uMScgfSxcbiAgeyBpZDogMiwgbmFtZTogJ09wdGlvbjInIH0sXG5dO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiDmiJHmmK/mnprkuL7muLLmn5PnmoTnu5HlrprmlbDnu4RjaGVja0xpc3R7eyBjaGVja0xpc3QgfX0gXG4gICAgPGVsLWNoZWNrYm94LWdyb3VwIHYtbW9kZWw9XCJjaGVja0xpc3RcIj5cbiAgICA8ZWwtY2hlY2tib3ggOmxhYmVsPVwiT3B0aW9uMVwiPk9wdGlvbjE8L2VsLWNoZWNrYm94PlxuICAgIDxlbC1jaGVja2JveCA6bGFiZWw9XCJPcHRpb24yXCI+T3B0aW9uMjwvZWwtY2hlY2tib3g+XG4gICAgPGVsLWNoZWNrYm94IDpsYWJlbD1cIk9wdGlvbjNcIj5PcHRpb24zPC9lbC1jaGVja2JveD5cbiAgPC9lbC1jaGVja2JveC1ncm91cD5cbiAgICDmiJHmmK/mlbDnu4TmuLLmn5PnmoTnu5HlrprmlbDnu4RjaGVja0xpc3RlZHt7IGNoZWNrTGlzdGVkIH19XG4gICA8ZWwtY2hlY2tib3gtZ3JvdXAgdi1tb2RlbD1cImNoZWNrTGlzdGVkXCI+XG4gICAgPGVsLWNoZWNrYm94IHYtZm9yPVwiY2hpbGQgaW4gT3B0aW9uXCIgOmxhYmVsPVwiY2hpbGRcIiA6a2V5PVwiY2hpbGQuaWRcIj57eyBjaGlsZC5uYW1lIH19PC9lbC1jaGVja2JveD5cbiAgPC9lbC1jaGVja2JveC1ncm91cD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在el-checkbox-group中点击el-checkbox进行多选，通过模版展示可以看到el-checkbox-group绑定的值，可以正确将el-checkbox的对象类型的label加入到绑定的数组中。但是el-checkbox的高亮选中态只有最后一个选中的el-checkbox的高亮态正确。

### What is Expected?

当el-checkbox的label为对象类型时，在多选时，可以保证el-checkbox的高亮选中态正确。

### What is actually happening?

当el-checkbox的label为对象类型时，在多选时，el-checkbox的高亮选中态只有最后一个选中的el-checkbox的高亮态正确。

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

close #9266 

image

When the `proxy object` is used as `props`, it will be restored to the `original object`. The currently selected value is a proxy object, and the value of `includes` must be `false`, so it must be restored to the original value and then judged.

### CODE REVIEW

File: packages/components/checkbox/src/checkbox.ts [hunk 1]
```diff
@@ -182,7 +190,7 @@ const useCheckboxStatus = (
     if (toTypeString(value) === '[object Boolean]') {
       return value
     } else if (Array.isArray(value)) {
-      return value.includes(props.label)
+      return value.map((o) => toRaw(o)).includes(props.label)
```
Comment (btea) [inline packages/components/checkbox/src/checkbox.ts:193]: It seems that it can be abbreviated 😆
```suggestion
      return value.map(toRaw).includes(props.label)
```

Comment (chenxch) [reply packages/components/checkbox/src/checkbox.ts:193]: You are right, I learned it again.

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Comment by lxy030988** [comment]
在2.2.16和2.2.17版本  这个bug又出现了

**Comment by chenxch** [comment]
> 在2.2.16和2.2.17版本 这个bug又出现了

这两个版本似乎并未对checkbox功能进行改动哦，我测试了下demo没有问题呀

**Comment by quqianyu** [comment]
大佬还可以再看下这个问题嘛 确实这个bug又出现了
