### PR TITLE
fix(components): [InfiniteScroll] error caused by value of el[SCOPE]

### LINKED ISSUE #14775: [Component] [infinite-scroll] 当 v-infinite-scroll 释放的时候, SCOPE 不存在导致的错误
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.9`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-infinite-scroll`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/HEAD/packages/components/infinite-scroll/src/index.ts#L165)

### Steps to reproduce

1. 页面使用 vue-router 进行切换
2. v-infinite-scroll 指令加在 el-collapse 组件之上
3. el-collapse 在 el-scrollbar 之内
4. 通过路由切换, 第一次离开该页面没有问题
5. 回到该页面
6. 再次通过 router 离开该页面, 则出现以下错误

```text
Uncaught (in promise) TypeError: Cannot destructure property 'container' of 'el[SCOPE9]' as it is undefined.
    at unmounted (index.ts:112:13)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at invokeDirectiveHook (runtime-core.esm-bundler.js:1914:7)
    at Array.<anonymous> (runtime-core.esm-bundler.js:6232:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:40)
    at flushJobs (runtime-core.esm-bundler.js:363:5)
```

[链接](https://github.com/element-plus/element-plus/blob/HEAD/packages/components/infinite-scroll/src/index.ts#L165)

经过检查, 发现源码中存在如下代码 

```js
  unmounted(el) {
    const { container, onScroll } = el[SCOPE]

    container?.removeEventListener('scroll', onScroll)
    destroyObserver(el)
  },
```

代码中存在 contaienr 不存在的 情况, 此时使用结构 (即错误中的 destructure ) 必然出错

应该将上述代码改为 
```js
  unmounted(el) {
    const container = el[SCOPE].container
    const onScroll = el[SCOPE].onScroll

    container?.removeEventListener('scroll', onScroll)
    destroyObserver(el)
  },
```

由于时间有限,暂时无法复现该问题, 但是使用此方法大概率可以修复该问题

### What is Expected?

修复该问题

### What is actually happening?

修复该问题

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by YiMo1**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

resolves #14776 
resolves #14775 

### 复现步骤

1. 创建五个文件：

   - App.vue:

     ```html
     <RouterLink to="/pageA/subA">PageA</RouterLink>
     <RouterLink to="/pageB/subB">PageB</RouterLink>
     <RouterView v-slot="{ Component }">
       <KeepAlive>
         <component :is="Component" />
       </KeepAlive>
     </RouterView>
     ```

   - PageA.vue:

     ```html
     <div>
       PageA
       <router-view />
     </div>
     ```

   - PageB.vue:

     ```html
     <div>
       PageB
       <router-view />
     </div>
     ```

   - subPageA.vue:

     ```html
     <div v-infinite-scroll="fn"></div>
     ```

   - subPageB.vue:

     ```html
     <div v-infinite-scroll="fn"></div>
     ```

2. 配置路由结构：

   ```javascript
   {
     path: "/pageA",
     component: PageA.vue,
     children: [{  path: "subA",component: subPageA.vue } ],
   },
   {
     path: "/pageB",
     component:  PageB.vue,
     children: [{  path: "subB",component: subPageB.vue } ],
   }
   ```

3. 来回点击两个路由链接即可。

### 控制台报错信息

image

### CODE REVIEW

File: packages/components/infinite-scroll/src/index.ts [hunk 1]
```diff
@@ -162,6 +162,7 @@ const InfiniteScroll: ObjectDirective<
     container.addEventListener('scroll', onScroll)
   },
   unmounted(el) {
```
Comment (kooriookami) [inline packages/components/infinite-scroll/src/index.ts:164]:
```suggestion
  beforeUnmount(el) {
```
@btea What do you think?

Comment (kooriookami) [reply packages/components/infinite-scroll/src/index.ts:164]: OK

**Review by kooriookami — APPROVED** [review]

**Review by btea — APPROVED** [review]
