### PR TITLE
fix(components): [input] Write Chinese in parenthesis, letters repeat

### LINKED ISSUE #11723: [Component] [input] safari浏览器下el-input在英文括号里面输入中文时字母会重复
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.3 Safari/605.1.15`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

固定现象, 官网可复现

### What is Expected?

safari浏览器el-input组件英文括号中输入中文时拼音不会重复

### What is actually happening?

safari浏览器el-input组件英文括号中输入中文时拼音会重复

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by HeftyKoo**
closed #11723

Write Chinese among parenthesis in the safari browser, letters repeat.

The parentheses are unnecessary because they create a capture group that is not used.  Also, this will make the reg match the parentheses, which causes composition judgment wrong.

Before:
20230322141418_rec_

After:
20230322141129_rec_

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by chenxch — APPROVED** [review]
safari pass

**Comment by chenxch** [comment]
@ryuhangyeong It's okay, I just added the Korean input method and typed it casually, and the test passed.

File: packages/utils/i18n.ts [hunk 1]
```diff
@@ -1,2 +1,2 @@
 export const isKorean = (text: string) =>
-  /([(\uAC00-\uD7AF)|(\u3130-\u318F)])+/gi.test(text)
+  /([\uAC00-\uD7AF|\u3130-\u318F])+/gi.test(text)
```
Comment (tolking) [inline packages/utils/i18n.ts:2]:
```suggestion
  /[\uAC00-\uD7AF\u3130-\u318F]+/gi.test(text)
```

``` ts
/([\uAC00-\uD7AF|\u3130-\u318F])+/gi.test('(|)') // true
```

The `|`  is redundant

Comment (HeftyKoo) [reply packages/utils/i18n.ts:2]: IMO, keeping the `|` makes it more readable.

Comment (HeftyKoo) [reply packages/utils/i18n.ts]: You are right, fixed it. Please take a look again.

**Review by tolking — APPROVED** [review]
