### PR TITLE
fix(components): [tree-v2] expand all ancestor nodes of the specified node

### LINKED ISSUE #18073: [Component] [tree-v2] el-treev2 的setExpandedKeys 有问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.0-beta.3`
- Element Plus Version: `2.8.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-tree-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgOmhlaWdodD1cIjIwOFwiXG4gICAgcmVmPVwidHJlZUVsXCJcbiAgICBoaWdobGlnaHQtY3VycmVudFxuICAgIDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVyTWV0aG9kXCJcbiAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPuWxleW8gDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2xvc2VcIj7mipjlj6A8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtzaGFsbG93UmVmfSBmcm9tICd2dWUnXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBnZXRLZXkgPSAocHJlZml4OiBzdHJpbmcsIGlkOiBudW1iZXIpID0+IHtcbiAgcmV0dXJuIGAke3ByZWZpeH0tJHtpZH1gXG59XG5cbmNvbnN0IGNyZWF0ZURhdGEgPSAoXG4gIG1heERlZXA6IG51bWJlcixcbiAgbWF4Q2hpbGRyZW46IG51bWJlcixcbiAgbWluTm9kZXNOdW1iZXI6IG51bWJlcixcbiAgZGVlcCA9IDEsXG4gIGtleSA9ICdub2RlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuXG5jb25zdCB0cmVlRWw9c2hhbGxvd1JlZigpXG5cbmNvbnN0IGZpbHRlck1ldGhvZCA9IChxdWVyeTogc3RyaW5nLCBub2RlKSA9PiB7XG4gIHJldHVybiBub2RlLmxhYmVsIS5pbmNsdWRlcyhxdWVyeSlcbn1cblxuY29uc3Qgc2V0Q2hlY2tlZEtleXM9KCk9PntcbiAgY29uc3Qga2V5PSdub2RlLTItMi0xLTEnO1xuICB0cmVlRWwudmFsdWUuc2V0Q3VycmVudEtleShrZXkpO1xuICBzZXRFeHBhbmRlZEtleXMoWydub2RlLTItMSddKVxufVxuXG5jb25zdCBjbG9zZT0oKT0+e1xuICBzZXRFeHBhbmRlZEtleXMoW10pXG59XG5cbmNvbnN0IHNldEV4cGFuZGVkS2V5cyA9IChrZXlzOiBhbnlbXSkgPT4ge1xuXHR0cmVlRWwudmFsdWUhLnNldEV4cGFuZGVkS2V5cyhrZXlzKTtcbn07XG5cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用官网的Playground，用基础案例就行,然后通过点击事件调用treeEl.value!.setExpandedKeys("node-2-1")，然后并不会展开，可是设置为treeEl.value!.setExpandedKeys("node-2")却是可以

### What is Expected?

treeEl.value!.setExpandedKeys里设置任何存在的key都可以展开指定节点

### What is actually happening?

目前并不是任何节点都可展开，初步看下来像是最外层的可以展开

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by tuskermanshu**
closed #18073

- [ √ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ √ ] Make sure you are merging your commits to `dev` branch.
- [ √ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by dadaguai-git** [comment]
[Playground ](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgOmhlaWdodD1cIjIwOFwiXG4gICAgcmVmPVwidHJlZUVsXCJcbiAgICBoaWdobGlnaHQtY3VycmVudFxuICAgIDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVyTWV0aG9kXCJcbiAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPuWxleW8gDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2xvc2VcIj7mipjlj6A8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtzaGFsbG93UmVmfSBmcm9tICd2dWUnXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBwcm9wcyA9IHtcbiAgdmFsdWU6ICdpZCcsXG4gIGxhYmVsOiAnbGFiZWwnLFxuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbn1cblxuY29uc3QgZGF0YSA9IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgaWQ6ICcxJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTEnLFxuICAgICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgIGlkOiAnMS0xJyxcbiAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0xLTEnLFxuICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMS0xLTEnLFxuICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0xLTEtMScsXG4gICAgICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMS0xLTEtMScsXG4gICAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTEtMS0xLTEnLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgICAgICAgaWQ6ICcxLTEtMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMS0xLTEtMicsXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICBdXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICBpZDogJzEtMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMS0xLTInLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgaWQ6ICcyJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTInLFxuICAgICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgIGlkOiAnMi0xJyxcbiAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0yLTEnLFxuICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMi0xLTEnLFxuICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0yLTEtMScsXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICBpZDogJzItMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMi0xLTInLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICBdXG5cblxuY29uc3QgdHJlZUVsPXNoYWxsb3dSZWYoKVxuXG5jb25zdCBmaWx0ZXJNZXRob2QgPSAocXVlcnk6IHN0cmluZywgbm9kZSkgPT4ge1xuICByZXR1cm4gbm9kZS5sYWJlbCEuaW5jbHVkZXMocXVlcnkpXG59XG5cbmNvbnN0IHNldENoZWNrZWRLZXlzPSgpPT57XG4gIHNldEV4cGFuZGVkS2V5cygnMS0xLTEnKVxufVxuXG5jb25zdCBjbG9zZT0oKT0+e1xuICBzZXRFeHBhbmRlZEtleXMoW10pXG59XG5cbmNvbnN0IHNldEV4cGFuZGVkS2V5cyA9IChrZXlzOiBhbnlbXSB8IGFueSkgPT4ge1xuXHR0cmVlRWwudmFsdWUhLnNldEV4cGFuZGVkS2V5cyhrZXlzKTtcbn07XG5cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE4MDc3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xODA3Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xODA3Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4MDc3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 1]
```diff
@@ -201,8 +196,32 @@ export function useTree(
...
+    if (!Array.isArray(keys)) {
+      keys = [keys]
+    }
+
+    const expandedKeys = new Set<TreeKey>()
+    const nodeMap = tree.value?.treeNodeMap || new Map()
+
+    keys.forEach((k) => {
+      let node = nodeMap.get(k)
+      while (node) {
```
[the remark this answers is not in the document]
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts]: Thanks for the code review!

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 2]
```diff
@@ -201,8 +196,32 @@ export function useTree(
     }
   }
 
-  function setExpandedKeys(keys: TreeKey[]) {
-    expandedKeySet.value = new Set(keys)
+  function setExpandedKeys(keys: TreeKey[] | TreeKey) {
```
[the remark this answers is not in the document]
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts]: Supporting both string and array offers flexibility. For single node expansion, using setExpandedKeys('node-1') can feel more straightforward than array syntax.

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 3]
```diff
@@ -201,8 +196,32 @@ export function useTree(
...
+    })
+
+    // expand all parent nodes
+    expandedKeys.forEach((k) => {
+      let node = nodeMap.get(k)
+      while (node && node.parent) {
+        expandedKeys.add(node.parent.key)
+        node = node.parent
+      }
+    })
```
[the remark this answers is not in the document]
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts]: Yes, my oversight, it's redundant code

File: packages/components/tree-v2/src/composables/useTree.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (makedopamine) [reply packages/components/tree-v2/src/composables/useTree.ts]: I agree with @tolking on this. Array-only is  more closely aligned with the semantic of setExpanded***Keys***.

[the remark this answers is not in the document]
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts]: In that case, it does seem that I didn't consider the semantics of function names

**Review by tolking — APPROVED** [review]
LGTM

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 4]
```diff
@@ -89,30 +89,24 @@ export function useTree(
...
-    function traverse() {
-      const stack: TreeNode[] = []
-      for (let i = nodes.length - 1; i >= 0; --i) {
-        stack.push(nodes[i])
-      }
-      while (stack.length) {
-        const node = stack.pop()
-        if (!node) continue
+
+    function traverse(currentNodes: TreeNode[], isParentExpanded = true) {
```
Comment (makedopamine) [inline packages/components/tree-v2/src/composables/useTree.ts:93]: Is it necessary to change this function to fix the issue? I've noticed that it leads to performance degradation.

Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts]: The space and time complexities are indeed the same. However, I've redesigned the approach to avoid the potential stack overflow issue in very deep trees.

The test data after expanding with 20,000 nodes is as follows：

before
preformance-before


after

preformance-after

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 5]
```diff
@@ -88,31 +88,33 @@ export function useTree(
...
     const flattenNodes: TreeNode[] = []
-    const nodes = (tree.value && tree.value.treeNodes) || []
-    function traverse() {
-      const stack: TreeNode[] = []
-      for (let i = nodes.length - 1; i >= 0; --i) {
-        stack.push(nodes[i])
+    const nodes = tree.value?.treeNodes || []
+
+    // Stack to simulate recursion, each item contains [nodes, index]
+    const stack: [TreeNode[], number][] = [[nodes, 0]]
```
Comment (makedopamine) [inline packages/components/tree-v2/src/composables/useTree.ts:94]: The data structure `[TreeNode[], number][]` appears to be over-design. I think `TreeNode[]` is just right for the function implementation.

Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts:94]: The [TreeNode[], number][] structure tracks our position in the tree, aiding navigation between related items. It handles large trees efficiently, particularly for partial tree operations. It's not redundant, but a deliberate choice to improve performance for complex tree manipulations.

Comment (makedopamine) [reply packages/components/tree-v2/src/composables/useTree.ts:94]: Without position tracking, I haven't hit any performance issues. What cases could there be a noticeable performance improvement compared to the following implementation? 

```ts
   const nodes = tree.value?.treeNodes || []

    const stack: TreeNode[] = []
    for (let i = nodes.length - 1; i >= 0; --i) {
      stack.push(nodes[i])
    }
    while (stack.length) {
      const node = stack.pop()!
      if (hiddenKeys.has(node.key)) continue

      flattenNodes.push(node)
      if (node.children && expandedKeys.has(node.key)) {
        for (let i = node.children.length - 1; i >= 0; --i) {
          stack.push(node.children[i])
        }
      }
    }
```

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 6]
```diff
@@ -202,7 +204,18 @@ export function useTree(
   }
 
   function setExpandedKeys(keys: TreeKey[]) {
-    expandedKeySet.value = new Set(keys)
+    const expandedKeys = new Set<TreeKey>()
+    const nodeMap = tree.value?.treeNodeMap || new Map()
```
Comment (makedopamine) [inline packages/components/tree-v2/src/composables/useTree.ts:208]:
```suggestion
    const nodeMap = tree.value!.treeNodeMap
```
`tree.value` never be undefined when setExpandedKeys is called.

File: packages/components/tree-v2/src/composables/useTree.ts (hunk 5 above)
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts:94]: After re-running performance tests with your code, I found that the difference is less than 100ms when expanding 20,000 tree nodes. Thank you for the code review

File: packages/components/tree-v2/src/composables/useTree.ts (hunk 6 above)
Comment (dadaguai-git) [reply packages/components/tree-v2/src/composables/useTree.ts:208]: Thank you for the code review

**Review by makedopamine — APPROVED** [review]
LGTM, thanks!

**Comment by btea** [comment]
> [Playground ](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZS12MlxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgOmhlaWdodD1cIjIwOFwiXG4gICAgcmVmPVwidHJlZUVsXCJcbiAgICBoaWdobGlnaHQtY3VycmVudFxuICAgIDpmaWx0ZXItbWV0aG9kPVwiZmlsdGVyTWV0aG9kXCJcbiAgLz5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPuWxleW8gDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2xvc2VcIj7mipjlj6A8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtzaGFsbG93UmVmfSBmcm9tICd2dWUnXG5pbnRlcmZhY2UgVHJlZSB7XG4gIGlkOiBzdHJpbmdcbiAgbGFiZWw6IHN0cmluZ1xuICBjaGlsZHJlbj86IFRyZWVbXVxufVxuXG5jb25zdCBwcm9wcyA9IHtcbiAgdmFsdWU6ICdpZCcsXG4gIGxhYmVsOiAnbGFiZWwnLFxuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbn1cblxuY29uc3QgZGF0YSA9IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgaWQ6ICcxJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTEnLFxuICAgICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgIGlkOiAnMS0xJyxcbiAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0xLTEnLFxuICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMS0xLTEnLFxuICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0xLTEtMScsXG4gICAgICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMS0xLTEtMScsXG4gICAgICAgICAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTEtMS0xLTEnLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgICB7XG4gICAgICAgICAgICAgICAgICAgICAgaWQ6ICcxLTEtMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMS0xLTEtMicsXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICBdXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICBpZDogJzEtMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMS0xLTInLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgaWQ6ICcyJyxcbiAgICAgICAgICAgICAgbGFiZWw6ICdub2RlLTInLFxuICAgICAgICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgIGlkOiAnMi0xJyxcbiAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0yLTEnLFxuICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICAgICAgICAgICAge1xuICAgICAgICAgICAgICAgICAgICAgIGlkOiAnMi0xLTEnLFxuICAgICAgICAgICAgICAgICAgICAgIGxhYmVsOiAnbm9kZS0yLTEtMScsXG4gICAgICAgICAgICAgICAgICAgIH0sXG4gICAgICAgICAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgICAgICAgICBpZDogJzItMS0yJyxcbiAgICAgICAgICAgICAgICAgICAgICBsYWJlbDogJ25vZGUtMi0xLTInLFxuICAgICAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgICB9LFxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgfSxcbiAgICAgICAgICBdXG5cblxuY29uc3QgdHJlZUVsPXNoYWxsb3dSZWYoKVxuXG5jb25zdCBmaWx0ZXJNZXRob2QgPSAocXVlcnk6IHN0cmluZywgbm9kZSkgPT4ge1xuICByZXR1cm4gbm9kZS5sYWJlbCEuaW5jbHVkZXMocXVlcnkpXG59XG5cbmNvbnN0IHNldENoZWNrZWRLZXlzPSgpPT57XG4gIHNldEV4cGFuZGVkS2V5cygnMS0xLTEnKVxufVxuXG5jb25zdCBjbG9zZT0oKT0+e1xuICBzZXRFeHBhbmRlZEtleXMoW10pXG59XG5cbmNvbnN0IHNldEV4cGFuZGVkS2V5cyA9IChrZXlzOiBhbnlbXSB8IGFueSkgPT4ge1xuXHR0cmVlRWwudmFsdWUhLnNldEV4cGFuZGVkS2V5cyhrZXlzKTtcbn07XG5cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE4MDc3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xODA3Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xODA3Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4MDc3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

The example in the link should be adjusted. `setExpandedKeys` can only accept an array, otherwise an error will be reported.

**Review by btea — APPROVED** [review]
Thanks!
