### PR TITLE
fix(checkbox): fix warn about lacking default value of inject

### LINKED ISSUE #254: Checkbox: lack default value of inject
The newest code lacks default value of inject of `elForm`, `elFormItem`, `CheckboxGroup`.

```
const elForm = inject<any>('elForm')
const elFormItem = inject<any>('elFormItem')
const checkboxGroup = inject<ICheckboxGroupInstance>('CheckboxGroup')
```

image

@zouhangwithsweet

### PR DESCRIPTION
**Pull request by Ryan2128**
- [ ] Component Migration

Fix #254

### CODE REVIEW

**Comment by Ryan2128** [comment]
Ready for review, PTAL.

**Comment by Ryan2128** [comment]
@HerringtonDarkholme Do you have time to review my PR now? I cannot request a review.

File: packages/checkbox/src/useCheckbox.ts [hunk 1]
```diff
@@ -13,9 +13,9 @@ import { ICheckboxGroupInstance, ICheckboxProps } from './checkbox'
 export const useCheckboxGroup = () => {
   //todo: ELEMENT
   const ELEMENT = null
-  const elForm = inject<any>('elForm')
-  const elFormItem = inject<any>('elFormItem')
-  const checkboxGroup = inject<ICheckboxGroupInstance>('CheckboxGroup')
+  const elForm = inject<any>('elForm', {})
+  const elFormItem = inject<any>('elFormItem', {})
+  const checkboxGroup = inject<ICheckboxGroupInstance>('CheckboxGroup', {})
```
Comment (HerringtonDarkholme) [inline packages/checkbox/src/useCheckbox.ts:18]: I think default value is needed here since checkbox can be used without form/checkboxGroup. @zouhangwithsweet

**Review by HerringtonDarkholme — APPROVED** [review]
