### PR TITLE
fix(components): [select-v2] support empty string value

### LINKED ISSUE #9602: [Component] [select-v2] Corresponding label of  empty string as option value  doesn't  show in input of `select-v2` when initial value is empty string too
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.15`
- Browser / OS: `Chrome 104.0.5112.102 (Official Build) (64-bit) / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cImxhcmdlXCJcbiAgLz5cbiAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAvPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIHBsYWNlaG9sZGVyPVwiUGxlYXNlIHNlbGVjdFwiXG4gICAgc2l6ZT1cInNtYWxsXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbml0aWFscyA9IFsnJywgJ2EnICwnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuXG5jb25zdCB2YWx1ZSA9IHJlZignJylcbmNvbnN0IG9wdGlvbnMgPWluaXRpYWxzLm1hcCgoaywgaWR4KSA9PiAoe1xuICB2YWx1ZTogayxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5leGFtcGxlLXNob3djYXNlIC5lbC1zZWxlY3QtdjIge1xuICBtYXJnaW4tcmlnaHQ6IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

When using an empty string as the initial value, if one of the option values is an empty string either, eg. `{ label: 'Empty Label', option: '' }` of `select-v2`, the corresponding label of the empty-string-valued option doesn't show in select input(input content stays as placeholder). Whereas the option did has a selected effect in the dropdown list.

### What is Expected?

Given the example described above, `Empty Label` should display in the input field, just as `select` does.

### What is actually happening?

The select input stays empty(placeholder showing)

微信截图_20220902182123

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by chenxch**
close #9602

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

Maybe we should make `select-v2` behave the same as `select`.

### CODE REVIEW

File: packages/components/select-v2/src/useSelect.ts [hunk 1]
```diff
@@ -88,11 +88,7 @@ const useSelect = (props: ExtractPropTypes<typeof SelectProps>, emit) => {
   })
 
   const hasModelValue = computed(() => {
-    return (
-      props.modelValue !== undefined &&
-      props.modelValue !== null &&
-      props.modelValue !== ''
-    )
+    return props.modelValue !== undefined && props.modelValue !== null
```
Comment (holazz) [inline packages/components/select-v2/src/useSelect.ts:91]: How about using `isNil` utility?

```ts
return !isNil(props.modelValue)
```

**Review by holazz — APPROVED** [review]

File: packages/components/select-v2/src/useSelect.ts (hunk 1 above)
Comment (chenxch) [reply packages/components/select-v2/src/useSelect.ts:91]: Good idea.

**Review by ryuhangyeong — APPROVED** [review]

**Review by btea — APPROVED** [review]
