### PR TITLE
fix(select): fix tag content error in multiple mode

### LINKED ISSUE #637: Multiple select show weird tags when options load after dropdown list showed.
Reproduction repo: https://github.com/ZzqiZQute/element-plus-select-options-issue.git

When options are loaded in the `visible-change` event where visible is true, if I select the second option, the other options tag before this option shows weirdly.

image

### PR DESCRIPTION
**Pull request by Ryan2128**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

Fix #637

### CODE REVIEW

**Comment by Ryan2128** [comment]
This bug was caused by migration.

#### In element:
in Vue2

#### After migration:
BUG

File: packages/select/src/useSelect.ts [hunk 1]
```diff
@@ -354,14 +354,14 @@ export const useSelect = (props, states: States, ctx) => {
 
   const getOption = value => {
     let option
-    const isObject = Object.prototype.toString.call(props.modelValue).toLowerCase() === '[object object]'
-    const isNull = Object.prototype.toString.call(props.modelValue).toLowerCase() === '[object null]'
-    const isUndefined = Object.prototype.toString.call(props.modelValue).toLowerCase() === '[object undefined]'
+    const isObject = Object.prototype.toString.call(value).toLowerCase() === '[object object]'
+    const isNull = Object.prototype.toString.call(value).toLowerCase() === '[object null]'
```
Comment (JeremyWuuuuu) [inline packages/select/src/useSelect.ts:358]: Prefer using ´toRawType´ in "@element-plus/utils"

**Review by jw-foss — APPROVED** [review]
