### PR TITLE
fix(components): [menu] skip comment nodes in ellipsis

### LINKED ISSUE #15868: [Style] [menu] 升级到2.5.0+后，el-menu 设置ellipsis为true后在全屏模式下一直省略多余的子项
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.19`
- Element Plus Version: `2.5.6`
- Browser / OS: `Edg/121.0.2277.106  macOS/13.6.1`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLW1lbnVcbiAgICBlbGxpcHNpc1xuICAgIGNsYXNzPVwiZWwtbWVudS1wb3BwZXItZGVtb1wiXG4gICAgbW9kZT1cImhvcml6b250YWxcIlxuICAgIDpwb3BwZXItb2Zmc2V0PVwiMTZcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCVcIlxuICA+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjFcIj5Qcm9jZXNzaW5nIENlbnRlcjwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+V29ya3NwYWNlPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMi00XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjNcIiA6cG9wcGVyLW9mZnNldD1cIjhcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+T3ZlcnJpZGUgUG9wcGVyIE9mZnNldDwvdGVtcGxhdGU+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMy0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzLTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjMtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjMtNFwiIDpwb3BwZXItb2Zmc2V0PVwiMjBcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5vdmVycmlkZSBjaGlsZDwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzLTQtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzLTQtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPC9lbC1zdWItbWVudT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNFwiIGRpc2FibGVkPkluZm88L2VsLW1lbnUtaXRlbT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNVwiPk9yZGVyczwvZWwtbWVudS1pdGVtPlxuICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

el-mean 设置ellipsis为true是根据屏幕大小省略多余子项失效

### What is Expected?

根据屏幕自适应

### What is actually happening?

没有根据屏幕自适应

### Additional comments

还原到2.4.4版本没有发生此情况

image

### LINKED ISSUE #21750: [Component] [menu, menu-item] el-menu 的children中包含 一行注释会生成一个额外 item
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.18`
- Element Plus Version: `2.10.7`
- Browser / OS: `138.0.3351.121`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`

### Reproduction Link

[Element Plus Playground 1](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jb250YWluZXIgc3R5bGU9XCJoZWlnaHQ6IDEwMHZoXCI+XG4gICAgPGVsLWhlYWRlciBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6ICM0MDllZmY7IGNvbG9yOiB3aGl0ZTsgbGluZS1oZWlnaHQ6IDYwcHg7IHBhZGRpbmc6IDAgMjBweFwiPlxuICAgICAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIiBiYWNrZ3JvdW5kLWNvbG9yPVwiIzQwOUVGRlwiIHRleHQtY29sb3I9XCIjZmZmZmZmXCIgYWN0aXZlLXRleHQtY29sb3I9XCIjZmZkMDRiXCIgcm91dGVyIHN0eWxlPVwiaGVpZ2h0OiAxMDAlXCI+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIvd29ya2JlbmNoZXNcIj5Xb3JrYmVuY2hlczwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiL3VzZXJzXCI+VXNlcnM8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPCEtLSAgLS0+ICAgICAgICAgPCEtLSB0cnkgZGVsZXRlIHRoaXMgbGluZSAtLT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWhlYWRlcj5cblxuICAgIDxlbC1tYWluIHN0eWxlPVwicGFkZGluZzogMjBweDsgb3ZlcmZsb3cteTogYXV0b1wiPlxuICAgICAgPHJvdXRlci12aWV3IC8+XG4gICAgPC9lbC1tYWluPlxuICA8L2VsLWNvbnRhaW5lcj5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

[Element Plus Playground1](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jb250YWluZXIgc3R5bGU9XCJoZWlnaHQ6IDEwMHZoXCI+XG4gICAgPGVsLWhlYWRlciBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6ICM0MDllZmY7IGNvbG9yOiB3aGl0ZTsgbGluZS1oZWlnaHQ6IDYwcHg7IHBhZGRpbmc6IDAgMjBweFwiPlxuICAgICAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIiBiYWNrZ3JvdW5kLWNvbG9yPVwiIzQwOUVGRlwiIHRleHQtY29sb3I9XCIjZmZmZmZmXCIgYWN0aXZlLXRleHQtY29sb3I9XCIjZmZkMDRiXCIgcm91dGVyIHN0eWxlPVwiaGVpZ2h0OiAxMDAlXCI+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIvd29ya2JlbmNoZXNcIj5Xb3JrYmVuY2hlczwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiL3VzZXJzXCI+VXNlcnM8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPCEtLSAgLS0+ICAgICAgICAgPCEtLSB0cnkgZGVsZXRlIHRoaXMgbGluZSAtLT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWhlYWRlcj5cblxuICAgIDxlbC1tYWluIHN0eWxlPVwicGFkZGluZzogMjBweDsgb3ZlcmZsb3cteTogYXV0b1wiPlxuICAgICAgPHJvdXRlci12aWV3IC8+XG4gICAgPC9lbC1tYWluPlxuICA8L2VsLWNvbnRhaW5lcj5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

[Element Plus Playground 2](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1jb250YWluZXIgc3R5bGU9XCJoZWlnaHQ6IDEwMHZoXCI+XG4gICAgPGVsLWhlYWRlciBzdHlsZT1cImJhY2tncm91bmQtY29sb3I6ICM0MDllZmY7IGNvbG9yOiB3aGl0ZTsgbGluZS1oZWlnaHQ6IDYwcHg7IHBhZGRpbmc6IDAgMjBweFwiPlxuICAgICAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIiBiYWNrZ3JvdW5kLWNvbG9yPVwiIzQwOUVGRlwiIHRleHQtY29sb3I9XCIjZmZmZmZmXCIgYWN0aXZlLXRleHQtY29sb3I9XCIjZmZkMDRiXCIgcm91dGVyIHN0eWxlPVwiaGVpZ2h0OiAxMDAlXCI+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIvd29ya2JlbmNoZXNcIj5Xb3JrYmVuY2hlczwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiL3VzZXJzXCI+VXNlcnM8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudT5cbiAgICA8L2VsLWhlYWRlcj5cblxuICAgIDxlbC1tYWluIHN0eWxlPVwicGFkZGluZzogMjBweDsgb3ZlcmZsb3cteTogYXV0b1wiPlxuICAgICAgPHJvdXRlci12aWV3IC8+XG4gICAgPC9lbC1tYWluPlxuICA8L2VsLWNvbnRhaW5lcj5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### What is Expected?

注释不应该生成item

### What is actually happening?

注释行生成了一个item

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #21750 
fix #15868

### CODE REVIEW

**Comment by rzzf** [comment]
After:
image

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8aDI+aXNzdWU6ICMxOTE2MTwvaDI+XG4gIDwhLS0g5L6LMe+8mmVsLW1lbnXnu4Tku7blhoXpg6jmsqHmnInms6jph4roioLngrnvvIzorqHnrpfpnIDopoHmmL7npLrnmoToj5zljZXkuKrmlbDmraPnoa4o55So5LqO5ZKM5L6LMuOAgeS+izPlgZrlr7nmr5QpIC0tPlxuICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cImkgaW4gY291bnRcIj5cbiAgICAgIDxlbC1tZW51LWl0ZW0gOmluZGV4PVwiaSArICcnXCJcbiAgICAgICAgPuiPnOWNlXt7IFN0cmluZyhpKS5wYWRTdGFydCgyLCAnMCcpIH19PC9lbC1tZW51LWl0ZW1cbiAgICAgID5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLW1lbnU+XG4gIDwhLS0g5L6LMu+8mmVsLW1lbnXnu4Tku7blhoXpg6jlrZjlnKjms6jph4roioLngrnvvIzorqHnrpfpnIDopoHmmL7npLrnmoToj5zljZXkuKrmlbDkuI3mraPnoa4gLS0+XG4gIDxlbC1tZW51IG1vZGU9XCJob3Jpem9udGFsXCI+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPHRlbXBsYXRlIHYtZm9yPVwiaSBpbiBjb3VudFwiPlxuICAgICAgPGVsLW1lbnUtaXRlbSA6aW5kZXg9XCJpICsgJydcIlxuICAgICAgICA+6I+c5Y2Ve3sgU3RyaW5nKGkpLnBhZFN0YXJ0KDIsICcwJykgfX08L2VsLW1lbnUtaXRlbVxuICAgICAgPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtbWVudT5cbiAgPCEtLSDkvosz77ya5b2T5a2Y5Zyodi1pZuaXtu+8jHZ1ZeahhuaetuS8muWcqOivpeS9jee9rueUn+aIkOS4gOS4quazqOmHiuiKgueCueadpeWNoOS9je+8jOS7juiAjOWvvOiHtOS+izLnmoTmg4XlhrXlh7rnjrAgLS0+XG4gIDxlbC1tZW51IG1vZGU9XCJob3Jpem9udGFsXCI+XG4gICAgPHRlbXBsYXRlIHYtZm9yPVwiaSBpbiBjb3VudFwiPlxuICAgICAgPGVsLW1lbnUtaXRlbSB2LWlmPVwiaSA+IDVcIiA6a2V5PVwiaVwiIDppbmRleD1cImkgKyAnJ1wiXG4gICAgICAgID7oj5zljZV7eyBTdHJpbmcoaSkucGFkU3RhcnQoMiwgJzAnKSB9fTwvZWwtbWVudS1pdGVtXG4gICAgICA+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuXG4gIDxoMj5pc3N1ZTogIzIxNzUwPC9oMj5cbiAgPGVsLW1lbnVcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgYmFja2dyb3VuZC1jb2xvcj1cIiM0MDlFRkZcIlxuICAgIHRleHQtY29sb3I9XCIjZmZmZmZmXCJcbiAgICBhY3RpdmUtdGV4dC1jb2xvcj1cIiNmZmQwNGJcIlxuICAgIHJvdXRlclxuICAgIHN0eWxlPVwiaGVpZ2h0OiAxMDAlXCJcbiAgPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIvd29ya2JlbmNoZXNcIj5Xb3JrYmVuY2hlczwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIvdXNlcnNcIj5Vc2VyczwvZWwtbWVudS1pdGVtPlxuICAgIDwhLS0gIC0tPlxuICAgIDwhLS0gdHJ5IGRlbGV0ZSB0aGlzIGxpbmUgLS0+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCBjb3VudCA9IDIwXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzIn19)

**Comment by btea** [comment]
#14657 and https://github.com/element-plus/element-plus/issues/15868#issuecomment-3047920760 Both scenarios still seem unresolved.

**Comment by rzzf** [comment]
> #14651 and [#15868 (comment)](https://github.com/element-plus/element-plus/issues/15868#issuecomment-3047920760) Both scenarios still seem unresolved.

I'm a bit confused—what does #14651 have to do with Menu? The Playground linked in  [#15868 (comment)](https://github.com/element-plus/element-plus/issues/15868#issuecomment-3047920760) seems fine, and testing this PR locally also appears to work without issues.

20250814141527_rec_

[15686 (comment) Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtbWVudVxuICAgIGVsbGlwc2lzXG4gICAgY2xhc3M9XCJlbC1tZW51LXBvcHBlci1kZW1vXCJcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgOnBvcHBlci1vZmZzZXQ9XCIxNlwiXG4gICAgc3R5bGU9XCJ3aWR0aDogMTAwJVwiXG4gID5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCIoXywgaW5kZXgpIGluIDEwXCI+XG4gICAgICA8U3ViTWVudSA6aW5kZXg9XCJpbmRleFwiIC8+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCBTdWJNZW51IGZyb20gJy4vU3ViTWVudS52dWUnXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJTdWJNZW51LnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPCEtLSDms6jph4ogLS0+XG4gIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxXCI+UHJvY2Vzc2luZyBDZW50ZXIge3sgaW5kZXggfX08L2VsLW1lbnUtaXRlbT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5kZWZpbmVQcm9wczx7IGluZGV4OiBudW1iZXIgfT4oKVxuPC9zY3JpcHQ+XG4iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzIn19)

**Comment by btea** [comment]
Sorry, the number is wrong, it should be 14657.

The issue in comment 15868 has indeed been resolved. Perhaps we can add a similar scenario to our test case.

**Comment by rzzf** [comment]
> Sorry, the number is wrong, it should be 14657.
> 
> The issue in comment 15868 has indeed been resolved. Perhaps we can add a similar scenario to our test case.

In this PR, the issue in #14657 might be resolved solely through CSS, and I’ll update the latest code shortly. I’m currently working on the test cases.

That said, I’m not sure whether this is something the component library should handle.

```scss
 @include m(horizontal) {
   ...

    @include when(ellipsis) {
      overflow-x: hidden;
      flex: 1;
    }
}
```

**Comment by rzzf** [comment]
14657 After:
20250814165535_rec_

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibmF2YmFyXCI+XG4gICAgPGRpdiBjbGFzcz1cImxvZ28tY29udGFpbmVyXCI+XG4gICAgICA8aW1nIHNyYz1cImh0dHBzOi8vc21zLmZ0LnVnbS5hYy5pZC91bmRhbmdhbi9hc3NldHMvaW1hZ2VzL2xvZ28tdWdtLnBuZ1wiIGhlaWdodD1cIjQwXCIgLz5cbiAgICA8L2Rpdj5cbiAgICA8ZWwtbWVudVxuICAgICAgOmRlZmF1bHQtYWN0aXZlPVwiYWN0aXZlSW5kZXhcIlxuICAgICAgY2xhc3M9XCJlbC1tZW51LWRlbW9cIlxuICAgICAgbW9kZT1cImhvcml6b250YWxcIlxuICAgICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gICAgPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjFcIj5Qcm9jZXNzaW5nIENlbnRlcjwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMlwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPldvcmtzcGFjZTwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMi00XCI+XG4gICAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5pdGVtIGZvdXI8L3RlbXBsYXRlPlxuICAgICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi00LTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgICAgPCEtLSBpJ20gY29tbWVudCAtLT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCIgZGlzYWJsZWQ+SW5mbzwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj40LWl0ZW08L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI1XCI+NS1pdGVtPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNlwiPjYtaXRlbTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjdcIj43LWl0ZW08L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI4XCI+OC1pdGVtPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiOVwiPjktaXRlbTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEwXCI+MTAtaXRlbTwvZWwtbWVudS1pdGVtPlxuICAgIDwvZWwtbWVudT5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBhY3RpdmVJbmRleCA9IHJlZignMScpXG5jb25zdCBhY3RpdmVJbmRleDIgPSByZWYoJzEnKVxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLm5hdmJhciB7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG59XG48L3N0eWxlPiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0yMTc1MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzIn19)

**Comment by btea** [comment]
> In this PR, the issue in #14657 might be resolved solely through CSS, and I’ll update the latest code shortly. I’m currently working on the test cases.
> 
> That said, I’m not sure whether this is something the component library should handle.
> 
> ```css-scss
>  @include m(horizontal) {
>    ...
> 
>     @include when(ellipsis) {
>       overflow-x: hidden;
>       flex: 1;
>     }
> }
> ```

Regarding the style issue, we might suggest that users configure the style themselves. If we modify the layout uniformly, it may lead to some unpredictable results.

**Comment by rzzf** [comment]
> Regarding the style issue, we might suggest that users configure the style themselves. If we modify the layout uniformly, it may lead to some unpredictable results.

Okay, I’ll revert the CSS changes now.

File: packages/components/menu/src/menu.ts [hunk 1]
```diff
@@ -478,7 +479,9 @@ export default defineComponent({
       const vShowMore: VNode[] = []
 
       if (props.mode === 'horizontal' && menu.value) {
-        const originalSlot = flattedChildren(slot) as VNodeArrayChildren
+        const originalSlot = (
+          flattedChildren(slot) as VNodeArrayChildren
+        ).filter((vnode) => (vnode as VNode)?.shapeFlag !== 8)
```
Comment (btea) [inline packages/components/menu/src/menu.ts]: I think we can add a comment, I'm not sure what nodes `shapeFlag !== 8` is used to filter at first glance.

Comment (rzzf) [reply packages/components/menu/src/menu.ts]: done, Thx

**Review by btea — APPROVED** [review]
LGTM 👍

File: packages/components/menu/__tests__/menu.test.ts [hunk 2]
```diff
@@ -6,6 +6,8 @@ import Menu from '../src/menu'
 import MenuGroup from '../src/menu-item-group.vue'
 import MenuItem from '../src/menu-item.vue'
 import SubMenu from '../src/sub-menu'
+import defineGetter from '@element-plus/test-utils/define-getter'
+import { rAF } from '@element-plus/test-utils/tick'
```
Comment (Dsaquel) [inline packages/components/menu/__tests__/menu.test.ts]: imports `@element-plus/**` should be before the imported components.

**Review by Dsaquel — APPROVED** [review]
LGTM.

File: packages/components/menu/__tests__/menu.test.ts (hunk 2 above)
Comment (rzzf) [reply packages/components/menu/__tests__/menu.test.ts]: done, Thx.
