### PR TITLE
fix(components): [el-menu] fix warn & listen item

### LINKED ISSUE #3193: [bug report] the location of rendering slots of elmenu component is incorrect, resulting in an alarm when using JSX
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Chrome 92 

### Vue version
3.2.7

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/components/menu/src/menu.vue

### Steps to reproduce
```txt
import { ElMenu, ElMenuItem } from 'element-plus'
import { defineComponent } from 'vue'
export default defineComponent({
   render() {
      return <ElMenu>
         <ElMenuItem index="1">123</ElMenuItem>
      </ElMenu>
   }
})
```
上述代码造成Vue告警：

[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 

### What is Expected?
使用T/JSX开发时，使用element-plus不出现此告警。

### What is actually happening?
menu.vue 81行
```
const filteredSlot = ref(slots.default?.())
```
该代码在setup中导致告警。slots渲染应当放置在render中进行。

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/menu/src/menu.ts [hunk 1]
```diff
@@ -21,22 +20,18 @@ import ElMenuCollapseTransition from './menu-collapse-transition.vue'
...
 import useMenuColor from './useMenuColor'
 
+import type { VNode } from 'vue'
 import type {
   IMenuProps,
   RootMenuProvider,
   RegisterMenuItem,
   SubMenuProvider,
 } from './menu.type'
+import debounce from 'lodash/debounce'
```
Comment (JeremyWuuuuu) [inline packages/components/menu/src/menu.ts:30]: Can we move this like after Line#16?

File: packages/components/menu/src/menu.ts [hunk 2]
```diff
@@ -222,65 +217,7 @@ export default defineComponent({
...
-
-    const handleResize = () => {
-      updateFilteredSlot()
-    }
-
-    // watch
-    watch(() => slots.default?.(), () => {
-      updateFilteredSlot()
-    })
+    const handleResize = debounce(() => instance.proxy.$forceUpdate(), 50)
```
Comment (JeremyWuuuuu) [inline packages/components/menu/src/menu.ts:220]: Why not 
```ts
    const handleResize = debounce(instance.proxy.$forceUpdate, 50)
```

File: packages/components/menu/src/menu.ts [hunk 3]
```diff
@@ -347,37 +284,71 @@ export default defineComponent({
...
+            showMore.push(h(ElSubMenu, {
+              index: 'sub-menu-more',
+              class: 'el-sub-menu__hide-arrow',
+            }, {
+              title: () => h('i', { class: ['el-icon-more', 'el-sub-menu__icon-more'] }),
+              default: () => moreSlot,
+            }))
+          }
+        } else {
+          nextTick(() => instance.proxy.$forceUpdate())
```
Comment (JeremyWuuuuu) [inline packages/components/menu/src/menu.ts:328]: Why not
```ts
nextTick(instance.proxy.$forceUpdate)
```

File: packages/components/menu/__tests__/menu.spec.ts [hunk 4]
```diff
@@ -3,7 +3,7 @@ import { nextTick } from 'vue'
 import { sleep } from '@element-plus/test-utils'
 import { rAF } from '@element-plus/test-utils/tick'
 
-import Menu from '../src/menu.vue'
+import Menu from '../src/menu'
```
Comment (kooriookami) [inline packages/components/menu/__tests__/menu.spec.ts:6]: Why remove `.vue` extension?

File: packages/components/menu/src/menu.ts (hunk 2 above)
Comment (sxzz) [reply packages/components/menu/src/menu.ts:220]: This is to call it explicitly, or to prevent the `handleResize` parameter from being passed to `$forceUpdate`

File: packages/components/menu/src/menu.ts (hunk 3 above)
Comment (sxzz) [reply packages/components/menu/src/menu.ts:328]: Same. Prevent the parameters of `nextTick` from being inadvertently passed to `$forceUpdate`

File: packages/components/menu/__tests__/menu.spec.ts (hunk 4 above)
Comment (sxzz) [reply packages/components/menu/__tests__/menu.spec.ts:6]: `menu.vue` has been removed to `menu.ts`

File: packages/components/menu/src/menu.ts (hunk 1 above)
Comment (sxzz) [reply packages/components/menu/src/menu.ts]: Changed.

File: packages/components/menu/__tests__/menu.spec.ts (hunk 4 above)
Comment (kooriookami) [reply packages/components/menu/__tests__/menu.spec.ts:6]: > `menu.vue` has been removed to `menu.ts`

OK~

**Comment by JeremyWuuuuu** [comment]
Please rebase your codebase :bow:

**Review by jw-foss — APPROVED** [review]
