### PR TITLE
fix(components): [upload] before-upload change data in promise

### LINKED ISSUE #12340: [Component] [upload] [el-upload] 升级到2.3.2后，上传组件上传全线报错，无法使用
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.2`
- Browser / OS: `Chrome 96`
- Build Tool: `Webpack`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJmaWxlTGlzdFwiXG4gICAgY2xhc3M9XCJ1cGxvYWQtZGVtb1wiXG4gICAgYWN0aW9uPVwiaHR0cHM6Ly9ydW4ubW9ja3kuaW8vdjMvOWQwNTliZjktNDY2MC00NWYyLTkyNWQtY2U4MGFkNmM0ZDE1XCJcbiAgICA6ZGF0YT1cInVwbG9hZERhdGFcIlxuICAgIG11bHRpcGxlXG4gICAgOm9uLXByZXZpZXc9XCJoYW5kbGVQcmV2aWV3XCJcbiAgICA6YmVmb3JlLXVwbG9hZD1cImJlZm9yZVVwbG9hZFwiXG4gICAgOm9uLXJlbW92ZT1cImhhbmRsZVJlbW92ZVwiXG4gICAgOmJlZm9yZS1yZW1vdmU9XCJiZWZvcmVSZW1vdmVcIlxuICAgIDpsaW1pdD1cIjk5OTlcIlxuICAgIDpvbi1leGNlZWQ9XCJoYW5kbGVFeGNlZWRcIlxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC11cGxvYWQ+XG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UsIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxuaW1wb3J0IHR5cGUgeyBVcGxvYWRQcm9wcywgVXBsb2FkVXNlckZpbGUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGZpbGVMaXN0ID0gcmVmPFVwbG9hZFVzZXJGaWxlW10+KFtcbl0pXG5cbmNvbnN0IHVwbG9hZERhdGEgPSByZWFjdGl2ZTx7XG4gIGtleTogc3RyaW5nO1xufT4oe1xuICBrZXk6ICcnLFxufSk7XG5cbi8vIOaooeaLn+WbvueJh+WOi+e8qeeoi+W6j1xuY29uc3QgY29tcHJlc3NJbWFnZSA9IChyYXdGaWxlLCBjYikgPT4ge1xuICAvLyDmraTlpITlupTosIPnlKggbmV3IEltYWdlQ29tcHJlc3NvcihvcHRpb25zKSDljovnvKnlupNcbiAgLy8g5qih5ouf5Y6L57yp5Zue6LCDXG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNiKHJhd0ZpbGUpXG4gIH0sIDEwMDApXG59XG5cbmNvbnN0IGJlZm9yZVVwbG9hZDogVXBsb2FkUHJvcHNbJ2JlZm9yZVVwbG9hZCddID0gKHJhd0ZpbGU6IFVwbG9hZFJhd0ZpbGUpID0+IHtcbiAgLy8g5Y2H57qn5YiwIDIuMy4y54mI5pys5Lul5ZCO77yMYmVmb3JlVXBsb2Fk5aW95YOP5LiN6K+G5YircHJvbWlzZeS6hu+8jOWvvOiHtOS7peWJjeeahOWKn+iDveWFqOmDqOaKpemUme+8jOS4iuS8oE9TU+S5n+aKpemUmeS6hlxuICByZXR1cm4gbmV3IFByb21pc2UocmVzb2x2ZSA9PiB7XG4gICAgLy8g5qih5ouf5byC5q2l5aSE55CGXG4gICAgLy8gMS4g6K+35rGCYXBp5ou/b3Nz55qE6YWN572u5pWw5o2uXG4gICAgLy8gMi4g5qih5ouf56ys5LiJ5pa55Zu+54mH5aSE55CG5bqT55qE5byC5q2l5Zue6LCD5Ye95pWw77yM5aaC6LCD55SoIEltYWdlQ29tcHJlc3NvciDljovnvKnlm77niYfnrYlcbiAgICBzZXRUaW1vdXQoKCkgPT4ge1xuICAgICAgdXBsb2FkRGF0YS5rZXkgPSBgJHtyYXdGaWxlLm5hbWV9YDtcbiAgICAgIGNvbXByZXNzSW1hZ2UocmF3RmlsZSwgcmVzdWx0ID0+IHtcbiAgICAgICAgcmVzb2x2ZShyZXN1bHQpXG4gICAgICB9KVxuICAgIH0sIDIwMDApXG4gIH0pO1xuICBcbn07XG5cbmNvbnN0IGhhbmRsZVJlbW92ZTogVXBsb2FkUHJvcHNbJ29uUmVtb3ZlJ10gPSAoZmlsZSwgdXBsb2FkRmlsZXMpID0+IHtcbiAgY29uc29sZS5sb2coZmlsZSwgdXBsb2FkRmlsZXMpXG59XG5cbmNvbnN0IGhhbmRsZVByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9ICh1cGxvYWRGaWxlKSA9PiB7XG4gIGNvbnNvbGUubG9nKHVwbG9hZEZpbGUpXG59XG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIEVsTWVzc2FnZS53YXJuaW5nKFxuICAgIGBUaGUgbGltaXQgaXMgMywgeW91IHNlbGVjdGVkICR7ZmlsZXMubGVuZ3RofSBmaWxlcyB0aGlzIHRpbWUsIGFkZCB1cCB0byAke1xuICAgICAgZmlsZXMubGVuZ3RoICsgdXBsb2FkRmlsZXMubGVuZ3RoXG4gICAgfSB0b3RhbGx5YFxuICApXG59XG5cbmNvbnN0IGJlZm9yZVJlbW92ZTogVXBsb2FkUHJvcHNbJ2JlZm9yZVJlbW92ZSddID0gKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIHJldHVybiBFbE1lc3NhZ2VCb3guY29uZmlybShcbiAgICBgQ2FuY2VsIHRoZSB0cmFuc2ZlcnQgb2YgJHt1cGxvYWRGaWxlLm5hbWV9ID9gXG4gICkudGhlbihcbiAgICAoKSA9PiB0cnVlLFxuICAgICgpID0+IGZhbHNlXG4gIClcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

const beforeUpload: UploadProps['beforeUpload'] = (rawFile: UploadRawFile) => {
  // 升级到 2.3.2版本以后，beforeUpload好像不识别promise了，导致以前的功能全部报错，上传OSS也报错了。
  return new Promise(resolve => {
    // 模拟异步处理
    // 1. 请求api拿oss的配置数据
    // 2. 模拟第三方图片处理库的异步回调函数，如调用 ImageCompressor 压缩图片等
    setTimout(() => {
      uploadData.key = `${rawFile.name}`;
      compressImage(rawFile, result => {
        resolve(result)
      })
    }, 2000)
  });
};

### What is Expected?

以前的逻辑是对的，beforeUpload会等待promise的返回，promise返回后，才会进行下一步的上传。

### What is actually happening?

新的2.3.2版本出大bug了，beforeUpload会直接同步执行，不支持promise等待了，导致所有在promise里的对data赋值的代码全部失效，在上传文件时并没有把有效的参数带上去，导致上传功能全崩了。。

### Additional comments

请开发团队仔细看一下，这个问题太严重了，整条生产线因为更新了2.3.2，所有上传不能用了。。。感谢。。

### PR DESCRIPTION
**Pull request by GenerQAQ**
closed #12340

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
@chenxch what do you think?

**Comment by GenerQAQ** [comment]
@chenxch pls～

**Comment by chenxch** [comment]
@GenerQAQ Good job, would you mind adding a test case, the case is as follows:
1. First upload the file `test-file.txt`
2. Upload `files test-file.txt`, `test-file2.txt`
Finally, save the keyList as `[test-file.txt, test-file.txt, test-file2.txt]`

**Comment by GenerQAQ** [comment]
> @GenerQAQ Good job, would you mind adding a test case, the case is as follows:
> 
> 1. First upload the file `test-file.txt`
> 2. Upload `files test-file.txt`, `test-file2.txt`
>    Finally, save the keyList as `[test-file.txt, test-file.txt, test-file2.txt]`

No problem, later today~

**Comment by GenerQAQ** [comment]
> @GenerQAQ Good job, would you mind adding a test case, the case is as follows:
> 
> 1. First upload the file `test-file.txt`
> 2. Upload `files test-file.txt`, `test-file2.txt`
>    Finally, save the keyList as `[test-file.txt, test-file.txt, test-file2.txt]`

Added case

**Comment by GenerQAQ** [comment]
> @GenerQAQ Good job, would you mind adding a test case, the case is as follows:
> 
> 1. First upload the file `test-file.txt`
> 2. Upload `files test-file.txt`, `test-file2.txt`
>    Finally, save the keyList as `[test-file.txt, test-file.txt, test-file2.txt]`

Modified a case error

**Comment by GenerQAQ** [comment]
> @GenerQAQ Good job, would you mind adding a test case, the case is as follows:
> 
> 1. First upload the file `test-file.txt`
> 2. Upload `files test-file.txt`, `test-file2.txt`
>    Finally, save the keyList as `[test-file.txt, test-file.txt, test-file2.txt]`

Corrected lint error, thx~

**Review by chenxch — APPROVED** [review]
LGTM.

File: packages/components/upload/src/upload-content.vue [hunk 1]
```diff
@@ -92,9 +92,15 @@ const upload = async (rawFile: UploadRawFile) => {
...
   try {
+    // origin data: Handle data changes after synchronization tasks are executed
+    const originData = props.data
     const beforeUploadPromise = props.beforeUpload(rawFile)
     beforeData = isObject(props.data) ? cloneDeep(props.data) : props.data
     hookResult = await beforeUploadPromise
+    beforeData =
+      isObject(props.data) && isEqual(originData, beforeData)
+        ? cloneDeep(props.data)
+        : beforeData
```
Comment (btea) [inline packages/components/upload/src/upload-content.vue:103]: It seems that it can be adjusted as follows:
```ts
if (isObject(props.data) && isEqual(originData, beforeData)) {
  beforeData = cloneDeep(props.data)
}
```

**Review by btea — APPROVED** [review]

File: packages/components/upload/src/upload-content.vue [hunk 2]
```diff
@@ -92,9 +92,14 @@ const upload = async (rawFile: UploadRawFile) => {
   let beforeData: UploadContentProps['data'] = {}
 
   try {
+    // origin data: Handle data changes after synchronization tasks are executed
+    const originData = props.data
     const beforeUploadPromise = props.beforeUpload(rawFile)
     beforeData = isObject(props.data) ? cloneDeep(props.data) : props.data
     hookResult = await beforeUploadPromise
+    if (isObject(props.data) && isEqual(originData, beforeData)) {
```
Comment (Benleie) [inline packages/components/upload/src/upload-content.vue:100]: i think this line should be changed to ` if (isObject(props.data) && !isEqual(originData, beforeData))`. Because we only need to change ‘beforeData’ when props.data is updated after Promise task is resolved.

Comment (chenxch) [reply packages/components/upload/src/upload-content.vue:100]: At this time, `beforeData` is still the value under the synchronization task.

Comment (chenxch) [reply packages/components/upload/src/upload-content.vue:100]: image

Comment (Benleie) [reply packages/components/upload/src/upload-content.vue:100]: @chenxch , i add some test code to explain it more clearly in https://github.com/element-plus/element-plus/pull/12655

Comment (chenxch) [reply packages/components/upload/src/upload-content.vue:100]: @Benleie Good job, I like your proof, but I think that's a wrong usage, and you shouldn't construct an asynchronous processing inside a promise. If you judge according to your judgment, then there is a problem with the more common beforeupload below.

```ts
const beforeUpload: UploadProps['beforeUpload'] = (rawFile: UploadRawFile) => {
  return new Promise(resolve => {
      uploadData.key = `${rawFile.name}`;
      resolve(rawFile)
  });
};
```
At this time, all requested keys will become the same value.

Comment (Benleie) [reply packages/components/upload/src/upload-content.vue:100]: okay！

**Comment by GenerQAQ** [comment]
@btea May I ask what further steps are required to merge this PR?

**Comment by btea** [comment]
I think there seems to be no problem.

**Comment by lyhczz** [comment]
image
Hello, I have the above problem. Failed to modify data in the beforeUpload method. The difference is that promises also have an asynchronous method inside them.
@GenerQAQ

**Comment by JustGenius-s** [comment]
@lyhczz Same question, but i havd made a solution to make this code work well.

Modify the file of `node_modules\element-plus\es\components\upload\src\upload-content2.mjs`

In function `upload`:
```javascript
const upload = async (rawFile) => {
      ...
      try {
        const originData = props.data;
        const beforeUploadPromise = props.beforeUpload(rawFile);
        hookResult = await beforeUploadPromise; // Change the order call this statement before to update `beforeData`
        beforeData = isObject(props.data) ? cloneDeep(props.data) : props.data;
        if (isObject(props.data) && isEqual(originData, beforeData)) {
          beforeData = cloneDeep(props.data);
        }
      } catch (e) {
        hookResult = false;
      }
      ...
    };
```

After that, manually import this component form `node_modules\element-plus\es\components\upload\index` in ur vue component. And enjoy use it!

```javascript
import { ElUpload } from "element-plus/es/components/upload/index"
```

But i wonder if i should make a PR to slove this prolem.

**Comment by GenerQAQ** [comment]
@chenxch @lyhczz Received! I will reproduce the question tonight. Thank you

**Comment by xiaoshawangzi** [comment]
This issue seems to have not been resolved yet. My version is 2.3.8, El-Upload reactivity of 'data' attribute has been broken in 2.3.2 onwards
