### PR TITLE
fix(components): [select] fix the logic of updating selected data

### LINKED ISSUE #13346: [Component] [select] select不回显默认值
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.2`
- Element Plus Version: `2.3.7`
- Browser / OS: `114.0.5735.134（正式版本）/Windows 10 专业版 20H2`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHJlYWN0aXZlLHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdzZWxlY3Tnu4Tku7bml6Dms5Xlm57mmL7pu5jorqTlgLznmoTpl67popgnKVxuY29uc3QgZm9ybURhdGEgPSByZWFjdGl2ZSh7dGVjaG5vbG9neTogMCB9KTtcbmNvbnN0IG9wdGlvbnMgPSByZWYoW10pO1xuY29uc3QgaGFuZGxlU2VsZWN0Rm9jdXMgPSAoKSA9PiB7XG4gIG9wdGlvbnMudmFsdWUgPSBbXG4gICAgeyBpZDogMCwgbmFtZTogJ3Rlc3QwJyB9LFxuICAgIHsgaWQ6IDEsIG5hbWU6ICd0ZXN0MScgfVxuICBdO1xufTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIDxlbC1mb3JtLWl0ZW0+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgY2xhc3M9XCJtLTJcIlxuICAgICAgdi1tb2RlbD1cImZvcm1EYXRhLnRlY2hub2xvZ3lcIlxuICAgICAgcGxhY2Vob2xkZXI9XCLor7fpgInmi6nnsbvlnotcIlxuICAgICAgQGZvY3VzPVwiaGFuZGxlU2VsZWN0Rm9jdXNcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS5pZFwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubmFtZVwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0uaWRcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9lbC1mb3JtLWl0ZW0+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

el-select通过v-model绑定了一个默认值，用户通过鼠标点击el-select获取焦点后触发异步请求，加载el-option数据，然后存入pinia的store实例进行状态管理。el-option列表数据加载完毕后，没有将对应的label回显到el-select的默认值上面(即使失去焦点)，其他未选中状态的el-selcet组件可以正常回显已绑定的默认值对应的label。(已排除数据类型的错误)

### What is Expected?

option数据更新后，可以回显已获取焦点的el-select组件绑定的默认值的label

### What is actually happening?

未正确回显label

### Additional comments

```
<script>
import {ref,reactive} from 'vue';
const formData = reactive({technology: 0 });
const options = ref([]);
const handleSelectFocus = () => {
  options.value = [
    { id: 0, name: 'test0' },
    { id: 1, name: 'test1' }
  ];
};
</script>
<template>
    <el-select
      class="m-2"
      v-model="formData.technology"
      placeholder="请选择类型"
      @focus="handleSelectFocus"
    >
      <el-option
        v-for="item in options"
        :key="item.id"
        :label="item.name"
        :value="item.id"
      />
    </el-select>
</template>
```

### PR DESCRIPTION
**Pull request by inottn**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 9b03904</samp>

This pull request improves the select component by adding a test case for options prop changes and preventing unwanted query changes for non-remote or non-filterable selects.

## Related Issue

Fixes #13346

### <samp>🤖 Generated by Copilot at 9b03904</samp>

*  Prevent unnecessary queryChange calls when options prop changes ([link](https://github.com/element-plus/element-plus/pull/13374/files?diff=unified&w=0#diff-ae55c3efc549b49d40b3f5b535ac2fc1572374d9309b6439f8d529b06edb1368R348))
* Add test case for updating selected data when options prop changes ([link](https://github.com/element-plus/element-plus/pull/13374/files?diff=unified&w=0#diff-7cabf9c29b1c9e9c05c8b9c9c0d39175230ba4e872e88d42536c2157723229e0R2174-R2212))

### CODE REVIEW

**Comment by jianxchen** [comment]
Excuse me, when will the fix be merged into the dev branch

**Comment by inottn** [comment]
@btea help review? thx.

File: packages/components/select/src/useSelect.ts [hunk 1]
```diff
@@ -345,6 +345,7 @@ export const useSelect = (props, states: States, ctx) => {
       }
       const inputs = selectWrapper.value?.querySelectorAll('input') || []
       if (
+        !(props.remote || props.filterable) ||
```
Comment (btea) [inline packages/components/select/src/useSelect.ts:348]: Perhaps it would be better to change the judgment condition to the following:
```suggestion
        (!props.filterable && !props.defaultFirstOption && !isUndefined(props.modelValue)) ||
```

Comment (inottn) [reply packages/components/select/src/useSelect.ts]: done~

**Review by btea — APPROVED** [review]

**Comment by jianxchen** [comment]
> @btea help review? thx.

不合了吗

**Comment by inottn** [comment]
> > @btea help review? thx.
> 
> 不合了吗

It has been a long time since the first commit. Is there anything else I can do for the merge? Over time, it may be necessary to resolve conflicts, so I hope we can merge as soon as possible. @btea @ryuhangyeong

**Review by tolking — APPROVED** [review]
