### PR TITLE
fix(components): [pagination] reset icon hover state when page changes

### LINKED ISSUE #21370: [Component] [pagination] pagination分页组件图标显示异常问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.1`
- Element Plus Version: `2.10.4`
- Browser / OS: `Chrome 138.0`
- Build Tool: `Other`

### Related Component

- `el-pagination`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/pagination.html)

### Steps to reproduce

选至附加功能
以Total item count为例 
第一步：点击左边的...（第一页右边的icon）  此时icon变成<<（双箭头icon）
第二步：点击第10页   此时左侧的图标还是双箭头<<
第三步（错误现象）：悬浮左侧双箭头icon后移出，图标变成了...

### What is Expected?

期望图标显示有自己的规律

### What is actually happening?

目前这个more的图标没有什么规则，很随机，部分情况下是双箭头，部分情况下是三个点；总之在无意识点击的情况下，会很疑惑

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

When switching pages, the icon's hover state was not properly reset, causing the icon to retain its previous hover effect after pagination. This fix ensures that the hover state is reset correctly whenever the page changes.

fix #21370

### CODE REVIEW

**Comment by btea** [comment]
Could you provide a before-and-after GIF or video of the modification? I still don't understand what the problem is. 🤔

**Comment by rzzf** [comment]
> Could you provide a before-and-after GIF or video of the modification? I still don't understand what the problem is. 🤔

Please check:

1. Click the icon on the left.
2. Click the fifth page, icon change to `<<`（Expected `...`)

Before:

https://github.com/user-attachments/assets/d908a8b5-bd21-47b0-9af1-353109e77024

After:

https://github.com/user-attachments/assets/f0f48846-5bf3-4553-b1c0-901496f39bcc

File: packages/components/pagination/src/components/pager.vue [hunk 1]
```diff
@@ -143,19 +143,25 @@ const nextMoreKls = computed(() => [
...
+
+    if (pageCount > pagerCount) {
+      showPrev = currentPage > pagerCount - halfPagerCount
+      showNext = currentPage < pageCount - halfPagerCount
     }
-  }
-})
+
+    quickPrevHover.value &&= showPrevMore.value
+    quickNextHover.value &&= showNextMore.value
```
Comment (Dsaquel) [inline packages/components/pagination/src/components/pager.vue]: Any reason to change to a watch?

I feel like just adding the potential reset here is good, there are no re-trigger of the `watchEffect` if that the purpose.

Comment (cszhjh) [reply packages/components/pagination/src/components/pager.vue:159]: I think there’s a special case to consider: when hovering over the icon and switching pages programmatically, if the icon’s position and visibility don’t change, we might want to preserve the hover state.

So I believe we should rely on the current hover and icon state to decide whether we need to reset it to false. If we use watchEffect, quickPrevHover will be collected as a dependency, which could cause the effect to re-run unnecessarily when mouse events change the hover state — even though it’s unrelated to pagination logic.

What do you think?

Comment (rzzf) [reply packages/components/pagination/src/components/pager.vue]: I think there’s a special case to consider: when hovering over the icon and changing pages programmatically, if the icon's position and visibility don’t change, we might want to preserve the hover state. 

So I think we should rely on the current hover and icon state to decide whether or not we need to reset it to `false`.

You're right about `watchEffect`—I’ll revert it.

What do you think?

Comment (rzzf) [reply packages/components/pagination/src/components/pager.vue]: Regarding `watchEffect`, I think although modifying `quickPrevHover` inside the effect won't cause repeated triggers, changes to `quickPrevHover` from mouse events will still cause unnecessary re-executions, even if those changes are unrelated to the pagination logic.

So I think using `watch` is better—at least it makes the sources we listen to explicit, which is easier to maintain and understand. What do you think?

Comment (Dsaquel) [reply packages/components/pagination/src/components/pager.vue]: Yeah i basically agree with you, i just realized that `&&=` will implicitly read the value and set it as dependency causing unexpect triggers when hover an icon hahaha.
Wanted initially to have a minimal diff but we may need to revert with your previous solution or use `unref` (both are fine for me).

Comment (rzzf) [reply packages/components/pagination/src/components/pager.vue]: hahaha🤣. I have just restored the code, please review it again.

Comment (Dsaquel) [reply packages/components/pagination/src/components/pager.vue]: nice thanks you :+1:

**Review by Dsaquel — APPROVED** [review]

**Review by btea — APPROVED** [review]
Thanks!
