### PR TITLE
fix(components): [tree-select] v-model invalid when source changes

### LINKED ISSUE #14204: [Component] [tree-select] v-for循环el-tree-select组件出来后无法修改第一个el-tree-select组件的value值
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.10`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbjxkaXYgdi1mb3I9XCIoaXRlbSxpbmRleCkgaW4gdmFsdWVMaXN0XCI+XG48ZWwtdHJlZS1zZWxlY3RcbiAgICB2LW1vZGVsPVwiaXRlbS5vcmdOYW1lXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGNoZWNrLXN0cmljdGx5XG4gICAgOnJlbmRlci1hZnRlci1leHBhbmQ9XCJmYWxzZVwiXG4gICAgbm8tZGF0YS10ZXh0PVwi5pqC5peg6YCJ6aG5XCJcbiAgICBhY2NvcmRpb25cbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBwbGFjZWhvbGRlcj1cIiBcIlxuICAgIHZhbHVlLWtleT1cIm9yZ05hbWVcIlxuICAgIDpwcm9wcz1cInsgbGFiZWw6ICdvcmdOYW1lJywgdmFsdWU6ICdvcmdOYW1lJywgY2hpbGRyZW46J2NoaWxkcmVuJywgfVwiXG4gIC8+XG48L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlTGlzdCA9IHJlZihbe1wib3JnTmFtZVwiOlwiXCJ9LHtcIm9yZ05hbWVcIjpcIlwifV0pXG5cbmNvbnN0IGdldERhdGEgPSBhc3luYyAoKSA9PiB7XG4gIGF3YWl0IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiBzZXRUaW1lb3V0KHJlc29sdmUsIDMwMCkpXG4gIHZhbHVlTGlzdC52YWx1ZSA9IFtcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4fkuIBcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5LqMXCJ9LFxuICAgIHtcIm9yZ05hbWVcIjpcIue7hOe7h+S4iVwifSxcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4flm5tcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5LqUXCJ9LFxuICAgIHtcIm9yZ05hbWVcIjpcIue7hOe7h+WFrVwifSxcbiAgICB7XCJvcmdOYW1lXCI6XCLnu4Tnu4fkuINcIn0sXG4gICAge1wib3JnTmFtZVwiOlwi57uE57uH5YWrXCJ9XG4gIF1cbn1cbmdldERhdGEoKVxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIFwiaWRcIjoyNyxcbiAgICBcInBhcmVudElkXCI6LTEsXG4gICAgXCJjaGlsZHJlblwiOltcbiAgICAgIHtcbiAgICAgICAgXCJpZFwiOjI4LFxuICAgICAgICBcInBhcmVudElkXCI6MjcsXG4gICAgICAgIFwiY2hpbGRyZW5cIjpbXG4gICAgICAgICAge1xuICAgICAgICAgICAgXCJpZFwiOjMwLFxuICAgICAgICAgICAgXCJwYXJlbnRJZFwiOjI4LFxuICAgICAgICAgICAgXCJjaGlsZHJlblwiOltdLFxuICAgICAgICAgICAgXCJvcmdOYW1lXCI6XCLnp4DmlrAy6ZifXCIsXG4gICAgICAgICAgICBcImxldmVsXCI6MyxcbiAgICAgICAgICAgIFwic29ydFwiOjFcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIFwiaWRcIjoyOSxcbiAgICAgICAgICAgIFwicGFyZW50SWRcIjoyOCxcbiAgICAgICAgICAgIFwiY2hpbGRyZW5cIjpbXSxcbiAgICAgICAgICAgIFwib3JnTmFtZVwiOlwi56eA5pawMemYn1wiLFxuICAgICAgICAgICAgXCJsZXZlbFwiOjMsXG4gICAgICAgICAgICBcInNvcnRcIjoxXG4gICAgICAgICAgfVxuICAgICAgICBdLFxuICAgICAgXCJvcmdOYW1lXCI6XCLnp4DmlrBcIixcbiAgICAgIFwibGV2ZWxcIjoyLFxuICAgICAgXCJzb3J0XCI6MVxuICAgICAgfVxuICAgIF0sXG4gICAgXCJvcmdOYW1lXCI6XCLlnZHmopPpobnnm65cIixcbiAgICBcImxldmVsXCI6MSxcbiAgICBcInNvcnRcIjoxXG4gIH0sXG4gIHtcbiAgICBcImlkXCI6MzIsXG4gICAgXCJwYXJlbnRJZFwiOi0xLFxuICAgIFwiY2hpbGRyZW5cIjpbXSxcbiAgICBcIm9yZ05hbWVcIjpcIuWdkeaik+a1i+ivlVwiLFxuICAgIFwibGV2ZWxcIjoxLFxuICAgIFwic29ydFwiOjJcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

1.初始化valueList的值
2.请求获取的值并赋值给valueList
3.修改valueList中的某一项
4.初始化的那一项无法触发修改
详细情况可通过`Element Plus Playground`查看，也就是上面的链接
1. Initialize the value of the valueList
2. Request the obtained value and assign it to the valueList
3. Modify an item in the valueList
4. The initialized item cannot trigger modification
Details can be found in the 'Element Plus Playground', which is the link above

### What is Expected?

希望修改tree-select组件的值
I want to change the value of tree-select component

### What is actually happening?

但是第一个tree-select组件无法更换值
But the first tree-select component cannot be replaced

### Additional comments

当`valueList`的初始化值为`[]`（空数组），又可以选择了，我就想知道这是问什么呢，在之前的写的都没遇到过这种问题
When the `valueList` is initialized to `[]` (empty array) and can be selected again, I wonder what this is asking, since I have never encountered this problem before

### PR DESCRIPTION
**Pull request by yujinpan**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 3083506</samp>

This pull request enhances the `TreeSelect` component with custom event emission and `v-model` reactivity. It also adds a test case to ensure the component works as expected with dynamic data.

## Related Issue

Fixes #14204.

### <samp>🤖 Generated by Copilot at 3083506</samp>

* Fix bug where `TreeSelect` component does not update `v-model` value when binding source changes ([link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-d895cf8665299f6e338ee3fcd1259cbb2de31a2278a4bb30f691fe86fb497df7L11-R11), [link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-d895cf8665299f6e338ee3fcd1259cbb2de31a2278a4bb30f691fe86fb497df7R26-R29), [link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-38c0e66ee242d4981b4f2cd98f7a9fee72c2a789424872de31570565d475726dR679-R705))
  - Add `emit` parameter to `useSelect` function in `select.ts` to emit custom events from `TreeSelect` component ([link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-d895cf8665299f6e338ee3fcd1259cbb2de31a2278a4bb30f691fe86fb497df7L11-R11))
  - Add listener for `update:modelValue` event to `attrs` object in `select.ts` to re-emit the same event from `TreeSelect` component ([link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-d895cf8665299f6e338ee3fcd1259cbb2de31a2278a4bb30f691fe86fb497df7R26-R29))
  - Add test case in `tree-select.test.tsx` to verify that `TreeSelect` component can handle dynamic `v-model` binding source changes ([link](https://github.com/element-plus/element-plus/pull/14603/files?diff=unified&w=0#diff-38c0e66ee242d4981b4f2cd98f7a9fee72c2a789424872de31570565d475726dR679-R705))

### CODE REVIEW

File: packages/components/tree-select/src/select.ts [hunk 1]
```diff
@@ -23,6 +23,10 @@ export const useSelect = (
   const result = {
     ...pick(toRefs(props), Object.keys(ElSelect.props)),
     ...attrs,
+    // attrs is not reactive, when v-model binding source changes,
+    // this listener is still old, see the bug(or test 'v-model source change'):
+    // https://github.com/element-plus/element-plus/issues/14204
+    'onUpdate:modelValue': (value) => emit('update:modelValue', value),
```
Comment (btea) [inline packages/components/tree-select/src/select.ts:29]: Maybe we can use the constant `UPDATE_MODEL_EVENT`.
https://github.com/element-plus/element-plus/blob/bb12dd5e7eb9ad77c42f6671ed0da59fac04751f/packages/constants/event.ts#L1

Comment (yujinpan) [reply packages/components/tree-select/src/select.ts]: Sure! Thank you!

**Review by btea — APPROVED** [review]
