### PR TITLE
fix(components): [el-table] avoid scrollbar not display

### LINKED ISSUE #5917: [Bug Report] ElTable 从keepalive中恢复后，垂直滚动条不显示。
### Discussed in https://github.com/element-plus/element-plus/discussions/5908

<div type='discussions-op-text'>

<sup>Originally posted by **zychome** February 10, 2022</sup>
ElTable 从keepalive中恢复后，垂直滚动条不显示。</div>

### PR DESCRIPTION
**Pull request by msidolphin**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/scrollbar/src/scrollbar.vue [hunk 1]
```diff
@@ -151,6 +150,19 @@ export default defineComponent({
       { immediate: true }
     )
 
+    watch(
```
Comment (JeremyWuuuuu) [inline packages/components/scrollbar/src/scrollbar.vue:153]: Should we deep watch or we do something like:

```ts
watch(() => {
  const [_, ourStyle] = style.value
  return {...ourStyle}
}, handler)
```

Comment (JeremyWuuuuu) [reply packages/components/scrollbar/src/scrollbar.vue:153]: I suspect that this watch would take effect since the `style.value.length` has not been changed, `watch` will not deep watch for us in Vue3.

File: packages/components/scrollbar/src/scrollbar.vue [hunk 2]
```diff
@@ -151,6 +150,19 @@ export default defineComponent({
...
+      () => style.value,
+      () => {
+        if (!props.native)
+          nextTick(() => {
+            update()
+            if (wrap$.value) {
+              barRef.value?.handleScroll(wrap$.value)
+            }
```
Comment (JeremyWuuuuu) [inline packages/components/scrollbar/src/scrollbar.vue:161]: Is this `nextTick` necessary here? I think we should be a little bit careful with using `nextTick` in our code.

**Review by jw-foss — COMMENTED** [review]
Left some comments for you to consider ;)

File: packages/components/scrollbar/src/scrollbar.vue (hunk 1 above)
Comment (msidolphin) [reply packages/components/scrollbar/src/scrollbar.vue:153]: > I suspect that this watch would take effect since the `style.value.length` has not been changed, `watch` will not deep watch for us in Vue3.

style is a `computed` property, so I think it's fine

File: packages/components/scrollbar/src/scrollbar.vue (hunk 2 above)
Comment (msidolphin) [reply packages/components/scrollbar/src/scrollbar.vue:161]: > Is this `nextTick` necessary here? I think we should be a little bit careful with using `nextTick` in our code.

I need to make sure the dom update is complete, otherwise the height will be wrong

File: packages/components/scrollbar/src/scrollbar.vue (hunk 1 above)
Comment (msidolphin) [reply packages/components/scrollbar/src/scrollbar.vue:153]: > I suspect that this watch would take effect since the `style.value.length` has not been changed, `watch` will not deep watch for us in Vue3.

I shouldn't listened to the computed property, I changed it to `watch(() => [props.maxHeight, props.height])`

**Review by jw-foss — APPROVED** [review]
