### PR TITLE
fix(components): [color-picker] attrs class

### LINKED ISSUE #16886: [Component] [color-picker] Cannot set class name of el-color-picker’s trigger
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`
- Build Tool: `Other`

### Related Component

- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNvbG9yLXBpY2tlciB2LW1vZGVsPVwiY29sb3JcIiBzaG93LWFscGhhIDpwcmVkZWZpbmU9XCJwcmVkZWZpbmVDb2xvcnNcIiBjbGFzcz1cImFueXRoaW5nXCIgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbG9yID0gcmVmKCdyZ2JhKDI1NSwgNjksIDAsIDAuNjgpJylcbmNvbnN0IHByZWRlZmluZUNvbG9ycyA9IHJlZihbXG4gICcjZmY0NTAwJyxcbiAgJyNjNzE1ODU3NycsXG5dKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

type
```html
<el-color-picker v-model="color" show-alpha :predefine="predefineColors" class="anything" />
```
in the template.

### What is Expected?

the div with class `el-color-picker` has also the class name `anything`

### What is actually happening?

the div with class `el-color-picker` has no class name `anything`

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Liao-js**
fix https://github.com/element-plus/element-plus/issues/16886

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/color-picker/src/color-picker.vue [hunk 1]
```diff
@@ -152,6 +153,7 @@ defineOptions({
 })
 const props = defineProps(colorPickerProps)
 const emit = defineEmits(colorPickerEmits)
+const attrs = useAttrs()
```
Comment (btea) [inline packages/components/color-picker/src/color-picker.vue:156]: Maybe we can directly use `v-bind` to bind `attrs`.

**Review by btea — APPROVED** [review]
LGTM
