### PR TITLE
fix: Input style use show-password and clearable (#2168)

### LINKED ISSUE #2168: [Bug Report] Input use 'show-password' and 'clearable', content too lange will cover clear icon
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
macOS 11.3 / Chorm Version 91.0.4472.77 (Official Build) (x86_64)

### Vue version
3.1.0-beta.7

### Reproduction Link
https://jsfiddle.net/3zv6gny1/

### Steps to reproduce
mouse cursor hovers over the input, can see text is covering on the clear icon

### What is Expected?
Use 'show-password' and 'clearable' at the same time, input padding-right should be wider

### What is actually happening?
text too lange, it will be covering on the clear icon

image

### PR DESCRIPTION
**Pull request by dreamqyq**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

fixed #2168

### CODE REVIEW

File: packages/input/src/index.vue [hunk 1]
```diff
@@ -10,7 +10,8 @@
         'el-input-group--append': $slots.append,
         'el-input-group--prepend': $slots.prepend,
         'el-input--prefix': $slots.prefix || prefixIcon,
-        'el-input--suffix': $slots.suffix || suffixIcon || clearable || showPassword
+        'el-input--suffix': $slots.suffix || suffixIcon || clearable || showPassword,
+        'el-input--suffix--passwordClear': clearable && showPassword
```
Comment (0song) [inline packages/input/src/index.vue:14]: 'el-input--suffix--password-clear' looks better?

Comment (dreamqyq) [reply packages/input/src/index.vue:14]: Thanks for your sugesstion, I will change it

**Review by iamkun — APPROVED** [review]

**Comment by iamkun** [comment]
Cool
