### PR TITLE
Select filtering is not working

### LINKED ISSUE #386: Options filtering isn't working for Select
use `yarn website:dev` to be able to test the select component.
go to the Option filtering example. Try to filter options. It won't work

### PR DESCRIPTION
**Pull request by g3r4n**
fix #386

### CODE REVIEW

File: packages/select/src/token.ts [hunk 1]
```diff
@@ -35,5 +35,10 @@ export const selectGroupKey: InjectionKey<SelectGroupContext> = Symbol('SelectGr
 export const selectKey: InjectionKey<SelectContext> = Symbol('Select')
 
 export const selectEvents = {
-  queryChange: 'elOptionGroupQueryChange',
+  elOptionGroup: {
```
Comment (HerringtonDarkholme) [inline packages/select/src/token.ts:38]: I would personally prefer using flat structure, say two names for different `queryChange`: queryChange and groupQueryChange.

Comment (g3r4n) [reply packages/select/src/token.ts]: Fixed

**Review by HerringtonDarkholme — APPROVED** [review]

File: packages/select/src/useSelect.ts [hunk 2]
```diff
@@ -313,7 +313,7 @@ export const useSelect = (props, states: States, ctx) => {
       const option = states.options[i]
       if (states.query) {
         // highlight first options that passes the filter
-        if (!option.props.disabled && !option.props.groupDisabled && option.visible) {
+        if (!option.$props.disabled && !option.$props.groupDisabled && option.visible) {
```
Comment (HerringtonDarkholme) [inline packages/select/src/useSelect.ts:316]: We can safely replace `options.$props.dsiabled` by `options.dislabed` I think?

```suggestion
        if (!option.disabled && !option.groupDisabled && option.visible) {
```
