### PR TITLE
fix(components): [time-picker] range type add id automatically

### LINKED ISSUE #21733: [Component] [form-item] el-form-item 嵌套el-date-picker时的dom生成bug
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.18`
- Element Plus Version: `2.10.6`
- Browser / OS: `chrome`
- Build Tool: `Vite`

### Related Component

- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuICBjb25zdCBxdWVyeUZvcm0gPSByZWYoe1xuICAgIHVzZXI6IFwiXCIsXG4gICAgZGVwYXJ0bWVudDogXCJcIixcbiAgICBpcDogXCJcIixcbiAgICB0aW1lOiBcIlwiLFxuICB9KTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIHJlZj1cInF1ZXJ5Rm9ybVJlZlwiIDptb2RlbD1cInF1ZXJ5Rm9ybVwiIGxhYmVsLXdpZHRoPVwiYXV0b1wiPlxuICAgPGVsLXJvdyA6Z3V0dGVyPVwiMTBcIj5cbiAgICAgICAgPGVsLWNvbCA6c3Bhbj1cIjVcIj5cbiAgICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiSVBcIiBwcm9wPVwiaXBcIj5cbiAgICAgICAgICAgIDxlbC1pbnB1dCBzdHlsZT1cIndpZHRoOiAxMDAlXCIgdi1tb2RlbD1cInF1ZXJ5Rm9ybS5pcFwiIC8+XG4gICAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgIDwvZWwtY29sPlxuICAgICAgICA8ZWwtY29sIDpzcGFuPVwiN1wiPlxuICAgICAgICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCLml7bpl7RcIj5cbiAgICAgICAgICAgIDxlbC1kYXRlLXBpY2tlciB2LW1vZGVsPVwicXVlcnlGb3JtLnRpbWVcIiB0eXBlPVwiZGF0ZXJhbmdlXCIgcmFuZ2Utc2VwYXJhdG9yPVwiLVwiIC8+XG4gICAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICAgIDwvZWwtY29sPlxuICAgICAgICA8L2VsLXJvdz5cbiAgICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

        <el-col :span="5">
          <el-form-item label="IP" prop="ip">
            <el-input style="width: 100%" v-model="queryForm.ip" />
          </el-form-item>
        </el-col>       
 <el-col :span="7">
          <el-form-item label="时间">
            <el-date-picker v-model="queryForm.time" type="daterange" range-separator="-" />
          </el-form-item>
        </el-col>

### What is Expected?

期望label="时间"时,el-form-item__label-wrap的子节点el-form-item__label 类名所对应的标签为label，而不是div

### What is actually happening?

label="时间" 的话  el-form-item__label-wrap的子节点el-form-item__label 类名所对应的标签为div ，但是label="IP"时，内部嵌套的不是el-date-picker而是其他时，el-form-item__label 类名所对应的标签为label

### Additional comments

可打开控制台后查看元素，进行对比，会发现el-form-item嵌套el-date-picker时，子节点不是label标签，而是div标签。

Image

### PR DESCRIPTION
**Pull request by catanswer**
close #21733
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/time-picker/src/common/picker-range-trigger.vue [hunk 1]
```diff
@@ -64,6 +65,14 @@ const emit = defineEmits([
   'endChange',
 ])
 
+const { formItem: elFormItem } = useFormItem()
+const { inputId } = useFormItemInputId(
+  { ...props, id: props.id && props.id[0] },
```
Comment (rzzf) [inline packages/components/time-picker/src/common/picker-range-trigger.vue]:
```suggestion
  reactive({ ...props, id: computed(() => props.id?.[0]) }),
```

Because currently cannot respond to `id` changes.

Failed [examples](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHF1ZXJ5Rm9ybSA9IHJlZih7XG4gIHVzZXI6ICcnLFxuICBkZXBhcnRtZW50OiAnJyxcbiAgaXA6ICcnLFxuICB0aW1lOiAnJyxcbn0pXG5cbmNvbnN0IGlkID0gcmVmPFtzdHJpbmcsIHN0cmluZ10+KClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1idXR0b24gQGNsaWNrID0gXCJpZCA9IFsndGVzdDEnLCAndGVzdDInXVwiPmNoYW5nZSBpZDwvZWwtYnV0dG9uPlxuXG4gIDxociAvPlxuXG4gIDxlbC1mb3JtIHJlZj1cInF1ZXJ5Rm9ybVJlZlwiIDptb2RlbD1cInF1ZXJ5Rm9ybVwiIGxhYmVsLXdpZHRoPVwiYXV0b1wiPlxuICAgIDxlbC1yb3cgOmd1dHRlcj1cIjEwXCI+XG4gICAgICA8ZWwtY29sIDpzcGFuPVwiNVwiPlxuICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiSVBcIiBwcm9wPVwiaXBcIj5cbiAgICAgICAgICA8ZWwtaW5wdXQgc3R5bGU9XCJ3aWR0aDogMTAwJVwiIHYtbW9kZWw9XCJxdWVyeUZvcm0uaXBcIiAvPlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDwvZWwtY29sPlxuICAgICAgPGVsLWNvbCA6c3Bhbj1cIjdcIj5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIuaXtumXtFwiPlxuICAgICAgICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgICAgICAgOmlkPVwiaWRcIlxuICAgICAgICAgICAgdi1tb2RlbD1cInF1ZXJ5Rm9ybS50aW1lXCJcbiAgICAgICAgICAgIHR5cGU9XCJkYXRlcmFuZ2VcIlxuICAgICAgICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiLVwiXG4gICAgICAgICAgLz5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICA8L2VsLWNvbD5cbiAgICA8L2VsLXJvdz5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0yMTc0Ni1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0yMTc0Ni1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0yMTc0Ni1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0yMTc0Ni1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzIn19)

File: packages/components/time-picker/src/common/picker-range-trigger.vue [hunk 2]
```diff
@@ -11,7 +11,7 @@
     <slot name="prefix" />
     <input
       v-bind="attrs"
-      :id="id && id[0]"
+      :id="(id && id[0]) ?? inputId"
```
Comment (rzzf) [inline packages/components/time-picker/src/common/picker-range-trigger.vue]:
```suggestion
      :id="inputId"
```

You can use `inputId` directly here, as useFormItemInputId has already [handled](https://github.com/element-plus/element-plus/blob/66a0ca27587f2404eb7dab86bceb1804ca2b96bc/packages/components/form/src/hooks/use-form-item.ts#L84) `props.id`.

File: packages/components/time-picker/src/common/picker-range-trigger.vue [hunk 3]
```diff
@@ -64,6 +65,14 @@ const emit = defineEmits([
   'endChange',
 ])
 
+const { formItem: elFormItem } = useFormItem()
+const { inputId } = useFormItemInputId(
+  reactive({ ...props, id: computed(() => props.id?.[0]) }),
```
Comment (Dsaquel) [inline packages/components/time-picker/src/common/picker-range-trigger.vue]: **nit**:

```suggestion
  reactive({ id: computed(() => props.id?.[0]) }),
```

File: packages/components/time-picker/src/common/picker-range-trigger.vue [hunk 4]
```diff
@@ -64,6 +65,14 @@ const emit = defineEmits([
   'endChange',
 ])
 
+const { formItem: elFormItem } = useFormItem()
```
Comment (Dsaquel) [inline packages/components/time-picker/src/common/picker-range-trigger.vue]:
```suggestion
const { formItem } = useFormItem()
```

**Review by Dsaquel — APPROVED** [review]
Thanks!

**Comment by catanswer** [comment]
@cszhjh review一下吧

**Review by rzzf — COMMENTED** [review]
LGTM

**Review by warmthsea — APPROVED** [review]
