### PR TITLE
fix(time-select): input value not changed with v-model bindings

### LINKED ISSUE #1724: [Bug Report] el-time-picker value not change
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Windows 10 / Chrome 84 & Firefox 87.0

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/hakurouken/pen/oNBzrLP

### Steps to reproduce
1. open https://codepen.io/hakurouken/pen/oNBzrLP
2. Click "Update Value" button.

### What is Expected?
The value of TimePicker should be changed to `18:15`.

### What is actually happening?
Nothing happened.

### PR DESCRIPTION
**Pull request by HakurouKen**
* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

fix #1724

### CODE REVIEW

File: packages/time-select/src/time-select.vue [hunk 1]
```diff
@@ -1,17 +1,21 @@
...
     :size="size"
     :placeholder="placeholder"
     default-first-option
     filterable
+    @update:model-value="
+      (value) => {
+        $emit('update:modelValue', value)
+      }
+    "
     @change="
```
Comment (JeremyWuuuuu) [inline packages/time-select/src/time-select.vue:16]: I don't quite understand why do you have to do this
since `v-model` is a syntax sugar for two way bindings which will be unwraps to `modelValue` and `update:modelValue`.
What is the point of rewriting this?

Comment (JeremyWuuuuu) [reply packages/time-select/src/time-select.vue:16]: I think I might know the root cause on this issue, the simplest way to fix this utilizing the props.modelValue instead of wrapping it with `computed`.

Comment (JeremyWuuuuu) [reply packages/time-select/src/time-select.vue:16]: cc @zazzaz

Comment (JeremyWuuuuu) [reply packages/time-select/src/time-select.vue:16]: The easiest way to fix this is that we bind it with `props.modelValue` instead of creating a new value, could you try that locally see if it works?

Comment (HakurouKen) [reply packages/time-select/src/time-select.vue:16]: Nope, `v-model` is shorten for `:model-value="v"` and `@update:model-value="v = $event"` (not `update:model-value="$emit('update:model-value', $event)"`), which will cause a error when clicking an option item in dropdown menu. I'll add a test case for that later.
image

Comment (HakurouKen) [reply packages/time-select/src/time-select.vue]: Also, maybe related to #1505 ?

Comment (JeremyWuuuuu) [reply packages/time-select/src/time-select.vue]: Right, make sense, I was wrong about the `@update` thing.  LGTM.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
I think the code still had some flaws in it. But I merged it anyway. The `computed` statement is not really needed, using `props.modelValue` should be ok.
