### PR TITLE
fix(build): output task name repeat

### LINKED ISSUE #6362: [Bug Report] [Build] [All] build：runtask包装任务导致控制台log重复输出
Bug Type: **`Build`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome 98.0.4758.102`
- Build Tool: `Rollup`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/dev/build/gulpfile.ts)

### Steps to reproduce

1、执行pnpm build 观察控制台输出即可（方便观察可以向下列一样注释部分task）
`parallel(
    runTask('buildModules')
    // runTask('buildFullBundle'),
    // runTask('generateTypesDefinitions'),
    // runTask('buildHelper'),
    // series(
    //   withTaskName('buildThemeChalk', () =>
    //     run('pnpm run -C packages/theme-chalk build')
    //   ),
    //   copyFullStyle
    // )
  )
`

### What is Expected?

Starting 'buildModules'...
Finished 'buildModules'
以上log仅输出一次

### What is actually happening?

Starting 'buildModules'...
Finished 'buildModules'
以上log重复输出

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by kinfuy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.
#6362

### CODE REVIEW

File: build/utils/gulp.ts [hunk 1]
```diff
@@ -1,8 +1,14 @@
...
+  fn: T,
+  shell = false
+) => {
+  if (shell) return Object.assign(fn, { displayName: `shell task ${name}` })
+  return Object.assign(fn, { displayName: name })
+}
 
 export const runTask = (name: string) =>
-  withTaskName(name, () => run(`pnpm run build ${name}`))
+  withTaskName(name, () => run(`pnpm run build ${name}`), true)
```
Comment (sxzz) [inline build/utils/gulp.ts:14]:
```suggestion
  withTaskName(`shellTask:${name}`, () => run(`pnpm run build ${name}`))
```

File: build/utils/gulp.ts [hunk 2]
```diff
@@ -1,8 +1,14 @@
...
-export const withTaskName = <T extends TaskFunction>(name: string, fn: T) =>
-  Object.assign(fn, { displayName: name })
+export const withTaskName = <T extends TaskFunction>(
+  name: string,
+  fn: T,
+  shell = false
+) => {
+  if (shell) return Object.assign(fn, { displayName: `shell task ${name}` })
+  return Object.assign(fn, { displayName: name })
+}
```
Comment (sxzz) [inline build/utils/gulp.ts:11]: Revert this

File: build/utils/gulp.ts (hunk 1 above)
Comment (HitStarrySky) [reply build/utils/gulp.ts:14]: Thank you for your suggestion. I'll deal with it

**Review by sxzz — APPROVED** [review]
