### PR TITLE
docs(components): [tree] fix import error type

### LINKED ISSUE #10619: [Component] [tree] Tree control: dropType type is not defined
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.21`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5pbXBvcnQgdHlwZSB7IERyYWdFdmVudHMgfSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC91c2VEcmFnTm9kZSdcbiAgLy8gVGhlIG9mZmljaWFsIGV4cG9ydCBpcycgRHJvcFR5cGUgJywgYnV0IHRoaXMgdHlwZSBoYXMgbm90IGJlZW4gZXhwb3J0ZWQuIFNlZScgTm9kZURyb3BUeXBlICdleHBvcnRlZCBpbiB0cmVlLiB0eXBlYFxuaW1wb3J0IHR5cGUgeyBOb2RlRHJvcFR5cGUgYXMgRHJvcFR5cGUgfSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy90cmVlLnR5cGUnXG5cbiBjb25zdCBoYW5kbGVEcmFnU3RhcnQgPSAobm9kZTogTm9kZSwgZXY6IERyYWdFdmVudHMpID0+IHtcbiAgY29uc29sZS5sb2coJ2RyYWcgc3RhcnQnLCBub2RlKVxufVxuY29uc3QgaGFuZGxlRHJhZ0VudGVyID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgZW50ZXI6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnTGVhdmUgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBsZWF2ZTonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdPdmVyID0gKGRyYWdnaW5nTm9kZTogTm9kZSwgZHJvcE5vZGU6IE5vZGUsIGV2OiBEcmFnRXZlbnRzKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgb3ZlcjonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdFbmQgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGRyb3BUeXBlOiBEcm9wVHlwZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVuZDonLCBkcm9wTm9kZSAmJiBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG4gIGNvbnNvbGUubG9nKCc9PWRyb3BUeXBlOicsIGRyb3BUeXBlKVxufVxuY29uc3QgaGFuZGxlRHJvcCA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZHJvcFR5cGU6IERyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyb3A6JywgZHJvcE5vZGUubGFiZWwsIGRyb3BUeXBlKVxufVxuY29uc3QgYWxsb3dEcm9wID0gKGRyYWdnaW5nTm9kZTogTm9kZSwgZHJvcE5vZGU6IE5vZGUsIHR5cGU6IERyb3BUeXBlKSA9PiB7XG4gIGlmIChkcm9wTm9kZS5kYXRhLmxhYmVsID09PSAnTGV2ZWwgdHdvIDMtMScpIHtcbiAgICByZXR1cm4gdHlwZSAhPT0gJ2lubmVyJ1xuICB9IGVsc2Uge1xuICAgIHJldHVybiB0cnVlXG4gIH1cbn1cbmNvbnN0IGFsbG93RHJhZyA9IChkcmFnZ2luZ05vZGU6IE5vZGUpID0+IHtcbiAgcmV0dXJuICFkcmFnZ2luZ05vZGUuZGF0YS5sYWJlbC5pbmNsdWRlcygnTGV2ZWwgdGhyZWUgMy0xLTEnKVxufVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiA8ZWwtdHJlZVxuICAgIDphbGxvdy1kcm9wPVwiYWxsb3dEcm9wXCJcbiAgICA6YWxsb3ctZHJhZz1cImFsbG93RHJhZ1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBkcmFnZ2FibGVcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBAbm9kZS1kcmFnLXN0YXJ0PVwiaGFuZGxlRHJhZ1N0YXJ0XCJcbiAgICBAbm9kZS1kcmFnLWVudGVyPVwiaGFuZGxlRHJhZ0VudGVyXCJcbiAgICBAbm9kZS1kcmFnLWxlYXZlPVwiaGFuZGxlRHJhZ0xlYXZlXCJcbiAgICBAbm9kZS1kcmFnLW92ZXI9XCJoYW5kbGVEcmFnT3ZlclwiXG4gICAgQG5vZGUtZHJhZy1lbmQ9XCJoYW5kbGVEcmFnRW5kXCJcbiAgICBAbm9kZS1kcm9wPVwiaGFuZGxlRHJvcFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

import type { DropType } from 'element-plus/es/components/tree/src/tree.type'

### What is Expected?

The type is correctly defined

### What is actually happening?

Type not exported correctly

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by init-qy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

close #10619

### CODE REVIEW

File: docs/examples/tree/draggable.vue [hunk 1]
```diff
@@ -18,7 +18,7 @@
 <script lang="ts" setup>
 import type Node from 'element-plus/es/components/tree/src/model/node'
 import type { DragEvents } from 'element-plus/es/components/tree/src/model/useDragNode'
-import type { DropType } from 'element-plus/es/components/tree/src/tree.type'
+import type { AllowDropType } from 'element-plus/es/components/tree/src/tree.type'
```
Comment (emojiiii) [inline docs/examples/tree/draggable.vue:21]: 应该是 `NodeDropType` 类型才对

**Review by emojiiii — CHANGES_REQUESTED** [review]

File: docs/examples/tree/draggable.vue (hunk 1 above)
Comment (init-qy) [reply docs/examples/tree/draggable.vue:21]: dropType的改动发生在 #8681
另外在文档中对于type的描述也多次出现 `node drop type (before / after / inner)`
所以这边demo中使用 `AllowDropType` 是没有问题的

Comment (emojiiii) [reply docs/examples/tree/draggable.vue]: > dropType的改动发生在 #8681 的确应该是`NodeDropType` 另外在文档中对于type的描述多次出现 `node drop type (before / after / inner)` 和`export declare type NodeDropType = 'before' | 'after' | 'inner' | 'none'` 仍有出入 是否需要修改

暂时不更改，这个组件的类型有点乱，需要统一再重新整理一遍

**Review by emojiiii — APPROVED** [review]

**Review by chenxch — APPROVED** [review]

**Review by holazz — APPROVED** [review]
