### PR TITLE
fix(input): non-emit events such as keyup not work

### LINKED ISSUE #837: input组件建议传出按键原生事件
直接在el-input上写v-on:keyup和v-on:keypress事件是不起作用的，因为vue3取消了native修饰符，源码里只emit了keydown事件，导致需要判断按键的时候使用很不方便，不知道有没有其他方法解决？

### PR DESCRIPTION
**Pull request by SimonaliaChen**
- remove `excludeListeners: true` in `useAttrs`, for there is no need with `inheritAttrs: true` of `input`, fix #837
- complete `useAttrs` test case

### CODE REVIEW

File: packages/input/src/index.vue [hunk 1]
```diff
@@ -219,7 +219,8 @@ export default defineComponent({
 
   setup(props, ctx) {
     const instance = getCurrentInstance()
-    const attrs = useAttrs({ excludeListeners: true })
+    const attrs = useAttrs()
```
Comment (JeremyWuuuuu) [inline packages/input/src/index.vue:222]: Remove console

**Review by jw-foss — APPROVED** [review]
