### PR TITLE
fix(loading): fix loading transition invalid and directive loading not show in the second time when service loading show between them

### LINKED ISSUE #1280: [Bug Report] ElLoading transition not work
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
Google Chrome 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/xyorz/pen/poEQrwJ

### Steps to reproduce
click show loading button

### What is Expected?
loading show and close with transition just like element-ui:
https://element.eleme.cn/#/zh-CN/component/loading#zheng-ye-jia-zai

### What is actually happening?
loading show and close without transition

### PR DESCRIPTION
**Pull request by Ryan2128**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

Fixed #1280 

- Fix loading transition invalid
- Fix directive loading not show in the second time when service loading show between them

### CODE REVIEW

**Comment by Ryan2128** [comment]
Not ready, found another bug.

File: packages/loading/src/directive.ts [hunk 1]
```diff
@@ -1,34 +1,37 @@
...
-      background: vm && vm[backgroundExr] || backgroundExr,
-      customClass: vm && vm[customClassExr] || customClassExr,
-      fullscreen: !!binding.modifiers.fullscreen,
-      target: !!binding.modifiers.fullscreen ? null : el,
-      body: !!binding.modifiers.body,
-      visible: !!binding.value,
-      lock: !!binding.modifiers.lock,
-    })
-    el.instance = instance
+    if(!!binding.value){
```
Comment (JeremyWuuuuu) [inline packages/loading/src/directive.ts:24]: Since it's bool type, why casting it anyway?

Comment (Ryan2128) [reply packages/loading/src/directive.ts:24]: These code was wrote by @bastarder. Maybe because the `binding.value` may be not a boolean typle value, there seems to be no way to enforce restrictions on directive to recept a boolean type value.

Comment (JeremyWuuuuu) [reply packages/loading/src/directive.ts:24]: Got it. We should constraint the type then. Let's keep it this way.

**Review by jw-foss — APPROVED** [review]
