### PR TITLE
fix(components): [message-box] the focus error when used ElMessageBox

### LINKED ISSUE #8292: [Bug Report] [Component] [message-box] MessageBox  close icon default color error when custom components
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.5`
- Browser / OS: `chrome101`
- Build Tool: `Vite`

### Related Component

- `el-message-box`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHRleHQgQGNsaWNrPVwib3BlblwiPkNsaWNrIHRvIG9wZW4gTWVzc2FnZSBCb3g8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxNZXNzYWdlLCBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5jb25zdCBvcGVuID0gKCkgPT4ge1xuICBFbE1lc3NhZ2VCb3goe1xuICAgIHRpdGxlOiAnTWVzc2FnZScsXG4gICAgbWVzc2FnZTogaCgncCcsIG51bGwsIFtcbiAgICAgIGgoJ3NwYW4nLCBudWxsLCAnTWVzc2FnZSBjYW4gYmUgJyksXG4gICAgICBoKCdpJywgeyBzdHlsZTogJ2NvbG9yOiB0ZWFsJyB9LCAnVk5vZGUnKSxcbiAgICBdKSxcbiAgICBzaG93Q2FuY2VsQnV0dG9uOiB0cnVlLFxuICAgIGNvbmZpcm1CdXR0b25UZXh0OiAnT0snLFxuICAgIGNhbmNlbEJ1dHRvblRleHQ6ICdDYW5jZWwnLFxuICAgIGJlZm9yZUNsb3NlOiAoYWN0aW9uLCBpbnN0YW5jZSwgZG9uZSkgPT4ge1xuICAgICAgaWYgKGFjdGlvbiA9PT0gJ2NvbmZpcm0nKSB7XG4gICAgICAgIGluc3RhbmNlLmNvbmZpcm1CdXR0b25Mb2FkaW5nID0gdHJ1ZVxuICAgICAgICBpbnN0YW5jZS5jb25maXJtQnV0dG9uVGV4dCA9ICdMb2FkaW5nLi4uJ1xuICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgICAgICBkb25lKClcbiAgICAgICAgICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICAgICAgICAgIGluc3RhbmNlLmNvbmZpcm1CdXR0b25Mb2FkaW5nID0gZmFsc2VcbiAgICAgICAgICB9LCAzMDApXG4gICAgICAgIH0sIDMwMDApXG4gICAgICB9IGVsc2Uge1xuICAgICAgICBkb25lKClcbiAgICAgIH1cbiAgICB9LFxuICB9KS50aGVuKChhY3Rpb24pID0+IHtcbiAgICBFbE1lc3NhZ2Uoe1xuICAgICAgdHlwZTogJ2luZm8nLFxuICAgICAgbWVzc2FnZTogYGFjdGlvbjogJHthY3Rpb259YCxcbiAgICB9KVxuICB9KVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

zh
1 .打开playground的地址
2 .点击open msgBox 按钮,默认关闭按钮的颜色异常(个性化设置模式)
en
1 . Open the official playground url
2 . open message-box , and the color of the close icon is abnormal

### What is Expected?

 the color of close icon is normal
 右上角关闭按钮颜色正常(不应该默认primary色)

### What is actually happening?

 the color of close icon is abnormal
 关闭按钮默认primary色,点击才会正常

### Additional comments

_(empty)_
image

### PR DESCRIPTION
**Pull request by LinZhanMing**
fix #8292 

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/message-box/src/index.vue [hunk 1]
```diff
@@ -335,7 +335,11 @@ export default defineComponent({
       () => visible.value,
       (val) => {
         if (val) {
-          if (props.boxType === 'alert' || props.boxType === 'confirm') {
+          if (
+            props.boxType === '' ||
```
Comment (tolking) [inline packages/components/message-box/src/index.vue:339]: boxType = '' | 'prompt' | 'alert' | 'confirm'

Maybe just exclude the 'prompt' here

**Review by tolking — APPROVED** [review]

**Comment by tolking** [comment]
LGTM, thanks for your contribution.
