### PR TITLE
fix(components): [form] `scrollToError` scroll to correct position

### LINKED ISSUE #20822: [Component] [form] scrollToError should scroll to the first error field in form order
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.14`
- Element Plus Version: `2.9.10`
- Browser / OS: `Chrome 136.0.7103.93`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIHN0eWxlPVwibWFyZ2luLXRvcDo1MHZoO21hcmdpbi1ib3R0b206IDIwMHZoO1wiXG4gICAgOm1vZGVsPVwicnVsZUZvcm1cIlxuICAgIDpydWxlcz1cInJ1bGVzXCJcbiAgICBzY3JvbGwtdG8tZXJyb3JcbiAgICA6c2Nyb2xsLWludG8tdmlldy1vcHRpb25zPVwie1xuICAgICAgYmVoYXZpb3I6ICdzbW9vdGgnXG4gICAgfVwiPlxuICAgIDxlbC1mb3JtLWl0ZW0+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwic3VibWl0Rm9ybVwiPlxuICAgICAgICBzY3JvbGxUb0Vycm9yXG4gICAgICA8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIHYtaWY9XCJmaWVsZFZpc2libGVcIiBsYWJlbD1cIm5hbWUgMVwiIHByb3A9XCJuYW1lMVwiPlxuICAgICAgPGVsLWlucHV0IC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSB2LWlmPVwiZmllbGRWaXNpYmxlXCIgbGFiZWw9XCJuYW1lIDJcIiBwcm9wPVwibmFtZTJcIj5cbiAgICAgIDxlbC1pbnB1dCAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJuYW1lIDNcIiBwcm9wPVwibmFtZTNcIj5cbiAgICAgIDxlbC1pbnB1dCAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSwgRm9ybVJ1bGVzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmaWVsZFZpc2libGUgPSByZWYoZmFsc2UpXG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBmaWVsZFZpc2libGUudmFsdWUgPSB0cnVlXG4gIG5leHRUaWNrKCgpID0+IHtcbiAgICBzdWJtaXRGb3JtKClcbiAgfSlcbn0sIDEwMDApXG5cbmNvbnN0IGZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpXG5jb25zdCBydWxlRm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTE6ICcnLFxuICBuYW1lMjogJycsXG4gIG5hbWUzOiAnJyxcbn0pXG5cbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmUoe1xuICBuYW1lMTogW1xuICAgIHsgcmVxdWlyZWQ6IHRydWUgfSxcbiAgXSxcbiAgbmFtZTI6IFtcbiAgICB7IHJlcXVpcmVkOiB0cnVlIH0sXG4gIF0sXG4gIG5hbWUzOiBbXG4gICAgeyByZXF1aXJlZDogdHJ1ZSB9LFxuICBdLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IGFzeW5jICgpID0+IHtcbiAgYXdhaXQgZm9ybVJlZi52YWx1ZS52YWxpZGF0ZSgodmFsaWQsIGZpZWxkcykgPT4geyB9KVxufVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

- Wait for 1 second
- OR click the scrollToError button

### What is Expected?

Should scroll to the first validation error field according to the form's declaration order

### What is actually happening?

Scrolls according to the FormItem's mounting order

### Additional comments

In dynamic forms, the scrolling position behaves counter-intuitively due to component mounting order affecting the error field detection sequence

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #20822

### CODE REVIEW

**Review by warmthsea — COMMENTED** [review]
Do you want to add a default value for `scrollIntoViewOptions` (`true` or `{}`)? 
If don't set a default value, it will be automatically `false`, only add `scroll-to-error` will not work.


https://github.com/element-plus/element-plus/blob/fix/form-scroll-to-correct-position/packages/components/form/src/form.ts#L107-L109

[play demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybVxuICAgIHJlZj1cImZvcm1SZWZcIlxuICAgIHN0eWxlPVwibWFyZ2luLXRvcDogNTB2aDsgbWFyZ2luLWJvdHRvbTogMjAwdmhcIlxuICAgIDptb2RlbD1cInJ1bGVGb3JtXCJcbiAgICA6cnVsZXM9XCJydWxlc1wiXG4gICAgc2Nyb2xsLXRvLWVycm9yXG4gID5cbiAgICA8ZWwtZm9ybS1pdGVtPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cInN1Ym1pdEZvcm1cIj4gc2Nyb2xsVG9FcnJvciA8L2VsLWJ1dHRvbj5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgICA8ZWwtZm9ybS1pdGVtIHYtaWY9XCJmaWVsZFZpc2libGVcIiBsYWJlbD1cIm5hbWUgMVwiIHByb3A9XCJuYW1lMVwiPlxuICAgICAgPGVsLWlucHV0IC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSB2LWlmPVwiZmllbGRWaXNpYmxlXCIgbGFiZWw9XCJuYW1lIDJcIiBwcm9wPVwibmFtZTJcIj5cbiAgICAgIDxlbC1pbnB1dCAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJuYW1lIDNcIiBwcm9wPVwibmFtZTNcIj5cbiAgICAgIDxlbC1pbnB1dCAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVhY3RpdmUsIHJlZiwgbmV4dFRpY2sgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IEZvcm1JbnN0YW5jZSwgRm9ybVJ1bGVzIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmaWVsZFZpc2libGUgPSByZWYoZmFsc2UpXG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBmaWVsZFZpc2libGUudmFsdWUgPSB0cnVlXG4gIG5leHRUaWNrKCgpID0+IHtcbiAgICBzdWJtaXRGb3JtKClcbiAgfSlcbn0sIDEwMDApXG5cbmNvbnN0IGZvcm1SZWYgPSByZWY8Rm9ybUluc3RhbmNlPigpXG5jb25zdCBydWxlRm9ybSA9IHJlYWN0aXZlKHtcbiAgbmFtZTE6ICcnLFxuICBuYW1lMjogJycsXG4gIG5hbWUzOiAnJyxcbn0pXG5cbmNvbnN0IHJ1bGVzID0gcmVhY3RpdmUoe1xuICBuYW1lMTogW3sgcmVxdWlyZWQ6IHRydWUgfV0sXG4gIG5hbWUyOiBbeyByZXF1aXJlZDogdHJ1ZSB9XSxcbiAgbmFtZTM6IFt7IHJlcXVpcmVkOiB0cnVlIH1dLFxufSlcblxuY29uc3Qgc3VibWl0Rm9ybSA9IGFzeW5jICgpID0+IHtcbiAgYXdhaXQgZm9ybVJlZi52YWx1ZS52YWxpZGF0ZSgodmFsaWQsIGZpZWxkcykgPT4ge30pXG59XG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0yMDgyNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0yMDgyNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0yMDgyNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0yMDgyNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2Rpc3QvaW5kZXguY3NzIn19)

**Comment by btea** [comment]
It seems that there is a problem with the original logic. Maybe a default value should be added to the following code as well.
https://github.com/element-plus/element-plus/blob/455b07d5e3c96021303a8d24fff44e6e4b691712/packages/components/form/src/form.vue#L157

File: packages/components/form/src/form.vue [hunk 1]
```diff
@@ -138,7 +139,12 @@ const validateField: FormContext['validateField'] = async (
     const invalidFields = e as ValidateFieldsError
 
     if (props.scrollToError) {
-      scrollToField(Object.keys(invalidFields)[0])
+      // form-item may be dynamically rendered based on the judgment conditions, and the order in invalidFields is uncertain.
+      // Therefore, the first form field with an error is determined by directly looking for the rendered element.
+      if (formRef.value) {
+        const formItem = formRef.value!.querySelector('.is-error')
```
Comment (btea) [inline packages/components/form/src/form.vue:145]: There is another problem that bothers me. Currently, the location of the form item with an error is found through the `querySelector` api. If the user happens to manually add the corresponding class to other elements, it may cause an error in finding the element(Although the possibility is relatively small.).

I can't think of a more reasonable way to avoid this situation.

File: packages/components/form/src/form.vue [hunk 2]
```diff
@@ -138,7 +139,12 @@ const validateField: FormContext['validateField'] = async (
...
+        formItem?.scrollIntoView(props.scrollIntoViewOptions)
```
Comment (warmthsea) [inline packages/components/form/src/form.vue:146]: > I can't think of a more reasonable way to avoid this situation.

so?

```suggestion
        const formItem = const formItem = formRef.value!.querySelector(
          `.${ns.b()}-item.is-error.is-required`
        )
        formItem?.scrollIntoView(props.scrollIntoViewOptions)
```

Comment (btea) [reply packages/components/form/src/form.vue:146]: Yeah, this can further reduce the chance of errors, but it can't completely avoid them. Maybe, we have to keep it like this for now.

**Review by warmthsea — APPROVED** [review]

**Comment by btea** [comment]
@xingyixiang Thanks for your review, it seems we shouldn't restrict class names too much.

**Review by warmthsea — APPROVED** [review]

**Review by kooriookami — APPROVED** [review]
