### PR TITLE
fix(components): [tree] FireFox dargging dataTransfer judge

### LINKED ISSUE #17846: [Component] 最新版本的火狐浏览器（129.0），tree组件拖拽报错
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.37`
- Element Plus Version: `2.8.0`
- Browser / OS: `FireFox 129.0 (64位)`
- Build Tool: `Vite`

### Related Component

- `el-tree`
- `el-tree-select`
- `el-tree-v2`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree.html#%E5%8F%AF%E6%8B%96%E6%8B%BD%E8%8A%82%E7%82%B9)

### Steps to reproduce

使用火狐129.0 官网示例即可复现
129.0下载地址：https://ftp.mozilla.org/pub/firefox/releases/129.0/win64/zh-CN/

### What is Expected?

不报错

### What is actually happening?

报错
TypeError: p.dataTransfer is null
    treeNodeDragEnd https://element-plus.org/assets/chunks/theme.CK6SIbTt.js:44
    handleDragEnd https://element-plus.org/assets/chunks/theme.CK6SIbTt.js:44
    wf https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    He https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    Ee https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4
    n https://element-plus.org/assets/chunks/framework.DcRevfCx.js:4

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by warmthsea**
close: https://github.com/element-plus/element-plus/issues/17846

FireFox: 129

screenshots
[Playground Demo Before](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmFsbG93LWRyb3A9XCJhbGxvd0Ryb3BcIlxuICAgIDphbGxvdy1kcmFnPVwiYWxsb3dEcmFnXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIGRyYWdnYWJsZVxuICAgIGRlZmF1bHQtZXhwYW5kLWFsbFxuICAgIG5vZGUta2V5PVwiaWRcIlxuICAgIEBub2RlLWRyYWctc3RhcnQ9XCJoYW5kbGVEcmFnU3RhcnRcIlxuICAgIEBub2RlLWRyYWctZW50ZXI9XCJoYW5kbGVEcmFnRW50ZXJcIlxuICAgIEBub2RlLWRyYWctbGVhdmU9XCJoYW5kbGVEcmFnTGVhdmVcIlxuICAgIEBub2RlLWRyYWctb3Zlcj1cImhhbmRsZURyYWdPdmVyXCJcbiAgICBAbm9kZS1kcmFnLWVuZD1cImhhbmRsZURyYWdFbmRcIlxuICAgIEBub2RlLWRyb3A9XCJoYW5kbGVEcm9wXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSBOb2RlIGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL25vZGUnXG5pbXBvcnQgdHlwZSB7IERyYWdFdmVudHMgfSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC91c2VEcmFnTm9kZSdcbmltcG9ydCB0eXBlIHtcbiAgQWxsb3dEcm9wVHlwZSxcbiAgTm9kZURyb3BUeXBlLFxufSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy90cmVlLnR5cGUnXG5cbmNvbnN0IGhhbmRsZURyYWdTdGFydCA9IChub2RlOiBOb2RlLCBldjogRHJhZ0V2ZW50cykgPT4ge1xuICBjb25zb2xlLmxvZygnZHJhZyBzdGFydCcsIG5vZGUpXG59XG5jb25zdCBoYW5kbGVEcmFnRW50ZXIgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBlbnRlcjonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdMZWF2ZSA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGxlYXZlOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ092ZXIgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlLCBkcm9wTm9kZTogTm9kZSwgZXY6IERyYWdFdmVudHMpID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBvdmVyOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ0VuZCA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZHJvcFR5cGU6IE5vZGVEcm9wVHlwZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVuZDonLCBkcm9wTm9kZSAmJiBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG59XG5jb25zdCBoYW5kbGVEcm9wID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBkcm9wVHlwZTogTm9kZURyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyb3A6JywgZHJvcE5vZGUubGFiZWwsIGRyb3BUeXBlKVxufVxuY29uc3QgYWxsb3dEcm9wID0gKGRyYWdnaW5nTm9kZTogTm9kZSwgZHJvcE5vZGU6IE5vZGUsIHR5cGU6IEFsbG93RHJvcFR5cGUpID0+IHtcbiAgaWYgKGRyb3BOb2RlLmRhdGEubGFiZWwgPT09ICdMZXZlbCB0d28gMy0xJykge1xuICAgIHJldHVybiB0eXBlICE9PSAnaW5uZXInXG4gIH0gZWxzZSB7XG4gICAgcmV0dXJuIHRydWVcbiAgfVxufVxuY29uc3QgYWxsb3dEcmFnID0gKGRyYWdnaW5nTm9kZTogTm9kZSkgPT4ge1xuICByZXR1cm4gIWRyYWdnaW5nTm9kZS5kYXRhLmxhYmVsLmluY2x1ZGVzKCdMZXZlbCB0aHJlZSAzLTEtMScpXG59XG5cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAxLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAyJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMi0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAzJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAzLTInLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0yLTEnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)
[Playground Demo After](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIHN0eWxlPVwibWF4LXdpZHRoOiA2MDBweFwiXG4gICAgOmFsbG93LWRyb3A9XCJhbGxvd0Ryb3BcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgZHJhZ2dhYmxlXG4gICAgZGVmYXVsdC1leHBhbmQtYWxsXG4gICAgbm9kZS1rZXk9XCJpZFwiXG4gICAgQG5vZGUtZHJhZy1zdGFydD1cImhhbmRsZURyYWdTdGFydFwiXG4gICAgQG5vZGUtZHJhZy1lbnRlcj1cImhhbmRsZURyYWdFbnRlclwiXG4gICAgQG5vZGUtZHJhZy1sZWF2ZT1cImhhbmRsZURyYWdMZWF2ZVwiXG4gICAgQG5vZGUtZHJhZy1vdmVyPVwiaGFuZGxlRHJhZ092ZXJcIlxuICAgIEBub2RlLWRyYWctZW5kPVwiaGFuZGxlRHJhZ0VuZFwiXG4gICAgQG5vZGUtZHJvcD1cImhhbmRsZURyb3BcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcbmltcG9ydCB0eXBlIHsgRHJhZ0V2ZW50cyB9IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL21vZGVsL3VzZURyYWdOb2RlJ1xuaW1wb3J0IHR5cGUge1xuICBBbGxvd0Ryb3BUeXBlLFxuICBOb2RlRHJvcFR5cGUsXG59IGZyb20gJ2VsZW1lbnQtcGx1cy9lcy9jb21wb25lbnRzL3RyZWUvc3JjL3RyZWUudHlwZSdcblxuY29uc3QgaGFuZGxlRHJhZ1N0YXJ0ID0gKG5vZGU6IE5vZGUsIGV2OiBEcmFnRXZlbnRzKSA9PiB7XG4gIC8vIGNvbnNvbGUubG9nKCdkcmFnIHN0YXJ0Jywgbm9kZSlcbn1cbmNvbnN0IGhhbmRsZURyYWdFbnRlciA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICAvLyBjb25zb2xlLmxvZygndHJlZSBkcmFnIGVudGVyOicsIGRyb3BOb2RlLmxhYmVsKVxufVxuY29uc3QgaGFuZGxlRHJhZ0xlYXZlID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIC8vIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgbGVhdmU6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnT3ZlciA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCBldjogRHJhZ0V2ZW50cykgPT4ge1xuICAvLyBjb25zb2xlLmxvZygndHJlZSBkcmFnIG92ZXI6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnRW5kID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBkcm9wVHlwZTogTm9kZURyb3BUeXBlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIC8vIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgZW5kOicsIGRyb3BOb2RlICYmIGRyb3BOb2RlLmxhYmVsLCBkcm9wVHlwZSlcbn1cbmNvbnN0IGhhbmRsZURyb3AgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGRyb3BUeXBlOiBOb2RlRHJvcFR5cGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgLy8gY29uc29sZS5sb2coJ3RyZWUgZHJvcDonLCBkcm9wTm9kZS5sYWJlbCwgZHJvcFR5cGUpXG59XG5jb25zdCBhbGxvd0Ryb3AgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlLCBkcm9wTm9kZTogTm9kZSwgdHlwZTogQWxsb3dEcm9wVHlwZSkgPT4ge1xuICBpZiAoZHJvcE5vZGUuZGF0YS5sYWJlbCA9PT0gJ0xldmVsIHR3byAzLTEnKSB7XG4gICAgcmV0dXJuIHR5cGUgIT09ICdpbm5lcidcbiAgfSBlbHNlIHtcbiAgICByZXR1cm4gdHJ1ZVxuICB9XG59XG5jb25zdCBhbGxvd0RyYWcgPSAoZHJhZ2dpbmdOb2RlOiBOb2RlKSA9PiB7XG4gIHJldHVybiAhZHJhZ2dpbmdOb2RlLmRhdGEubGFiZWwuaW5jbHVkZXMoJ0xldmVsIHRocmVlIDMtMS0xJylcbn1cblxuY29uc3QgZGF0YSA9IFtcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE3ODQ5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xNzg0OS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTc4NDktZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE3ODQ5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by btea — APPROVED** [review]
Thanks!

File: packages/components/tree/src/model/useDragNode.ts [hunk 1]
```diff
@@ -164,7 +164,10 @@ export function useDragNodeHandler({ props, ctx, el$, dropIndicator$, store }) {
   const treeNodeDragEnd = (event: DragEvent) => {
     const { draggingNode, dropType, dropNode } = dragState.value
     event.preventDefault()
-    event.dataTransfer.dropEffect = 'move'
+
```
Comment (btea) [inline packages/components/tree/src/model/useDragNode.ts:167]: Maybe we can add a link to the bug in the comments.
https://bugzilla.mozilla.org/show_bug.cgi?id=1911486

**Review by tolking — APPROVED** [review]
