### PR TITLE
fix(components): [cascader] correctly handle focus and blur events

### LINKED ISSUE #20251: [Component] [cascader] focus、blur事件触发时机混乱
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.7`
- Browser / OS: `Edge 134.0.3124.83`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+Q2hpbGQgb3B0aW9ucyBleHBhbmQgd2hlbiBob3ZlcmVkPC9wPlxuICAgIDxlbC1jYXNjYWRlclxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCJcbiAgICAgIEBmb2N1cz1cImhhbmRsZUZvY3VzXCJcbiAgICAgIEBibHVyPVwiaGFuZGxlQmx1clwiXG4gICAgLz5cbiAgICA8ZGl2IGNsYXNzPVwiY29uc29sZVwiPlxuICAgICAgPGRpdiB2LWZvcj1cIihsb2csIGluZGV4KSBpbiBsb2dzXCIgOmtleT1cImluZGV4XCI+e3sgbG9nIH19PC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBsb2dzID0gcmVmPHN0cmluZ1tdPihbXSlcblxuY29uc3QgcHJvcHMgPSB7XG4gIGV4cGFuZFRyaWdnZXI6ICdob3ZlcicgYXMgY29uc3QsXG59XG5cbmZ1bmN0aW9uIGdldEN1cnJlbnRUaW1lKCkge1xuICBjb25zdCBub3cgPSBuZXcgRGF0ZSgpXG4gIGNvbnN0IHBhZCA9IChuOiBudW1iZXIpID0+IG4udG9TdHJpbmcoKS5wYWRTdGFydCgyLCAnMCcpXG4gIGNvbnN0IHllYXIgPSBub3cuZ2V0RnVsbFllYXIoKVxuICBjb25zdCBtb250aCA9IHBhZChub3cuZ2V0TW9udGgoKSArIDEpXG4gIGNvbnN0IGRheSA9IHBhZChub3cuZ2V0RGF0ZSgpKVxuICBjb25zdCBob3VycyA9IHBhZChub3cuZ2V0SG91cnMoKSlcbiAgY29uc3QgbWludXRlcyA9IHBhZChub3cuZ2V0TWludXRlcygpKVxuICBjb25zdCBzZWNvbmRzID0gcGFkKG5vdy5nZXRTZWNvbmRzKCkpXG4gIHJldHVybiBgJHt5ZWFyfS0ke21vbnRofS0ke2RheX0gJHtob3Vyc306JHttaW51dGVzfToke3NlY29uZHN9YFxufVxuXG5mdW5jdGlvbiBhZGRMb2codHlwZTogc3RyaW5nLCBtZXNzYWdlOiBzdHJpbmcpIHtcbiAgY29uc3QgdGltZSA9IGdldEN1cnJlbnRUaW1lKClcbiAgY29uc3QgbG9nTWVzc2FnZSA9IGAke3RpbWV9IC0gWyR7dHlwZX1dICR7bWVzc2FnZX1gXG4gIGxvZ3MudmFsdWUucHVzaChsb2dNZXNzYWdlKVxuICBzZXRUaW1lb3V0KCgpID0+IHtcbiAgICBjb25zdCBjb25zb2xlRWwgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcuY29uc29sZScpXG4gICAgaWYgKGNvbnNvbGVFbCkge1xuICAgICAgY29uc29sZUVsLnNjcm9sbFRvcCA9IGNvbnNvbGVFbC5zY3JvbGxIZWlnaHRcbiAgICB9XG4gIH0sIDApXG59XG5cbmNvbnN0IGhhbmRsZUNoYW5nZSA9ICh2YWx1ZSkgPT4ge1xuICBjb25zdCBtZXNzYWdlID0gYENoYW5nZTogJHtKU09OLnN0cmluZ2lmeSh2YWx1ZSl9YFxuICBjb25zb2xlLmxvZyhtZXNzYWdlKVxuICBhZGRMb2coJ2NoYW5nZScsIG1lc3NhZ2UpXG59XG5cbmNvbnN0IGhhbmRsZUZvY3VzID0gKGUpID0+IHtcbiAgY29uc3QgbWVzc2FnZSA9ICdGb2N1cyB0cmlnZ2VyZWQnXG4gIGNvbnNvbGUubG9nKG1lc3NhZ2UsIGUpXG4gIGFkZExvZygnZm9jdXMnLCBtZXNzYWdlKVxufVxuXG5jb25zdCBoYW5kbGVCbHVyID0gKGUpID0+IHtcbiAgY29uc3QgbWVzc2FnZSA9ICdCbHVyIHRyaWdnZXJlZCdcbiAgY29uc29sZS5sb2cobWVzc2FnZSwgZSlcbiAgYWRkTG9nKCdibHVyJywgbWVzc2FnZSlcbn1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnZ3VpZGUnLFxuICAgIGxhYmVsOiAnR3VpZGUnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZGlzY2lwbGluZXMnLFxuICAgICAgICBsYWJlbDogJ0Rpc2NpcGxpbmVzJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAnY29uc2lzdGVuY3knLCBsYWJlbDogJ0NvbnNpc3RlbmN5JyB9LFxuICAgICAgICAgIHsgdmFsdWU6ICdmZWVkYmFjaycsIGxhYmVsOiAnRmVlZGJhY2snIH0sXG4gICAgICAgICAgeyB2YWx1ZTogJ2VmZmljaWVuY3knLCBsYWJlbDogJ0VmZmljaWVuY3knIH0sXG4gICAgICAgICAgeyB2YWx1ZTogJ2NvbnRyb2xsYWJpbGl0eScsIGxhYmVsOiAnQ29udHJvbGxhYmlsaXR5JyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAnc2lkZSBuYXYnLCBsYWJlbDogJ1NpZGUgTmF2aWdhdGlvbicgfSxcbiAgICAgICAgICB7IHZhbHVlOiAndG9wIG5hdicsIGxhYmVsOiAnVG9wIE5hdmlnYXRpb24nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ2NvbXBvbmVudCcsXG4gICAgbGFiZWw6ICdDb21wb25lbnQnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnYmFzaWMnLFxuICAgICAgICBsYWJlbDogJ0Jhc2ljJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAnbGF5b3V0JywgbGFiZWw6ICdMYXlvdXQnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogJ2NvbG9yJywgbGFiZWw6ICdDb2xvcicgfSxcbiAgICAgICAgICB7IHZhbHVlOiAndHlwb2dyYXBoeScsIGxhYmVsOiAnVHlwb2dyYXBoeScgfSxcbiAgICAgICAgICB7IHZhbHVlOiAnaWNvbicsIGxhYmVsOiAnSWNvbicgfSxcbiAgICAgICAgICB7IHZhbHVlOiAnYnV0dG9uJywgbGFiZWw6ICdCdXR0b24nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ3Jlc291cmNlJyxcbiAgICBsYWJlbDogJ1Jlc291cmNlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAgeyB2YWx1ZTogJ2F4dXJlJywgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzJyB9LFxuICAgICAgeyB2YWx1ZTogJ3NrZXRjaCcsIGxhYmVsOiAnU2tldGNoIFRlbXBsYXRlcycgfSxcbiAgICAgIHsgdmFsdWU6ICdkb2NzJywgbGFiZWw6ICdEZXNpZ24gRG9jdW1lbnRhdGlvbicgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uY29uc29sZSB7XG4gIGhlaWdodDogMjAwcHg7IFxuICBvdmVyZmxvdy15OiBhdXRvO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMDAwO1xuICBjb2xvcjogIzBmMDtcbiAgcGFkZGluZzogMTBweDtcbiAgbWFyZ2luLXRvcDogMzIwcHg7XG4gIGJvcmRlci1yYWRpdXM6IDZweDtcbiAgZm9udC1mYW1pbHk6IG1vbm9zcGFjZTtcbiAgYm9yZGVyOiAxcHggc29saWQgIzMzMztcbn1cbjwvc3R5bGU+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1、点击组件，触发 focus事件
2、随机选择一项，触发了 blur事件
3、选择完毕后，触发了focus事件

### What is Expected?

1、组件在没有离开时不应该调用blur事件。
2、组件在选择完毕后不应该重复调用focus事件

### What is actually happening?

focus、blur事件在整个过程中被重复调用

### Additional comments

_(empty)_

https://github.com/user-attachments/assets/94c5fa35-bb0f-4c25-9b9b-5375353a7b49

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #21509
fix #20251

### CODE REVIEW

File: packages/components/cascader/src/cascader.vue [hunk 1]
```diff
@@ -391,14 +390,38 @@ const cascaderIconKls = computed(() => {
...
+      if (props.validateEvent) {
+        formItem?.validate?.('blur').catch((err) => debugWarn(err))
+      }
+    },
+  }
+)
+
+const handleClickOutside = (event: Event) => {
+  if (isFocused.value) {
+    const _event = new FocusEvent('focus', event)
```
Comment (tolking) [inline packages/components/cascader/src/cascader.vue]:
```suggestion
    const _event = new FocusEvent('blur', event)
```

Comment (rzzf) [reply packages/components/cascader/src/cascader.vue]: thx.

**Review by tolking — APPROVED** [review]
LGTM

**Comment by rzzf** [comment]
@btea @Dsaquel Hi, this PR has been open for a while. When you have time, could you please take a look? Thanks a lot, and sorry if I’m disturbing you.

**Comment by Dsaquel** [comment]
> Hi, this PR has been open for a while. When you have time, could you please take a look? Thanks a lot, and sorry if I’m disturbing you.

Yes, i notice the PR yesterday but didn't review it since i have done more or less similar change in this pr https://github.com/element-plus/element-plus/pull/21732, therefore there are code conflict now that need to be resolved.

**Comment by rzzf** [comment]
@Dsaquel Thank you for your work. 

I think my changes did not break the fix for #21732. Could you please review it again? Thanks!

**Review by Dsaquel — APPROVED** [review]
It works well on local but there are some trouble in playground.

I assume it is not related on your changes, thanks!
