### PR TITLE
fix(components): [focus-trap] respect focusout null relatedTarget

### LINKED ISSUE #7871: [Bug Report] [Component] [drawer, form-item] Drawer 抽屉导致表单控件被聚焦重选
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.2`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-drawer`
- `el-form-item`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

利用Drawer打开的组件包含表单控件，表单控件输入完毕，点击空白区域，依然触发上一步的控件被聚焦选定

### What is Expected?

点击空白区域，表单控件自动失去焦点

### What is actually happening?

点击空白区域，依然触发上一步的控件被聚焦选定

### Additional comments
问题复现地址：
https://element-plus.org/zh-CN/component/drawer.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%86%85%E5%AE%B9

### PR DESCRIPTION
**Pull request by Giwayume**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/focus-trap/src/focus-trap.vue [hunk 1]
```diff
@@ -168,11 +168,9 @@ export default defineComponent({
...
 
       if (props.trapped) {
-        if (
-          !trapContainer.contains(
-            (e as FocusEvent).relatedTarget as HTMLElement | null
-          )
-        ) {
+        const relatedTarget = (e as FocusEvent)
+          .relatedTarget as HTMLElement | null
+        if (trapContainer != null && !trapContainer.contains(relatedTarget)) {
```
Comment (JeremyWuuuuu) [inline packages/components/focus-trap/src/focus-trap.vue:173]:
```suggestion
import { isNil } from 'lodash-unified'
        if (!isNil(trapContainer) && !trapContainer.contains(relatedTarget)) {
```

**Review by jw-foss — APPROVED** [review]

File: packages/components/focus-trap/src/focus-trap.vue (hunk 1 above)
Comment (JeremyWuuuuu) [reply packages/components/focus-trap/src/focus-trap.vue:173]: Since `isNil` cannot tell typescript about whether this `trapContainer` is null or not, we will just skip it.

**Comment by Giwayume** [comment]
#7871
