### PR TITLE
fix(components): [carousel] improper active item

### LINKED ISSUE #5533: [Bug Report] 轮播图组件在设置了interval参数之后，异步获取数据用于渲染轮播图 ，组件会延迟interval相同的时间后才出现
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10 / chrome 版本 97.0.4692.71（正式版本） （64 位）

### Vue version
3.2.25

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-8j74f?file=/src/App.vue

### Steps to reproduce
在onMounted中请求数据用于渲染轮播组件，组件会延迟与 interval 参数的时间之后才出现

### What is Expected?
组件立即出现

### What is actually happening?
轮播图组件在设置了interval参数之后，异步获取数据用于渲染轮播图 ，组件会延迟interval相同的时间后才出现

### LINKED ISSUE #7294: [Bug Report] [Component] [carousel, carousel-item] carousel走马灯组件，在Carousel-Item 的数据源改变后，展示的第一张幻灯片不是数据源的第0项
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `chrome 98.0.4758.82`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImNoYW5nZVwiIHR5cGU9XCJwcmltYXJ5XCI+5pS55Y+YaXRlbXM8L2VsLWJ1dHRvbj5cbiAgPGVsLWNhcm91c2VsIGluZGljYXRvci1wb3NpdGlvbj1cIm91dHNpZGVcIiA6YXV0b3BsYXk9XCJmYWxzZVwiPlxuICAgIDxlbC1jYXJvdXNlbC1pdGVtIHYtZm9yPVwiaXRlbSBpbiBpdGVtc1wiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDM+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IGl0ZW1zID0gcmVmKFsxLCAyLCAzLCA0XSk7XG4gIFxuZnVuY3Rpb24gY2hhbmdlKCkge1xuICBpZiAoaXRlbXMudmFsdWVbMF0gPT09IDEpIHtcbiAgICBpdGVtcy52YWx1ZSA9IFs2LCA3LCA4LCA5XTtcbiAgfSBlbHNlIHtcbiAgICBpdGVtcy52YWx1ZSA9IFsxLCAyLCAzLCA0XTtcbiAgfVxufVxuICBcbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmVsLWNhcm91c2VsX19pdGVtIGgzIHtcbiAgY29sb3I6ICM0NzU2Njk7XG4gIGZvbnQtc2l6ZTogMThweDtcbiAgb3BhY2l0eTogMC43NTtcbiAgbGluZS1oZWlnaHQ6IDMwMHB4O1xuICBtYXJnaW46IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbn1cblxuLmVsLWNhcm91c2VsX19pdGVtOm50aC1jaGlsZCgybikge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjOTlhOWJmO1xufVxuXG4uZWwtY2Fyb3VzZWxfX2l0ZW06bnRoLWNoaWxkKDJuICsgMSkge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZDNkY2U2O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. 点出改变items的按钮，items的数据变更

### What is Expected?

第一次点击改变items按钮后，幻灯片的第一项是6，显示的也是第一项，幻灯片顺序和items的索引顺序一致。items为[6, 7, 8, 9],幻灯片也是6， 7， 8， 9

### What is actually happening?

第一次点击改变items按钮后，幻灯片的第一项是9，显示的是第二项8，幻灯片的顺序和items的索引顺序相反。items为[6, 7,  8, 9]，幻灯片是9， 8， 7， 6

### Additional comments

_(empty)_

图片
图片

### LINKED ISSUE #8891: [Component] [carousel, carousel-item] ElCarousel组件无法正确显示第一张
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Microsoft edge 103.0.1264.62 (正式版本) (64 位)`
- Build Tool: `Webpack`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[CodePen](https://codepen.io/jikunguo/pen/QWmpgXq)
[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDMgdGV4dD1cIjJ4bFwiIGp1c3RpZnk9XCJjZW50ZXJcIj57eyBpdGVtIH19PC9oMz5cbiAgICA8L2VsLWNhcm91c2VsLWl0ZW0+XG4gIDwvZWwtY2Fyb3VzZWw+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGxpc3QgPSByZWYoW10pXG4gIG9uTW91bnRlZCgoKT0+e1xuICAgIC8vIGxpc3QudmFsdWUgPSBbMSwyLDMsNF07XG4gICAgc2V0VGltZW91dCgoKT0+e1xuICAgICAgbGlzdC52YWx1ZSA9IFsyLDMsNCw1XVxuICAgIH0sNTAwKVxuICB9KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

ElCarouselItem使用异步获取的数据渲染能复现

### What is Expected?

可以正常显示第一项ElCarouselItem

### What is actually happening?

所有ElCarouselItem都处于隐藏状态

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by makedopamine**
closed #8891
closed #7294
closed #5533
closed #6548

[Before](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgc3R5bGU9XCJcbiAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG4gICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgcGFkZGluZzogMjBweDtcbiAgICBcIlxuICA+XG4gICAgPGRpdj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVtb3ZlRmlyc3RcIj5yZW1vdmVGaXJzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZW1vdmVMYXN0XCI+cmVtb3ZlTGFzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJhZGRUb0ZpcnN0XCI+YWRkVG9GaXJzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJhZGRUb0xhc3RcIj5hZGRUb0xhc3Q8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVwbGFjZUFsbFwiPnJlcGxhY2VBbGw8L2VsLWJ1dHRvbj5cbiAgICA8L2Rpdj5cblxuICAgIDxkaXY+XG4gICAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cImF1dG9wbGF5XCI+YXV0b3BsYXk8L2VsLWNoZWNrYm94PlxuICAgICAgPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJsb29wXCI+bG9vcDwvZWwtY2hlY2tib3g+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuXG4gIDxlbC1jYXJvdXNlbFxuICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgOmluaXRpbmFsLWluZGV4PVwiaW5pdGluYWxJbmRleFwiXG4gICAgOmF1dG9wbGF5PVwiYXV0b3BsYXlcIlxuICAgIDpsb29wPVwibG9vcFwiXG4gID5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCIgOmxhYmVsPVwiaXRlbVwiPlxuICAgICAgPGgzIHRleHQ9XCIyeGxcIiBqdXN0aWZ5PVwiY2VudGVyXCI+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgbGlzdCA9IHJlZjxudW1iZXJbXT4oW10pXG5jb25zdCBpbml0aW5hbEluZGV4ID0gcmVmKDEpXG5jb25zdCBhdXRvcGxheSA9IHJlZihmYWxzZSlcbmNvbnN0IGxvb3AgPSByZWYodHJ1ZSlcblxuc2V0VGltZW91dCgoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbMSwgMiwgMywgNF1cbn0sIDUwMClcblxuZnVuY3Rpb24gcmVtb3ZlRmlyc3QoKSB7XG4gIGxpc3QudmFsdWUuc2hpZnQoKVxufVxuZnVuY3Rpb24gcmVtb3ZlTGFzdCgpIHtcbiAgbGlzdC52YWx1ZS5wb3AoKVxufVxuZnVuY3Rpb24gYWRkVG9GaXJzdCgpIHtcbiAgbGlzdC52YWx1ZS51bnNoaWZ0KGxpc3QudmFsdWVbMF0gLSAxKVxufVxuZnVuY3Rpb24gYWRkVG9MYXN0KCkge1xuICBsaXN0LnZhbHVlLnB1c2gobGlzdC52YWx1ZVtsaXN0LnZhbHVlLmxlbmd0aCAtIDFdICsgMSlcbn1cbmZ1bmN0aW9uIHJlcGxhY2VBbGwoKSB7XG4gIGxpc3QudmFsdWUgPSBsaXN0LnZhbHVlLmluY2x1ZGVzKDEpID8gWzEwLCAyMCwgMzAsIDQwXSA6IFsxLCAyLCAzLCA0XVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtY2Fyb3VzZWxfX2l0ZW0ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbn1cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4pIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzk5YTliZjtcbn1cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4gKyAxKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNkM2RjZTY7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

[After](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgc3R5bGU9XCJcbiAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47XG4gICAgICBhbGlnbi1pdGVtczogY2VudGVyO1xuICAgICAgcGFkZGluZzogMjBweDtcbiAgICBcIlxuICA+XG4gICAgPGRpdj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVtb3ZlRmlyc3RcIj5yZW1vdmVGaXJzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJyZW1vdmVMYXN0XCI+cmVtb3ZlTGFzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJhZGRUb0ZpcnN0XCI+YWRkVG9GaXJzdDwvZWwtYnV0dG9uPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJhZGRUb0xhc3RcIj5hZGRUb0xhc3Q8L2VsLWJ1dHRvbj5cbiAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwicmVwbGFjZUFsbFwiPnJlcGxhY2VBbGw8L2VsLWJ1dHRvbj5cbiAgICA8L2Rpdj5cblxuICAgIDxkaXY+XG4gICAgICA8ZWwtY2hlY2tib3ggdi1tb2RlbD1cImF1dG9wbGF5XCI+YXV0b3BsYXk8L2VsLWNoZWNrYm94PlxuICAgICAgPGVsLWNoZWNrYm94IHYtbW9kZWw9XCJsb29wXCI+bG9vcDwvZWwtY2hlY2tib3g+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuXG4gIDxlbC1jYXJvdXNlbFxuICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgOmluaXRpbmFsLWluZGV4PVwiaW5pdGluYWxJbmRleFwiXG4gICAgOmF1dG9wbGF5PVwiYXV0b3BsYXlcIlxuICAgIDpsb29wPVwibG9vcFwiXG4gID5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCIgOmxhYmVsPVwiaXRlbVwiPlxuICAgICAgPGgzIHRleHQ9XCIyeGxcIiBqdXN0aWZ5PVwiY2VudGVyXCI+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgbGlzdCA9IHJlZjxudW1iZXJbXT4oW10pXG5jb25zdCBpbml0aW5hbEluZGV4ID0gcmVmKDEpXG5jb25zdCBhdXRvcGxheSA9IHJlZihmYWxzZSlcbmNvbnN0IGxvb3AgPSByZWYodHJ1ZSlcblxuc2V0VGltZW91dCgoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbMSwgMiwgMywgNF1cbn0sIDUwMClcblxuZnVuY3Rpb24gcmVtb3ZlRmlyc3QoKSB7XG4gIGxpc3QudmFsdWUuc2hpZnQoKVxufVxuZnVuY3Rpb24gcmVtb3ZlTGFzdCgpIHtcbiAgbGlzdC52YWx1ZS5wb3AoKVxufVxuZnVuY3Rpb24gYWRkVG9GaXJzdCgpIHtcbiAgbGlzdC52YWx1ZS51bnNoaWZ0KGxpc3QudmFsdWVbMF0gLSAxKVxufVxuZnVuY3Rpb24gYWRkVG9MYXN0KCkge1xuICBsaXN0LnZhbHVlLnB1c2gobGlzdC52YWx1ZVtsaXN0LnZhbHVlLmxlbmd0aCAtIDFdICsgMSlcbn1cbmZ1bmN0aW9uIHJlcGxhY2VBbGwoKSB7XG4gIGxpc3QudmFsdWUgPSBsaXN0LnZhbHVlLmluY2x1ZGVzKDEpID8gWzEwLCAyMCwgMzAsIDQwXSA6IFsxLCAyLCAzLCA0XVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtY2Fyb3VzZWxfX2l0ZW0ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcbn1cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4pIHtcbiAgYmFja2dyb3VuZC1jb2xvcjogIzk5YTliZjtcbn1cbi5lbC1jYXJvdXNlbF9faXRlbTpudGgtY2hpbGQoMm4gKyAxKSB7XG4gIGJhY2tncm91bmQtY29sb3I6ICNkM2RjZTY7XG59XG48L3N0eWxlPlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by holazz** [comment]
Hi, I think this isn't how we solve this issue. We should probably use `setActiveItem` instead of setting the value of `activeIndex` directly. FYI,

```ts
watch(
  () => items.value.length,
  (len) => {
    if (len > 0) setActiveItem(props.initialIndex)
  }
)
```

Then we don't need to change anywhere else. WDYT?

**Comment by makedopamine** [comment]
Yep, I should use `setActiveItem`.  IMHO, we need to reset the active item only if `activeIndex`  isn't in the range of  `[0, items.length - 1]`. So that we can keep `activeIndex` value in some cases, such as push.
```
watch(
  () => items.value.length,
  (len) => {
    if (activeIndex.value < 0 || activeIndex.value > len - 1) setActiveItem(props.initialIndex)
  }
)
```
In addition, sliding to the next item after removing the active item causes a weird result.

QQ图片20220720193011

Here is the reproduction:  [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlbW92ZUFjdGl2ZVwiPnJlbW92ZSBhY3RpdmUgaXRlbTwvZWwtYnV0dG9uPlxuICA8ZWwtY2Fyb3VzZWwgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCIgOmxhYmVsPVwiaXRlbVwiPlxuICAgICAgPGgzIHRleHQ9XCIyeGxcIiBqdXN0aWZ5PVwiY2VudGVyXCI+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiBpbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbiBjb25zdCBsaXN0ID0gcmVmKFtdKVxuIGZ1bmN0aW9uIHJlbW92ZUFjdGl2ZSgpIHtcbiAgIGxpc3QudmFsdWUuc2hpZnQoKVxuIH1cbiBvbk1vdW50ZWQoKCk9PntcbiAgICBsaXN0LnZhbHVlID0gWzEsIDIsIDMsIDRdO1xuICB9KVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

Here is the related code: 
https://github.com/element-plus/element-plus/blob/0efdebceefa50f0b1faccb4927f0babec28a12eb/packages/components/carousel/src/carousel.vue#L209

**Comment by holazz** [comment]
> Yep, I should use `setActiveItem`. IMHO, we need to reset the active item only if `activeIndex` isn't in the range of `[0, items.length - 1]`. So that we can keep `activeIndex` value in some cases, such as push.

Sorry, I didn't take this situation into consideration. I think this is basically due to the issue you mentioned below:

> In addition, sliding to the next item after removing the active item causes a weird result.
> 
> QQ图片20220720193011

So let's solve this issue first, I think to change the condition here like this:

https://github.com/element-plus/element-plus/blob/0efdebceefa50f0b1faccb4927f0babec28a12eb/packages/components/carousel/src/carousel.vue#L209

```diff
- if (activeIndex.value === index) next() 
+ if (activeIndex.value === index) setActiveItem(activeIndex.value)
+ else if (activeIndex.value > index) prev()
```

Then we just need to watch the old length of `items` (because the initial value of `items` is always an empty array): 

```ts
watch(
  () => items.value.length,
  (_, len) => {
    if (len === 0) setActiveItem(props.initialIndex)
  }
)
```

Finally, remove these lines:

```diff
  onMounted(async () => {
-   await nextTick()

    resizeObserver.value = useResizeObserver(root.value, () => {
      resetItemPosition()
    })
-   if (props.initialIndex < items.value.length && props.initialIndex >= 0) {
-     activeIndex.value = props.initialIndex
-   }
    startTimer()
  })
```
I would like your opinion.😊

**Comment by makedopamine** [comment]
It looks awesome now :). I have updated the commit.

**Comment by btea** [comment]
After I click the button to modify items, the active status seems to be lost [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDMgdGV4dD1cIjJ4bFwiIGp1c3RpZnk9XCJjZW50ZXJcIj57eyBpdGVtIH19PC9oMz5cbiAgICA8L2VsLWNhcm91c2VsLWl0ZW0+XG4gIDwvZWwtY2Fyb3VzZWw+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlXCI+Y2hhbmdlPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGxpc3QgPSByZWYoW10pXG5jb25zdCBjaGFuZ2UgPSAoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbMTAsIDIwLCAzMCwgNDBdXG59XG4gIG9uTW91bnRlZCgoKT0+e1xuICAgIC8vIGxpc3QudmFsdWUgPSBbMSwyLDMsNF07XG4gICAgc2V0VGltZW91dCgoKT0+e1xuICAgICAgbGlzdC52YWx1ZSA9IFsyLDMsNCw1XVxuICAgIH0sNTAwKVxuICB9KVxuPC9zY3JpcHQ+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by holazz** [comment]
> After I click the button to modify items, the active status seems to be lost [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDMgdGV4dD1cIjJ4bFwiIGp1c3RpZnk9XCJjZW50ZXJcIj57eyBpdGVtIH19PC9oMz5cbiAgICA8L2VsLWNhcm91c2VsLWl0ZW0+XG4gIDwvZWwtY2Fyb3VzZWw+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlXCI+Y2hhbmdlPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGxpc3QgPSByZWYoW10pXG5jb25zdCBjaGFuZ2UgPSAoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbMTAsIDIwLCAzMCwgNDBdXG59XG4gIG9uTW91bnRlZCgoKT0+e1xuICAgIC8vIGxpc3QudmFsdWUgPSBbMSwyLDMsNF07XG4gICAgc2V0VGltZW91dCgoKT0+e1xuICAgICAgbGlzdC52YWx1ZSA9IFsyLDMsNCw1XVxuICAgIH0sNTAwKVxuICB9KVxuPC9zY3JpcHQ+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

Indeed, maybe watch the length of `items` is not a reasonable approach. I think we should just need to watch the `uid` of `items`, and upadte `activeIndex` when `uid` changes.

```ts
watch(
  () => items.value.map((item) => item.uid),
  (ids) => {
    if (ids.length > 0) setActiveItem(props.initialIndex)
  }
)
```

This way we don't need to handle the `activeIndex` in the `removeItem` function.

```diff
  function removeItem(uid?: number) {
    const index = items.value.findIndex((item) => item.uid === uid)
    if (index !== -1) {
      items.value.splice(index, 1)
-     if (activeIndex.value === index) next()
    }
  }
```
WDYT?

**Comment by btea** [comment]
@holazz There still seems to be a problem with this modification. 

For example, when I switch the `activeIndex` to 1, and then modify the items, the active state is not correct.

You can have a try.

**Comment by makedopamine** [comment]
@btea @holazz 

> After I click the button to modify items, the active status seems to be lost [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gbGlzdFwiIDprZXk9XCJpdGVtXCI+XG4gICAgICA8aDMgdGV4dD1cIjJ4bFwiIGp1c3RpZnk9XCJjZW50ZXJcIj57eyBpdGVtIH19PC9oMz5cbiAgICA8L2VsLWNhcm91c2VsLWl0ZW0+XG4gIDwvZWwtY2Fyb3VzZWw+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlXCI+Y2hhbmdlPC9lbC1idXR0b24+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGxpc3QgPSByZWYoW10pXG5jb25zdCBjaGFuZ2UgPSAoKSA9PiB7XG4gIGxpc3QudmFsdWUgPSBbMTAsIDIwLCAzMCwgNDBdXG59XG4gIG9uTW91bnRlZCgoKT0+e1xuICAgIC8vIGxpc3QudmFsdWUgPSBbMSwyLDMsNF07XG4gICAgc2V0VGltZW91dCgoKT0+e1xuICAgICAgbGlzdC52YWx1ZSA9IFsyLDMsNCw1XVxuICAgIH0sNTAwKVxuICB9KVxuPC9zY3JpcHQ+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

To solve the issue, we should invoke `resetItemPosition` methods of `carousel` component  after all `carousel-item` are mounted.

I would do this (the modification is base on the latest commit of this pr).
```diff
- function addItem(item: CarouselItemContext) {
+ async function addItem(item: CarouselItemContext) {
+    if (items.value.length === 0) {
+      await nextTick()
+      this.setActiveItem(props.initialIndex)
+    }
     items.value.push(item)
}

- watch(
-   () => items.value.length,
-   (_, len) => {
-     if (len === 0) setActiveItem(props.initialIndex)
-   }
- )
```

**Comment by makedopamine** [comment]
@holazz @btea hi, bro.  
I pushed a commit to fix this issue. Let's check it out. [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlXCI+Y2hhbmdlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJlbXB0eVwiPmVtcHR5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJwdXNoXCI+cHVzaDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwicG9wXCI+cG9wPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ1bnNoaWZ0XCI+dW5zaGlmdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwic2hpZnRcIj5zaGlmdDwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cbiAgPGJyIC8+XG4gIDxkaXY+cmVuZGVyTGlzdDoge3sgbGlzdCB9fTwvZGl2PlxuICA8ZWwtY2Fyb3VzZWwgaWQ9XCJlbC1jYXJvdXNlbFwiIDphdXRvcGxheT1cImZhbHNlXCIgOmluaXRpYWwtaW5kZXg9XCIxXCI+XG4gICAgPGVsLWNhcm91c2VsLWl0ZW1cbiAgICAgIHYtZm9yPVwiKGl0ZW0sIGluZGV4KSBpbiBsaXN0XCJcbiAgICAgIDprZXk9XCJpdGVtXCJcbiAgICAgIDpsYWJlbD1cImluZGV4ICsgMVwiXG4gICAgPlxuICAgICAgPGgxIHN0eWxlPVwidGV4dC1hbGlnbjogY2VudGVyXCI+e3sgaXRlbSB9fTwvaDE+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbGlzdCA9IHJlZihbXSlcbmxldCBmbGFnID0gZmFsc2VcblxuZnVuY3Rpb24gY2hhbmdlKCkge1xuICBsaXN0LnZhbHVlID0gZmxhZyA/IFsxLCAyLCAzLCA0XSA6IFsxMCwgMjAsIDMwXVxuICBmbGFnID0gIWZsYWdcbn1cblxuZnVuY3Rpb24gZW1wdHkoKSB7XG4gIGxpc3QudmFsdWUgPSBbXVxufVxuXG5mdW5jdGlvbiBwb3AoKSB7XG4gIGxpc3QudmFsdWUucG9wKClcbn1cblxuZnVuY3Rpb24gc2hpZnQoKSB7XG4gIGxpc3QudmFsdWUuc2hpZnQoKVxufVxuXG5mdW5jdGlvbiB1bnNoaWZ0KCkge1xuICBsaXN0LnZhbHVlLnVuc2hpZnQoTWF0aC5mbG9vcihNYXRoLnJhbmRvbSgpICogMTApKVxufVxuICBcbmZ1bmN0aW9uIHB1c2goKSB7XG4gIGxpc3QudmFsdWUucHVzaChNYXRoLmZsb29yKE1hdGgucmFuZG9tKCkgKiAxMCkpXG59XG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGxpc3QudmFsdWUgPSBbMSwgMiwgMywgNF1cbiAgfSwgNTAwKVxufSlcbjwvc2NyaXB0PiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODkwNC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy04OTA0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ1xuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICB9KVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTg5MDQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

File: packages/components/carousel/src/carousel-item.vue [hunk 1]
```diff
@@ -185,6 +189,7 @@ onMounted(() => {
     }),
     uid: instance.uid,
     translateItem,
+    el: carouselItemRef.value as Node,
```
Comment (holazz) [inline packages/components/carousel/src/carousel-item.vue:192]: Maybe we can get `el` from `instance`.

```suggestion
    el: instance.vnode.el!,
```

File: packages/components/carousel/src/carousel.vue [hunk 2]
```diff
@@ -300,17 +315,25 @@ watch(
...
+    if (activeIndex.value < 0) setActiveItem(props.initialIndex)
+    else {
+      const activeId = oldIds[activeIndex.value]
+      const index = ids.indexOf(activeId)
+      if (index > -1) setActiveItem(index)
+      else setActiveItem(activeIndex.value)
+    }
+  }
+)
+
```
Comment (holazz) [inline packages/components/carousel/src/carousel.vue:330]: I think when the items change, we don't need to maintain the active state, but directly reset the active index to the initial index. This behavior is consistent with `element-ui`.

```ts
if (ids.length > 0) setActiveItem(props.initialIndex)
```

File: packages/tokens/carousel.ts [hunk 3]
```diff
@@ -17,6 +17,7 @@ export type CarouselItemContext = {
   states: CarouselItemStates
   uid: number | undefined
   translateItem: (index: number, activeIndex: number, oldIndex?: number) => void
+  el: Node
```
Comment (holazz) [inline packages/tokens/carousel.ts:20]: According to the previous comment, the type here should be:

```ts
import type { RendererNode } from 'vue'
```

```ts
el: RendererNode
```

**Review by holazz — COMMENTED** [review]
@makedopamine Sorry for the late reply, I realize that this is mainly caused by the `carouse-item` rendering order. 

link: 
https://github.com/vuejs/core/issues/5848 
https://github.com/vuejs/core/issues/4550

And I think you've solved this issue pretty well. Finally, left a few comments for your consideration.

File: packages/components/carousel/src/carousel-item.vue (hunk 1 above)
Comment (makedopamine) [reply packages/components/carousel/src/carousel-item.vue:192]: But we can't get help from code completion, because of `RendererNode` type is less specific than `HTMLDivElement` type. I would like using `Template Refs` .  Or how about using type assertions?
```
el:  instance.vnode.el! as HTMLDivElement
```

**Comment by holazz** [comment]
@makedopamine Sorry for the late response, The PR https://github.com/element-plus/element-plus/pull/9785 addressed a similar issue to this one. You can refer to it, maybe that is a better way.

**Comment by makedopamine** [comment]
@holazz Carousel is ready, please review it

File: packages/components/carousel/__tests__/carousel.test.tsx [hunk 4]
```diff
@@ -195,4 +195,30 @@ describe('Carousel', () => {
     await wait(60)
     expect(items[1].classList.contains('is-active')).toBeTruthy()
   })
+  it('sholud guarantee order of indicators', async () => {
```
Comment (holazz) [inline packages/components/carousel/__tests__/carousel.test.tsx:198]: sholud -> should

File: packages/components/carousel/__tests__/carousel.test.tsx [hunk 5]
```diff
@@ -195,4 +195,30 @@ describe('Carousel', () => {
...
+      },
+    })
+    await nextTick()
+
+    data.value.splice(1, 0, 5)
+    await nextTick()
+    const indicators = wrapper.vm.$el.querySelectorAll('.el-carousel__button')
+    data.value.forEach((value, index) => {
+      expect(indicators[index].textContent).toEqual(value.toString())
+    })
```
Comment (holazz) [inline packages/components/carousel/__tests__/carousel.test.tsx:222]:
```suggestion
    const indicators = wrapper.findAll('.el-carousel__button')
    data.value.forEach((value, index) => {
      expect(indicators[index].element.textContent).toEqual(value.toString())
    })
```

File: packages/components/carousel/src/carousel.vue [hunk 6]
```diff
@@ -80,6 +80,7 @@ import { ElIcon } from '@element-plus/components/icon'
 import { ArrowLeft, ArrowRight } from '@element-plus/icons-vue'
 import { useNamespace } from '@element-plus/hooks'
 import { carouselContextKey } from '@element-plus/tokens'
+import { useOrderedChildren } from '@element-plus/hooks/use-ordered-children'
```
Comment (holazz) [inline packages/components/carousel/src/carousel.vue:83]: We could export composable function at the entry of hooks.

`@element-plus/hooks/index.ts`
```ts
export * from './use-ordered-children'
```

File: packages/components/carousel/src/carousel.vue [hunk 7]
```diff
@@ -312,17 +309,19 @@ watch(
...
+watch(
+  () => items.value,
+  () => {
+    if (items.value.length > 0) setActiveItem(props.initialIndex)
+  }
+)
+
 const resizeObserver = shallowRef<ReturnType<typeof useResizeObserver>>()
 // lifecycle
 onMounted(async () => {
```
Comment (holazz) [inline packages/components/carousel/src/carousel.vue:321]: Useless async keyword.

**Review by holazz — COMMENTED** [review]
@makedopamine Overall LGTM, left some comments for your consideration.

File: packages/hooks/index.ts [hunk 8]
```diff
@@ -28,3 +28,4 @@ export * from './use-namespace'
 export * from './use-z-index'
 export * from './use-floating'
 export * from './use-cursor'
+export * from './use-ordered-children'
```
Comment (holazz) [inline packages/hooks/index.ts:31]: It is better to place this line after line#11.

**Review by holazz — COMMENTED** [review]
Nice! Thanks for your hard work.

**Review by holazz — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]
