### PR TITLE
fix(components): [input] lose focus when click suffix icon

### LINKED ISSUE #13153: [Component] [select] Select 选择器 点击icon 无法收回弹出层
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Edg/113.0.1774.57 / Macintosh`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/select.html)

### Steps to reproduce

点击右侧icon 展示出来可选项，再次点击右侧 icon 可选项收缩回去又直接展示出来

### What is Expected?

再次点击可正常隐藏可选项

### What is actually happening?

再次点击可正常无法隐藏可选项

### Additional comments

selectv2 操作正常

### PR DESCRIPTION
**Pull request by tolking**
fix #13153, close #13159

When click on the prefix or suffix icon, it causes the input to lose focus and then regain focus, resulting in unnecessary loss of focus behavior, This PR has corrected this behavior.

[before](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnO1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcblxuY29uc3QgaXNMb3N0ID0gcmVmKGZhbHNlKVxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5jb25zdCBoYW5kbGVGb2N1cyA9IChlOiB1bmtub3duKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdmb2N1cycsIGUpXG59XG5jb25zdCBoYW5kbGVCbHVyID0gKGU6IHVua25vd24pID0+IHtcbiAgY29uc29sZS5sb2coJ2JsdXInLCBlKVxuICBpc0xvc3QudmFsdWUgPSB0cnVlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5sb3N0IGZvY3VzOiB7eyBpc0xvc3QgfX08L3A+XG4gIDxwPkNsaWNrIG9uIHRoZSBpY29uIGF0IHRoZSBmYXIgcmlnaHQ8L3A+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwidmFsdWVcIiA6c3VmZml4LWljb249XCJFbGVtZW50UGx1c1wiIGNsZWFyYWJsZSBzdHlsZT1cIndpZHRoOiAyMDBweDtcIiBAZm9jdXM9XCJoYW5kbGVGb2N1c1wiIEBibHVyPVwiaGFuZGxlQmx1clwiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

[after](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnO1xuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcblxuY29uc3QgaXNMb3N0ID0gcmVmKGZhbHNlKVxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5jb25zdCBoYW5kbGVGb2N1cyA9IChlOiB1bmtub3duKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdmb2N1cycsIGUpXG59XG5jb25zdCBoYW5kbGVCbHVyID0gKGU6IHVua25vd24pID0+IHtcbiAgY29uc29sZS5sb2coJ2JsdXInLCBlKVxuICBpc0xvc3QudmFsdWUgPSB0cnVlXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5sb3N0IGZvY3VzOiB7eyBpc0xvc3QgfX08L3A+XG4gIDxwPkNsaWNrIG9uIHRoZSBpY29uIGF0IHRoZSBmYXIgcmlnaHQ8L3A+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwidmFsdWVcIiA6c3VmZml4LWljb249XCJFbGVtZW50UGx1c1wiIGNsZWFyYWJsZSBzdHlsZT1cIndpZHRoOiAyMDBweDtcIiBAZm9jdXM9XCJoYW5kbGVGb2N1c1wiIEBibHVyPVwiaGFuZGxlQmx1clwiIC8+XG48L3RlbXBsYXRlPlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEzMjY0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMzI2NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctMTMyNjQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTMyNjQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 7b9db8c</samp>

This pull request introduces a new `useFocusController` hook that simplifies the focus and blur logic of input components. It also updates the tests and the implementation of the `input`, `input-number`, and `select` components to use this hook. The hook avoids unnecessary blur events when clicking on prefix or suffix elements and provides callbacks for custom focus and blur actions.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 7b9db8c</samp>

*  Add `useFocusController` hook to handle focus and blur events of input elements ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L175-R180), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L239-R260), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L448-L460), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-a2275f5046e45dab2261fa65b8b67eecf411212ce5ba7b26c72ad8e7115c0d87R29), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-2bdec9b56644a5e68363c0e58d37a4f2288ac2a5777adfb2b939617cd912f190R1-R50), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-5211bf9449eae978ee3bbaa79f074698b22b7e1fb33a919193b25f868a34cf51R1-R68))
* Replace original focus and blur logic in `input.vue` with `useFocusController` hook ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L239-R260), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L448-L460))
  - The hook is imported from `@element-plus/hooks` module ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L175-R180))
  - The `wrapperRef` is bound to the `div` element with the `wrapperKls` class using the `ref` attribute ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L18-R21))
  - The `triggerAttrs` are bound to the `span` element with the `nsInput.e('suffix-inner')` class using the `v-bind` directive ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-740318b89e9e14e0ecf7296023cfe04687fea7371612db4f9b5d456d1648b2a7L57-R57))
* Add `sleep` calls to `input-number.test.tsx` and `input.test.tsx` to wait for asynchronous updates and events ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-72ec1db9873d845eb37943dfa7857b7fd8f4c8b156ac648e4bdb53b21efb3239R6), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-72ec1db9873d845eb37943dfa7857b7fd8f4c8b156ac648e4bdb53b21efb3239R322), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-7ec889d4dc91be0fa6db8bbaf6271ab596f617ad15a31ba2c5d5645d2f666d93R6), [link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-7ec889d4dc91be0fa6db8bbaf6271ab596f617ad15a31ba2c5d5645d2f666d93R350))
* Increase delay argument of `sleep` call in `select.test.ts` to ensure `blur` event is emitted ([link](https://github.com/element-plus/element-plus/pull/13264/files?diff=unified&w=0#diff-7cabf9c29b1c9e9c05c8b9c9c0d39175230ba4e872e88d42536c2157723229e0L1227-R1227))

### CODE REVIEW

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -236,11 +241,23 @@ const inputSize = useFormSize()
 const inputDisabled = useFormDisabled()
 const nsInput = useNamespace('input')
 const nsTextarea = useNamespace('textarea')
+const {
+  wrapperRef,
+  targetRef: input,
+  isFocused: focused,
```
Comment (btea) [inline packages/components/input/src/input.vue:247]: There may be no need to assign to the new variable name here, just let `useFocusController` return the corresponding variable name.

**Review by btea — APPROVED** [review]

**Review by chenxch — APPROVED** [review]

**Comment by purepear** [comment]
Looks like this is adding `role="button"` and `tabindex` attributes to ElInput 🤔 
This can be observed in the docs https://element-plus.org/en-US/component/input.html#basic-usage

This is potential problem for accessibility and tests that use `getByRole()` might start failing.

image

**Comment by tolking** [comment]
The `role="button"` and `tabindex` only capture focus events from the mouse.

I do not think this will cause accessibility issues, but I am really sorry for the testing and I have not thought of any other alternative methods at the moment.
