### PR TITLE
fix(components): [tree] `up/down` keys stop working after expanding nodes

### LINKED ISSUE #21514: [Component] [tree] [component] [tree] 使用 :render-after-expand="false"，在展开节点，会出现up/down被阻止的情况
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.10.4`
- Browser / OS: `Chrome 138 / windows11`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/tree.html)

### Steps to reproduce

使用 :render-after-expand="false"，在展开节点，会出现up/down被阻止的情况

### What is Expected?

上下按键选择正确

### What is actually happening?

选择不正确

### Additional comments

Image

### PR DESCRIPTION
**Pull request by SpanManX**
Fix #21514

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by Dsaquel — APPROVED** [review]
Nice, LGTM !

**Review by warmthsea — APPROVED** [review]
LGTM

File: packages/components/tree/src/model/useKeydown.ts [hunk 1]
```diff
@@ -74,7 +78,11 @@ export function useKeydown({ el$ }: UseKeydownOption, store: Ref<TreeStore>) {
           const currentNode = store.value.getNode(
             treeItems[nextIndex].dataset.key!
           )
-          if (currentNode.canFocus && currentNode.visible) {
+          if (
+            currentNode.canFocus &&
+            currentNode.visible &&
+            (currentNode.parent?.expanded || currentNode.parent?.level === 0)
+          ) {
```
Comment (btea) [inline packages/components/tree/src/model/useKeydown.ts]: Lines 78 to 85 this part of the code has the same logic as above and may be able to be extracted.

**Review by btea — APPROVED** [review]
Thanks!
