### PR TITLE
fix(components): [select] fix placeholder display

### LINKED ISSUE #11049: [Component] [select] When the selection box has a value, the placeholder will still be displayed after the dynamic change.
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+ZGVmYXVsdDwvcD5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICA6cGxhY2Vob2xkZXI9XCJwbGFjXCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbJ09wdGlvbjEnXSlcbmNvbnN0IHZhbHVlMiA9IHJlZihbXSlcbmNvbnN0IHZhbHVlMyA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoW1xuICAgIHtcbiAgICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgICBsYWJlbDogJ09wdGlvbjExJyxcbiAgICB9LFxuICBdKVxuY29uc3QgcGxhYyA9IHJlZignZGVmYXVsdCBwbGFjZWhvbGRlcicpXG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBwbGFjLnZhbHVlID0gJ3VwZGF0ZWQgcGxhY2Vob2xkZXInXG59LCA2MDApXG4gIFxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. Assign value to select box
2. Assign value to placeholder

something unusual happened:
image

### What is Expected?

placeholder does not show.

### What is actually happening?

placeholder show.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by sleepyShen1989**
closed #11049

动态修改placeholder时，判断modelValue是否有值，如果有值则清空placeholder

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/select/src/useSelect.ts [hunk 1]
```diff
@@ -210,6 +210,15 @@ export const useSelect = (props, states: States, ctx) => {
...
       states.cachedPlaceHolder = states.currentPlaceholder = val
+
+      const hasValue =
+        props.multiple &&
+        Array.isArray(props.modelValue) &&
+        props.modelValue.length > 0
+
+      if (hasValue) {
+        states.currentPlaceholder = ''
+      }
```
Comment (btea) [inline packages/components/select/src/useSelect.ts:221]: It seems to be consistent with the logic of the following code, maybe it can be extracted
https://github.com/element-plus/element-plus/blob/2ab408ae4856afe4a64d33d4ddde52cbc5c85a61/packages/components/select/src/select.vue#L547-L552

**Comment by Lionad-Morotar** [comment]
@btea Hello, would this pr being merged in the next release?

**Review by btea — APPROVED** [review]

**Review by ryuhangyeong — APPROVED** [review]

File: packages/components/select/src/useSelect.ts [hunk 2]
```diff
@@ -210,6 +210,15 @@ export const useSelect = (props, states: States, ctx) => {
     () => props.placeholder,
     (val) => {
       states.cachedPlaceHolder = states.currentPlaceholder = val
+
+      const hasValue =
+        props.multiple &&
+        Array.isArray(props.modelValue) &&
+        props.modelValue.length > 0
```
Comment (ryuhangyeong) [inline packages/components/select/src/useSelect.ts:217]: ## Suggest

A duplicate of that code exists at line `114`.

I think it would be better to separate it into computed and reuse it.

**Review by ryuhangyeong — APPROVED** [review]
