### PR TITLE
fix(table): when the data changes, the layout is not updated

### LINKED ISSUE #1019: el-table doesn't show scrollbar
```
vue: 3.0.4
element-plus:  1.0.1-beta.8
```
```
<template>
  <el-table :data="data" height="300" style="width: 300px">
    <el-table-column prop="index" label="index"></el-table-column>
    <el-table-column prop="label" label="label"></el-table-column>
  </el-table>
</template>

<script>
import { onMounted, ref } from "vue";
export default {
  name: "Test",
  setup() {
    const data = ref([]);
    onMounted(() => {
      // simulate network request
      setTimeout(() => {
        data.value = getData();
      }, 100);
    });
    return {
      data,
    };
  },
};

function getData() {
  const temp = [];
  for (let i = 1; i < 20; i++) {
    temp.push({ index: i, label: "line: " + i });
  }
  return temp;
}
</script>
```

screenshot

### PR DESCRIPTION
**Pull request by justwiner**
* [table] fix #1019,#1142

### CODE REVIEW

File: packages/table/src/store/index.ts [hunk 1]
```diff
@@ -150,15 +152,15 @@ function useStore(): Store {
...
     const mutations = instance.store.mutations
     if (mutations[name]) {
       mutations[name].apply(instance, [instance.store.states].concat(args))
     } else {
       throw new Error(`Action not found: ${name}`)
     }
   }
-  const updateTableScrollY = function () {
+  const updateTableScrollY = function() {
     nextTick(instance.layout.updateScrollY.apply(instance.layout))
```
Comment (JeremyWuuuuu) [inline packages/table/src/store/index.ts:164]: Use 
```ts
nextTick(() => instance.layout.updateScrollY.apply(instance.layout))
```

Comment (JeremyWuuuuu) [reply packages/table/src/store/index.ts:164]: @justwiner  can you address this comment?

Comment (justwiner) [reply packages/table/src/store/index.ts:164]: yeah, it's right

**Review by jw-foss — APPROVED** [review]
