### PR TITLE
fix(components): [tree-v2] icon display is abnormal when expanding nodes

### LINKED ISSUE #21505: [Component] [divider] ElTreeV2 使用setExpandedKeys展开后，其他已展开的项会关闭，但是图标没有改变
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.17`
- Element Plus Version: `2.10.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-divider`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8YnV0dG9uIEBjbGljaz1cImNsaWNrYVwiPjEyMzwvYnV0dG9uPlxuICA8ZWwtdHJlZS12MlxuICByZWY9XCJ0cmVlXCJcbiAgICBzdHlsZT1cIm1heC13aWR0aDogNjAwcHhcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOnByb3BzPVwicHJvcHNcIlxuICAgIDpoZWlnaHQ9XCIyMDhcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiAgaW1wb3J0IHtyZWZ9IGZyb20gJ3Z1ZSdcblxuaW50ZXJmYWNlIFRyZWUge1xuICBpZDogc3RyaW5nXG4gIGxhYmVsOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cbmNvbnN0IHRyZWUgPSByZWYoKVxuY29uc3QgZ2V0S2V5ID0gKHByZWZpeDogc3RyaW5nLCBpZDogbnVtYmVyKSA9PiB7XG4gIHJldHVybiBgJHtwcmVmaXh9LSR7aWR9YFxufVxuXG5jb25zdCBjbGlja2E9KCk9PntcbiAgY29uc29sZS5sb2coZGF0YSwnZGF0YScpXG4gIHRyZWUudmFsdWUuc2V0RXhwYW5kZWRLZXlzKFsnbm9kZS0zJ10pXG59XG5cbmNvbnN0IGNyZWF0ZURhdGEgPSAoXG4gIG1heERlZXA6IG51bWJlcixcbiAgbWF4Q2hpbGRyZW46IG51bWJlcixcbiAgbWluTm9kZXNOdW1iZXI6IG51bWJlcixcbiAgZGVlcCA9IDEsXG4gIGtleSA9ICdub2RlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC40L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsiZXBWZXJzaW9uIjoiMi4xMC40In19)

### Steps to reproduce

Image

展开node-1
点击按钮

2.10.2 版本正确

### What is Expected?

渲染正确

### What is actually happening?

渲染错误

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by keeplearning66**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

This PR is to fix #21505 

The bug is caused by not setting `expanded` of nodes that do not need to be expanded to `false` when using `setExpandedKeys`.
And when using `filter-method`, it is also necessary to handle the display of the icon.

After modification

https://github.com/user-attachments/assets/58482a13-5592-42e7-9e59-5188fd02422c

### CODE REVIEW

**Comment by btea** [comment]
这个场景仍然有问题。https://github.com/element-plus/element-plus/issues/21627#issuecomment-3153750753

**Comment by patienry** [comment]
> 这个场景仍然有问题。[#21627 (comment)](https://github.com/element-plus/element-plus/issues/21627#issuecomment-3153750753)

[issue](https://github.com/element-plus/element-plus/issues/21505)是`setExpandedKeys`引发的，[issue](https://github.com/element-plus/element-plus/issues/21627)是`filter-method`引发的，我已经更新了PR

File: packages/components/tree-v2/src/composables/useTree.ts [hunk 1]
```diff
@@ -180,15 +180,23 @@ export function useTree(
...
+          }
+        } else {
+          node.expanded = false
+        }
         node = node.parent
       }
-    })
+    }
 
     expandedKeySet.value = expandedKeys
```
Comment (Dsaquel) [inline packages/components/tree-v2/src/composables/useTree.ts]: The previous logic was successful because `expandedKeySet` was fully reassign and there was no `expanded` property to handle in `node`.

Now we can replicate the logic by resetting the previous nodes expanded before the assign logic.

Pseudo code:
```diff
  function setExpandedKeys(keys: TreeKey[]) {
    const expandedKeys = new Set<TreeKey>()
    const nodeMap = tree.value!.treeNodeMap
+    expandedKeySet.value.forEach((key) => {
+      const node = nodeMap.get(key)!
+      expandedKeySet.value.delete(node.key)
+      node.expanded = false
+    })

    keys.forEach((k) => {
      let node = nodeMap.get(k)
      while (node && !expandedKeys.has(node.key)) {
        expandedKeys.add(node.key)
        node.expanded = true
        node = node.parent
      }
    })

    expandedKeySet.value = expandedKeys
  }
```

Comment (patienry) [reply packages/components/tree-v2/src/composables/useTree.ts]: Thank you for your review, the code is much better now and no longer requires iterating through each node. I have updated the PR, thanks again!

**Review by Dsaquel — APPROVED** [review]
Thanks!

**Comment by ZhangYC193** [comment]
修复之后，是否可以支持手风琴效果

**Comment by patienry** [comment]
> 修复之后，是否可以支持手风琴效果@keeplearning66

{D5857F62-B1E1-4B71-8A08-8B64955F4F67}

目前组件是支持手风琴效果的，您遇到了什么问题吗？

**Comment by ZhangYC193** [comment]
@keeplearning66
el-tree-v2不支持吧，想问问这个

**Review by btea — APPROVED** [review]
