### PR TITLE
fix(components): [message] fix consecutive closeAll method calls

### LINKED ISSUE #20333: [Component] [message] Rapidly creating and destroying ElMessage leaves divs that don't get removed
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.34`
- Element Plus Version: `2.9.6`
- Browser / OS: `Chrome/135.0.0.0 / Ubuntu 22.04.4 LTS`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiwgRWxNZXNzYWdlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5cbmZ1bmN0aW9uIG9uQ2xpY2soKSB7XG4gIEVsTWVzc2FnZSh7IG1lc3NhZ2U6IFwiMVwiIH0pO1xuICBFbE1lc3NhZ2UuY2xvc2VBbGwoKTtcbiAgRWxNZXNzYWdlKHsgbWVzc2FnZTogXCIyXCIgfSk7XG4gIEVsTWVzc2FnZS5jbG9zZUFsbCgpO1xuICBFbE1lc3NhZ2UoeyBtZXNzYWdlOiBcIjNcIiB9KTtcbiAgRWxNZXNzYWdlLmNsb3NlQWxsKCk7XG4gIEVsTWVzc2FnZSh7IG1lc3NhZ2U6IFwiNFwiIH0pO1xuICBFbE1lc3NhZ2UuY2xvc2VBbGwoKTtcbiAgRWxNZXNzYWdlKHsgbWVzc2FnZTogXCI1XCIgfSk7XG4gIEVsTWVzc2FnZS5jbG9zZUFsbCgpO1xuICBFbE1lc3NhZ2UoeyBtZXNzYWdlOiBcIjZcIiB9KTtcbn1cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJvbkNsaWNrXCI+Q2xpY2sgTWU8L2VsLWJ1dHRvbj5cblxuICA8cD5cbiAgICBUaGUgbW9yZSB5b3UgY2xpY2ssIHRoZSBsb3dlciBkb3duIHRoZSBtZXNzYWdlIHdpbGwgYmUuXG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjkuNi9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjkuNi90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjQuMzQvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQDMuNC4zNC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi45LjYvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjkuNi9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJ2dWVWZXJzaW9uIjoiMy40LjM0IiwiZXBWZXJzaW9uIjoiMi45LjYifX0=)

### Steps to reproduce

1. Show an ElMessage.
2. Close the message with either `message.close()` or `ElMessage.closeAll()`
3. Show another message

### What is Expected?

The second message should show in the correct location. There should only be one `div.el-message` element in the DOM.

### What is actually happening?

The message shows lower down than it should. There are old message divs remaining in the DOM which are never removed.

### Additional comments

If the process is repeated then the issue gets worse.

### PR DESCRIPTION
**Pull request by DDDDD12138**
fix: #20333

### Before

https://github.com/user-attachments/assets/01a158b1-7224-46ee-bf57-629a327b7897

### After

https://github.com/user-attachments/assets/b1c3896a-8bba-4f78-91f9-836c56541e19

### CODE REVIEW

**Review by warmthsea — APPROVED** [review]
LGTM

File: packages/components/message/src/method.ts [hunk 1]
```diff
@@ -188,7 +188,10 @@ messageTypes.forEach((type) => {
 })
 
 export function closeAll(type?: messageType): void {
-  for (const instance of instances) {
+  // Create a copy of instances to avoid modification during iteration
+  const instancesToClose = [...instances]
```
Comment (btea) [inline packages/components/message/src/method.ts:192]: This step is not necessary, the spread syntax is just a shallow copy.

Comment (DDDDD12138) [reply packages/components/message/src/method.ts:192]: https://github.com/element-plus/element-plus/blob/544d710db720719daae86a6b8d283159934716d9/packages/components/message/src/method.ts#L79-L86

It's not advisable to perform splice operations on an array during iteration. Creating a shallow copy of the array would be the expected approach.

**Review by btea — APPROVED** [review]
Thanks!
