### PR TITLE
fix(components): [select] inner input height is inconsistent with select

### LINKED ISSUE #6939: [Bug Report] [Component] [select, drawer] el-select在el-drawer内使用，动态设置el-select禁用，el-select高度发生变化
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.7`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwib3BlbkRpYWxvZ1wiXG4gICAgPk9wZW4gRHJhd2VyIHdpdGggbmVzdGVkIGZvcm08L2VsLWJ1dHRvblxuICA+XG5cbiAgPGVsLWRyYXdlclxuICAgIHJlZj1cImRyYXdlclJlZlwiXG4gICAgdi1tb2RlbD1cImRpYWxvZ1wiXG4gICAgdGl0bGU9XCJJIGhhdmUgYSBuZXN0ZWQgZm9ybSBpbnNpZGUhXCJcbiAgICA6YmVmb3JlLWNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICAgIHNpemU9XCI1MCVcIlxuICAgIGN1c3RvbS1jbGFzcz1cImRlbW8tZHJhd2VyXCJcbiAgPlxuICAgIDxkaXYgY2xhc3M9XCJkZW1vLWRyYXdlcl9fY29udGVudFwiPlxuICAgICAgPGVsLWZvcm0gOm1vZGVsPVwiZm9ybVwiPlxuICAgICAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiTmFtZVwiIDpsYWJlbC13aWR0aD1cImZvcm1MYWJlbFdpZHRoXCI+XG4gICAgICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJmb3JtLm5hbWVcIiBhdXRvY29tcGxldGU9XCJvZmZcIiAvPlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cIkFyZWFcIiA6bGFiZWwtd2lkdGg9XCJmb3JtTGFiZWxXaWR0aFwiPlxuICAgICAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgICAgIHYtbW9kZWw9XCJmb3JtLnJlZ2lvblwiXG4gICAgICAgICAgICA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiXG4gICAgICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3QgYWN0aXZpdHkgYXJlYVwiXG4gICAgICAgICAgPlxuICAgICAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIkFyZWExXCIgdmFsdWU9XCJzaGFuZ2hhaVwiIC8+XG4gICAgICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwiQXJlYTJcIiB2YWx1ZT1cImJlaWppbmdcIiAvPlxuICAgICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgICAgIDwvZWwtZm9ybT5cbiAgICAgIDxkaXYgY2xhc3M9XCJkZW1vLWRyYXdlcl9fZm9vdGVyXCI+XG4gICAgICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2FuY2VsRm9ybVwiPkNhbmNlbDwvZWwtYnV0dG9uPlxuICAgICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgOmxvYWRpbmc9XCJsb2FkaW5nXCIgQGNsaWNrPVwib25DbGlja1wiPnt7XG4gICAgICAgICAgbG9hZGluZyA/ICdTdWJtaXR0aW5nIC4uLicgOiAnU3VibWl0J1xuICAgICAgICB9fTwvZWwtYnV0dG9uPlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZWwtZHJhd2VyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlYWN0aXZlLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3ggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgdHlwZSB7IEVsRHJhd2VyIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBmb3JtTGFiZWxXaWR0aCA9ICc4MHB4J1xubGV0IHRpbWVyXG5cbmNvbnN0IGRpYWxvZyA9IHJlZihmYWxzZSlcbmNvbnN0IGxvYWRpbmcgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGZvcm0gPSByZWFjdGl2ZSh7XG4gIG5hbWU6ICcnLFxuICByZWdpb246ICcnLFxuICBkYXRlMTogJycsXG4gIGRhdGUyOiAnJyxcbiAgZGVsaXZlcnk6IGZhbHNlLFxuICB0eXBlOiBbXSxcbiAgcmVzb3VyY2U6ICcnLFxuICBkZXNjOiAnJyxcbn0pXG5cbmNvbnN0IGRyYXdlclJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsRHJhd2VyPj4oKVxuY29uc3Qgb25DbGljayA9ICgpID0+IHtcbiAgZHJhd2VyUmVmLnZhbHVlIS5jbG9zZSgpXG59XG5cbmNvbnN0IGhhbmRsZUNsb3NlID0gKGRvbmUpID0+IHtcbiAgaWYgKGxvYWRpbmcudmFsdWUpIHtcbiAgICByZXR1cm5cbiAgfVxuICBFbE1lc3NhZ2VCb3guY29uZmlybSgnRG8geW91IHdhbnQgdG8gc3VibWl0PycpXG4gICAgLnRoZW4oKCkgPT4ge1xuICAgICAgbG9hZGluZy52YWx1ZSA9IHRydWVcbiAgICAgIHRpbWVyID0gc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgIGRvbmUoKVxuICAgICAgICAvLyDliqjnlLvlhbPpl63pnIDopoHkuIDlrprnmoTml7bpl7RcbiAgICAgICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICAgICAgbG9hZGluZy52YWx1ZSA9IGZhbHNlXG4gICAgICAgIH0sIDQwMClcbiAgICAgIH0sIDIwMDApXG4gICAgfSlcbiAgICAuY2F0Y2goKCkgPT4ge1xuICAgICAgLy8gY2F0Y2ggZXJyb3JcbiAgICB9KVxufVxuXG5jb25zdCBjYW5jZWxGb3JtID0gKCkgPT4ge1xuICBsb2FkaW5nLnZhbHVlID0gZmFsc2VcbiAgZGlhbG9nLnZhbHVlID0gZmFsc2VcbiAgY2xlYXJUaW1lb3V0KHRpbWVyKVxufVxuXG5jb25zdCBkaXNhYmxlZCA9IHJlZihmYWxzZSlcbmNvbnN0IG9wZW5EaWFsb2cgPSAoKSA9PiB7XG4gIGRpYWxvZy52YWx1ZSA9IHRydWVcbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgZGlzYWJsZWQudmFsdWUgPSB0cnVlXG4gIH0sIDMwMDApXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1.点击按钮
2.等待3s

### What is Expected?

el-select和内部的el-input高度不变

### What is actually happening?

el-select内部的el-input高度发生变化

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by buqiyuan**
Please make sure these boxes are checked before submitting your PR, thank you!

fix: #6939

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/constants/size.ts [hunk 1]
```diff
@@ -1,2 +1,13 @@
...
+
 export type ComponentSize = typeof componentSizes[number]
+
+export const componentSizeMap = {
+  large: 40,
+  default: 32,
+  small: 24,
+} as const
+
+export const getComponentSize = (size?: ComponentSize) => {
```
Comment (JeremyWuuuuu) [inline packages/constants/size.ts:11]:
```suggestion
export const getComponentSize = (size: ComponentSize = 'default') => {
```

**Review by jw-foss — APPROVED** [review]
Left a non-blocking comment for you, merge it if you feel like to.
