### PR TITLE
fix(components): [notification] correct offset value

### LINKED ISSUE #9078: [Component] [notification] If the offset attribute is used when notification and duration are 0, notifications will overlap
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.9`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15`
- Build Tool: `Webpack`

### Related Component

- `el-notification`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sRWxOb3RpZmljYXRpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG4gIFxuY29uc3QgaGFuZGxlQ2xpY2sgPSAoKSA9PiB7XG5cdEVsTm90aWZpY2F0aW9uLnN1Y2Nlc3Moe1xuICAgIHRpdGxlOiAnU3VjY2VzcycsXG4gICAgbWVzc2FnZTogJ1RoaXMgaXMgYSBzdWNjZXNzIG1lc3NhZ2UnLFxuICAgIGR1cmF0aW9uOjAsXG4gICAgb2Zmc2V0OiAxMDAsXG4gIH0pXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5DbGljayB0aGUgYnV0dG9uIG1hbnkgdGltZXMsIGFuZCB0aGUgbm90aWZpY2F0aW9uIGJveGVzIG92ZXJsYXA8L3A+XG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJoYW5kbGVDbGlja1wiPueCueWHuzwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

The duration attribute is set to 0, and the offset is set to any value. Multiple notifications are generated by clicking the button many times, and the message prompt boxes overlap

### What is Expected?

Notification boxes do not overlap

### What is actually happening?

All notification boxes overlap

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by holazz**
closes #9078

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/notification/src/notify.ts [hunk 1]
```diff
@@ -50,10 +50,9 @@ const notify: NotifyFn & Partial<Notify> & { _context: AppContext | null } =
     const id = `notification_${seed++}`
     const userOnClose = options.onClose
     const props: Partial<NotificationProps> = {
-      // default options end
       zIndex: nextZIndex(),
-      offset: verticalOffset,
       ...options,
```
Comment (xiaoxian521) [inline packages/components/notification/src/notify.ts:54]:
```
 const props: Partial<NotificationProps> = {
      ...options,
      zIndex: nextZIndex(),
      offset: verticalOffset,
      id,
      onClose: () => {
        close(id, position, userOnClose)
      },
    }
```

**Review by xiaoxian521 — APPROVED** [review]
