### PR TITLE
fix(table): avoiding the error of el-table-column rendering

### LINKED ISSUE #793: Bug with slot of el-table-column
When use `scope.row.xxx.yyy` in el-table-column, There is an error: TypeError: Cannot read property 'yyy' of undefined. I can use `scope.row.xxx?.yyy`. It seems a bug with lifecycle.

### PR DESCRIPTION
**Pull request by justwiner**
fix #793

* [table] fix:#793

### CODE REVIEW

File: packages/table/src/table-column/index.ts [hunk 1]
```diff
@@ -202,24 +199,22 @@ export default defineComponent({
...
-        row: {},
-        $index: undefined,
-      }),
-    )
+    try {
+      return h(
+        'div',
+        this.$slots.default?.({
+          store: {},
+          _self: {},
```
Comment (JeremyWuuuuu) [inline packages/table/src/table-column/index.ts:210]: Without passing any data, how could users get data from?

Comment (justwiner) [reply packages/table/src/table-column/index.ts:210]: Rendering within `el-table-column` helps to generate column structures, cell rendering is called actively in `table-body` by `slots.default`
https://github.com/element-plus/element-plus/blob/fe42f4404e522f8bd6730fb51e0245d014a03512/packages/table/src/table-body/render-helper.ts#L81-L87
https://github.com/element-plus/element-plus/blob/fe42f4404e522f8bd6730fb51e0245d014a03512/packages/table/src/table-body/render-helper.ts#L104-L116
https://github.com/element-plus/element-plus/blob/fe42f4404e522f8bd6730fb51e0245d014a03512/packages/table/src/table-column/render-helper.ts#L111-L131

**Review by jw-foss — APPROVED** [review]
