### PR TITLE
fix(components): [watermark] resolve text clipping caused by textAlign

### LINKED ISSUE #21638: [Component] [watermark] [Style]  water remark is not displaying correctly when the textAlign is not 'center'
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.10.5`
- Browser / OS: `chrome 135.0.7049.42 （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-watermark`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyByZWYscmVhY3RpdmUsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGZvbnQgPSByZWFjdGl2ZSh7XG4gIGNvbG9yOiAncmdiYSgwLCAwLCAwLCAuMTUpJyxcbiAgdGV4dEFsaWduOidsZWZ0Jyxcbn0pXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC13YXRlcm1hcmsgOmZvbnQ9XCJmb250XCIgOmNvbnRlbnQ9XCJbJ2FkbWluJywgJ2FkbWluJ11cIj5cbiAgICA8ZGl2IHN0eWxlPVwid2lkdGg6IDEwMHZ3O2hlaWdodDogMTAwdmg7XCIgLz5cbiAgPC9lbC13YXRlcm1hcms+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC41L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTAuNS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjUuMTAvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQDMuNS4xMC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC41L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC41L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InZ1ZVZlcnNpb24iOiIzLjUuMTAiLCJlcFZlcnNpb24iOiIyLjEwLjUifX0=)

### Steps to reproduce

In the Playground example, set the textAlign 'left' ,text admin a word is cutoff

### What is Expected?

text admin displaying correctly

### What is actually happening?

text admin a word is cutoff

### Additional comments

_(empty)_

Image

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Before:

After:

fix #21638

### CODE REVIEW

File: packages/components/watermark/src/useClips.ts [hunk 1]
```diff
@@ -1,9 +1,20 @@
...
+const TEXT_ALIGN_RATIO_MAP: Record<
+  Required<WatermarkFontType>['textAlign'],
+  number
+> = {
+  left: 0,
+  start: 0,
+  center: 0.5,
+  right: 1,
+  end: 1,
+}
```
Comment (btea) [inline packages/components/watermark/src/useClips.ts]: Could you explain why these are the base numbers? 🤔

Comment (rzzf) [reply packages/components/watermark/src/useClips.ts]: Since `fillText` aligns text relative to the given `x` position, I think x should be set to 0 when `text-align` is `left`, and to `contentWidth` when `text-align` is `right`.

Here’s a visual diagram that helps explain the concept.

image

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/textAlign)

File: packages/components/watermark/src/useClips.ts [hunk 2]
```diff
@@ -1,9 +1,20 @@
...
+
```
Comment (btea) [inline packages/components/watermark/src/useClips.ts:15]:
```suggestion
const TEXT_ALIGN_RATIO_MAP = {
  left: 0,
  start: 0,
  center: 0.5,
  right: 1,
  end: 1,
} as const
```

Comment (rzzf) [reply packages/components/watermark/src/useClips.ts:15]: done

**Comment by btea** [comment]
image

When it comes to multiple lines, it still looks like some content is cut off.

**Review by btea — APPROVED** [review]
LGTM

**Review by warmthsea — APPROVED** [review]
