### PR TITLE
fix(components): ensure table size affects inner selection

### LINKED ISSUE #3629: [bug report] the size attribute of El table does not take effect under specific circumstances
### Element Plus version
1.1.0-beta.16

### OS/Browsers version
macOS Big Sur-11.4    /  Google Chrome-94.0.4606.61

### Vue version
3.2.18

### Reproduction Link
https://codesandbox.io/embed/element-plus-spa-forked-thzs5?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
将 el-table 的size属性设置为 mini,正常情况下是生效的

将 el-table 的size属性设置为 mini,并将某一列的类型设置为 selection 复选框,el-table的 mini 就失效

### What is Expected?
将 el-table 的size属性设置为 mini,不论列的类型设置什,el-table的的size属性不会失效

### What is actually happening?
将 el-table 的size属性设置为 mini,并将某一列的类型设置为 selection 复选框,el-table的大小，就会变成small样式

### PR DESCRIPTION
**Pull request by cokemine**
Please make sure these boxes are checked before submitting your PR, thank you!
fix #3629
- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/table/src/store/watcher.ts [hunk 1]
```diff
@@ -46,6 +46,7 @@ const doFlattenColumns = (columns) => {
 
 function useWatcher<T>() {
   const instance = getCurrentInstance() as Table<T>
+  const { size: tableSize } = toRefs(instance.props)
```
Comment (JeremyWuuuuu) [inline packages/components/table/src/store/watcher.ts:49]: I think we should use `instance.$props` instead of `instance.$proxy.$props`(this one is actually reactive)

Comment (JeremyWuuuuu) [reply packages/components/table/src/store/watcher.ts:49]: cc @cokemine (

Comment (cokemine) [reply packages/components/table/src/store/watcher.ts:49]: It seems that the instance object obtained by getCurrentInstance Hook does not have $props or $proxy properties, we can only get the props through instance.props or instance.ctx(proxy).$props (still reactive)

Comment (JeremyWuuuuu) [reply packages/components/table/src/store/watcher.ts:49]: It was marked as optional because you can define a component without props so that would be accurate. For us we know that there must be this $props object you can use `!.` to bypass the type checking.

Comment (cokemine) [reply packages/components/table/src/store/watcher.ts:49]: But actually it is always `undefined` when I try to output it

Comment (JeremyWuuuuu) [reply packages/components/table/src/store/watcher.ts:49]: that's weird cc @sxzz can you have a look on this? Until we have found the root cause let's stick with your way.

Comment (sxzz) [reply packages/components/table/src/store/watcher.ts:49]: It's `instance.proxy.$props`. /cc @JeremyWuuuuu @cokemine 
image

Comment (sxzz) [reply packages/components/table/src/store/watcher.ts:49]: @cokemine Emmm, we just use instance.proxy.$props
```suggestion
  const { size: tableSize } = toRefs(instance.proxy.$props)
```

Comment (cokemine) [reply packages/components/table/src/store/watcher.ts:49]: What's the different between using `instance.props` and `instance.proxy.$props`.
I only know that `instance.ctx` can be only used in dev mode.
BTW, it seems like `instance.proxy.$props` will may lose types

**Review by jw-foss — APPROVED** [review]

File: packages/components/table/src/store/watcher.ts (hunk 1 above)
Comment (JeremyWuuuuu) [reply packages/components/table/src/store/watcher.ts]: Doesn't matter, since `$props` is defined by Vue so we can simply cast it.

**Comment by JeremyWuuuuu** [comment]
Thank you so much for making Element Plus better! :pray:
