### PR TITLE
fix(components): [input] avoid border flicker while resizing

### LINKED ISSUE #24076: [Component] [input] Border is shaking while resizing
Bug Type: **`Component`**

## Environment

- Vue Version: `3.6.0-beta.3`
- Element Plus Version: `2.13.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbWVzc2FnZSA9IGBMb3JlbSwgaXBzdW0gZG9sb3Igc2l0IGFtZXQgY29uc2VjdGV0dXIgYWRpcGlzaWNpbmcgZWxpdC4gVml0YWUgaW4gaXRhcXVlIGRlbGVjdHVzIG5lc2NpdW50IGxhdWRhbnRpdW0sIHNvbHV0YSBzYXBpZW50ZSBxdWkgYWQgbm9uIHJlcGVsbGF0IGV1bSB0ZW5ldHVyIGV4cGxpY2FibyBhc3BlcmlvcmVzIGVvcyBzdW50IHJlcHVkaWFuZGFlIGlsbHVtIGRvbG9yaWJ1cyBsYWJvcmUuXG4gICAgICAgICAgTG9yZW0sIGlwc3VtIGRvbG9yIHNpdCBhbWV0IGNvbnNlY3RldHVyIGFkaXBpc2ljaW5nIGVsaXQuIFZpdGFlIGluIGl0YXF1ZSBkZWxlY3R1cyBuZXNjaXVudCBsYXVkYW50aXVtLCBzb2x1dGEgc2FwaWVudGUgcXVpIGFkIG5vbiByZXBlbGxhdCBldW0gdGVuZXR1ciBleHBsaWNhYm8gYXNwZXJpb3JlcyBlb3Mgc3VudCByZXB1ZGlhbmRhZSBpbGx1bSBkb2xvcmlidXMgbGFib3JlLmBcbmNvbnN0IG1zZyA9IHJlZihtZXNzYWdlKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEVsRm9ybT5cbiAgICA8RWxGb3JtSXRlbSBjbGFzcz1cInctNDBcIj5cbiAgICAgIDxFbElucHV0IHYtbW9kZWw9XCJtc2dcIiBjbGVhcmFibGUgdHlwZT1cInRleHRhcmVhXCIgOmF1dG9zaXplPVwieyBtaW5Sb3dzOiAxLCBtYXhSb3dzOiA1IH1cIiAvPlxuICAgIDwvRWxGb3JtSXRlbT5cbiAgPC9FbEZvcm0+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

While `type="textarea"` and `autoresize` are both enabled on [input] this bug will show up.

### What is Expected?

The bottom border should be synchronized with pointer.

### What is actually happening?

It's shaking and very unstabled, this behavior will make user uncomfortabled.

### Additional comments

_(empty)_

https://github.com/user-attachments/assets/6cd4ff6d-ed4b-41d3-b45c-e6cf2a967a6c

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #24076

This happens because resizing triggers frequent `mouseenter` and `mouseleave` events as the cursor moves, causing `hovering.value` to change repeatedly. As a result, the clear icon is constantly created and destroyed, leading to layout reflow.

There is no event for detecting textarea resize, so this is a workaround. If there’s a better approach, please let me know.

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved textarea auto-resizing so height is calculated and applied reliably after value changes, and manual/resizable textareas preserve and respect explicit heights when present.

### CODE REVIEW

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -408,7 +410,12 @@ const resizeTextarea = () => {
 const createOnceInitResize = (resizeTextarea: () => void) => {
   let isInit = false
   return () => {
-    if (isInit || !props.autosize) return
+    if (isInit || !props.autosize) {
+      if (props.resize !== 'none') {
+        textareaHeight.value = textarea.value?.style.height
+      }
```
[the remark this answers is not in the document]
Comment (rzzf) [reply packages/components/input/src/input.vue:420]: <del>I think this is expected behavior — autosize only takes effect during initialization, consistent with Element UI.</del>

https://element.eleme.io/#/zh-CN/component/input#ke-zi-gua-ying-wen-ben-gao-du-de-wen-ben-yu

<hr />

This is indeed an issue. When maxRows is not set, the textarea height should update dynamically based on its content.

File: packages/components/input/src/utils.ts [hunk 2]
```diff
@@ -123,6 +124,7 @@ export function calcTextareaHeight(
       maxHeight = maxHeight + paddingSize + borderSize
     }
     height = Math.min(maxHeight, height)
+    result.maxHeight = `${maxHeight}px`
```
Comment (btea) [inline packages/components/input/src/utils.ts]: Is this necessary?

Comment (rzzf) [reply packages/components/input/src/utils.ts]: I think this is necessary; otherwise, it leads to a rather odd behavior: when the textarea is resized beyond `maxRows`, its layout will jump again upon further input. Therefore, introducing `maxHeight` seems reasonable. 
Also, the issue where resizing the textarea smaller has no effect has existed since version 2.7.5.

[repro](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG1lc3NhZ2UgPSBgTG9yZW0sIGlwc3VtIGRvbG9yIHNpdCBhbWV0IGNvbnNlY3RldHVyIGFkaXBpc2ljaW5nIGVsaXQuIFZpdGFlIGluIGl0YXF1ZSBkZWxlY3R1cyBuZXNjaXVudCBsYXVkYW50aXVtLCBzb2x1dGEgc2FwaWVudGUgcXVpIGFkIG5vbiByZXBlbGxhdCBldW0gdGVuZXR1ciBleHBsaWNhYm8gYXNwZXJpb3JlcyBlb3Mgc3VudCByZXB1ZGlhbmRhZSBpbGx1bSBkb2xvcmlidXMgbGFib3JlLlxuICAgICAgICAgIExvcmVtLCBpcHN1bSBkb2xvciBzaXQgYW1ldCBjb25zZWN0ZXR1ciBhZGlwaXNpY2luZyBlbGl0LiBWaXRhZSBpbiBpdGFxdWUgZGVsZWN0dXMgbmVzY2l1bnQgbGF1ZGFudGl1bSwgc29sdXRhIHNhcGllbnRlIHF1aSBhZCBub24gcmVwZWxsYXQgZXVtIHRlbmV0dXIgZXhwbGljYWJvIGFzcGVyaW9yZXMgZW9zIHN1bnQgcmVwdWRpYW5kYWUgaWxsdW0gZG9sb3JpYnVzIGxhYm9yZS5gXG5jb25zdCBtc2cgPSByZWYobWVzc2FnZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxFbElucHV0IHYtbW9kZWw9XCJtc2dcIiB0eXBlPVwidGV4dGFyZWFcIiA6YXV0b3NpemU9XCJ7IG1pblJvd3M6IDEsIG1heFJvd3M6IDUgfVwiIC8+XG4gIDxwPkVsZW1lbnQgUGx1cyBWZXJzaW9uOiB7e3ZlcnNpb259fSAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vdW5wa2cuY29tL2VsZW1lbnQtcGx1c0AyLjcuNS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3VucGtnLmNvbS9lbGVtZW50LXBsdXNAMi43LjUvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vZWxlbWVudC1wbHVzQDIuNy41L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vZWxlbWVudC1wbHVzQDIuNy41L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJlcFZlcnNpb24iOiIyLjcuNSJ9fQ==)


https://github.com/user-attachments/assets/fb0deb85-547d-4553-8326-bc8d56a3bcba

Comment (btea) [reply packages/components/input/src/utils.ts]: Okay, let's go.

**Review by btea — APPROVED** [review]

File: packages/components/input/src/utils.ts (hunk 2 above)
Comment (rzzf) [reply packages/components/input/src/utils.ts]: The issue mentioned [here](https://github.com/element-plus/element-plus/pull/24078#discussion_r3092537091) does indeed exist. As noted in comment, when `modelValue` changes, the textarea height needs to be recalculated and reapplied. In other words, this layout jumping seems unavoidable, so I restored `maxHeight` for now, even though it does look a bit odd.
