### PR TITLE
fix(docs): fix table v2 filter demo style error

### LINKED ISSUE #8845: [Docs] [table-v2] the demo's style is wrong in Virtualized Table > Filter
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114 / macos 12.1`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Docs](https://element-plus.org/en-US/component/table-v2.html#filter)

### Steps to reproduce

1. open the reproduction link
2. click the filter icon in demo

### What is Expected?

no style error

### What is actually happening?

style error

image

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by KimYangOfCat**
fix #8845 
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by btea — APPROVED** [review]

File: docs/examples/table-v2/filter.vue [hunk 1]
```diff
@@ -70,7 +70,7 @@ columns[0].headerCellRenderer = (props: HeaderCellSlotProps) => {
   return (
     <div class="flex items-center justify-center">
       <span class="mr-2 text-xs">{props.column.title}</span>
-      <ElPopover ref={popoverRef} trigger="click">
+      <ElPopover ref={popoverRef} trigger="click" width="180">
```
Comment (ryuhangyeong) [inline docs/examples/table-v2/filter.vue:73]: ## Suggest

```
<ElPopover
  ref={popoverRef}
  trigger="click"
  :width="180" // here
>
```

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgdGl0bGU9XCJUaXRsZVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgIGNvbnRlbnQ9XCI6d2lkdGg9JzIwMCdcIlxuICA+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uPkNsaWNrIHRvIGFjdGl2YXRlPC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wb3BvdmVyPlxuICAgPGVsLXBvcG92ZXJcbiAgICBwbGFjZW1lbnQ9XCJib3R0b21cIlxuICAgIHRpdGxlPVwiVGl0bGVcIlxuICAgIHdpZHRoPVwiMjAwXCJcbiAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgIGNvbnRlbnQ9XCJ3aWR0aD0nMjAwJ1wiXG4gID5cbiAgICA8dGVtcGxhdGUgI3JlZmVyZW5jZT5cbiAgICAgIDxlbC1idXR0b24+Q2xpY2sgdG8gYWN0aXZhdGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

If you look at the example, you can see the difference between `:width` and `width`. It seems that you need to use `:width` to enter the size normally.

Comment (KimYangOfCat) [reply docs/examples/table-v2/filter.vue]: yeah, you are right. I should use v-bind to bind props value for width, but `:width` don't work here becuase of tsx.
so I use `{...{width: 200}}` to replace `:width`.
thanks your suggest!

**Comment by ryuhangyeong** [comment]
Thank you!
