### PR TITLE
fix(components): [select] filter all ElOption item labels

### LINKED ISSUE #11903: [Component] [select] not render when some comment in ElSelect
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.35`
- Browser / OS: `Chrome 110.0.0.0 / mac OS 10.15.7`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG50eXBlIElNZW51VGFyZ2V0ID0ge1xuICBsYWJlbDogc3RyaW5nXG4gIHZhbHVlOiBzdHJpbmdcbn1cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbmNvbnN0IHRhcmdldCA9IHJlZignJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG4gIFxuXHQ8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ0YXJnZXRcIiBwbGFjZWhvbGRlcj1cIuivt+mAieaLqVwiPlxuICAgIDwhLS0gdGVzdCAtLT5cbiAgICA8ZWwtb3B0aW9uIHZhbHVlPVwidmFsdWVcIiBsYWJlbD1cImxhYmVsXCIgLz5cbiAgPC9lbC1zZWxlY3Q+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

```vue
<script setup>
const target = ref('')
</script>

<template>
  <el-select v-model="target" placeholder="请选择">
    <!-- test -->
    <el-option value="value" label="label" />
  </el-select>
</template>
```

### What is Expected?

It works

### What is actually happening?

Not render components, and some Error in Console.
```js
Uncaught (in promise) TypeError: g.filter is not a function
```

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by godxiaoji**
Include children of ElOptionGroup

closed #11903

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/select/src/options.ts [hunk 1]
```diff
@@ -20,22 +20,36 @@ export default defineComponent({
...
+          const name = ((item?.type || {}) as Component)?.name
 
-          if (!isSameOptions(filteredOptions, cachedOptions)) {
-            cachedOptions = filteredOptions
-            emit('update-options', filteredOptions)
+          if (name === 'ElOptionGroup') {
+            filterOptions(
+              !isString(item.children) &&
+                !Array.isArray(item.children) &&
+                typeof item.children?.default === 'function'
```
Comment (jw-foss) [inline packages/components/select/src/options.ts:34]: We actually have a `isFunction` in the utils bundle.

**Review by jw-foss — APPROVED** [review]
LGTM in general, I'll approve this one, left a non-blocking comments for your consideration, let me know if you have any questions
