### PR TITLE
fix(table): #1653

### LINKED ISSUE #1653: [Bug Report] el-table The sorting function causes a table style disorder
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
win10

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/iamkun/ods21k7t/

### Steps to reproduce
So when I click sort, it's going to make my table look a little bit different

### What is Expected?
fix 

### What is actually happening?
So when I click sort, it's going to make my table look a little bit different
t

### PR DESCRIPTION
**Pull request by justwiner**
Fix table can not correctly calculate bug of cell width after sorting or filtering

fix #1653

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/table/src/table-layout.ts [hunk 1]
```diff
@@ -72,12 +72,19 @@ class TableLayout {
...
     const height = this.height.value
+    // 未初始化时为null，table初始化后，未配置height时，height为0
     if (height === null) return false
     const bodyWrapper = this.table.refs.bodyWrapper as HTMLElement
     if (this.table.vnode.el && bodyWrapper) {
-      const body = bodyWrapper.querySelector('.el-table__body') as HTMLElement
+      let scrollY = true
       const prevScrollY = this.scrollY.value
-      const scrollY = body.offsetHeight > this.bodyHeight.value
+      // bodyHeight无值时，表示未设置table高度，永远不会出现滚动条
```
Comment (Ryan2128) [inline packages/table/src/table-layout.ts:81]: Maybe English annotations are better?

**Review by Ryan2128 — CHANGES_REQUESTED** [review]

File: packages/table/src/table-layout.ts (hunk 1 above)
Comment (justwiner) [reply packages/table/src/table-layout.ts]: Done

**Review by jw-foss — APPROVED** [review]

**Review by Ryan2128 — APPROVED** [review]
