### PR TITLE
fix(components): [input] scrollbar not hide after autosize

### LINKED ISSUE #8825: [Component] [input] autosize不能正确得到高度
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG1zZyA9IHJlZign6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOl6bih5ZOlJylcblxuY29uc3Qgc2hvdyA9IHJlZihmYWxzZSlcblxub25Nb3VudGVkKCgpID0+IHtcbiAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgc2hvdy52YWx1ZSA9IHRydWVcbiAgfSwgMjAwMClcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwid2lkdGg6MjAwcHhcIj5cbiAgICA8ZWwtaW5wdXQgYXV0b3NpemUgdHlwZT1cInRleHRhcmVhXCIgdi1tb2RlbD1cIm1zZ1wiIHYtaWY9XCJzaG93XCIgLz5cbiAgPC9kaXY+XG4gIFxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

等着就行了

### What is Expected?

正常autosize

### What is actually happening?

初始化文字超过4行，出现了滚动条，在官网中不存在这个问题是因为官网设置了全局滚动条样式，而在组件库中，只对el-input设置了scrollbar,如果el-textarea也设置，在textarea padding 11px ， scrollbar 6px 的情况下，utils里计算宽度就能拿到正确的宽度。。。，但是现在不对。

::-webkit-scrollbar {
    width: 6px
}

::-webkit-scrollbar:horizontal {
    height: 6px
}

::-webkit-scrollbar-track {
    border-radius: 10px
}

::-webkit-scrollbar-thumb {
    background-color: #0003;
    border-radius: 10px;
    transition: all .2s ease-in-out
}

::-webkit-scrollbar-thumb:hover {
    cursor: pointer;
    background-color: #0000004d
}

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by HeftyKoo**
closed #8825

If the scrollbar is displayed, the height of the textarea needs more space than the calculated height.
If set height in this case, the scrollbar will not hide.
So we need to hide the scrollbar first and reset it in next tick.

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -324,9 +324,21 @@ const resizeTextarea = () => {
...
+    // So we need to hide scrollbar first, and reset it in next tick.
+    // see https://github.com/element-plus/element-plus/issues/8825
     textareaCalcStyle.value = {
-      ...calcTextareaHeight(textarea.value!, minRows, maxRows),
+      overflowY: 'hidden',
+      ...textareaStyle,
     }
+
+    nextTick(() => {
+      textarea.value!.offsetHeight
```
Comment (jw-foss) [inline packages/components/input/src/input.vue:339]: **Question:** may I ask what is the point of this line of code here?

Comment (HeftyKoo) [reply packages/components/input/src/input.vue:339]: > **Question:** may I ask what is the point of this line of code here?

Because component update Effect and nextTick callback function are in the same Microtask Queue, so have to force the browser to repaint.

Here is `nextTick` implement:

```
export function nextTick<T = void>(
  this: T,
  fn?: (this: T) => void
): Promise<void> {
  const p = currentFlushPromise || resolvedPromise
  return fn ? p.then(this ? fn.bind(this) : fn) : p
}

```

It works like:

```
Promise.resolve().then(function () {
  el.setAttribute('style', 'height: 100px; overflow: hidden;')
}).then(function () {
  el.setAttribute('style', 'height: 100px;')
})
```

May be not use `nextTick`，use `setTimeout` is better?

Comment (HeftyKoo) [reply packages/components/input/src/input.vue:339]: I prefer to use force repaint. Because `setTimeout` is async, it may cause some problems in the edge case.

here is force repaint in 6x slower cpu:


here is setTimeout in 6x slower cpu

**Comment by btea** [comment]
The code seems to be conflicting.

**Comment by HeftyKoo** [comment]
> The code seems to be conflicting.

Please take a look again.

File: packages/components/input/src/input.vue [hunk 2]
```diff
@@ -330,9 +330,23 @@ const resizeTextarea = () => {
...
+    const textareaStyle = calcTextareaHeight(textarea.value, minRows, maxRows)
+
+    // If the scrollbar is displayed, the height of the textarea needs more space than the calculated height.
+    // If set textarea height in this case, the scrollbar will not hide.
+    // So we need to hide scrollbar first, and reset it in next tick.
+    // see https://github.com/element-plus/element-plus/issues/8825
     textareaCalcStyle.value = {
       ...calcTextareaHeight(textarea.value, minRows, maxRows),
+      overflowY: 'hidden',
+      ...textareaStyle,
```
Comment (btea) [inline packages/components/input/src/input.vue:342]: Lines 342 and 340 seem to be duplicates?

Comment (HeftyKoo) [reply packages/components/input/src/input.vue:341]: > Lines 342 and 340 seem to be duplicates?

Resolved

**Review by btea — APPROVED** [review]
LGTM
