### PR TITLE
fix(select): fix error position of input and tags

### LINKED ISSUE #1680: [Bug Report] ElSelect prefix wont hide on Focus
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
Manjaro, Firefox 86.0.1 (64-bit)

### Vue version
3.0.5

### Reproduction Link
https://jsfiddle.net/Lscxfhgd/9/

### Steps to reproduce
Just write on the tag input and the text will be on top of the prefix

### What is Expected?
The input text to be aside of the prefix

### What is actually happening?
The input text is on top of the prefix

### LINKED ISSUE #1681: [Bug Report] ElSelect prefix content is blocked by selected tags when add attribute multiple
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
Google Chrome  89.0.4389.90 (official version)   (64-bit)

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/xjxujing/pen/MWJWRwo

### Steps to reproduce
Add ElSelect attribute multiple, and use slot prefix

### What is Expected?
When with attribute multiple, the prefix content will not be blocked.

### What is actually happening?
When multiple choices are available,  it will block prefix content.

### PR DESCRIPTION
**Pull request by Ryan2128**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

Fix #1680  Fix #1681

### CODE REVIEW

**Review by HerringtonDarkholme — APPROVED** [review]

**Comment by Ryan2128** [comment]
Wait a moment, there may be other styles that need to be optimized.

**Comment by Ryan2128** [comment]
@HerringtonDarkholme  Do you think the code marked below should be extracted into the Input component?

image

**Review by HerringtonDarkholme — APPROVED** [review]

File: packages/select/src/select.vue [hunk 1]
```diff
@@ -77,7 +77,7 @@
               :class="[selectSize ? `is-${ selectSize }` : '']"
               :disabled="selectDisabled"
               :autocomplete="autocomplete"
-              :style="{ 'flex-grow': '1', width: inputLength / (inputWidth - 32) + '%', 'max-width': inputWidth - 42 + 'px' }"
+              :style="{ 'margin-left': prefixWidth && !selected.length || tagInMultiLine ? `${prefixWidth}px` : null, 'flex-grow': '1', width: inputLength / (inputWidth - 32) + '%', 'max-width': inputWidth - 42 + 'px' }"
```
Comment (JeremyWuuuuu) [inline packages/select/src/select.vue:80]: Since you have been using string template, why not update `inputWidth - 42 + 'px'` and `inputLength / (inputWidth - 32) + '%'` with the syntax?

File: packages/select/src/select.vue [hunk 2]
```diff
@@ -52,7 +52,7 @@
             </span>
             <!-- <div> -->
             <transition v-if="!collapseTags" @after-leave="resetInputHeight">
-              <span>
+              <span :style="{'margin-left': prefixWidth && selected.length ? `${prefixWidth}px` : null}">
```
Comment (JeremyWuuuuu) [inline packages/select/src/select.vue:55]: I think here we can use `marginLeft` is also an option.

File: packages/select/src/select.vue [hunk 3]
```diff
@@ -366,10 +371,27 @@ export default defineComponent({
...
+          const inputChildNodes = reference.value.$el.childNodes
+          const input = [].filter.call(inputChildNodes, item => item.tagName === 'INPUT')[0]
+          watch(() => ctx.slots.prefix(), () => {
+            nextTick(() => {
+              const prefix = reference.value.$el.querySelector('.el-input__prefix')
+              prefixWidth.value = Math.max(prefix.getBoundingClientRect().width + 5, 30)
+              if(states.prefixWidth){
+                input.style.paddingLeft = `${Math.max(states.prefixWidth, 30)}px`
+              }
+            })
```
Comment (JeremyWuuuuu) [inline packages/select/src/select.vue:384]: I do not think calling `$slot.xxx()` outside render function is a good idea, which could cause `Vue` warning. Can we have some work around on this?

**Review by jw-foss — APPROVED** [review]
