### PR TITLE
fix(table-column): parse width and minWidth

### LINKED ISSUE #1999: [bug report] dynamic modification of table column width results in style change
### Element Plus version
1.0.2-beta.44

### OS/Browsers version
chrome 90

### Vue version
3.1.0-beta.3

### Reproduction Link
https://codepen.io/zhoujiang/pen/yLMeWbx

### Steps to reproduce
初始化列宽度，点击修改宽度按钮， 表格列宽度变无效

### What is Expected?
可以动态修改列宽度

### What is actually happening?
无法动态修改列宽度

### PR DESCRIPTION
**Pull request by BeADre**
fix #1999

### CODE REVIEW

File: packages/table/src/table-column/watcher-helper.ts [hunk 1]
```diff
@@ -24,8 +25,15 @@ function useWatcher<T>(
         watch(
           () => props_[columnKey],
           newVal => {
-            instance.columnConfig.value[columnKey] = newVal
-            instance.columnConfig.value[key] = newVal
+            let value: any = newVal
```
Comment (JeremyWuuuuu) [inline packages/table/src/table-column/watcher-helper.ts:28]: Since both `parseWidth` and `parseMinWidth` returns `number`, we should mark the type here as number I suppose?

Comment (BeADre) [reply packages/table/src/table-column/watcher-helper.ts:28]: 只有进入下面的`if`条件语句之后`value`才一定会是`number`，其他的时候可能为其他类型

Comment (JeremyWuuuuu) [reply packages/table/src/table-column/watcher-helper.ts:28]: Can we specify the type here? 
Say:

```ts
let value: numer | OtherType = newVal
```

Comment (JeremyWuuuuu) [reply packages/table/src/table-column/watcher-helper.ts:28]: If we can't, then I think this is acceptable.

Comment (BeADre) [reply packages/table/src/table-column/watcher-helper.ts]: done

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
Nice!
