### PR TITLE
fix(components): [carousel] reset the timer

### LINKED ISSUE #8383: [Bug Report] [Component] [carousel] Change el-carousel interval attr not work
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Chrome 102.0.5005.115 / Windows 11`
- Build Tool: `Vite`

### Related Component

- `el-carousel`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmludGVydmFsPVwiaW50ZXJ2YWxcIiB0eXBlPVwiY2FyZFwiIGhlaWdodD1cIjIwMHB4XCI+XG4gICAgPGVsLWNhcm91c2VsLWl0ZW0gdi1mb3I9XCJpdGVtIGluIDZcIiA6a2V5PVwiaXRlbVwiPlxuICAgICAgPGgzIHRleHQ9XCIyeGxcIiBqdXN0aWZ5PVwiY2VudGVyXCI+e3sgaXRlbSB9fTwvaDM+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuICA8YnV0dG9uIEBjbGljaz1cImNoYW5nZVwiIHN0eWxlPVwibWFyZ2luLXRvcDogODBweDtcIj5cbiAgICBDaGFuZ2UgaW50ZXJ2YWwgdG8gNTAwMFxuICA8L2J1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbnRlcnZhbCA9IHJlZigxMDAwKVxuXG5jb25zdCBjaGFuZ2UgPSAoKSA9PiB7XG4gIGludGVydmFsLnZhbHVlID0gNTAwMFxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtY2Fyb3VzZWxfX2l0ZW0gaDMge1xuICBjb2xvcjogIzQ3NTY2OTtcbiAgb3BhY2l0eTogMC43NTtcbiAgbGluZS1oZWlnaHQ6IDIwMHB4O1xuICBtYXJnaW46IDA7XG4gIHRleHQtYWxpZ246IGNlbnRlcjtcbn1cblxuLmVsLWNhcm91c2VsX19pdGVtOm50aC1jaGlsZCgybikge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjOTlhOWJmO1xufVxuXG4uZWwtY2Fyb3VzZWxfX2l0ZW06bnRoLWNoaWxkKDJuICsgMSkge1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjZDNkY2U2O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click [Change interval to 5000] button

### What is Expected?

carousel interval change to 5000ms 

### What is actually happening?

still default 1000ms

### Additional comments

_(empty)_

### LINKED ISSUE #9056: [Component] [carousel, carousel-item] el-carousel设置interval失效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `Chrom 103.0.5060.114`
- Build Tool: `Vite`

### Related Component

- `el-carousel`
- `el-carousel-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

默认interval是3秒更改成1秒，还是3秒的自动切换的时间间隔

### What is Expected?

1秒自动切换的时间间隔

### What is actually happening?

3秒自动切换的时间间隔

### Additional comments

 #9022版本没修改好 https://github.com/element-plus/element-plus/issues/9021

### PR DESCRIPTION
**Pull request by Chuck-Lau**
closed #8383, closed #9056 
 
- fix: reset the timer when setActiveItem method is called
- fix: reset the timer when changed interval

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
Thank you for your contribution! I'm sorry, I didn't notice this pr before, I will close the pr I created.

File: packages/components/carousel/src/carousel.vue [hunk 1]
```diff
@@ -300,6 +305,13 @@ watch(
   }
 )
 
+watch(
+  () => props.interval,
+  () => {
+    resetTimer()
```
Comment (btea) [inline packages/components/carousel/src/carousel.vue:311]: Maybe you can call `pasueTimer` and `startTimer` directly without creating the `resetTimer` function

```suggestion
    pauseTimer()
    startTimer()
```

**Comment by zxtux** [comment]
> 关闭 [#8383 ](https://github.com/element-plus/element-plus/issues/8383) #9056
> 
> * 修复：调用 setActiveItem 方法时重置计时器
> * 修复：更改间隔时重置计时器
> 
> 请确保在提交 PR 之前选中这些框，谢谢！
> 
> * [x] 确保您遵循贡献[指南 ](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md)([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md)| [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md) )。
> * [x] 确保将提交合并到`dev`分支。
> * [x] 添加一些描述并参考您的 PR 的相关问题。

setActiveItem  怎么用

File: packages/components/carousel/src/carousel.vue (hunk 1 above)
Comment (Tsong-LC) [reply packages/components/carousel/src/carousel.vue:311]: Hi, I think the timer needs to be reset when calling the `setActiveItem` method too. What do you think about calling `pauseTimer` and `startTimer`?

Comment (btea) [reply packages/components/carousel/src/carousel.vue:311]: You are right 👍

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]
