### PR TITLE
fix(components): [table] fixed hover on colSpan > 2 background is error

### LINKED ISSUE #16439: [Style] [table] el-table合并某行所有列后hover高亮问题
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.6.3`
- Browser / OS: `Chrome 123.0.6312.59`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdGFibGUvc3JjL3RhYmxlLWNvbHVtbi9kZWZhdWx0cydcbmludGVyZmFjZSBVc2VyIHtcbiAgICBpZDogc3RyaW5nXG4gICAgbmFtZTogc3RyaW5nXG4gICAgYW1vdW50MTogc3RyaW5nXG4gICAgYW1vdW50Mjogc3RyaW5nXG4gICAgYW1vdW50MzogbnVtYmVyXG4gICAgbWFyZ2U6IG51bWJlcltdXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICAgIHJvdzogVXNlclxuICAgIGNvbHVtbjogVGFibGVDb2x1bW5DdHg8VXNlcj5cbiAgICByb3dJbmRleDogbnVtYmVyXG4gICAgY29sdW1uSW5kZXg6IG51bWJlclxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAgICB7XG4gICAgICAgIGlkOiAnMTI5ODcxMjInLFxuICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgYW1vdW50MTogJzIzNCcsXG4gICAgICAgIGFtb3VudDI6ICczLjInLFxuICAgICAgICBhbW91bnQzOiAxMCxcbiAgICAgICAgbWFyZ2U6IFsxLCAxXVxuICAgIH0sXG4gICAge1xuICAgICAgICBpZDogJzEyOTg3MTIzJyxcbiAgICAgICAgbmFtZTogJ1RvbScsXG4gICAgICAgIGFtb3VudDE6ICcxNjUnLFxuICAgICAgICBhbW91bnQyOiAnNC40MycsXG4gICAgICAgIGFtb3VudDM6IDEyLFxuICAgICAgICBtYXJnZTogWzEsIDFdXG4gICAgfSxcbiAgICB7XG4gICAgICAgIGlkOiAnMTI5ODcxMjQnLFxuICAgICAgICBuYW1lOiAnVG9tJyxcbiAgICAgICAgYW1vdW50MTogJzMyNCcsXG4gICAgICAgIGFtb3VudDI6ICcxLjknLFxuICAgICAgICBhbW91bnQzOiA5LFxuICAgICAgICBtYXJnZTogWzEsIDFdXG4gICAgfVxuXVxuICBjb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHsgcm93LCBjb2x1bW4sIHJvd0luZGV4LCBjb2x1bW5JbmRleCB9OiBTcGFuTWV0aG9kUHJvcHMpID0+IHtcbiAgICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICAgICAgaWYgKHJvd0luZGV4ID09PSAyKSB7XG4gICAgICAgICAgICByZXR1cm4gWzEsIDVdXG4gICAgICAgIH0gZWxzZSB7XG4gICAgICAgICAgICByZXR1cm4gWzEsIDFdXG4gICAgICAgIH1cbiAgICB9IGVsc2Uge1xuICAgICAgICBpZiAocm93SW5kZXggPT09IDIpIHtcbiAgICAgICAgICAgIHJldHVybiBbMCwgMF1cbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIHJldHVybiBbMSwgMV1cbiAgICAgICAgfVxuICAgIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gICAgICAgIDxlbC10YWJsZVxuICAgICAgICAgICAgYm9yZGVyXG4gICAgICAgICAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgICAgICAgICA6c3Bhbi1tZXRob2Q9XCJvYmplY3RTcGFuTWV0aG9kXCJcbiAgICAgICAgICAgIDpoZWFkZXItcm93LXN0eWxlPVwieyBjb2xvcjogJ3JnYmEoMCwgMCwgMCwgMC44NSknIH1cIlxuICAgICAgICAgICAgOmhlYWRlci1jZWxsLXN0eWxlPVwieyAnYmFja2dyb3VuZC1jb2xvcic6ICdyZ2JhKDAsIDAsIDAsIDAuMDIpJywgcGFkZGluZzogJzE1cHggMCcgfVwiXG4gICAgICAgICAgICA6Y2VsbC1zdHlsZT1cInsgcGFkZGluZzogJzE1cHggMCcgfVwiXG4gICAgICAgID5cbiAgICAgICAgICAgXG4gICAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgICAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICAgICAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

span-method将某一行的全部列合并

### What is Expected?

鼠标悬浮到合并的行时，应该只高亮本行

### What is actually happening?

本行高亮的同时上一行的也亮了

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Liao-js**
fix https://github.com/element-plus/element-plus/issues/16439

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by dowinweb** [comment]
> @dowinweb Can you help review this PR?

OK， sorry cause a problem， i will fix this asap

**Comment by Liao-js** [comment]
@dowinweb 
```
const indexes = Array.from(childNodes).reduce((acc, item, index) => {
  // drop colsSpan
  const pre = childNodes[index - 1]?.colSpan > 1
  const next = childNodes[index + 1]?.colSpan > 1
  if (item.nodeName !== 'TD' && !pre && !next) {
    acc.push(index)
  }
  return acc
}, [])
```

There's something wrong with this method's boundary judgment， can you see this demo  [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdGFibGUvc3JjL3RhYmxlLWNvbHVtbi9kZWZhdWx0cydcbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbiAgbWFyZ2U6IG51bWJlcltdXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBpZDogJzEyOTg3MTIyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMjM0JyxcbiAgICBhbW91bnQyOiAnMy4yJyxcbiAgICBhbW91bnQzOiAxMCxcbiAgICBtYXJnZTogWzEsIDFdXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gICAgbWFyZ2U6IFsxLCAxXVxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzMyNCcsXG4gICAgYW1vdW50MjogJzEuOScsXG4gICAgYW1vdW50MzogOSxcbiAgICBtYXJnZTogWzEsIDFdXG4gIH1cbl1cblxuY29uc3Qgb2JqZWN0U3Bhbk1ldGhvZCA9ICh7IHJvdywgY29sdW1uLCByb3dJbmRleCwgY29sdW1uSW5kZXggfTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChbMSwgMl0uaW5jbHVkZXMoY29sdW1uSW5kZXgpKSB7XG4gICAgaWYgKHJvd0luZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSBpZiAocm93SW5kZXggPT09IDEpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG5cbiAgaWYgKFsxXS5pbmNsdWRlcyhyb3dJbmRleCkpIHtcbiAgICBpZiAoWzNdLmluY2x1ZGVzKGNvbHVtbkluZGV4KSkge1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgcm93c3BhbjogMSxcbiAgICAgICAgY29sc3BhbjogMixcbiAgICAgIH1cbiAgICB9IGVsc2UgaWYgKFs0XS5pbmNsdWRlcyhjb2x1bW5JbmRleCkpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgYm9yZGVyIDpkYXRhPVwidGFibGVEYXRhXCIgOnNwYW4tbWV0aG9kPVwib2JqZWN0U3Bhbk1ldGhvZFwiIDpoZWFkZXItcm93LXN0eWxlPVwieyBjb2xvcjogJ3JnYmEoMCwgMCwgMCwgMC44NSknIH1cIlxuICAgIDpoZWFkZXItY2VsbC1zdHlsZT1cInsgJ2JhY2tncm91bmQtY29sb3InOiAncmdiYSgwLCAwLCAwLCAwLjAyKScsIHBhZGRpbmc6ICcxNXB4IDAnIH1cIlxuICAgIDpjZWxsLXN0eWxlPVwieyBwYWRkaW5nOiAnMTVweCAwJyB9XCI+XG5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPiIsInNyYy9QbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTY0NDMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2VsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xNjQ0My1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTY0NDMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTY0NDMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

**Comment by Liao-js** [comment]
Is it possible to record **prev. colSpan** and then determine the number of **nodeName ! == 'TD'**

**Comment by dowinweb** [comment]
> Is it possible to record **prev. colSpan** and then determine the number of **nodeName ! == 'TD'**

@Liao-js i test your case ， it seams have this problem

**Comment by dowinweb** [comment]
> Is it possible to record **prev. colSpan** and then determine the number of **nodeName ! == 'TD'**
@Liao-js it seems have this problem
image

**Comment by dowinweb** [comment]
@Liao-js  you can test these situations and try fixed your code

> Is it possible to record **prev. colSpan** and then determine the number of **nodeName ! == 'TD'**

we dont need to record, we can try to control when colspan > 1 didnt push the indexes, you can have a try 
@Liao-js

**Comment by Liao-js** [comment]
> > Is it possible to record **prev. colSpan** and then determine the number of **nodeName ! == 'TD'**
> 
> we dont need to record, we can try to control when colspan > 1 didnt push the indexes, you can have a try @Liao-js

I see you pr，there's still something wrong with your method ,can you see this demo [Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdGFibGUvc3JjL3RhYmxlLWNvbHVtbi9kZWZhdWx0cydcbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbiAgbWFyZ2U6IG51bWJlcltdXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBpZDogJzEyOTg3MTIyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMjM0JyxcbiAgICBhbW91bnQyOiAnMy4yJyxcbiAgICBhbW91bnQzOiAxMCxcbiAgICBtYXJnZTogWzEsIDFdLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI1JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG5dXG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChbMiwgM10uaW5jbHVkZXMoY29sdW1uSW5kZXgpKSB7XG4gICAgaWYgKHJvd0luZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSBpZiAocm93SW5kZXggPT09IDEpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG5cbiAgaWYgKFsxXS5pbmNsdWRlcyhyb3dJbmRleCkpIHtcbiAgICBpZiAoWzBdLmluY2x1ZGVzKGNvbHVtbkluZGV4KSkge1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgcm93c3BhbjogMSxcbiAgICAgICAgY29sc3BhbjogMixcbiAgICAgIH1cbiAgICB9IGVsc2UgaWYgKFsxXS5pbmNsdWRlcyhjb2x1bW5JbmRleCkpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICBib3JkZXJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgOnNwYW4tbWV0aG9kPVwib2JqZWN0U3Bhbk1ldGhvZFwiXG4gICAgOmhlYWRlci1yb3ctc3R5bGU9XCJ7IGNvbG9yOiAncmdiYSgwLCAwLCAwLCAwLjg1KScgfVwiXG4gICAgOmhlYWRlci1jZWxsLXN0eWxlPVwie1xuICAgICAgJ2JhY2tncm91bmQtY29sb3InOiAncmdiYSgwLCAwLCAwLCAwLjAyKScsXG4gICAgICBwYWRkaW5nOiAnMTVweCAwJyxcbiAgICB9XCJcbiAgICA6Y2VsbC1zdHlsZT1cInsgcGFkZGluZzogJzE1cHggMCcgfVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE2NDc0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsKHN0eWxlcylcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

**Comment by Liao-js** [comment]
I think that's right.
```
let control = 0
const indexes = Array.from(childNodes).reduce((acc, item, index) => {
  // drop colsSpan
  if (childNodes[index]?.colSpan > 1) {
    control = childNodes[index]?.colSpan - 1
  } else {
    control--
  }
  if (item.nodeName !== 'TD' && control == 0) {
    acc.push(index)
  }
  return acc
}, [])
```

**Review by dowinweb — COMMENTED** [review]
you are right @Liao-js  LGTM

**Comment by btea** [comment]
Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js

**Comment by Liao-js** [comment]
> Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js

It's done.

File: packages/components/table/src/table-body/index.ts [hunk 1]
```diff
@@ -39,13 +39,16 @@ export default defineComponent({
...
+        let control = 0
         const indexes = Array.from(childNodes).reduce((acc, item, index) => {
           // drop colsSpan
-          const pre = childNodes[index - 1]?.colSpan > 1
-          const next = childNodes[index + 1]?.colSpan > 1
-          if (item.nodeName !== 'TD' && !pre && !next) {
+          if (childNodes[index]?.colSpan > 1) {
+            control = childNodes[index]?.colSpan
+          }
+          if (item.nodeName !== 'TD' && control == 0) {
```
Comment (btea) [inline packages/components/table/src/table-body/index.ts:48]:
```suggestion
          if (item.nodeName !== 'TD' && control === 0) {
```
Perhaps it would be better to use strict equality.

**Comment by dowinweb** [comment]
> > Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js
> 
> It's done.

preChildNodes[rowIndex].rowSpan > 1
this is for what situation, i didnot test this
@Liao-js

**Comment by Liao-js** [comment]
> > > Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js
> > 
> > 
> > It's done.
> 
> preChildNodes[rowIndex].rowSpan > 1 this is for what situation, i didnot test this @Liao-js

[demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdGFibGUvc3JjL3RhYmxlLWNvbHVtbi9kZWZhdWx0cydcbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbiAgbWFyZ2U6IG51bWJlcltdXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgdGFibGVEYXRhOiBVc2VyW10gPSBbXG4gIHtcbiAgICBpZDogJzEyOTg3MTIyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMjM0JyxcbiAgICBhbW91bnQyOiAnMy4yJyxcbiAgICBhbW91bnQzOiAxMCxcbiAgICBtYXJnZTogWzEsIDFdLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI1JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICAgIG1hcmdlOiBbMSwgMV0sXG4gIH0sXG5dXG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChbMiwgM10uaW5jbHVkZXMoY29sdW1uSW5kZXgpKSB7XG4gICAgaWYgKHJvd0luZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSBpZiAocm93SW5kZXggPT09IDEpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG5cbiAgaWYgKFsxXS5pbmNsdWRlcyhyb3dJbmRleCkpIHtcbiAgICBpZiAoWzFdLmluY2x1ZGVzKGNvbHVtbkluZGV4KSkge1xuICAgICAgcmV0dXJuIHtcbiAgICAgICAgcm93c3BhbjogMSxcbiAgICAgICAgY29sc3BhbjogMixcbiAgICAgIH1cbiAgICB9IGVsc2UgaWYgKFswXS5pbmNsdWRlcyhjb2x1bW5JbmRleCkpIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtdGFibGVcbiAgICBib3JkZXJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgOnNwYW4tbWV0aG9kPVwib2JqZWN0U3Bhbk1ldGhvZFwiXG4gICAgOmhlYWRlci1yb3ctc3R5bGU9XCJ7IGNvbG9yOiAncmdiYSgwLCAwLCAwLCAwLjg1KScgfVwiXG4gICAgOmhlYWRlci1jZWxsLXN0eWxlPVwie1xuICAgICAgJ2JhY2tncm91bmQtY29sb3InOiAncmdiYSgwLCAwLCAwLCAwLjAyKScsXG4gICAgICBwYWRkaW5nOiAnMTVweCAwJyxcbiAgICB9XCJcbiAgICA6Y2VsbC1zdHlsZT1cInsgcGFkZGluZzogJzE1cHggMCcgfVwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhbW91bnQzXCIgbGFiZWw9XCJBbW91bnQgM1wiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE2NDc0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsKHN0eWxlcylcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNjQ3NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

> > > Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js
> > 
> > 
> > It's done.
> 
> preChildNodes[rowIndex].rowSpan > 1 this is for what situation, i didnot test this @Liao-js

I think it's more rigorous.

**Comment by Liao-js** [comment]
> > > Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js
> > 
> > 
> > It's done.
> 
> preChildNodes[rowIndex].rowSpan > 1 this is for what situation, i didnot test this @Liao-js

I think it's more rigorous.

**Comment by dowinweb** [comment]
> > > > Can you roll back what you just did? No changes are required when there are no conflicts with the dev branch. @Liao-js
> > > 
> > > 
> > > It's done.
> > 
> > 
> > preChildNodes[rowIndex].rowSpan > 1 this is for what situation, i didnot test this @Liao-js
> 
> I think it's more rigorous.

OK, it works fine. LGTM @btea

**Review by btea — APPROVED** [review]
@Liao-js @dowinweb Thanks!

**Review by kooriookami — APPROVED** [review]
LGTM
