### PR TITLE
fix(components): [table-v2] keep scrollToRow from changing horiz offset

### LINKED ISSUE #22928: [Component] [table-v2] Virtualized Table 虚拟化表格  scrollToRow滚动到指定行，会滚动水平位置
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.18`
- Element Plus Version: `2.11.8`
- Browser / OS: `Chrome 142.0.7444.176`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB0eXBlIHsgVGFibGVWMkluc3RhbmNlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5cbmNvbnN0IHRhYmxlUmVmID0gcmVmPFRhYmxlVjJJbnN0YW5jZSB8IG51bGw+KG51bGwpXG5cbmNvbnN0IGNvbHVtbnMgPSByZWYoW1xuICB7XG4gICAga2V5OiAnUHJvZElkJyxcbiAgICB0aXRsZTogJ+WVhuWTgUlkJyxcbiAgICBkYXRhS2V5OiAnUHJvZElkJyxcbiAgICB3aWR0aDogNDAwLFxuICAgIG1pbldpZHRoOiA5MCxcbiAgfSxcbiAge1xuICAgIGtleTogJ1Byb2ROYW1lJyxcbiAgICB0aXRsZTogJ+WVhuWTgeWQjeensCcsXG4gICAgZGF0YUtleTogJ1Byb2ROYW1lJyxcbiAgICB3aWR0aDogNDAwLFxuICAgIG1pbldpZHRoOiA5MCxcbiAgfSxcbl0pXG5jb25zdCB0YWJsZURhdGEgPSByZWY8YW55W10+KFtcbiAgICB7IFByb2RJZDogMzQsIFByb2ROYW1lOiAn54mb5aW2JyB9LFxuICAgIHsgUHJvZElkOiA1NiwgUHJvZE5hbWU6ICfpnaLljIUnIH0sXG4gICAgeyBQcm9kSWQ6IDc4LCBQcm9kTmFtZTogJ+m4oeibiycgfSxcbiAgICB7IFByb2RJZDogOTAsIFByb2ROYW1lOiAn6Iu55p6cJyB9LFxuICAgIHsgUHJvZElkOiAxMjMsIFByb2ROYW1lOiAn6YW45aW2JyB9LFxuICAgIHsgUHJvZElkOiAxMywgUHJvZE5hbWU6ICfljIXlrZAnIH0sXG5dKVxuXG5jb25zdCBoYW5kbGVTY3JvbGwgPSAocm93SW5kZXg6IG51bWJlcikgPT4ge1xuICB0YWJsZVJlZi52YWx1ZS5zY3JvbGxUb1Jvdyg1KVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlLXYyXG4gICAgcmVmPVwidGFibGVSZWZcIlxuICAgIGZpeGVkXG4gICAgOmNvbHVtbnM9XCJjb2x1bW5zXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgOndpZHRoPVwiNTAwXCJcbiAgICA6aGVpZ2h0PVwiMjAwXCJcbiAgICA6cm93LWhlaWdodD1cIjQ0XCJcbiAgICA6aGVhZGVyLWhlaWdodD1cIjQ0XCJcbiAgICBzdHlsZT1cImJvcmRlcjogMXB4IHNvbGlkIHJlZFwiXG4gID5cbiAgPC9lbC10YWJsZS12Mj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJoYW5kbGVTY3JvbGwoNSlcIj7mu5rliqjliLDnrKzkupTooYw8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击滚动按钮进行滚动

### What is Expected?

垂直位置滚动到该行，水平位置不变

### What is actually happening?

垂直位置滚动到该行，水平位置也滚动了最后

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by yicheny**
closed #22928

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

## Summary by CodeRabbit

* **Bug Fixes**
  * Preserves horizontal scroll position when jumping to a row and avoids errors if the grid body is unavailable.

* **Tests**
  * Added a test verifying horizontal scroll remains unchanged when mixing horizontal scrolling with row-based scrolling.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/components/table-v2/src/table-grid.tsx [hunk 1]
```diff
@@ -114,7 +114,16 @@ const useTableGrid = (props: TableV2GridProps) => {
...
+    const body = unref(bodyRef)
+    if (!body) return
+
+    const prevScrollLeft = scrollLeft.value
+
+    body.scrollToItem(row, 1, strategy)
+
+    scrollTo({
+      scrollLeft: prevScrollLeft,
+    })
```
Comment (Dsaquel) [inline packages/components/table-v2/src/table-grid.tsx]: I'm thinking of a solution where `columnIndex` can be approximately known in advance. With `props.bodyWith` and `props.columns` it can probably work 🤔 .

File: packages/components/table-v2/src/table-grid.tsx [hunk 2]
```diff
@@ -114,7 +114,16 @@ const useTableGrid = (props: TableV2GridProps) => {
   }
 
   function scrollToRow(row: number, strategy: ScrollStrategy) {
-    unref(bodyRef)?.scrollToItem(row, 1, strategy)
+    const body = unref(bodyRef)
+    if (!body) return
+
+    const prevScrollLeft = scrollLeft.value
+
+    body.scrollToItem(row, 1, strategy)
```
Comment (YunYouJun) [inline packages/components/table-v2/src/table-grid.tsx]: Maybe we should use `0` for second param?

cc @jw-foss

File: packages/components/table-v2/src/table-grid.tsx [hunk 3]
```diff
@@ -114,7 +114,16 @@ const useTableGrid = (props: TableV2GridProps) => {
...
+
+    scrollTo({
```
Comment (YunYouJun) [inline packages/components/table-v2/src/table-grid.tsx]:
```suggestion
  body.scrollToItem(row, 0, strategy)
  if (scrollLeft.value) {
    scrollTo({ scrollLeft: scrollLeft.value })
  }
```

**Review by YunYouJun — CHANGES_REQUESTED** [review]

**Review by YunYouJun — APPROVED** [review]
