### PR TITLE
fix(components): [input-number] Fix value decimals miss prop precision

### LINKED ISSUE #8570: [Component] [input-number] 数字精度问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: ` Chrome 102.0.5005.63 / Windows10`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBudW0gPSByZWYoMClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuICBcbiAgPGVsLWlucHV0LW51bWJlclxuICAgICAgICAgICAgICAgIDptaW49XCIwXCJcbiAgICAgICAgICAgICAgICA6bWF4PVwiMTAwXCJcbiAgICAgICAgICAgICAgICBjb250cm9scy1wb3NpdGlvbj1cInJpZ2h0XCJcbiAgICAgICAgICAgICAgICB2LW1vZGVsPVwibnVtXCJcbiAgICAgICAgICAgICAgICA6c3RlcD1cIjAuMVwiXG4gICAgICAgICAgICAgICAgc3RlcC1zdHJpY3RseVxuICAgICAgICAgICAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.设置step为0.1
2.设置step-strictly
3.输入0.3

### What is Expected?

输出值为0.3

### What is actually happening?

输出值为0.30000000000000004

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by so11y**
input-number components modelValue is decimals and  stepStrictly miss prop precision if 0.2 to 0.3 result 0.300004
fix:stepStrictly verifyValue function miss use toPrecision 
close #8570 

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/input-number/src/input-number.vue [hunk 1]
```diff
@@ -201,7 +201,10 @@ const verifyValue = (
     newVal = isString(valueOnClear) ? { min, max }[valueOnClear] : valueOnClear
   }
   if (stepStrictly) {
-    newVal = Math.round(newVal / step) * step
+    newVal = toPrecision(
+      Math.round(newVal / step) * step,
+      precision || numPrecision.value
+    )
```
Comment (btea) [inline packages/components/input-number/src/input-number.vue:207]:
```suggestion
    newVal = toPrecision(Math.round(newVal / step) * step, precision)
```

Comment (so11y) [reply packages/components/input-number/src/input-number.vue:207]: ok toPrecision pre if null，default use  numPrecision.value，nice

Comment (so11y) [reply packages/components/input-number/src/input-number.vue]: code change

File: packages/components/input-number/__tests__/input-number.test.tsx [hunk 2]
```diff
@@ -94,6 +94,20 @@ describe('InputNumber.vue', () => {
     expect(wrapper.find('input').element.value).toEqual('4')
   })
 
+  test('value decimals miss prop precision', async () => {
+    const num = ref(0.2)
+    const wrapper = mount(() => <InputNumber step={0.1} v-model={num.value} />)
+    const elInputNumber = wrapper.findComponent({ name: 'ElInputNumber' }).vm
```
Comment (ryuhangyeong) [inline packages/components/input-number/__tests__/input-number.test.tsx:100]: ## Suggest

```ts
const elInputNumber = wrapper.findComponent(InputNumber).vm
```

I think this could be a little more concise!

Comment (so11y) [reply packages/components/input-number/__tests__/input-number.test.tsx:100]: ok soga

**Comment by btea** [comment]
Unit tests seem to fail

**Comment by ryuhangyeong** [comment]
Sorry. I hadn't thought about the TypeScript type checker error.

**Comment by so11y** [comment]
> 
why use 

> 单元测试似乎失败了

why code 
``` javascript
const elInputNumber = wrapper.findComponent(InputNumber).vm  
```
typecheck report increase exist  
``` javascript
 const elInputNumber = wrapper.findComponent(InputNumber).vm 
```
bat code ok

**Review by btea — APPROVED** [review]

**Review by chenxch — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
@so11y

Sorry for the confusion!

**Comment by so11y** [comment]
@ryuhangyeong

no sry, smile, the question is solved

> @so11y
> 
> Sorry for the confusion!

no sry, smile, the question is solved
