### PR TITLE
fix(components): [dialog] fix dialog zindex should update responsively

### LINKED ISSUE #16329: [Component] [dialog] dialog zIndex动态修改的情况下无效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.20`
- Element Plus Version: `2.6.3`
- Browser / OS: `edge win10`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uLHVzZVpJbmRleCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCB7IG5leHRaSW5kZXggfSA9IHVzZVpJbmRleCgpO1xuY29uc3QgekluZGV4MSA9IHJlZihuZXh0WkluZGV4KCkpO1xuY29uc3QgekluZGV4MiA9IHJlZihuZXh0WkluZGV4KCkpO1xuY29uc3QgZGlhbG9nMVNob3cgPXJlZihmYWxzZSlcbmNvbnN0IGRpYWxvZzJTaG93ID1yZWYoZmFsc2UpXG5mdW5jdGlvbiBoYW5kbGVTaG93RGlhbG9nMSgpe1xuICBkaWFsb2cxU2hvdy52YWx1ZT10cnVlXG59XG5mdW5jdGlvbiBoYW5kbGVTaG93RGlhbG9nMigpe1xuICBkaWFsb2cyU2hvdy52YWx1ZT10cnVlXG59XG5cbmZ1bmN0aW9uIGhhbmRsZUNsaWNrMSgpe1xuICB6SW5kZXgxLnZhbHVlPW5leHRaSW5kZXgoKVxufVxuXG5mdW5jdGlvbiBoYW5kbGVDbGljazIoKXtcbiAgIHpJbmRleDIudmFsdWU9bmV4dFpJbmRleCgpXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuIDxlbC1kaWFsb2dcbiAgICB2LW1vZGVsPVwiZGlhbG9nMVNob3dcIlxuICAgIDptb2RhbD1cImZhbHNlXCJcbiAgICB0aXRsZT1cIua1i+ivlVwiXG4gICAgOmNsb3NlLW9uLWNsaWNrLW1vZGFsPVwiZmFsc2VcIlxuICAgIDpsb2NrLXNjcm9sbD1cInRydWVcIlxuICAgIDphcHBlbmQtdG8tYm9keT1cInRydWVcIlxuICAgIG1vZGFsLWNsYXNzPVwicGVuZXRyYXRlX2RpYWxvZ1wiXG4gICAgY2xhc3M9XCJ0dF9kaWFsb2dcIlxuICAgIGRyYWdnYWJsZVxuICAgIDpzaG93LWNsb3NlPVwidHJ1ZVwiXG4gICAgOndpZHRoPVwiJ21heC1jb250ZW50J1wiXG4gICAgQGNsaWNrPVwiaGFuZGxlQ2xpY2sxXCJcbiAgICA6ei1pbmRleD1cInpJbmRleDFcIlxuICA+XG4gICAgPGRpdiBjbGFzcz1cImNvbnRlbnRcIj5cbiAgICAgIOW8ueahhjHlhoXlrrk8YnIvPlxuICAgICAg5b2T54K55Ye75by55qGGMeeahOaXtuWAme+8jOW8ueahhjHlpITkuo7pobbnq69cbiAgICA8L2Rpdj5cbiAgPC9lbC1kaWFsb2c+XG4gICA8ZWwtZGlhbG9nXG4gICAgdi1tb2RlbD1cImRpYWxvZzJTaG93XCJcbiAgICA6bW9kYWw9XCJmYWxzZVwiXG4gICAgdGl0bGU9XCLmtYvor5VcIlxuICAgIDpjbG9zZS1vbi1jbGljay1tb2RhbD1cImZhbHNlXCJcbiAgICA6bG9jay1zY3JvbGw9XCJ0cnVlXCJcbiAgICA6YXBwZW5kLXRvLWJvZHk9XCJ0cnVlXCJcbiAgICBtb2RhbC1jbGFzcz1cInBlbmV0cmF0ZV9kaWFsb2dcIlxuICAgIGNsYXNzPVwidHRfZGlhbG9nXCJcbiAgICBkcmFnZ2FibGVcbiAgICA6c2hvdy1jbG9zZT1cInRydWVcIlxuICAgIDp3aWR0aD1cIidtYXgtY29udGVudCdcIlxuICAgIEBjbGljaz1cImhhbmRsZUNsaWNrMlwiXG4gICAgOnotaW5kZXg9XCJ6SW5kZXgyXCJcbiAgPlxuICAgIDxkaXYgY2xhc3M9XCJjb250ZW50XCI+XG4gICAgICDlvLnmoYYy5YaF5a65PGJyLz5cbiAgICAgIOW9k+eCueWHu+W8ueahhjLnmoTml7blgJnvvIzlvLnmoYYy5aSE5LqO6aG256uvXG4gICAgPC9kaXY+XG4gIDwvZWwtZGlhbG9nPlxuICA8RWxCdXR0b24gQGNsaWNrPVwiaGFuZGxlU2hvd0RpYWxvZzEoKVwiPuaYvuekumRpYWxvZzE8L0VsQnV0dG9uPlxuICA8RWxCdXR0b24gQGNsaWNrPVwiaGFuZGxlU2hvd0RpYWxvZzIoKVwiPuaYvuekumRpYWxvZzI8L0VsQnV0dG9uPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbi5wZW5ldHJhdGVfZGlhbG9nIHtcbiAgcG9pbnRlci1ldmVudHM6IG5vbmU7XG59XG4ucGVuZXRyYXRlX2RpYWxvZyAuZWwtb3ZlcmxheS1kaWFsb2d7XG4gIHBvaW50ZXItZXZlbnRzOiBub25lO1xufVxuLnBlbmV0cmF0ZV9kaWFsb2cgLmVsLW92ZXJsYXktZGlhbG9nIC5lbC1kaWFsb2d7XG4gIHBvaW50ZXItZXZlbnRzOiBhdXRvO1xufVxuLmNvbnRlbnR7XG4gIHdpZHRoOiAzMDBweDtcbiAgaGVpZ2h0OiAzMDBweDtcbn1cbjwvc3R5bGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

我现在界面上有多个弹框，每个弹框可以拖动，且当点击弹框的时候，此弹框要处于界面顶端

### What is Expected?

处于顶端

### What is actually happening?

弹框的zindex修改成功，但是zindex不是相应式的，真是的zindex并未发生改变，导致未处于顶端

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by wsVIC**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Description
fixes #16329 

现在dialog的zIndex可以随参数响应式更新

1. 用户显式给出非空值zIndex参数时，永远以用户给出值的为准。
2. 用户未给出zIndex参数或zIndex为空值时，fallback到默认zIndex分配逻辑，包括再次打开dialog时分配新zIndex值。
3. 用户将zIndex值从非空转为空值时，这可以理解为用户放弃了对dialog的zIndex的控制，此时应当可以取任何合理值，我的做法是直接使用nextZIndex分配一个值。

### CODE REVIEW

**Comment by wsVIC** [comment]
I'd appreciate it if anyone could review this PR, thanks.

**Comment by wsVIC** [comment]
[example](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IG9uTW91bnRlZCwgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24sIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24sIHVzZVpJbmRleCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCB7IG5leHRaSW5kZXggfSA9IHVzZVpJbmRleCgpXG5cbnR5cGUgRGlhbG9nSW5mbyA9IHtcbiAgekluZGV4PzogbnVtYmVyXG4gIGRpYWxvZ1Nob3c6IGJvb2xlYW5cbiAgYWN0dWFsWkluZGV4Pzogc3RyaW5nXG4gIGlkOiBudW1iZXJcbiAgdGl0bGU6IHN0cmluZ1xuICBjb250ZW50OiBzdHJpbmdcbiAgY2xpY2tCZWhhdmlvcjogKC4uLmFyZzA6IGFueVtdKSA9PiBhbnlcbn1cblxuY29uc3QgZGlhbG9nSW5mbyA9IHJlZjxEaWFsb2dJbmZvW10+KFtcbiAge1xuICAgIGlkOiAxLFxuICAgIHpJbmRleDogbmV4dFpJbmRleCgpLFxuICAgIGRpYWxvZ1Nob3c6IGZhbHNlLFxuICAgIGNsaWNrQmVoYXZpb3I6IGhhbmRsZURpYWxvZ0NsaWNrLFxuICAgIHRpdGxlOiAnZGlhbG9nMScsXG4gICAgY29udGVudDogJ2Fsd2F5cyBvbiB0aGUgdG9wIGFmdGVyIGNsaWNrJyxcbiAgfSxcbiAge1xuICAgIGlkOiAyLFxuICAgIHpJbmRleDogbmV4dFpJbmRleCgpLFxuICAgIGRpYWxvZ1Nob3c6IGZhbHNlLFxuICAgIGNsaWNrQmVoYXZpb3I6IGhhbmRsZURpYWxvZ0NsaWNrLFxuICAgIHRpdGxlOiAnZGlhbG9nMicsXG4gICAgY29udGVudDogJ2Fsd2F5cyBvbiB0aGUgdG9wIGFmdGVyIGNsaWNrJyxcbiAgfSxcbiAge1xuICAgIGlkOiAzLFxuICAgIHpJbmRleDogMixcbiAgICBkaWFsb2dTaG93OiBmYWxzZSxcbiAgICBjbGlja0JlaGF2aW9yOiAoKSA9PiB7fSxcbiAgICB0aXRsZTogJ2RpYWxvZzMnLFxuICAgIGNvbnRlbnQ6ICdoYXZlIGEgc3RhdGljIHZhbHVlIG9mIHpJbmRleCcsXG4gIH0sXG4gIHtcbiAgICBpZDogNCxcbiAgICBkaWFsb2dTaG93OiBmYWxzZSxcbiAgICBjbGlja0JlaGF2aW9yOiAoKSA9PiB7fSxcbiAgICB0aXRsZTogJ2RpYWxvZzQnLFxuICAgIGNvbnRlbnQ6ICdubyB6SW5kZXggcHJvcCBnaXZlbicsXG4gIH0sXG5dKVxuXG5mdW5jdGlvbiByZWZyZXNoQWN0dWFsWmluZGV4RGlzcGxheSgpIHtcbiAgY29uc3QgekluZGVjaWVzID0gWy4uLmRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJy5wZW5ldHJhdGVfZGlhbG9nJyldLm1hcChcbiAgICAoZWwpID0+IGdldENvbXB1dGVkU3R5bGUoZWwpLnpJbmRleFxuICApXG4gIGZvciAobGV0IGkgPSAwOyBpIDwgekluZGVjaWVzLmxlbmd0aDsgaSsrKSB7XG4gICAgZGlhbG9nSW5mby52YWx1ZVtpXS5hY3R1YWxaSW5kZXggPSB6SW5kZWNpZXNbaV1cbiAgfVxufVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICByZWZyZXNoQWN0dWFsWmluZGV4RGlzcGxheSgpXG59KVxuXG5mdW5jdGlvbiBoYW5kbGVTaG93RGlhbG9nKGRpYWxvZzogRGlhbG9nSW5mbykge1xuICBkaWFsb2cuZGlhbG9nU2hvdyA9ICFkaWFsb2cuZGlhbG9nU2hvd1xuICBuZXh0VGljaygpLnRoZW4ocmVmcmVzaEFjdHVhbFppbmRleERpc3BsYXkpXG59XG5cbmZ1bmN0aW9uIGhhbmRsZURpYWxvZ0NsaWNrKGRpYWxvZzogRGlhbG9nSW5mbykge1xuICBkaWFsb2cuekluZGV4ID0gbmV4dFpJbmRleCgpXG4gIG5leHRUaWNrKCkudGhlbihyZWZyZXNoQWN0dWFsWmluZGV4RGlzcGxheSlcbn1cblxuZnVuY3Rpb24gdG9nZ2xlRGlhbG9nM1pJbmRleCgpIHtcbiAgZGlhbG9nSW5mby52YWx1ZVsyXS56SW5kZXggPSBkaWFsb2dJbmZvLnZhbHVlWzJdLnpJbmRleCA/IHVuZGVmaW5lZCA6IDJcbiAgZGlhbG9nSW5mby52YWx1ZVsyXS5jb250ZW50ID0gZGlhbG9nSW5mby52YWx1ZVsyXS56SW5kZXhcbiAgICA/ICdoYXZlIGEgc3RhdGljIHZhbHVlIG9mIHpJbmRleCdcbiAgICA6ICdoYXZlIGEgc3RhdGljIHZhbHVlIG9mIHpJbmRleCAodGVtcG9yYXJpbHkgZGlzYWJsZWQpJ1xuICBuZXh0VGljaygpLnRoZW4ocmVmcmVzaEFjdHVhbFppbmRleERpc3BsYXkpXG59XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLnBsYXktY29udGFpbmVyIHtcbiAgaGVpZ2h0OiAxMDAlO1xuICB3aWR0aDogMTAwJTtcbiAgZGlzcGxheTogZ3JpZDtcbiAgZ3JpZC10ZW1wbGF0ZTogMWZyIC8gMWZyIDFmciAxZnIgMWZyO1xufVxuXG4ucGVuZXRyYXRlX2RpYWxvZyB7XG4gIHBvaW50ZXItZXZlbnRzOiBub25lO1xufVxuXG4ucGVuZXRyYXRlX2RpYWxvZyAuZWwtb3ZlcmxheS1kaWFsb2cge1xuICBwb2ludGVyLWV2ZW50czogbm9uZTtcbn1cblxuLnBlbmV0cmF0ZV9kaWFsb2cgLmVsLW92ZXJsYXktZGlhbG9nIC5lbC1kaWFsb2cge1xuICBwb2ludGVyLWV2ZW50czogYXV0bztcbn1cblxuLmNvbnRlbnQge1xuICB3aWR0aDogMzAwcHg7XG4gIGhlaWdodDogMzAwcHg7XG59XG48L3N0eWxlPlxuXG48dGVtcGxhdGU+XG4gIDxkaXYgY2xhc3M9XCJwbGF5LWNvbnRhaW5lclwiIHJlZj1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgdi1mb3I9XCJkaWFsb2cgb2YgZGlhbG9nSW5mb1wiIDprZXk9XCJkaWFsb2cuaWRcIj5cbiAgICAgIDxlbC1kaWFsb2dcbiAgICAgICAgdi1tb2RlbD1cImRpYWxvZy5kaWFsb2dTaG93XCJcbiAgICAgICAgOm1vZGFsPVwiZmFsc2VcIlxuICAgICAgICA6dGl0bGU9XCJkaWFsb2cudGl0bGVcIlxuICAgICAgICA6Y2xvc2Utb24tY2xpY2stbW9kYWw9XCJmYWxzZVwiXG4gICAgICAgIDpsb2NrLXNjcm9sbD1cInRydWVcIlxuICAgICAgICA6YXBwZW5kLXRvLWJvZHk9XCJ0cnVlXCJcbiAgICAgICAgbW9kYWwtY2xhc3M9XCJwZW5ldHJhdGVfZGlhbG9nXCJcbiAgICAgICAgZHJhZ2dhYmxlXG4gICAgICAgIDpzaG93LWNsb3NlPVwidHJ1ZVwiXG4gICAgICAgIDp3aWR0aD1cIidtYXgtY29udGVudCdcIlxuICAgICAgICA6ei1pbmRleD1cImRpYWxvZy56SW5kZXhcIlxuICAgICAgICBAY2xpY2s9XCJkaWFsb2cuY2xpY2tCZWhhdmlvcihkaWFsb2cpXCJcbiAgICAgID5cbiAgICAgICAgPGRpdiBzdHlsZT1cIndpZHRoOiAyMDBweDsgaGVpZ2h0OiAyMDBweFwiPlxuICAgICAgICAgIHt7IGRpYWxvZy5jb250ZW50IH19XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9lbC1kaWFsb2c+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImhhbmRsZVNob3dEaWFsb2coZGlhbG9nKVwiPlxuICAgICAgICB0b2dnbGUgRGlhbG9nIHt7IGRpYWxvZy5pZCB9fVxuICAgICAgPC9lbC1idXR0b24+XG4gICAgICA8ZGl2PlxuICAgICAgICB7eyBkaWFsb2cuYWN0dWFsWkluZGV4IH19XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlRGlhbG9nM1pJbmRleFwiPlxuICAgIHRvZ2dsZSBkaWFsb2czIHpJbmRleCBwcm9wXG4gIDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xODUyMC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTg1MjAtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE4NTIwLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xODUyMC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

File: packages/components/dialog/src/use-dialog.ts [hunk 1]
```diff
@@ -155,14 +154,21 @@ export const useDialog = (
...
+
   watch(
     () => props.modelValue,
     (val) => {
       if (val) {
         closed.value = false
         open()
         rendered.value = true // enables lazy rendering
-        zIndex.value = isUndefined(props.zIndex) ? nextZIndex() : zIndex.value++
+        zIndex.value = props.zIndex ?? nextZIndex()
```
Comment (btea) [inline packages/components/dialog/src/use-dialog.ts:171]: The logic here doesn't need to be changed, or is your goal to stop the zIndex from increasing?

Comment (btea) [reply packages/components/dialog/src/use-dialog.ts:171]: I get it, that seems to make sense.

**Review by btea — APPROVED** [review]

**Review by Dsaquel — APPROVED** [review]
LGTM

**Review by warmthsea — APPROVED** [review]
