### PR TITLE
fix(components): [table] show-overflow-tooltip dynamic switch

### LINKED ISSUE #21800: [Component] [table-column] table组件Table-column中show-overflow-tooltip动态切换显示异常
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.18`
- Element Plus Version: `2.10.7`
- Browser / OS: `Chrome/139.0.0.0 / Intel Mac OS X 10_15_7`
- Build Tool: `Vite`

### Related Component

- `el-table-column`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRhYmxlUmVmID0gcmVmKCk7XG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0FsZXluYSBLdXR6bmVyJyxcbiAgICBhZGRyZXNzOiAnTG9ocmJlcmdzdHIuIDg2YywgU8O8ZCBMaWxsaSwgU2FhcmxhbmQnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdIZWxlbiBKYWNvYmknLFxuICAgIGFkZHJlc3M6ICc3NjAgQSBTdHJlZXQsIFNvdXRoIEZyYW5rZmllbGQsIElsbGlub2lzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnQnJhbmRvbiBEZWNrZXJ0JyxcbiAgICBhZGRyZXNzOiAnQXJub2xkLU9obGV0ei1TdHIuIDQxYSwgQWx0IE1hbGluYXNjaGVpZCwgVGjDvHJpbmdlbicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ01hcmdpZSBTbWl0aCcsXG4gICAgYWRkcmVzczogJzIzNjE4IFdpbmRzb3IgRHJpdmUsIFdlc3QgUmljYXJkb3ZpZXcsIElkYWhvJyxcbiAgfSxcbl0pXG5jb25zdCBzaG93T3ZlcmZsb3dUb29sdGlwID0gcmVmKHRydWUpO1xuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbDogYW55KSA9PiB7XG59XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zd2l0Y2ggQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiIHYtbW9kZWw9XCJzaG93T3ZlcmZsb3dUb29sdGlwXCIgLz5cbiAg5YiH5o2ic2hvd092ZXJmbG93VG9vbHRpcFxuICA8ZWwtdGFibGUgcmVmPVwidGFibGVSZWZcIiA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAgOnNob3ctb3ZlcmZsb3ctdG9vbHRpcD1cInNob3dPdmVyZmxvd1Rvb2x0aXBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJhZGRyZXNzXCIgbGFiZWw9XCJ1c2Ugc2hvdy1vdmVyZmxvdy10b29sdGlwXCIgd2lkdGg9XCIyNDBcIiA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwic2hvd092ZXJmbG93VG9vbHRpcFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cImFkZHJlc3NcIiB3aWR0aD1cIjEyMFwiIDpzaG93LW92ZXJmbG93LXRvb2x0aXA9XCJzaG93T3ZlcmZsb3dUb29sdGlwXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

当show-overflow-tooltip初始值为true时，鼠标移入是正确显示弹出内容。切换show-overflow-tooltip状态，最后一次鼠标移入的元素即使不开启show-overflow-tooltip也会弹出弹出层，其他内容正常。

### What is Expected?

show-overflow-tooltip正确被状态管理

### What is actually happening?

show-overflow-tooltip动态切换显示异常

### Additional comments

在初始测试时想使用table的show-overflow-tooltip属性进行控制，但是切换时不会正确更新状态。是否还有其他方式完成动态切换show-overflow-tooltip属性

### PR DESCRIPTION
**Pull request by dhj-l**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix: #21800

### CODE REVIEW

**Comment by dhj-l** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRhYmxlUmVmID0gcmVmKCk7XG5cbmNvbnN0IHRhYmxlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ0FsZXluYSBLdXR6bmVyJyxcbiAgICBhZGRyZXNzOiAnTG9ocmJlcmdzdHIuIDg2YywgU8O8ZCBMaWxsaSwgU2FhcmxhbmQnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDMnLFxuICAgIG5hbWU6ICdIZWxlbiBKYWNvYmknLFxuICAgIGFkZHJlc3M6ICc3NjAgQSBTdHJlZXQsIFNvdXRoIEZyYW5rZmllbGQsIElsbGlub2lzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnQnJhbmRvbiBEZWNrZXJ0JyxcbiAgICBhZGRyZXNzOiAnQXJub2xkLU9obGV0ei1TdHIuIDQxYSwgQWx0IE1hbGluYXNjaGVpZCwgVGjDvHJpbmdlbicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ01hcmdpZSBTbWl0aCcsXG4gICAgYWRkcmVzczogJzIzNjE4IFdpbmRzb3IgRHJpdmUsIFdlc3QgUmljYXJkb3ZpZXcsIElkYWhvJyxcbiAgfSxcbl0pXG5jb25zdCBzaG93T3ZlcmZsb3dUb29sdGlwID0gcmVmKHRydWUpO1xuY29uc3QgaGFuZGxlQ2hhbmdlID0gKHZhbDogYW55KSA9PiB7XG59XG5cbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1zd2l0Y2ggQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiIHYtbW9kZWw9XCJzaG93T3ZlcmZsb3dUb29sdGlwXCIgLz5cbiAg5YiH5o2ic2hvd092ZXJmbG93VG9vbHRpcFxuICA8ZWwtdGFibGUgcmVmPVwidGFibGVSZWZcIiA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIiA+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjEyMFwiPlxuICAgICAgPHRlbXBsYXRlICNkZWZhdWx0PVwic2NvcGVcIj57eyBzY29wZS5yb3cuZGF0ZSB9fTwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAgOnNob3ctb3ZlcmZsb3ctdG9vbHRpcD1cInNob3dPdmVyZmxvd1Rvb2x0aXBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcGVydHk9XCJhZGRyZXNzXCIgbGFiZWw9XCJ1c2Ugc2hvdy1vdmVyZmxvdy10b29sdGlwXCIgd2lkdGg9XCIyNDBcIiA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwic2hvd092ZXJmbG93VG9vbHRpcFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wZXJ0eT1cImFkZHJlc3NcIiBsYWJlbD1cImFkZHJlc3NcIiB3aWR0aD1cIjEyMFwiIDpzaG93LW92ZXJmbG93LXRvb2x0aXA9XCJzaG93T3ZlcmZsb3dUb29sdGlwXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjE4MTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjE4MTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjE4MTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjE4MTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==
对应的示例

File: packages/components/table/src/util.ts [hunk 1]
```diff
@@ -507,8 +507,15 @@ export function createTablePopper<T extends DefaultRow>(
...
+    if (vm.component?.exposed?.onClose) {
+      vm.component.exposed.onClose()
+    }
     render(null, container)
     scrollContainer?.removeEventListener('scroll', removePopper!)
+    if (removePopper) {
+      removePopper.trigger = undefined
+      removePopper.vm = undefined
+    }
     removePopper = null
```
[the remark this answers is not in the document]
Comment (dhj-l) [reply packages/components/table/src/util.ts:518]: This issue has been resolved

File: packages/components/table/__tests__/table-column.test.ts
Comment (warmthsea) [inline packages/components/table/__tests__/table-column.test.ts:1]: These tests run successfully even without new code.

image

Comment (dhj-l) [reply packages/components/table/__tests__/table-column.test.ts:1]: Yes, but the new code will be more standardized.

Comment (Dsaquel) [reply packages/components/table/__tests__/table-column.test.ts:1]: @dhj-l At least one test case should fail without the fix. I can help you on this if you want.

Comment (dhj-l) [reply packages/components/table/__tests__/table-column.test.ts:1]: > @dhj-l At least one test case should fail without the fix. I can help you on this if you want.

OK, thank you.

Comment (Dsaquel) [reply packages/components/table/__tests__/table-column.test.ts:1]: I removed your previous tests case, i didn't judge them relevant. Hope you will understand that :smiley: .

**Review by Dsaquel — APPROVED** [review]

**Review by btea — APPROVED** [review]

**Comment by btea** [comment]
Thanks!
