### PR TITLE
fix(table): fix shadow rendering bug of initializing fixed columns

### LINKED ISSUE #1353: [Bug Report] when table-column fixed, the shadow shows incorrectly
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
chrome84

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-k9586

### Steps to reproduce
Change the width of browser

### What is Expected?
There should be shown a shadow
image

The shadow should be hidden
image

### PR DESCRIPTION
**Pull request by justwiner**
fix #1353

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/table/src/table.vue [hunk 1]
```diff
@@ -397,9 +397,8 @@ export default defineComponent({
       toggleAllSelection,
       toggleRowExpansion,
       clearSort,
-      doLayout,
       sort,
-    } = useUtils(store, layout, shouldUpdateHeight)
```
Comment (JeremyWuuuuu) [inline packages/table/src/table.vue:402]: Should we remove the `shouldUpdateHeight`?

**Review by jw-foss — APPROVED** [review]
