### PR TITLE
fix(components): [dialog] fix dialog not fill full screen after drag

### LINKED ISSUE #5870: [Bug Report] dialog not fill full screen after drag
### Element Plus version
2.0.1

### OS/Browsers version
chrome

### Vue version
3.2.30

### Reproduction Link
https://codepen.com/see_below

### Steps to reproduce
1. open dialog
2. drag dialog
3. fullscreen dialog

https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwiZGlhbG9nVmlzaWJsZSA9IHRydWVcIlxuICAgID5DbGljayB0byBvcGVuIERpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgdGl0bGU9XCJUaXBzXCIgd2lkdGg9XCIzMCVcIiBkcmFnZ2FibGUgOmZ1bGxzY3JlZW49XCJmdWxsc2NyZWVuXCI+XG4gICAgPHNwYW4+SXQncyBhIGRyYWdnYWJsZSBEaWFsb2c8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNmb290ZXI+XG4gICAgICA8c3BhbiBjbGFzcz1cImRpYWxvZy1mb290ZXJcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiIEBjbGljaz1cImZ1bGxzY3JlZW4gPSAhZnVsbHNjcmVlblwiXG4gICAgICAgICAgPkZ1bGxzY3JlZW48L2VsLWJ1dHRvblxuICAgICAgICA+XG4gICAgICA8L3NwYW4+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kaWFsb2c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZGlhbG9nVmlzaWJsZSA9IHJlZihmYWxzZSlcbmNvbnN0IGZ1bGxzY3JlZW4gPSByZWYoZmFsc2UpXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9

### What is Expected?
fill the window

### What is actually happening?
has some offset caused by dragging

### PR DESCRIPTION
**Pull request by buqiyuan**
fix #5870
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

File: packages/components/dialog/src/use-dialog.ts [hunk 1]
```diff
@@ -153,6 +154,23 @@ export const useDialog = (
     }
   )
 
+  watch(
+    () => props.fullscreen,
+    (val) => {
+      if (targetRef.value) {
```
Comment (sxzz) [inline packages/components/dialog/src/use-dialog.ts:160]: suggestion `if(!targetRef.value) return` to avoid too much nested

File: packages/components/dialog/src/use-dialog.ts [hunk 2]
```diff
@@ -153,6 +154,23 @@ export const useDialog = (
...
+        if (val) {
+          lastPosition = targetRef.value.style.transform
+          targetRef.value.style.transform = ''
+        } else {
+          targetRef.value.style.transform = lastPosition
+        }
+      }
+    },
+    {
+      flush: 'post',
```
Comment (sxzz) [inline packages/components/dialog/src/use-dialog.ts:170]: Why

**Review by sxzz — APPROVED** [review]
