### PR TITLE
fix(select): filtered empty groups

### LINKED ISSUE #2506: [Bug Report] Select filterable: labels of empty option groups should be filtered out
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows 10 / Edge Version 91.0.864.67

### Vue version
3.1.4

### Reproduction Link
https://codepen.io/maelga/pen/dyWOZRV

### Steps to reproduce
See codepen, using a filterable select with options grouping.
Try this: type "sh" in the filterable select will return 'Shanghai' and 'Shenzhen'.
However, option group labels with no options (i.e. "Australia", "Indonesia", "India") should not show.

### What is Expected?
When using filterable, the label of empty option groups should not show if no options are available. There is no benefits for users to see labels (e.g. country names in this codepen example) when no options (e.g. cities) can be selected. The select should show only option group labels (e.g. country names) if options are available (e.g. cities).

### What is actually happening?
Labels of empty option groups are currently displayed even if there are no options displayed for the user to select.

### PR DESCRIPTION
**Pull request by msidolphin**
fix #2506

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/select/src/option-group.vue [hunk 1]
```diff
@@ -37,8 +38,32 @@ export default defineComponent({
 
     const select = inject(selectKey)
 
+    onMounted(() => {
+      children.value = flattedChildren(instance.subTree)
+    })
```
Comment (XingXiaoWu) [inline packages/select/src/option-group.vue:43]: I have been looking for a long time, but I have no idea how to get the options under the current group, I learned it

**Review by XingXiaoWu — APPROVED** [review]

File: packages/select/src/option-group.vue (hunk 1 above)
Comment (JeremyWuuuuu) [reply packages/select/src/option-group.vue:43]: Although I think this is not the best way or the best approach to solve this issue you can see we took different approach in `ElSelectV2` which used data with explicit structure that hints us to render group or item. 

AntDesign took both ways for the users which I think the structured data would be more elegant.

**Review by jw-foss — APPROVED** [review]
