### PR TITLE
fix(components): [tabs] tab-bar need to adapt to tabs width change

### LINKED ISSUE #11722: [Style] [tabs] 响应式布局中，Tabs组件的tab bar宽度无法随el-tab-pane的宽度变化而变化
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.17`
- Browser / OS: `Chrome 109.0.5414.119/ macOS 13.0.1`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBhY3RpdmVUYWIgPSBcIjJcIjtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIC8+XG5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZVRhYlwiIHN0cmV0Y2g+XG4gIFx0PGVsLXRhYi1wYW5lIGxhYmVsPVwi5rWL6K+VMVwiIGtleT1cIjFcIj7mtYvor5UxPC9lbC10YWItcGFuZT5cbiAgICA8ZWwtdGFiLXBhbmUgbGFiZWw9XCLmtYvor5UxXCIga2V5PVwiMlwiPua1i+ivlTI8L2VsLXRhYi1wYW5lPlxuICAgIDxlbC10YWItcGFuZSBsYWJlbD1cIua1i+ivlTFcIiBrZXk9XCIzXCI+5rWL6K+VMzwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwi5rWL6K+VMVwiIGtleT1cIjRcIj7mtYvor5U0PC9lbC10YWItcGFuZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开【最小复现环境的链接】，拉动代码和展示框中间的竖线。

### What is Expected?

展示窗口大小变化时，tab bar能够focus在当前active的el-tab-pane下面，长度和el-tab-pane保持一致

### What is actually happening?

展示窗口大小变化时，tab bar固定在原处不动

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by godxiaoji**
closed #11722

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/tabs/src/tab-nav.tsx [hunk 1]
```diff
@@ -82,6 +82,8 @@ const TabNav = defineComponent({
     const nav$ = ref<HTMLDivElement>()
     const el$ = ref<HTMLDivElement>()
 
+    const tabBar = ref<InstanceType<typeof TabBar>>()
```
Comment (btea) [inline packages/components/tabs/src/tab-nav.tsx:85]: The variable name may be changed to `tabBarRef`, which looks easy to be confused with the component name `TabBar`.

Comment (godxiaoji) [reply packages/components/tabs/src/tab-nav.tsx]: ok

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]
