### PR TITLE
fix(components): [el-table] rangeWidth dealing with loss of precision

### LINKED ISSUE #12687: [Component] [table, table-column] [Component] [table]配置show-overflow-tooltip属性，调整列宽到显示tooltip的临界值，tooltip不生效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.34`
- Browser / OS: `Chrome 112.0.5615.138`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`
- `el-table-column`

### Reproduction Link

[CodePen](https://codepen.io/LandaHao/pen/qBJpXma)

### Steps to reproduce

调整表格的列宽到显示tooltip的临界值（出现省略号），会出现tooltip效果不生效。例子中调整Address列宽为230，虽然显示省略号但是tooltip不生效。
```vue
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://unpkg.com/vue@next"></script>
    <!-- import CSS -->
    <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
    <!-- import JavaScript -->
    <script src="https://unpkg.com/element-plus"></script>
    <title>Element Plus demo</title>
  </head>
  <body>
    <div id="app">
      <el-table :data="tableData" border>
          <el-table-column prop="date" label="Date" width="100" show-overflow-tooltip></el-table-column>
          <el-table-column prop="name" label="Name" width="100" show-overflow-tooltip></el-table-column>
          <el-table-column prop="address" label="Address" width=230" show-overflow-tooltip></el-table-column>
        </el-table>
    </div>
    <script>
      const App = {
        data() {
          return {
            message: "Hello Element Plus",
            tableData: [{
              date: '2016-05-03',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            },
            {
              date: '2016-05-02',
              name: 'Tom',
              address: 'No. 189, Grove St, Los Angeles',
            }]
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");
    </script>
  </body>
</html>

```

### What is Expected?

只要显示省略号，tooltip效果就应该生效。

### What is actually happening?

调整长度到临界值附近会出现tooltip不生效

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by lxy030988**
Closes #12687

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Description

调整表格的列宽到显示tooltip的临界值（出现省略号），会出现tooltip效果不生效。
造成词现象的原因，rangeWidth 计算使用的四舍五入，丢失零点几像素的宽度。
修改方案：计算 rangeWidth 宽度 使用向上取整。

## Related Issue

Fixes #12687

### CODE REVIEW

File: packages/components/table/src/table-body/events-helper.ts [hunk 1]
```diff
@@ -102,7 +102,7 @@ function useEvents<T>(props: Partial<TableBodyProps<T>>) {
      *    - Expected: 188
      *    - Actual: 188.00000762939453
      */
-    const rangeWidth = Math.round(range.getBoundingClientRect().width)
+    const rangeWidth = Math.ceil(range.getBoundingClientRect().width)
```
Comment (btea) [inline packages/components/table/src/table-body/events-helper.ts:105]: This may cause problems fixed by #10816.

`Math.ceil` and `Math.round` may not work here. For the problem solved by #10816, it may be roughly judged, for example, only 5 digits after the decimal point are used to solve it.
```ts
const rangeWidth = Number(range.getBoundingClientRect().width.toFixed(5))
```
This may not be entirely accurate though, do you guys have any good workarounds? @holazz @Cenavy1019

**Comment by qiYuei** [comment]
hello ,  [the actions](https://github.com/element-plus/element-plus/actions/runs/5069789145) failed, Do I need to add anything?
image

File: packages/components/table/src/table-body/events-helper.ts (hunk 1 above)
Comment (lxy030988) [reply packages/components/table/src/table-body/events-helper.ts:105]: I think it's okay

**Comment by btea** [comment]
@lxy030988 Could you please update the code with this suggestion?

File: packages/components/table/src/table-body/events-helper.ts [hunk 2]
```diff
@@ -115,8 +115,17 @@ function useEvents<T>(props: Partial<TableBodyProps<T>>) {
      *    - Expected: 188
      *    - Actual: 188.00000762939453
      */
-    const rangeWidth = Math.round(range.getBoundingClientRect().width)
-    const rangeHeight = Math.round(range.getBoundingClientRect().height)
+    let rangeWidth = range.getBoundingClientRect().width
+    let rangeHeight = range.getBoundingClientRect().height
+    const offsetWidth = rangeWidth - Math.floor(rangeWidth)
+    if (offsetWidth > 0 && offsetWidth < 0.001) {
```
Comment (btea) [inline packages/components/table/src/table-body/events-helper.ts:121]: `offsetWidth` must be greater than or equal to 0, so there is no need to judge that it is less than 0.
```suggestion
    if (offsetWidth < 0.001) {
```

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Comment by btea** [comment]
@lxy030988 Thank you for your contribution! ❤️
