### PR TITLE
fix(select): fix not scroll to default option

### LINKED ISSUE #1356: [bug report] uses El select to select a data by default. After opening the drop-down list, it does not jump to the currently selected data anchor, but only displays the top data
### Element Plus version
1.0.2-beta.30

### OS/Browsers version
 86.0.4240.198（正式版本）谷歌

### Vue version
3.0.5

### Steps to reproduce
no

### What is Expected?
应该跳转到当前选中的数据

### What is actually happening?
没有跳转当前选中数据的锚地

### PR DESCRIPTION
**Pull request by Ryan2128**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

Fixed #1356

### CODE REVIEW

File: packages/select/src/useSelect.ts [hunk 1]
```diff
@@ -521,15 +521,21 @@ export const useSelect = (props, states: States, ctx) => {
   }
 
   const scrollToOption = option => {
-    const target = Array.isArray(option) ? option[0]?.$el : option.$el
+    const getEl = option => {
```
Comment (JeremyWuuuuu) [inline packages/select/src/useSelect.ts:524]: Ssems to me that this function will only be called once. The only thing different is that you need to pick options out of multiple options, I don't see the benefit of encapsulating a function for that

Comment (Ryan2128) [reply packages/select/src/useSelect.ts:524]: Yes, I will extract it to the outside.

**Review by zazzaz — APPROVED** [review]
