### PR TITLE
fix(components): [image] support lazy inside transformed containers

### LINKED ISSUE #21571: [Component] [image, carousel] el-carousel 和el-image结合使用 给el-image加lazy属性图片出不来
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.17`
- Element Plus Version: `2.10.2`
- Browser / OS: ` Chrome/127.0.6533.100`
- Build Tool: `Webpack`

### Related Component

- `el-image`
- `el-carousel`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgOmludGVydmFsPVwiNTAwMFwiIGFycm93PVwiYWx3YXlzXCIgOmF1dG9wbGF5PVwiZmFsc2VcIj5cbiAgICA8ZWwtY2Fyb3VzZWwtaXRlbSB2LWZvcj1cIml0ZW0gaW4gdXJsc1wiIDprZXk9XCJpdGVtXCI+XG4gICAgICAgPGVsLWltYWdlIDpzcmM9XCJpdGVtXCIgbGF6eS8+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5jb25zdCB1cmxzID0gW1xuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzEvMzQvMTlhYTk4YjFmY2IyNzgxYzRmYmEzM2Q4NTA1NDlqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzAvNmYvZTM1ZmYzNzU4MTJlNmIwMDIwYjZiNGU4Zjk1ODNqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzkvYmIvZTI3ODU4ZTk3M2Y1ZDdkMzkwNDgzNWY0NmFiYmRqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2QvZTYvYzRkOTNhMzgwNWIzY2UzZjMyM2Y3OTc0ZTZmNzhqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvMjgvYmJmODkzZjc5MmYwM2E1NDQwOGIzYjdhN2ViZjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzIvMTEvNjUzNWJjZmIyNmU0Yzc5YjQ4ZGRkZTQ0ZjRiNmZqcGVnLmpwZWcnLFxuXVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuXG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

走马灯第三张以后图片出不来lazy的问题

### What is Expected?

图片出来

### What is actually happening?

图片出不来

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Previously, image lazy loading relied on scroll event listeners, which do not work inside containers using CSS transform. This commit replaces scroll-based detection with `IntersectionObserver`, which properly supports lazy loading within transformed contexts.

Transform: 

https://github.com/user-attachments/assets/bd95d1fe-129e-4fc7-be73-9c2c436a1665

Scroll:

https://github.com/user-attachments/assets/61ef1998-c18b-4c2f-ba22-06c62d14830e

fix #21571

### CODE REVIEW

**Comment by rzzf** [comment]
21571 [Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY2Fyb3VzZWwgcmVmPVwiY2Fyb3VzZWxSZWZcIiA6aW50ZXJ2YWw9XCI1MDAwXCIgYXJyb3c9XCJhbHdheXNcIiA6YXV0b3BsYXk9XCJmYWxzZVwiPlxuICAgIDxlbC1jYXJvdXNlbC1pdGVtIHYtZm9yPVwiaXRlbSBpbiB1cmxzXCIgOmtleT1cIml0ZW1cIj5cbiAgICAgICA8ZWwtaW1hZ2UgOnNjcm9sbC1jb250YWluZXI9XCJjYXJvdXNlbFJlZlwiIDpzcmM9XCJpdGVtXCIgbGF6eS8+XG4gICAgPC9lbC1jYXJvdXNlbC1pdGVtPlxuICA8L2VsLWNhcm91c2VsPlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHVybHMgPSBbXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vYS8zZi8zMzAyZTU4ZjlhMTgxZDI1MDlmM2RjMGZhNjhiMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMS8zNC8xOWFhOThiMWZjYjI3ODFjNGZiYTMzZDg1MDU0OWpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMC82Zi9lMzVmZjM3NTgxMmU2YjAwMjBiNmI0ZThmOTU4M2pwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vOS9iYi9lMjc4NThlOTczZjVkN2QzOTA0ODM1ZjQ2YWJiZGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vZC9lNi9jNGQ5M2EzODA1YjNjZTNmMzIzZjc5NzRlNmY3OGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMy8yOC9iYmY4OTNmNzkyZjAzYTU0NDA4YjNiN2E3ZWJmMGpwZWcuanBlZycsXG4gICdodHRwczovL2Z1c3MxMC5lbGVtZWNkbi5jb20vMi8xMS82NTM1YmNmYjI2ZTRjNzliNDhkZGRlNDRmNGI2ZmpwZWcuanBlZycsXG5dXG5jb25zdCBjYXJvdXNlbFJlZiA9IHJlZigpXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG5cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMjE1NzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMjE1NzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMjE1NzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMjE1NzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9kaXN0L2luZGV4LmNzcyJ9fQ==)

**Review by Dsaquel — APPROVED** [review]
LGTM, Thanks!

File: packages/components/image/src/image.vue [hunk 1]
```diff
@@ -191,24 +191,27 @@ async function addLazyLoadListener() {
     _scrollContainer.value =
       document.querySelector<HTMLElement>(scrollContainer) ?? undefined
   } else if (container.value) {
-    _scrollContainer.value = getScrollContainer(container.value)
+    const scrollContainer = getScrollContainer(container.value)
+    _scrollContainer.value = isWindow(scrollContainer)
+      ? undefined
+      : scrollContainer
   }
```
Comment (btea) [inline packages/components/image/src/image.vue:199]:
```suggestion
if (!_scrollContainer) return
```

Comment (rzzf) [reply packages/components/image/src/image.vue:199]: 感谢您的review

这个问题我觉得需要讨论一下🤔，如果直接`return`的话会导致图片不会加载（因为`lazyLoadHandler`没有被调用），另外当`_scrollContainer`为`undefined`时，`intersectionObserver`参考的是视口。
1. 如果为图片设置了尺寸则随着视口的滚动正确的懒加载图片，我认为即使是`undefined`也需要监听，因为它的参考对象会变成视口

[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXG4gIDxoMT7luIzmnJvpmo/nnYDmu5rliqjliqDovb3lm77niYc8L2gxPlxuXG4gIDxlbC1pbWFnZVxuICAgIHYtZm9yPVwidXJsIGluIHVybHNcIlxuICAgIDprZXk9XCJ1cmxcIlxuICAgIHN0eWxlPVwid2lkdGg6IDEwMCU7IGhlaWdodDogNDAwcHhcIlxuICAgIDpzcmM9XCJ1cmxcIlxuICAgIGxhenlcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCB1cmxzID0gW1xuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2EvM2YvMzMwMmU1OGY5YTE4MWQyNTA5ZjNkYzBmYTY4YjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzEvMzQvMTlhYTk4YjFmY2IyNzgxYzRmYmEzM2Q4NTA1NDlqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzAvNmYvZTM1ZmYzNzU4MTJlNmIwMDIwYjZiNGU4Zjk1ODNqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzkvYmIvZTI3ODU4ZTk3M2Y1ZDdkMzkwNDgzNWY0NmFiYmRqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tL2QvZTYvYzRkOTNhMzgwNWIzY2UzZjMyM2Y3OTc0ZTZmNzhqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzMvMjgvYmJmODkzZjc5MmYwM2E1NDQwOGIzYjdhN2ViZjBqcGVnLmpwZWcnLFxuICAnaHR0cHM6Ly9mdXNzMTAuZWxlbWVjZG4uY29tLzIvMTEvNjUzNWJjZmIyNmU0Yzc5YjQ4ZGRkZTQ0ZjRiNmZqcGVnLmpwZWcnLFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZGVtby1pbWFnZV9fbGF6eSB7XG4gIGhlaWdodDogNDAwcHg7XG4gIG92ZXJmbG93LXk6IGF1dG87XG59XG4uZGVtby1pbWFnZV9fbGF6eSAuZWwtaW1hZ2Uge1xuICBkaXNwbGF5OiBibG9jaztcbiAgbWluLWhlaWdodDogMjAwcHg7XG4gIG1hcmdpbi1ib3R0b206IDEwcHg7XG59XG4uZGVtby1pbWFnZV9fbGF6eSAuZWwtaW1hZ2U6bGFzdC1jaGlsZCB7XG4gIG1hcmdpbi1ib3R0b206IDA7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

File: packages/components/image/src/image.vue [hunk 2]
```diff
@@ -191,24 +191,27 @@ async function addLazyLoadListener() {
...
+  stopScrollListener = stop
 }
 
 function removeLazyLoadListener() {
-  if (!isClient || !_scrollContainer.value || !lazyLoadHandler) return
+  if (!isClient || !lazyLoadHandler) return
 
   stopScrollListener?.()
-  _scrollContainer.value = undefined
+  stopScrollListener = undefined
```
Comment (btea) [inline packages/components/image/src/image.vue:215]: `_scrollContainer.value = undefined` Should be retained.

File: packages/components/image/src/image.vue (hunk 1 above)
Comment (btea) [reply packages/components/image/src/image.vue:199]: 如果是这样，194行是不是不用修改。

File: packages/components/image/src/image.vue (hunk 2 above)
Comment (rzzf) [reply packages/components/image/src/image.vue:215]: 是的，感谢您的细心

Comment (cszhjh) [reply packages/components/image/src/image.vue:214]: 194行的修改是因为`getScrollContainer`可能会返回`window`而`root`不允许传`window`

File: packages/components/image/src/image.vue (hunk 1 above)
Comment (rzzf) [reply packages/components/image/src/image.vue:199]: 194行的修改是因为getScrollContainer可能会返回window而root不允许传window

Comment (btea) [reply packages/components/image/src/image.vue:199]: 了解 👍

File: packages/components/image/src/image.vue (hunk 2 above)
Comment (rzzf) [reply packages/components/image/src/image.vue:215]: image

我在新的[提交](https://github.com/element-plus/element-plus/pull/21573/commits/0e067c3953ed3dae4abe6fdf6277cbb75440ee16)上恢复了🤔

**Review by btea — APPROVED** [review]
Thanks!

File: packages/components/image/src/image.vue (hunk 2 above)
Comment (btea) [reply packages/components/image/src/image.vue:215]: 嗯，我看到了，但刚才一直没刷新出来。
