### PR TITLE
fix(components): [cascader] multiple selection mode tag causes height change

### LINKED ISSUE #5219: [Bug Report] [ElCascader] The height of the input is incorrect when the `size`, `filterable`, and `multiple` attributes are set at the same time.
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Google Chrome 97

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/cfy/pen/abLjgeO

### Steps to reproduce
1. Open the [online demo](https://codepen.io/cfy/pen/abLjgeO).
2. Switch the sizes.
3. Check the height of the cascader, and compress to other form elements.

**PS:** The wrong code might be [this line](https://github.com/element-plus/element-plus/blob/3172fec0e4558b59c0adf5cd44530c331cd16c12/packages/components/cascader/src/index.vue#L509), the `6` number should be different for different sizes.

### What is Expected?
The height of the cascader is correct and is responsive when size changed.

### What is actually happening?
The height of the cascader is fixed, even changing the `size` to another one.

### LINKED ISSUE #7504: [Bug Report] [Component] [cascader] Cascader在多选模式下大小不会随size改变、选择内容后多2px、placeholder不消失
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Firefox 100.0 / win 10`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[CodePen](https://codepen.io/satrong/pen/qBxdvrZ)

### Steps to reproduce

目前发现有三个问题，具体请查看复现demo

```html
<template>
  <div>
      <div>
        <div>
          bug1. 选择一项，选择框的高度会多2px
        </div>
        <div style="display:flex">
          <div>
            <el-cascader
              v-model="value1"
              :options="options"
              :props="props"
              style="width:400px"
              filterable
              :show-all-levels="false"
              :collapse-tags="true"
              collapse-tags-tooltip
              :clearable="true"
            />
          </div>
        	<div>
            <el-input v-model="size" placeholder="输入" />
          </div>
        </div>
      </div>
    <div style="margin-top:20px;">
      <div>bug2. 动态size，多选模式不能正常切换size</div>
      <el-radio-group v-model="size" size="default">
        <el-radio-button label="default" value="default" />
        <el-radio-button label="small" value="small" />
        <el-radio-button label="large" value="large" />
      </el-radio-group>
    </div>
    <div style="display: flex">
      <div>
        <el-cascader
          v-model="value1"
          :options="options"
          placeholder="多选模式"
          :props="props"
          filterable
          :show-all-levels="false"
          :collapse-tags="true"
          collapse-tags-tooltip
          :clearable="true"
          :size="size"
        />
      </div>
      <div>
        <el-cascader
          v-model="value2"
          :options="options"
          placeholder="单选模式"
          :props="{ multiple: false }"
          :show-all-levels="false"
          :collapse-tags="false"
          collapse-tags-tooltip
          filterable
          :clearable="true"
          :size="size"
        />
      </div>
      <div>
        <el-input v-model="size" :size="size" placeholder="输入" />
      </div>
    </div>
    
    <div style="margin-top: 20px">
      <div>
        bug3. multiple+filter 模式下，输入搜索内容 placeholder 不消失
      </div>
      <div>
        <el-cascader v-model="value1"
                     :options="options"
                     :props="props"
                     style="width:400px"
                     filterable
                     :show-all-levels="false"
                     :collapse-tags="true"
                     collapse-tags-tooltip
                     :clearable="true"
                     />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import type { ComponentSize } from 'element-plus'
// code here

const size = ref<ComponentSize>('default')
const value1 = ref([])
const value2 = ref('')
const props = {
  multiple: true,
}

const options = [
  {
    value: 'guide',
    label: 'Guide',
    children: [
      {
        value: 'disciplines',
        label: 'Disciplines'
      },
    ],
  },
  {
    value: 'resource',
    label: 'Resource',
    children: [
      {
        value: 'axure',
        label: 'Axure Components',
      },
      {
        value: 'sketch',
        label: 'Sketch Templates',
      },
      {
        value: 'docs',
        label: 'Design Documentation',
      },
    ],
  },
]
</script>
```

### What is Expected?

1. 高度不变
2. 跟随 size 变化
3. 输入内容后 placeholder 消失

### What is actually happening?

1. 高度多2px
2. 尺寸不会变
3. 输入内容后 placeholder 不会消失

### Additional comments

_(empty)_

### LINKED ISSUE #13017: [Component] [cascader] Cascader 级联选择器在设置为多选时，选择其中一项时高度会增加2px
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.3.5`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54`
- Build Tool: `Vue CLI`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+RGlzcGxheSBhbGwgdGFncyAoZGVmYXVsdCk8L3A+XG4gICAgPGVsLWNhc2NhZGVyIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cInByb3BzXCIgY2xlYXJhYmxlIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHByb3BzID0geyBtdWx0aXBsZTogdHJ1ZSB9XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogMSxcbiAgICBsYWJlbDogJ0FzaWEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAyLFxuICAgICAgICBsYWJlbDogJ0NoaW5hJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAzLCBsYWJlbDogJ0JlaWppbmcnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogNCwgbGFiZWw6ICdTaGFuZ2hhaScgfSxcbiAgICAgICAgICB7IHZhbHVlOiA1LCBsYWJlbDogJ0hhbmd6aG91JyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDYsXG4gICAgICAgIGxhYmVsOiAnSmFwYW4nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDcsIGxhYmVsOiAnVG9reW8nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogOCwgbGFiZWw6ICdPc2FrYScgfSxcbiAgICAgICAgICB7IHZhbHVlOiA5LCBsYWJlbDogJ0t5b3RvJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDEwLFxuICAgICAgICBsYWJlbDogJ0tvcmVhJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAxMSwgbGFiZWw6ICdTZW91bCcgfSxcbiAgICAgICAgICB7IHZhbHVlOiAxMiwgbGFiZWw6ICdCdXNhbicgfSxcbiAgICAgICAgICB7IHZhbHVlOiAxMywgbGFiZWw6ICdUYWVndScgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAxNCxcbiAgICBsYWJlbDogJ0V1cm9wZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDE1LFxuICAgICAgICBsYWJlbDogJ0ZyYW5jZScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMTYsIGxhYmVsOiAnUGFyaXMnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMTcsIGxhYmVsOiAnTWFyc2VpbGxlJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDE4LCBsYWJlbDogJ0x5b24nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogMTksXG4gICAgICAgIGxhYmVsOiAnVUsnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDIwLCBsYWJlbDogJ0xvbmRvbicgfSxcbiAgICAgICAgICB7IHZhbHVlOiAyMSwgbGFiZWw6ICdCaXJtaW5naGFtJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDIyLCBsYWJlbDogJ01hbmNoZXN0ZXInIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMjMsXG4gICAgbGFiZWw6ICdOb3J0aCBBbWVyaWNhJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogMjQsXG4gICAgICAgIGxhYmVsOiAnVVMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDI1LCBsYWJlbDogJ05ldyBZb3JrJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDI2LCBsYWJlbDogJ0xvcyBBbmdlbGVzJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDI3LCBsYWJlbDogJ1dhc2hpbmd0b24nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogMjgsXG4gICAgICAgIGxhYmVsOiAnQ2FuYWRhJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAyOSwgbGFiZWw6ICdUb3JvbnRvJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDMwLCBsYWJlbDogJ01vbnRyZWFsJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDMxLCBsYWJlbDogJ090dGF3YScgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

1、选中其中一项就能复现

### What is Expected?

选择后高度不变

### What is actually happening?

选择后高度会增加2px

### LINKED ISSUE #15089: [Style] [cascader] cascader(mutiple mode) input height is not correct
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoKVxuXG5jb25zdCBwcm9wcyA9IHsgbXVsdGlwbGU6IHRydWUgfVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6IDEsXG4gICAgbGFiZWw6ICdBc2lhJyxcbiAgfVxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNhc2NhZGVyIHBsYWNlaG9sZGVyPVwiZWwtY2FzY2FkZXJcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiA6cHJvcHM9XCJwcm9wc1wiIGNsZWFyYWJsZSAvPlxuICA8ZWwtc2VsZWN0IHN0eWxlPVwibWFyZ2luLWxlZnQ6IDhweDtcIiB2LW1vZGVsPVwidmFsdWVcIiBwbGFjZWhvbGRlcj1cImVsLXNlbGVjdFwiIG11bHRpcGxlPlxuICAgIDxlbC1vcHRpb24gbGFiZWw9XCJBc2lhXCIgdmFsdWU9XCIxXCIgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

1. check/uncheck Asia
2. you can see the height of the input is flicking

### What is Expected?

el-input__inner's height is 30px

### What is actually happening?

height is 34px

### Additional comments

The behavior should be the same as el-select(multiple mode)

### LINKED ISSUE #18282: [Style] [cascader] el-cascader
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.5`
- Element Plus Version: `2.8.3`
- Browser / OS: `Chrome 128.0.6613.138 / Macos 14.6.1`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+6YCJ5Lit55qE6auY5bqm5q+U5LiL6Z2i5rKh6YCJ5Lit55qE6auY5bqm5aSnPC9wPlxuICAgIDxlbC1jYXNjYWRlciB2LW1vZGVsPVwidmFsdWUxXCIgOm9wdGlvbnM9XCJvcHRpb25zXCIgOnByb3BzPVwicHJvcHMxXCIgY2xlYXJhYmxlIC8+XG4gIDwvZGl2PiBcbiAgPGRpdiBjbGFzcz1cIm0tNFwiPlxuICAgIDxwPuacqumAieS4reeahDwvcD5cbiAgICA8ZWwtY2FzY2FkZXIgOm9wdGlvbnM9XCJvcHRpb25zXCIgOnByb3BzPVwicHJvcHMyXCIgY2xlYXJhYmxlIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7cmVmfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZTEgPSByZWYoWydndWlkZSddKVxuY29uc3QgcHJvcHMxID0ge1xuICBtdWx0aXBsZTogdHJ1ZSxcbiAgY2hlY2tTdHJpY3RseTogdHJ1ZSxcbn1cblxuY29uc3QgcHJvcHMyID0ge1xuICBtdWx0aXBsZTogdHJ1ZSxcbiAgY2hlY2tTdHJpY3RseTogdHJ1ZSxcbn1cblxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdndWlkZScsXG4gICAgbGFiZWw6ICdHdWlkZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkaXNjaXBsaW5lcycsXG4gICAgICAgIGxhYmVsOiAnRGlzY2lwbGluZXMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29uc2lzdGVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdDb25zaXN0ZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2ZlZWRiYWNrJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRmVlZGJhY2snLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdlZmZpY2llbmN5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnRWZmaWNpZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzaWRlIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1NpZGUgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RvcCBuYXYnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb3AgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnY29tcG9uZW50JyxcbiAgICBsYWJlbDogJ0NvbXBvbmVudCcsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdiYXNpYycsXG4gICAgICAgIGxhYmVsOiAnQmFzaWMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbGF5b3V0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGF5b3V0JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29sb3InLFxuICAgICAgICAgICAgbGFiZWw6ICdDb2xvcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3R5cG9ncmFwaHknLFxuICAgICAgICAgICAgbGFiZWw6ICdUeXBvZ3JhcGh5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnaWNvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0ljb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdidXR0b24nLFxuICAgICAgICAgICAgbGFiZWw6ICdCdXR0b24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncmFkaW8nLFxuICAgICAgICAgICAgbGFiZWw6ICdSYWRpbycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NoZWNrYm94JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2hlY2tib3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpbnB1dCcsXG4gICAgICAgICAgICBsYWJlbDogJ0lucHV0JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnaW5wdXQtbnVtYmVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnSW5wdXROdW1iZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzZWxlY3QnLFxuICAgICAgICAgICAgbGFiZWw6ICdTZWxlY3QnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXNjYWRlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0Nhc2NhZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc3dpdGNoJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3dpdGNoJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc2xpZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2xpZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdUaW1lUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZXRpbWUtcGlja2VyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRGF0ZVRpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd1cGxvYWQnLFxuICAgICAgICAgICAgbGFiZWw6ICdVcGxvYWQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYXRlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUmF0ZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICAgICAgbGFiZWw6ICdGb3JtJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkYXRhJyxcbiAgICAgICAgbGFiZWw6ICdEYXRhJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhYmxlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFibGUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWcnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWcnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwcm9ncmVzcycsXG4gICAgICAgICAgICBsYWJlbDogJ1Byb2dyZXNzJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHJlZScsXG4gICAgICAgICAgICBsYWJlbDogJ1RyZWUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwYWdpbmF0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUGFnaW5hdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JhZGdlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQmFkZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25vdGljZScsXG4gICAgICAgIGxhYmVsOiAnTm90aWNlJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2FsZXJ0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQWxlcnQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsb2FkaW5nJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTG9hZGluZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ21lc3NhZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZS1ib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlQm94JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbm90aWZpY2F0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTm90aWZpY2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ21lbnUnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZW51JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGFicycsXG4gICAgICAgICAgICBsYWJlbDogJ1RhYnMnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdicmVhZGNydW1iJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQnJlYWRjcnVtYicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Ryb3Bkb3duJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRHJvcGRvd24nLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzdGVwcycsXG4gICAgICAgICAgICBsYWJlbDogJ1N0ZXBzJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdvdGhlcnMnLFxuICAgICAgICBsYWJlbDogJ090aGVycycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkaWFsb2cnLFxuICAgICAgICAgICAgbGFiZWw6ICdEaWFsb2cnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0b29sdGlwJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVG9vbHRpcCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3BvcG92ZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdQb3BvdmVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY2FyZCcsXG4gICAgICAgICAgICBsYWJlbDogJ0NhcmQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXJvdXNlbCcsXG4gICAgICAgICAgICBsYWJlbDogJ0Nhcm91c2VsJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29sbGFwc2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdDb2xsYXBzZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAncmVzb3VyY2UnLFxuICAgIGxhYmVsOiAnUmVzb3VyY2UnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnYXh1cmUnLFxuICAgICAgICBsYWJlbDogJ0F4dXJlIENvbXBvbmVudHMnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdza2V0Y2gnLFxuICAgICAgICBsYWJlbDogJ1NrZXRjaCBUZW1wbGF0ZXMnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkb2NzJyxcbiAgICAgICAgbGFiZWw6ICdEZXNpZ24gRG9jdW1lbnRhdGlvbicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

多选的情况下，选中数据之后，显示在输入框，导致整个输入框的高度变大了；

### What is Expected?

高度保持不变

### What is actually happening?

高度变高了

### Additional comments

希望和el-select的样式风格一样，包括多选的情况下，几种折叠多选项的样式显示。

image

### LINKED ISSUE #18316: [Style] [cascader] cascader input height flickering at multiple mode
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.6`
- Element Plus Version: `2.8.3`
- Browser / OS: `Chrome 129.0.6668.59`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBlcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZigpXG5cbmNvbnN0IHByb3BzID0geyBtdWx0aXBsZTogdHJ1ZSB9XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogMSxcbiAgICBsYWJlbDogJ0FzaWEnLFxuICB9XG5dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtY2FzY2FkZXIgcGxhY2Vob2xkZXI9XCJlbC1jYXNjYWRlclwiIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cInByb3BzXCIgY2xlYXJhYmxlIC8+XG4gIDxlbC1zZWxlY3Qgc3R5bGU9XCJtYXJnaW4tbGVmdDogOHB4O1wiIHYtbW9kZWw9XCJ2YWx1ZVwiIHBsYWNlaG9sZGVyPVwiZWwtc2VsZWN0XCIgbXVsdGlwbGU+XG4gICAgPGVsLW9wdGlvbiBsYWJlbD1cIkFzaWFcIiB2YWx1ZT1cIjFcIiAvPlxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJfbyI6e319)

### Steps to reproduce

1.check/uncheck Asia
2.you can see the height of the input is flicking

### What is Expected?

height do not change

### What is actually happening?

height changes

### Additional comments

same as isssue #15089, it is not fixed and the issue was marked as inactive

### LINKED ISSUE #18584: [Component] [cascader] el-cascader { multiple=true}  size='small'   cheked change height
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.5`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6IDEsXG4gICAgbGFiZWw6ICdBc2lhJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogMixcbiAgICAgICAgbGFiZWw6ICdDaGluYScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMywgbGFiZWw6ICdCZWlqaW5nJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDQsIGxhYmVsOiAnU2hhbmdoYWknIH0sXG4gICAgICAgICAgeyB2YWx1ZTogNSwgbGFiZWw6ICdIYW5nemhvdScgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiA2LFxuICAgICAgICBsYWJlbDogJ0phcGFuJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiA3LCBsYWJlbDogJ1Rva3lvJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDgsIGxhYmVsOiAnT3Nha2EnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogOSwgbGFiZWw6ICdLeW90bycgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAxMCxcbiAgICAgICAgbGFiZWw6ICdLb3JlYScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMTEsIGxhYmVsOiAnU2VvdWwnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMTIsIGxhYmVsOiAnQnVzYW4nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMTMsIGxhYmVsOiAnVGFlZ3UnIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMTQsXG4gICAgbGFiZWw6ICdFdXJvcGUnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAxNSxcbiAgICAgICAgbGFiZWw6ICdGcmFuY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDE2LCBsYWJlbDogJ1BhcmlzJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDE3LCBsYWJlbDogJ01hcnNlaWxsZScgfSxcbiAgICAgICAgICB7IHZhbHVlOiAxOCwgbGFiZWw6ICdMeW9uJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDE5LFxuICAgICAgICBsYWJlbDogJ1VLJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAyMCwgbGFiZWw6ICdMb25kb24nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjEsIGxhYmVsOiAnQmlybWluZ2hhbScgfSxcbiAgICAgICAgICB7IHZhbHVlOiAyMiwgbGFiZWw6ICdNYW5jaGVzdGVyJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDIzLFxuICAgIGxhYmVsOiAnTm9ydGggQW1lcmljYScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDI0LFxuICAgICAgICBsYWJlbDogJ1VTJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAyNSwgbGFiZWw6ICdOZXcgWW9yaycgfSxcbiAgICAgICAgICB7IHZhbHVlOiAyNiwgbGFiZWw6ICdMb3MgQW5nZWxlcycgfSxcbiAgICAgICAgICB7IHZhbHVlOiAyNywgbGFiZWw6ICdXYXNoaW5ndG9uJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDI4LFxuICAgICAgICBsYWJlbDogJ0NhbmFkYScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMjksIGxhYmVsOiAnVG9yb250bycgfSxcbiAgICAgICAgICB7IHZhbHVlOiAzMCwgbGFiZWw6ICdNb250cmVhbCcgfSxcbiAgICAgICAgICB7IHZhbHVlOiAzMSwgbGFiZWw6ICdPdHRhd2EnIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG5cbmNvbnN0IHByb3BzID0geyBtdWx0aXBsZTogdHJ1ZSB9XG5cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdiAgOnN0eWxlPVwie3dpZHRoOic0MDBweCd9XCI+XG4gPGVsLWNhc2NhZGVyXG4gICAgICBzaXplPSdzbWFsbCdcbiAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICA6cHJvcHM9XCJwcm9wc1wiXG4gICAgICA6c3R5bGU9XCJ7d2lkdGg6JzEwMCUnfVwiXG4gICAgICBjb2xsYXBzZS10YWdzXG4gICAgICBjb2xsYXBzZS10YWdzLXRvb2x0aXBcbiAgICAgIGNsZWFyYWJsZVxuICAgIC8+XG48L2Rpdj5cbiAgPHA+XG4gICAg5aSa6YCJ5pe26L6T5YWl5qGG6auY5bqm5Y+Y6auYIC0gV2hlbiBtYWtpbmcgbXVsdGlwbGUgc2VsZWN0aW9ucywgdGhlIGhlaWdodCBvZiB0aGUgaW5wdXQgYm94IGluY3JlYXNlc1xuICAgIDxici8+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

size=samll  多选情况下会导致组件高度变高且无法修改
Multiple selection can cause the component height to increase and cannot be modified

### What is Expected?

高度不变
Height remains unchanged

### What is actually happening?

多选时输入框高度变高 - When making multiple selections, the height of the input box increases

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by zzjiaxiang**
fix #18282    fix #18316 fix #18584 fix #15089 fix #7504 fix #13017 fix #5219
about  #15198 #13023 #5159

### CODE REVIEW

**Comment by tolking** [comment]
The interval between tags is larger compared to Select component, and it is best to maintain consistency.

[Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+6YCJ5Lit55qE6auY5bqm5q+U5LiL6Z2i5rKh6YCJ5Lit55qE6auY5bqm5aSnPC9wPlxuICAgIDxlbC1jYXNjYWRlciB2LW1vZGVsPVwidmFsdWUxXCIgOm9wdGlvbnM9XCJvcHRpb25zXCIgOnByb3BzPVwicHJvcHMxXCIgY2xlYXJhYmxlIHN0eWxlPVwid2lkdGg6IDEwMCVcIiAvPlxuICA8L2Rpdj4gXG4gIDxkaXYgY2xhc3M9XCJtLTRcIj5cbiAgICA8cD7mnKrpgInkuK3nmoQ8L3A+XG4gICAgPGVsLWNhc2NhZGVyIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cInByb3BzMlwiIGNsZWFyYWJsZSAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoWydjb25zaXN0ZW5jeScsICdmZWVkYmFjaycsICdlZmZpY2llbmN5J10pXG5jb25zdCBwcm9wczEgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5jb25zdCBwcm9wczIgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ2d1aWRlJyxcbiAgICBsYWJlbDogJ0d1aWRlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Rpc2NpcGxpbmVzJyxcbiAgICAgICAgbGFiZWw6ICdEaXNjaXBsaW5lcycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb25zaXN0ZW5jeScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnNpc3RlbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZmVlZGJhY2snLFxuICAgICAgICAgICAgbGFiZWw6ICdGZWVkYmFjaycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2VmZmljaWVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdFZmZpY2llbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NpZGUgbmF2JyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2lkZSBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndG9wIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1RvcCBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdjb21wb25lbnQnLFxuICAgIGxhYmVsOiAnQ29tcG9uZW50JyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Jhc2ljJyxcbiAgICAgICAgbGFiZWw6ICdCYXNpYycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsYXlvdXQnLFxuICAgICAgICAgICAgbGFiZWw6ICdMYXlvdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xvcicsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbG9yJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHlwb2dyYXBoeScsXG4gICAgICAgICAgICBsYWJlbDogJ1R5cG9ncmFwaHknLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpY29uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnSWNvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2J1dHRvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0J1dHRvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgIGxhYmVsOiAnRm9ybScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYWRpbycsXG4gICAgICAgICAgICBsYWJlbDogJ1JhZGlvJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY2hlY2tib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdDaGVja2JveCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2lucHV0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnSW5wdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpbnB1dC1udW1iZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdJbnB1dE51bWJlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NlbGVjdCcsXG4gICAgICAgICAgICBsYWJlbDogJ1NlbGVjdCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhc2NhZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FzY2FkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzd2l0Y2gnLFxuICAgICAgICAgICAgbGFiZWw6ICdTd2l0Y2gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzbGlkZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdTbGlkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0aW1lLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1RpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRlLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0RhdGVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRldGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlVGltZVBpY2tlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3VwbG9hZCcsXG4gICAgICAgICAgICBsYWJlbDogJ1VwbG9hZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3JhdGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdSYXRlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RhdGEnLFxuICAgICAgICBsYWJlbDogJ0RhdGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGFibGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWJsZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhZycsXG4gICAgICAgICAgICBsYWJlbDogJ1RhZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Byb2dyZXNzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUHJvZ3Jlc3MnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0cmVlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVHJlZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3BhZ2luYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdQYWdpbmF0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYmFkZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdCYWRnZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbm90aWNlJyxcbiAgICAgICAgbGFiZWw6ICdOb3RpY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYWxlcnQnLFxuICAgICAgICAgICAgbGFiZWw6ICdBbGVydCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2xvYWRpbmcnLFxuICAgICAgICAgICAgbGFiZWw6ICdMb2FkaW5nJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZScsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdtZXNzYWdlLWJveCcsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2VCb3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdub3RpZmljYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdOb3RpZmljYXRpb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25hdmlnYXRpb24nLFxuICAgICAgICBsYWJlbDogJ05hdmlnYXRpb24nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVudScsXG4gICAgICAgICAgICBsYWJlbDogJ01lbnUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWJzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFicycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JyZWFkY3J1bWInLFxuICAgICAgICAgICAgbGFiZWw6ICdCcmVhZGNydW1iJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZHJvcGRvd24nLFxuICAgICAgICAgICAgbGFiZWw6ICdEcm9wZG93bicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3N0ZXBzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3RlcHMnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ290aGVycycsXG4gICAgICAgIGxhYmVsOiAnT3RoZXJzJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2RpYWxvZycsXG4gICAgICAgICAgICBsYWJlbDogJ0RpYWxvZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Rvb2x0aXAnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb29sdGlwJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncG9wb3ZlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1BvcG92ZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXJkJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FyZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhcm91c2VsJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2Fyb3VzZWwnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xsYXBzZScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbGxhcHNlJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdyZXNvdXJjZScsXG4gICAgbGFiZWw6ICdSZXNvdXJjZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZScsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50cycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ3NrZXRjaCcsXG4gICAgICAgIGxhYmVsOiAnU2tldGNoIFRlbXBsYXRlcycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RvY3MnLFxuICAgICAgICBsYWJlbDogJ0Rlc2lnbiBEb2N1bWVudGF0aW9uJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by zzjiaxiang** [comment]
> The interval between tags is larger compared to Select component, and it is best to maintain consistency.
> 
> [Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+6YCJ5Lit55qE6auY5bqm5q+U5LiL6Z2i5rKh6YCJ5Lit55qE6auY5bqm5aSnPC9wPlxuICAgIDxlbC1jYXNjYWRlciB2LW1vZGVsPVwidmFsdWUxXCIgOm9wdGlvbnM9XCJvcHRpb25zXCIgOnByb3BzPVwicHJvcHMxXCIgY2xlYXJhYmxlIHN0eWxlPVwid2lkdGg6IDEwMCVcIiAvPlxuICA8L2Rpdj4gXG4gIDxkaXYgY2xhc3M9XCJtLTRcIj5cbiAgICA8cD7mnKrpgInkuK3nmoQ8L3A+XG4gICAgPGVsLWNhc2NhZGVyIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cInByb3BzMlwiIGNsZWFyYWJsZSAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTEgPSByZWYoWydjb25zaXN0ZW5jeScsICdmZWVkYmFjaycsICdlZmZpY2llbmN5J10pXG5jb25zdCBwcm9wczEgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5jb25zdCBwcm9wczIgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ2d1aWRlJyxcbiAgICBsYWJlbDogJ0d1aWRlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Rpc2NpcGxpbmVzJyxcbiAgICAgICAgbGFiZWw6ICdEaXNjaXBsaW5lcycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb25zaXN0ZW5jeScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnNpc3RlbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZmVlZGJhY2snLFxuICAgICAgICAgICAgbGFiZWw6ICdGZWVkYmFjaycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2VmZmljaWVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdFZmZpY2llbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NpZGUgbmF2JyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2lkZSBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndG9wIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1RvcCBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdjb21wb25lbnQnLFxuICAgIGxhYmVsOiAnQ29tcG9uZW50JyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Jhc2ljJyxcbiAgICAgICAgbGFiZWw6ICdCYXNpYycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsYXlvdXQnLFxuICAgICAgICAgICAgbGFiZWw6ICdMYXlvdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xvcicsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbG9yJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHlwb2dyYXBoeScsXG4gICAgICAgICAgICBsYWJlbDogJ1R5cG9ncmFwaHknLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpY29uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnSWNvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2J1dHRvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0J1dHRvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgIGxhYmVsOiAnRm9ybScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYWRpbycsXG4gICAgICAgICAgICBsYWJlbDogJ1JhZGlvJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY2hlY2tib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdDaGVja2JveCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2lucHV0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnSW5wdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpbnB1dC1udW1iZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdJbnB1dE51bWJlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NlbGVjdCcsXG4gICAgICAgICAgICBsYWJlbDogJ1NlbGVjdCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhc2NhZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FzY2FkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzd2l0Y2gnLFxuICAgICAgICAgICAgbGFiZWw6ICdTd2l0Y2gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzbGlkZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdTbGlkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0aW1lLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1RpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRlLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0RhdGVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRldGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlVGltZVBpY2tlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3VwbG9hZCcsXG4gICAgICAgICAgICBsYWJlbDogJ1VwbG9hZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3JhdGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdSYXRlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RhdGEnLFxuICAgICAgICBsYWJlbDogJ0RhdGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGFibGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWJsZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhZycsXG4gICAgICAgICAgICBsYWJlbDogJ1RhZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Byb2dyZXNzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUHJvZ3Jlc3MnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0cmVlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVHJlZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3BhZ2luYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdQYWdpbmF0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYmFkZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdCYWRnZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbm90aWNlJyxcbiAgICAgICAgbGFiZWw6ICdOb3RpY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYWxlcnQnLFxuICAgICAgICAgICAgbGFiZWw6ICdBbGVydCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2xvYWRpbmcnLFxuICAgICAgICAgICAgbGFiZWw6ICdMb2FkaW5nJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZScsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdtZXNzYWdlLWJveCcsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2VCb3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdub3RpZmljYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdOb3RpZmljYXRpb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25hdmlnYXRpb24nLFxuICAgICAgICBsYWJlbDogJ05hdmlnYXRpb24nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVudScsXG4gICAgICAgICAgICBsYWJlbDogJ01lbnUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWJzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFicycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JyZWFkY3J1bWInLFxuICAgICAgICAgICAgbGFiZWw6ICdCcmVhZGNydW1iJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZHJvcGRvd24nLFxuICAgICAgICAgICAgbGFiZWw6ICdEcm9wZG93bicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3N0ZXBzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3RlcHMnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ290aGVycycsXG4gICAgICAgIGxhYmVsOiAnT3RoZXJzJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2RpYWxvZycsXG4gICAgICAgICAgICBsYWJlbDogJ0RpYWxvZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Rvb2x0aXAnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb29sdGlwJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncG9wb3ZlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1BvcG92ZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXJkJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FyZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhcm91c2VsJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2Fyb3VzZWwnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xsYXBzZScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbGxhcHNlJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdyZXNvdXJjZScsXG4gICAgbGFiZWw6ICdSZXNvdXJjZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZScsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50cycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ3NrZXRjaCcsXG4gICAgICAgIGxhYmVsOiAnU2tldGNoIFRlbXBsYXRlcycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RvY3MnLFxuICAgICAgICBsYWJlbDogJ0Rlc2lnbiBEb2N1bWVudGF0aW9uJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

I fixed it

**Review by tolking — APPROVED** [review]

**Review by warmthsea — COMMENTED** [review]
I think this is best to keep in line with the previous multi-line display.

```scss
margin-left: 6px;
gap: 4px 6px;
```

screenshots

**Comment by zzjiaxiang** [comment]
Both choices make sense, which one should we choose?

**Comment by tolking** [comment]
IMO, It is better to maintain consistency with the Select components. [latest design](https://www.figma.com/community/file/1305760370797950824)

**Comment by btea** [comment]
I don't know if there is something wrong with the link I visited, I don't see any design diagram of the `cascader` component when an option is selected.

**Comment by tolking** [comment]
The Select components is a new design.

**Review by warmthsea — APPROVED** [review]

**Comment by btea** [comment]
This problem seems to exist still when the size value is `small`.

**Comment by zzjiaxiang** [comment]
Maintained consistency with the Select component style.

[preview](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5sYXJnZSBjYXNjYWRlci9zZWxlY3Q8L3A+XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJsYXJnZVwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgLz5cbiAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDE2cHhcIj5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgIHNpemU9XCJsYXJnZVwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG4gIDxwPmRlZmF1bHQgY2FzY2FkZXIvc2VsZWN0PC9wPlxuICA8ZWwtY2FzY2FkZXJcbiAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIDpwcm9wcz1cInByb3BzMVwiXG4gICAgY2xlYXJhYmxlXG4gICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAvPlxuICA8ZGl2IHN0eWxlPVwibWFyZ2luLXRvcDogMTZweFwiPlxuICAgIDxlbC1zZWxlY3RcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICBtdWx0aXBsZVxuICAgICAgcGxhY2Vob2xkZXI9XCJTZWxlY3RcIlxuICAgICAgc3R5bGU9XCJ3aWR0aDogMjQwcHhcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8cD5zbWFsbCBjYXNjYWRlci9zZWxlY3Q8L3A+XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJzbWFsbFwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgLz5cbiAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDE2cHhcIj5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoKVxuY29uc3QgdmFsdWUxID0gcmVmKFsnY29uc2lzdGVuY3knXSlcbmNvbnN0IHByb3BzMSA9IHtcbiAgbXVsdGlwbGU6IHRydWUsXG4gIGNoZWNrU3RyaWN0bHk6IHRydWUsXG59XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ2d1aWRlJyxcbiAgICBsYWJlbDogJ0d1aWRlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Rpc2NpcGxpbmVzJyxcbiAgICAgICAgbGFiZWw6ICdEaXNjaXBsaW5lcycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb25zaXN0ZW5jeScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnNpc3RlbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZmVlZGJhY2snLFxuICAgICAgICAgICAgbGFiZWw6ICdGZWVkYmFjaycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2VmZmljaWVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdFZmZpY2llbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NpZGUgbmF2JyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2lkZSBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndG9wIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1RvcCBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdjb21wb25lbnQnLFxuICAgIGxhYmVsOiAnQ29tcG9uZW50JyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Jhc2ljJyxcbiAgICAgICAgbGFiZWw6ICdCYXNpYycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsYXlvdXQnLFxuICAgICAgICAgICAgbGFiZWw6ICdMYXlvdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xvcicsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbG9yJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHlwb2dyYXBoeScsXG4gICAgICAgICAgICBsYWJlbDogJ1R5cG9ncmFwaHknLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpY29uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnSWNvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2J1dHRvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0J1dHRvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgIGxhYmVsOiAnRm9ybScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYWRpbycsXG4gICAgICAgICAgICBsYWJlbDogJ1JhZGlvJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY2hlY2tib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdDaGVja2JveCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2lucHV0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnSW5wdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpbnB1dC1udW1iZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdJbnB1dE51bWJlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NlbGVjdCcsXG4gICAgICAgICAgICBsYWJlbDogJ1NlbGVjdCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhc2NhZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FzY2FkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzd2l0Y2gnLFxuICAgICAgICAgICAgbGFiZWw6ICdTd2l0Y2gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzbGlkZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdTbGlkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0aW1lLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1RpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRlLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0RhdGVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRldGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlVGltZVBpY2tlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3VwbG9hZCcsXG4gICAgICAgICAgICBsYWJlbDogJ1VwbG9hZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3JhdGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdSYXRlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RhdGEnLFxuICAgICAgICBsYWJlbDogJ0RhdGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGFibGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWJsZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhZycsXG4gICAgICAgICAgICBsYWJlbDogJ1RhZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Byb2dyZXNzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUHJvZ3Jlc3MnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0cmVlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVHJlZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3BhZ2luYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdQYWdpbmF0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYmFkZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdCYWRnZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbm90aWNlJyxcbiAgICAgICAgbGFiZWw6ICdOb3RpY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYWxlcnQnLFxuICAgICAgICAgICAgbGFiZWw6ICdBbGVydCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2xvYWRpbmcnLFxuICAgICAgICAgICAgbGFiZWw6ICdMb2FkaW5nJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZScsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdtZXNzYWdlLWJveCcsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2VCb3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdub3RpZmljYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdOb3RpZmljYXRpb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25hdmlnYXRpb24nLFxuICAgICAgICBsYWJlbDogJ05hdmlnYXRpb24nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVudScsXG4gICAgICAgICAgICBsYWJlbDogJ01lbnUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWJzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFicycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JyZWFkY3J1bWInLFxuICAgICAgICAgICAgbGFiZWw6ICdCcmVhZGNydW1iJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZHJvcGRvd24nLFxuICAgICAgICAgICAgbGFiZWw6ICdEcm9wZG93bicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3N0ZXBzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3RlcHMnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ290aGVycycsXG4gICAgICAgIGxhYmVsOiAnT3RoZXJzJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2RpYWxvZycsXG4gICAgICAgICAgICBsYWJlbDogJ0RpYWxvZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Rvb2x0aXAnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb29sdGlwJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncG9wb3ZlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1BvcG92ZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXJkJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FyZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhcm91c2VsJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2Fyb3VzZWwnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xsYXBzZScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbGxhcHNlJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdyZXNvdXJjZScsXG4gICAgbGFiZWw6ICdSZXNvdXJjZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZScsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50cycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ3NrZXRjaCcsXG4gICAgICAgIGxhYmVsOiAnU2tldGNoIFRlbXBsYXRlcycsXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RvY3MnLFxuICAgICAgICBsYWJlbDogJ0Rlc2lnbiBEb2N1bWVudGF0aW9uJyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by zzjiaxiang** [comment]
> This problem seems to exist still when the size value is `small`.

done

File: packages/components/cascader/src/cascader.vue [hunk 1]
```diff
@@ -294,9 +294,7 @@ const presentTags: Ref<Tag[]> = ref([])
 const allPresentTags: Ref<Tag[]> = ref([])
 const suggestions: Ref<CascaderNode[]> = ref([])
 
-const cascaderStyle = computed<StyleValue>(() => {
-  return attrs.style as StyleValue
-})
+const cascaderStyle = computed<StyleValue>(() => attrs.style as StyleValue)
```
Comment (btea) [inline packages/components/cascader/src/cascader.vue:297]: We should modify the code in a PR only related to the current problem to be solved. Other irrelevant changes can easily distract attention. If you want to change it, it's best to put it in a new refactoring PR.

**Review by tolking — APPROVED** [review]

**Comment by btea** [comment]
When set to filterable, the input box seems to cause the bottom margin to be too large, and the input box does not seem aligned with the label. [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5sYXJnZSBjYXNjYWRlci9zZWxlY3Q8L3A+XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJsYXJnZVwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8cD5kZWZhdWx0IGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAgPGVsLWNhc2NhZGVyXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG4gIDxwPnNtYWxsIGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAgPGVsLWNhc2NhZGVyXG4gICAgc2l6ZT1cInNtYWxsXCJcbiAgICB2LW1vZGVsPVwidmFsdWUxXCJcbiAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgIDpwcm9wcz1cInByb3BzMVwiXG4gICAgY2xlYXJhYmxlXG4gICAgZmlsdGVyYWJsZVxuICAgIHN0eWxlPVwid2lkdGg6IDQ2MHB4XCJcbiAgLz5cbiAgPGRpdiBzdHlsZT1cIm1hcmdpbi10b3A6IDE2cHhcIj5cbiAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIGZpbHRlcmFibGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICAgIHNpemU9XCJzbWFsbFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoKVxuY29uc3QgdmFsdWUxID0gcmVmKFsnY29uc2lzdGVuY3knXSlcbmNvbnN0IHByb3BzMSA9IHtcbiAgbXVsdGlwbGU6IHRydWUsXG4gIGNoZWNrU3RyaWN0bHk6IHRydWUsXG59XG5cbmNvbnN0IG9wdGlvbnMgPSBbXG4gIHtcbiAgICB2YWx1ZTogJ2d1aWRlJyxcbiAgICBsYWJlbDogJ0d1aWRlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Rpc2NpcGxpbmVzJyxcbiAgICAgICAgbGFiZWw6ICdEaXNjaXBsaW5lcycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb25zaXN0ZW5jeScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnNpc3RlbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZmVlZGJhY2snLFxuICAgICAgICAgICAgbGFiZWw6ICdGZWVkYmFjaycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2VmZmljaWVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdFZmZpY2llbmN5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ29udHJvbGxhYmlsaXR5JyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICduYXZpZ2F0aW9uJyxcbiAgICAgICAgbGFiZWw6ICdOYXZpZ2F0aW9uJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NpZGUgbmF2JyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2lkZSBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndG9wIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1RvcCBOYXZpZ2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdjb21wb25lbnQnLFxuICAgIGxhYmVsOiAnQ29tcG9uZW50JyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Jhc2ljJyxcbiAgICAgICAgbGFiZWw6ICdCYXNpYycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsYXlvdXQnLFxuICAgICAgICAgICAgbGFiZWw6ICdMYXlvdXQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjb2xvcicsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbG9yJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHlwb2dyYXBoeScsXG4gICAgICAgICAgICBsYWJlbDogJ1R5cG9ncmFwaHknLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdpY29uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnSWNvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2J1dHRvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0J1dHRvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgIGxhYmVsOiAnRm9ybScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYWRpbycsXG4gICAgICAgICAgICBsYWJlbDogJ1JhZGlvJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY2hlY2tib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdDaGVja2JveCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3NlbGVjdCcsXG4gICAgICAgICAgICBsYWJlbDogJ1NlbGVjdCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Nhc2NhZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2FzY2FkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzd2l0Y2gnLFxuICAgICAgICAgICAgbGFiZWw6ICdTd2l0Y2gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzbGlkZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdTbGlkZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0aW1lLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ1RpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRlLXBpY2tlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0RhdGVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdkYXRldGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlVGltZVBpY2tlcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3VwbG9hZCcsXG4gICAgICAgICAgICBsYWJlbDogJ1VwbG9hZCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3JhdGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdSYXRlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZm9ybScsXG4gICAgICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2RhdGEnLFxuICAgICAgICBsYWJlbDogJ0RhdGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGFibGUnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWJsZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhZycsXG4gICAgICAgICAgICBsYWJlbDogJ1RhZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3Byb2dyZXNzJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUHJvZ3Jlc3MnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0cmVlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVHJlZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3BhZ2luYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdQYWdpbmF0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYmFkZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdCYWRnZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbm90aWNlJyxcbiAgICAgICAgbGFiZWw6ICdOb3RpY2UnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnYWxlcnQnLFxuICAgICAgICAgICAgbGFiZWw6ICdBbGVydCcsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2xvYWRpbmcnLFxuICAgICAgICAgICAgbGFiZWw6ICdMb2FkaW5nJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZScsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdtZXNzYWdlLWJveCcsXG4gICAgICAgICAgICBsYWJlbDogJ01lc3NhZ2VCb3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdub3RpZmljYXRpb24nLFxuICAgICAgICAgICAgbGFiZWw6ICdOb3RpZmljYXRpb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9XG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAncmVzb3VyY2UnLFxuICAgIGxhYmVsOiAnUmVzb3VyY2UnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnYXh1cmUnLFxuICAgICAgICBsYWJlbDogJ0F4dXJlIENvbXBvbmVudHMnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdza2V0Y2gnLFxuICAgICAgICBsYWJlbDogJ1NrZXRjaCBUZW1wbGF0ZXMnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkb2NzJyxcbiAgICAgICAgbGFiZWw6ICdEZXNpZ24gRG9jdW1lbnRhdGlvbicsXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

QQ_1731940376527

**Review by warmthsea — COMMENTED** [review]
The cursor position seems to be wrong.

screenshots

**Review by btea — APPROVED** [review]
LGTM

**Comment by warmthsea** [comment]
@tolking @btea 

After the change, the cursor and label of the new row are at the same distance from the left border, but they look very close. Do you think this is reasonable? (Select has always been like this)

#### Select

image

### [Before Cascader](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5sYXJnZSBjYXNjYWRlci9zZWxlY3Q8L3A+XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJsYXJnZVwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8cD5kZWZhdWx0IGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAgPGVsLWNhc2NhZGVyXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG4gIDxwPnNtYWxsIGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAge3t2YWx1ZX19XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJzbWFsbFwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICBzaXplPVwic21hbGxcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZhbHVlID0gcmVmKFsgXCJndWlkZTJcIiwgXCJndWlkZVwiLCBcImNvbXBvbmVudFwiLCBcInJlc291cmNlXCIgXSlcbmNvbnN0IHZhbHVlMSA9IHJlZihbIFsgXCJndWlkZVwiLCBcImRpc2NpcGxpbmVzXCIsIFwiY29uc2lzdGVuY3lcIiBdLCBbIFwiZ3VpZGVcIiwgXCJkaXNjaXBsaW5lc1wiLCBcImZlZWRiYWNrXCIgXSwgWyBcImd1aWRlXCIsIFwiZGlzY2lwbGluZXNcIiwgXCJlZmZpY2llbmN5XCIgXSwgWyBcImd1aWRlXCIsIFwiZGlzY2lwbGluZXNcIiwgXCJjb250cm9sbGFiaWxpdHlcIiBdIF0pXG5jb25zdCBwcm9wczEgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5jb25zdCBvcHRpb25zID0gW1xueyB2YWx1ZTogJ2d1aWRlMScsXG4gICAgbGFiZWw6ICdHdWkxZGUnLH0sXG4gICAgeyB2YWx1ZTogJ2d1aWRlMicsXG4gICAgbGFiZWw6ICdHdWkxZGUyJyx9LFxuICB7XG4gICAgdmFsdWU6ICdndWlkZScsXG4gICAgbGFiZWw6ICdHdWlkZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkaXNjaXBsaW5lcycsXG4gICAgICAgIGxhYmVsOiAnRGlzY2lwbGluZXMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29uc2lzdGVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdDb25zaXN0ZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2ZlZWRiYWNrJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRmVlZGJhY2snLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdlZmZpY2llbmN5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnRWZmaWNpZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzaWRlIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1NpZGUgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RvcCBuYXYnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb3AgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnY29tcG9uZW50JyxcbiAgICBsYWJlbDogJ0NvbXBvbmVudCcsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdiYXNpYycsXG4gICAgICAgIGxhYmVsOiAnQmFzaWMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbGF5b3V0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGF5b3V0JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29sb3InLFxuICAgICAgICAgICAgbGFiZWw6ICdDb2xvcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3R5cG9ncmFwaHknLFxuICAgICAgICAgICAgbGFiZWw6ICdUeXBvZ3JhcGh5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnaWNvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0ljb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdidXR0b24nLFxuICAgICAgICAgICAgbGFiZWw6ICdCdXR0b24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncmFkaW8nLFxuICAgICAgICAgICAgbGFiZWw6ICdSYWRpbycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NoZWNrYm94JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2hlY2tib3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzZWxlY3QnLFxuICAgICAgICAgICAgbGFiZWw6ICdTZWxlY3QnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXNjYWRlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0Nhc2NhZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc3dpdGNoJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3dpdGNoJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc2xpZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2xpZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdUaW1lUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZXRpbWUtcGlja2VyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRGF0ZVRpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd1cGxvYWQnLFxuICAgICAgICAgICAgbGFiZWw6ICdVcGxvYWQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYXRlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUmF0ZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICAgICAgbGFiZWw6ICdGb3JtJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkYXRhJyxcbiAgICAgICAgbGFiZWw6ICdEYXRhJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhYmxlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFibGUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWcnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWcnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwcm9ncmVzcycsXG4gICAgICAgICAgICBsYWJlbDogJ1Byb2dyZXNzJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHJlZScsXG4gICAgICAgICAgICBsYWJlbDogJ1RyZWUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwYWdpbmF0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUGFnaW5hdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JhZGdlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQmFkZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25vdGljZScsXG4gICAgICAgIGxhYmVsOiAnTm90aWNlJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2FsZXJ0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQWxlcnQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsb2FkaW5nJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTG9hZGluZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ21lc3NhZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZS1ib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlQm94JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbm90aWZpY2F0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTm90aWZpY2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfVxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ3Jlc291cmNlJyxcbiAgICBsYWJlbDogJ1Jlc291cmNlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlJyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnc2tldGNoJyxcbiAgICAgICAgbGFiZWw6ICdTa2V0Y2ggVGVtcGxhdGVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZG9jcycsXG4gICAgICAgIGxhYmVsOiAnRGVzaWduIERvY3VtZW50YXRpb24nLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6e319)

image


#### [After  Cascader](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8cD5sYXJnZSBjYXNjYWRlci9zZWxlY3Q8L3A+XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJsYXJnZVwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICBzaXplPVwibGFyZ2VcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuICA8cD5kZWZhdWx0IGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAgPGVsLWNhc2NhZGVyXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgICAgPGVsLW9wdGlvblxuICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgPC9kaXY+XG4gIDxwPnNtYWxsIGNhc2NhZGVyL3NlbGVjdDwvcD5cbiAge3t2YWx1ZX19XG4gIDxlbC1jYXNjYWRlclxuICAgIHNpemU9XCJzbWFsbFwiXG4gICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICA6cHJvcHM9XCJwcm9wczFcIlxuICAgIGNsZWFyYWJsZVxuICAgIGZpbHRlcmFibGVcbiAgICBzdHlsZT1cIndpZHRoOiA0NjBweFwiXG4gIC8+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxNnB4XCI+XG4gICAgPGVsLXNlbGVjdFxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIG11bHRpcGxlXG4gICAgICBmaWx0ZXJhYmxlXG4gICAgICBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgICBzaXplPVwic21hbGxcIlxuICAgID5cbiAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICAgIC8+XG4gICAgPC9lbC1zZWxlY3Q+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZhbHVlID0gcmVmKFsgXCJndWlkZTJcIiwgXCJndWlkZVwiLCBcImNvbXBvbmVudFwiLCBcInJlc291cmNlXCIgXSlcbmNvbnN0IHZhbHVlMSA9IHJlZihbIFsgXCJndWlkZVwiLCBcImRpc2NpcGxpbmVzXCIsIFwiY29uc2lzdGVuY3lcIiBdLCBbIFwiZ3VpZGVcIiwgXCJkaXNjaXBsaW5lc1wiLCBcImZlZWRiYWNrXCIgXSwgWyBcImd1aWRlXCIsIFwiZGlzY2lwbGluZXNcIiwgXCJlZmZpY2llbmN5XCIgXSwgWyBcImd1aWRlXCIsIFwiZGlzY2lwbGluZXNcIiwgXCJjb250cm9sbGFiaWxpdHlcIiBdIF0pXG5jb25zdCBwcm9wczEgPSB7XG4gIG11bHRpcGxlOiB0cnVlLFxuICBjaGVja1N0cmljdGx5OiB0cnVlLFxufVxuXG5jb25zdCBvcHRpb25zID0gW1xueyB2YWx1ZTogJ2d1aWRlMScsXG4gICAgbGFiZWw6ICdHdWkxZGUnLH0sXG4gICAgeyB2YWx1ZTogJ2d1aWRlMicsXG4gICAgbGFiZWw6ICdHdWkxZGUyJyx9LFxuICB7XG4gICAgdmFsdWU6ICdndWlkZScsXG4gICAgbGFiZWw6ICdHdWlkZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkaXNjaXBsaW5lcycsXG4gICAgICAgIGxhYmVsOiAnRGlzY2lwbGluZXMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29uc2lzdGVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdDb25zaXN0ZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2ZlZWRiYWNrJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRmVlZGJhY2snLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdlZmZpY2llbmN5JyxcbiAgICAgICAgICAgIGxhYmVsOiAnRWZmaWNpZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgICBsYWJlbDogJ0NvbnRyb2xsYWJpbGl0eScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzaWRlIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1NpZGUgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RvcCBuYXYnLFxuICAgICAgICAgICAgbGFiZWw6ICdUb3AgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnY29tcG9uZW50JyxcbiAgICBsYWJlbDogJ0NvbXBvbmVudCcsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdiYXNpYycsXG4gICAgICAgIGxhYmVsOiAnQmFzaWMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbGF5b3V0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGF5b3V0JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29sb3InLFxuICAgICAgICAgICAgbGFiZWw6ICdDb2xvcicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3R5cG9ncmFwaHknLFxuICAgICAgICAgICAgbGFiZWw6ICdUeXBvZ3JhcGh5JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnaWNvbicsXG4gICAgICAgICAgICBsYWJlbDogJ0ljb24nLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdidXR0b24nLFxuICAgICAgICAgICAgbGFiZWw6ICdCdXR0b24nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICBsYWJlbDogJ0Zvcm0nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAncmFkaW8nLFxuICAgICAgICAgICAgbGFiZWw6ICdSYWRpbycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2NoZWNrYm94JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQ2hlY2tib3gnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzZWxlY3QnLFxuICAgICAgICAgICAgbGFiZWw6ICdTZWxlY3QnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdjYXNjYWRlcicsXG4gICAgICAgICAgICBsYWJlbDogJ0Nhc2NhZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc3dpdGNoJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU3dpdGNoJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnc2xpZGVyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnU2xpZGVyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndGltZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdUaW1lUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZS1waWNrZXInLFxuICAgICAgICAgICAgbGFiZWw6ICdEYXRlUGlja2VyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnZGF0ZXRpbWUtcGlja2VyJyxcbiAgICAgICAgICAgIGxhYmVsOiAnRGF0ZVRpbWVQaWNrZXInLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd1cGxvYWQnLFxuICAgICAgICAgICAgbGFiZWw6ICdVcGxvYWQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdyYXRlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUmF0ZScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2Zvcm0nLFxuICAgICAgICAgICAgbGFiZWw6ICdGb3JtJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkYXRhJyxcbiAgICAgICAgbGFiZWw6ICdEYXRhJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3RhYmxlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnVGFibGUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICd0YWcnLFxuICAgICAgICAgICAgbGFiZWw6ICdUYWcnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwcm9ncmVzcycsXG4gICAgICAgICAgICBsYWJlbDogJ1Byb2dyZXNzJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAndHJlZScsXG4gICAgICAgICAgICBsYWJlbDogJ1RyZWUnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdwYWdpbmF0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUGFnaW5hdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2JhZGdlJyxcbiAgICAgICAgICAgIGxhYmVsOiAnQmFkZ2UnLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogJ25vdGljZScsXG4gICAgICAgIGxhYmVsOiAnTm90aWNlJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ2FsZXJ0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnQWxlcnQnLFxuICAgICAgICAgIH0sXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdsb2FkaW5nJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTG9hZGluZycsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ21lc3NhZ2UnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbWVzc2FnZS1ib3gnLFxuICAgICAgICAgICAgbGFiZWw6ICdNZXNzYWdlQm94JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbm90aWZpY2F0aW9uJyxcbiAgICAgICAgICAgIGxhYmVsOiAnTm90aWZpY2F0aW9uJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfVxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ3Jlc291cmNlJyxcbiAgICBsYWJlbDogJ1Jlc291cmNlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlJyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnc2tldGNoJyxcbiAgICAgICAgbGFiZWw6ICdTa2V0Y2ggVGVtcGxhdGVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZG9jcycsXG4gICAgICAgIGxhYmVsOiAnRGVzaWduIERvY3VtZW50YXRpb24nLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE4Mjg1LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn1cbiIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xODI4NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTgyODUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)
image

**Comment by btea** [comment]
IMO, the revised style is more reasonable.

**Comment by tolking** [comment]
I support keeping the style consistent

**Review by warmthsea — APPROVED** [review]

**Comment by zzjiaxiang** [comment]
What else needs to be done to merge into the dev branch ?
