### PR TITLE
fix(time-picker): update oldValue when visible change

### LINKED ISSUE #1561: [bug report] TimePicker Click to cancel the bug
### Element Plus version
1.0.2-beta.33

### OS/Browsers version
all

### Vue version
3.0.7

### Reproduction Link
https://jsfiddle.net/iamkun/ods20kt/

### Steps to reproduce
重现链接直接看官网例子即可：https://element-plus.org/#/zh-CN/component/time-picker
1、更改时间并确定
2、再次打开更改面板，点击取消

### What is Expected?
点击取消后，时间不变化

### What is actually happening?
点击取消后，时间变成了初始值，element2.0没有这个bug

### PR DESCRIPTION
**Pull request by inottn**
fix #1561

I found #1633 was trying to solve the same problem. I prefer to use watch to update oldValue. Because in the current version, there is more than one place that needs to do this operation. For example, click on the outside of pick panel.

In addition, range mode also had this problem. So I fixed it together.

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/time-picker/src/time-picker-com/panel-time-range.vue [hunk 1]
```diff
@@ -125,6 +126,13 @@ export default defineComponent({
     const minSelectableRange = ref([])
     const maxSelectableRange = ref([])
 
+    // watch
+    watch(() => props.visible, val => {
+      if (!val) {
+        oldValue.value = props.parsedValue
+      }
+    })
+
```
Comment (JeremyWuuuuu) [inline packages/time-picker/src/time-picker-com/panel-time-range.vue:135]: Since the code is sort of the same here, can we encapsulate them together with some `useXxxx` hook to avoid duplication?

Comment (inottn) [reply packages/time-picker/src/time-picker-com/panel-time-range.vue:135]: Yes, it is better.

Comment (inottn) [reply packages/time-picker/src/time-picker-com/panel-time-range.vue]: done~

**Review by jw-foss — APPROVED** [review]
