### PR TITLE
fix(components): [el-table] hide tooltip when table is scrolling

### LINKED ISSUE #7995: [Bug Report] [Component] el-table-column设置show-overflow-tooltip属性后tooltip滚动溢出问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome99.0.4844.84/Windows10.0 x64`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`
- `el-tooltip`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-zu7v3m?file=/src/App.vue)

### Steps to reproduce

`el-table`中的`el-table-column`组件在设置`show-overflow-tooltip`属性后，`hover`上去出现tooltip，在鼠标进行内容滚动时，tooltip会跟随hover激活的一栏滚动并溢出，目前采用的不成熟解决方案如下：
#### 方案一：
```JavaScript
app.directive("hidde-tooltip", {
	mounted (el: HTMLElement) {
		console.log(el);
		// 监听表格的mousewheel
		el.addEventListener("mousewheel", (e: any) => {
			const tooltip_ele = document.querySelector(".el-popper.is-dark");
			if (tooltip_ele) {
				(tooltip_ele as HTMLElement).style.display = "none";
			}
		});
	}
});
```
#### 方案二：
```JavaScript
import {onBeforeUnmount, onMounted} from "vue";

export function useElTableTooltip() {
	let app = document.body;

	const isIncludes = (path_arr, dom_arr) => {
		return [...dom_arr].some(dom => {
			return path_arr.includes(dom);
		});
	};

	const handleMouseWheel = (e) => {
		// 事件对象源中匹配el-table的el-scrollbar;
		const all_el_scrollbars = document.querySelectorAll(".el-table .el-scrollbar");
		if (isIncludes(e.path, all_el_scrollbars)) {
			const tooltip_ele = document.querySelector(".el-popper.is-dark");
			if (tooltip_ele) {
				tooltip_ele.style.display = "none";
			}
		}
	};

	onMounted(() => {
		if (app) {
			// console.log("注册");
			app.addEventListener("mousewheel", handleMouseWheel);
		}
	});

	onBeforeUnmount(() => {
		if (app) {
			// console.log("注销");
			app.removeEventListener("mousewheel", handleMouseWheel);
		}
	});
}
```  
之所以没有采用`ref`获取table中的滚动实例是因为还有一种情况下，table是存在于dialog中动态创建出来的，此时无法通过ref获取。

### What is Expected?

滚动时`tooltip`消失

### What is actually happening?

`tooltip`会跟随hover激活的一栏滚动并溢出table

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by msidolphin**
fix #7995

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/table/src/util.ts [hunk 1]
```diff
@@ -374,6 +382,9 @@ export function createTablePopper(
   })
   on(trigger, 'mouseenter', showPopper)
   on(trigger, 'mouseleave', removePopper)
+  if (scrollContainer) {
+    on(scrollContainer, 'scroll', removePopper)
```
Comment (jw-foss) [inline packages/components/table/src/util.ts:386]: **Suggestion:** I suggest we use `scrollContainer.addEventListener` since `on` has been deprecated

**Review by jw-foss — APPROVED** [review]
