### PR TITLE
fix(components): [menu] resize when dynamic data in horizontal mode

### LINKED ISSUE #8756: [Component] [menu] el-menu 存在异常问题，horizontal 模式，写成组件 异步请求 渲染数据 展现为三个点
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `windows11`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCA+XG5leHBvcnQgZGVmYXVsdCB7XG4gIGRhdGEoKXtcbiAgICByZXR1cm4ge1xuICAgICAgdGFibGVEYXRhOlsxLDIsM11cbiAgICB9XG4gIH0sXG4gIG1vdW50ZWQoKXtcbiAgICB2YXIgX3RoaXMgPSB0aGlzO1xuICAgIHNldFRpbWVvdXQoZnVuY3Rpb24oKXtcbiAgICAgIF90aGlzLnRhYmxlRGF0YSA9IFsxLDIsMyw0LDUsNiw3LDgsOSwxMF1cbiAgICB9LDIwMDApXG4gIH1cbn1cbjwvc2NyaXB0PiBcbiBcbjx0ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51ICA6ZGVmYXVsdC1hY3RpdmU9XCIxXCIgY2xhc3M9XCJlbC1tZW51LWRlbW9cIiBtb2RlPVwiaG9yaXpvbnRhbFwiID5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSB2LWZvcj1cIml0ZW0gaW4gdGFibGVEYXRhXCIgOmluZGV4PVwiaXRlbVwiID57eyBpdGVtIH19PC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

重新渲染 出现无法渲染的问题   可见最小复现环境

### What is Expected?

数据渲染正常

### What is actually happening?

数据渲染异常

### Additional comments

_(empty)_

### LINKED ISSUE #8890: [Style] [menu] 在使用<el-menu>组件时，水平模式下导航栏的宽度够放下7个<el-menu-item>但是只显示一个“主页”的<el-menu-item>，其他的被“...”替换。要刷新多次才会正常显示。
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.4`
- Browser / OS: `Chrome版本 103.0.5060.114（正式版本）`
- Build Tool: `Webpack`

### Related Component

- `el-menu`

### Reproduction Link

[Link](https://www.itourtranslator.com/)

### Steps to reproduce

刚进入首页，导航栏只有“首页”和“...”多次刷新之后才全部显示。

### What is Expected?

随着屏幕宽度逐渐减少，才会出现“...”

### What is actually happening?

屏幕很宽，却不能全部显示。

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by holazz**
closes #8756, closes #8890

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/menu/src/menu.ts [hunk 1]
```diff
@@ -286,6 +289,10 @@ export default defineComponent({
       initMenu()
       if (props.mode === 'horizontal') {
         new Menubar(instance.vnode.el!, nsMenu.namespace.value)
+
+        if (props.ellipsis) {
```
Comment (sxzz) [inline packages/components/menu/src/menu.ts:293]: Please move it to `watch`, since it should be updated when `props.ellipsis` changes.

File: packages/components/menu/src/menu.ts [hunk 2]
```diff
@@ -236,6 +239,15 @@ export default defineComponent({
       }
     )
 
+    watch(
```
Comment (sxzz) [inline packages/components/menu/src/menu.ts:242]: We can use `watchEffect` here, since we should watch `props.mode` too.

Comment (holazz) [reply packages/components/menu/src/menu.ts:242]: You're right, I missed it.

**Review by sxzz — APPROVED** [review]
