### PR TITLE
fix(components): [select & select-v2] status-icon is invalid

### LINKED ISSUE #18437: [Component] [input, select] el-select will show the validate icon when :status-icon of el-form is false if it is put in #suffix slot of el-input
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.10`
- Element Plus Version: `2.8.4`
- Browser / OS: `版本 129.0.6668.70（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-input`
- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSByZWY9XCJmb3JtUmVmXCIgOm1vZGVsPVwiZm9ybVwiIDpzdGF0dXMtaWNvbj1cImZhbHNlXCI+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImxlbmd0aFwiIHByb3A9XCJsZW5ndGhcIiByZXF1aXJlZD5cbiAgICAgICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImZvcm0ubGVuZ3RoXCI+XG4gICAgICAgICAgICA8dGVtcGxhdGUgI3N1ZmZpeD5cbiAgICAgICAgICAgICAgPGVsLXNlbGVjdFxuICAgICAgICAgICAgICAgIHYtbW9kZWw9XCJmb3JtLnVuaXRcIlxuICAgICAgICAgICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICAgICAgICAgIGxhYmVsPVwibVwiXG4gICAgICAgICAgICAgICAgICB2YWx1ZT1cImZlZXRcIlxuICAgICAgICAgICAgICAgIC8+XG4gICAgICAgICAgICAgIDwvZWwtc2VsZWN0PlxuICAgICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgICA8L2VsLWlucHV0PlxuICAgICAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgZm9ybVJlZiA9IHJlZigpO1xuY29uc3QgZm9ybSA9IHJlZih7XG4gIGxlbmd0aDogMSxcbiAgdW5pdDogJ2NtJ1xufSk7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuPC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

click el-input

### What is Expected?

el-select should follow :status-icon of el-form

### What is actually happening?

even :status-icon of el-form is false, el-select will show validate-icon when el-form-item is validated, even though el-input will not show the icon

### Additional comments

when :status-icon of el-form is true, there are two icons in el-input

### PR DESCRIPTION
**Pull request by WangYJEE**
The check result icon is still displayed when status-icon is false

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #18437

### CODE REVIEW

**Comment by WangYJEE** [comment]
image

image

**Comment by tolking** [comment]
Can you provide a demo?

**Comment by WangYJEE** [comment]
> Can you provide a demo?

我这边网络问题打不开playground，重现步骤如下：
1. el-form默认配置` status-icon `为false
2. 表单子项有`ElInput`，` prepend`插槽内有`ElSelect`
3. 先触发`ElInput`的校验error，然后输入值校验通过
4. `ElSelect`出现了` status-icon `图标

代码如下，可以试试：
```vue
<template>
  <el-form
    ref="ruleFormRef"
    :model="ruleForm"
    :rules="rules"
  >
    <el-form-item
      label="Activity name"
      prop="name"
    >
      <el-input v-model="ruleForm.name">
        <template #prepend>
          <el-select
            v-model="ruleForm.region"
            placeholder="Activity zone"
            style="width: 200px"
          >
            <el-option
              label="Zone one"
              value="shanghai"
            />
            <el-option
              label="Zone two"
              value="beijing"
            />
          </el-select>
        </template>
      </el-input>
    </el-form-item>
  </el-form>
</template>

<script>

export default {
  data () {
    return {
      ruleForm: {
        name: '',
        region: ''
      },
      rules: {
        name: [
          { required: true, message: '请输入活动名称', trigger: 'blur' },
          { min: 3, max: 5, message: '长度在 3 到 5 个字符', trigger: 'blur' }
        ],
        region: [
          { required: true, message: '请选择活动区域', trigger: ['blur', 'change'] }
        ]
      }
    }
  }
}
</script>
```

**Review by tolking — APPROVED** [review]

File: packages/components/select/src/useSelect.ts [hunk 1]
```diff
@@ -140,6 +140,8 @@ export const useSelect = (props: ISelectProps, emit) => {
       : !isEmptyValue(props.modelValue)
   })
 
+  const needStatusIcon = computed(() => form?.statusIcon ?? false)
```
Comment (btea) [inline packages/components/select/src/useSelect.ts:143]: The status icon never appears if you use only the `el-form-item` by itself.

**Comment by WangYJEE** [comment]
Just consistent with ElInput's status icon logic.




---Original---
From: ***@***.***&gt;
Date: Tue, Sep 3, 2024 22:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] fix(components): [select &amp; select-v2]status-icon is invalid (PR #18101)




 
@btea commented on this pull request.
 
 
In packages/components/select/src/useSelect.ts:
 &gt; @@ -140,6 +140,8 @@ export const useSelect = (props: ISelectProps, emit) =&gt; {        : !isEmptyValue(props.modelValue)    })   +  const needStatusIcon = computed(() =&gt; form?.statusIcon ?? false)  
The status icon never appears if you use only the el-form-item by itself.

File: packages/components/select-v2/src/select.vue [hunk 2]
```diff
@@ -226,7 +226,7 @@
               <component :is="clearIcon" />
             </el-icon>
             <el-icon
-              v-if="validateState && validateIcon"
+              v-if="validateState && validateIcon && needStatusIcon"
```
Comment (btea) [inline packages/components/select-v2/src/select.vue:229]: Perhaps we can consider adjusting the judgment condition here and add a third logical judgment only when `elForm` exists?

Comment (tolking) [reply packages/components/select-v2/src/select.vue:229]: Now this line does not need to be adjusted, the `statusIcon` can only be configured when used in the Form

**Review by btea — APPROVED** [review]
