### PR TITLE
fix(components): [tree] enable ellipsis on label

### LINKED ISSUE #20260: [Component] [table-v2] Tree V2 虚拟化树形控件宽度超出时没有出现滚动条，从而导致内容被挡住
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.7`
- Browser / OS: `Google Chrome131.0.6778.140（正式版本）`
- Build Tool: `Vite`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmludGVyZmFjZSBUcmVlIHtcbiAgaWQ6IHN0cmluZ1xuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGdldEtleSA9IChwcmVmaXg6IHN0cmluZywgaWQ6IG51bWJlcikgPT4ge1xuICByZXR1cm4gYCR7cHJlZml4fS0ke2lkfWBcbn1cblxuY29uc3QgY3JlYXRlRGF0YSA9IChcbiAgbWF4RGVlcDogbnVtYmVyLFxuICBtYXhDaGlsZHJlbjogbnVtYmVyLFxuICBtaW5Ob2Rlc051bWJlcjogbnVtYmVyLFxuICBkZWVwID0gMSxcbiAga2V5ID0gJ25vZGVub2Rlbm9kZW5vZGVub2Rlbm9kZW5vZG5vZGVlJ1xuKTogVHJlZVtdID0+IHtcbiAgbGV0IGlkID0gMFxuICByZXR1cm4gQXJyYXkuZnJvbSh7IGxlbmd0aDogbWluTm9kZXNOdW1iZXIgfSlcbiAgICAuZmlsbChkZWVwKVxuICAgIC5tYXAoKCkgPT4ge1xuICAgICAgY29uc3QgY2hpbGRyZW5OdW1iZXIgPVxuICAgICAgICBkZWVwID09PSBtYXhEZWVwID8gMCA6IE1hdGgucm91bmQoTWF0aC5yYW5kb20oKSAqIG1heENoaWxkcmVuKVxuICAgICAgY29uc3Qgbm9kZUtleSA9IGdldEtleShrZXksICsraWQpXG4gICAgICByZXR1cm4ge1xuICAgICAgICBpZDogbm9kZUtleSxcbiAgICAgICAgbGFiZWw6IG5vZGVLZXksXG4gICAgICAgIGNoaWxkcmVuOiBjaGlsZHJlbk51bWJlclxuICAgICAgICAgID8gY3JlYXRlRGF0YShtYXhEZWVwLCBtYXhDaGlsZHJlbiwgY2hpbGRyZW5OdW1iZXIsIGRlZXAgKyAxLCBub2RlS2V5KVxuICAgICAgICAgIDogdW5kZWZpbmVkLFxuICAgICAgfVxuICAgIH0pXG59XG5cbmNvbnN0IHByb3BzID0ge1xuICB2YWx1ZTogJ2lkJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxufVxuY29uc3QgZGF0YSA9IGNyZWF0ZURhdGEoNCwgMzAsIDQwKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC10cmVlLXYyXG4gICAgc3R5bGU9XCJtYXgtd2lkdGg6IDIwMHB4XCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIDpwcm9wcz1cInByb3BzXCJcbiAgICA6aGVpZ2h0PVwiMjA4XCJcbiAgLz5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjMuNy9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjMuNy90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjMuNC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy4zLjQvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMy43L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4zLjcvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsidnVlVmVyc2lvbiI6IjMuMy40IiwiZXBWZXJzaW9uIjoiMi4zLjcifX0=)

### Steps to reproduce

label文本填写长一点，超出装el-tree-v2组件容器宽度,超出部分会被挡住，不出现滚动条

### What is Expected?

期望出现横向滚动条，使我能够看到完整的信息

### What is actually happening?

没有出现横向滚动条

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Dsaquel**
fixes #20260
This pr add a scrollbar if a long label in a tree is set.

### CODE REVIEW

File: packages/components/tree/src/tree-node-content.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
-<script lang="ts">
```
Comment (Dsaquel) [inline packages/components/tree/src/tree-node-content.ts:1]: changed the filename to be the same as tree-v2.

**Comment by btea** [comment]
Maybe adding ellips is also a good option. https://element-plus.org/en-US/component/text.html#ellipsis

**Comment by Dsaquel** [comment]
Ok i'll change it 👍

**Comment by warmthsea** [comment]
I can't seem to see the diff between the before and after changes.

image

**Comment by Dsaquel** [comment]
That interesting, i cannot reproduce your error.
I have copied whole playground from the issue and pasted into pr preview.
Result: 
image

**Comment by Dsaquel** [comment]
No, its purely subjective, i change it back :+1:

**Review by btea — APPROVED** [review]
Thanks for your work! 👍

File: packages/components/tree/src/tree-node-content.vue [hunk 2]
```diff
@@ -1,5 +1,6 @@
 <script lang="ts">
 import { defineComponent, h, inject, renderSlot } from 'vue'
+import { ElText } from '@element-plus/components/text'
```
Comment (kooriookami) [inline packages/components/tree/src/tree-node-content.vue:3]:
```suggestion
import ElText from '@element-plus/components/text'
```

**Review by kooriookami — DISMISSED** [review]

**Comment by warmthsea** [comment]
> I can't seem to see the diff between the before and after changes.
> 
> image


It seems to be caused by the style.

Need to import text style files:

`import '@element-plus/components/text/style/css'`
`import '@element-plus/components/text/style'`


https://github.com/dsaquel/element-plus/tree/tree-scroll/packages/components/tree/style

Like table use `ElCheckbox`:
https://github.com/dsaquel/element-plus/blob/tree-scroll/packages/components/table/style/index.ts#L3
https://github.com/dsaquel/element-plus/blob/tree-scroll/packages/components/table/src/config.ts#L75

**Review by warmthsea — APPROVED** [review]
