### PR TITLE
fix: [el-input]hidden input is not hidden

### LINKED ISSUE #4116: [Bug Report] hidden input is taking place in document
### Element Plus version
1.1.0-beta.24

### OS/Browsers version
Windows 10 / Chrome 95.0.4638.54

### Vue version
3.2.20

### Reproduction Link
https://codepen.io/kawaiizapic/pen/eYEEaaN

### Steps to reproduce
1. Create a el-input with type="hidden"
2. Look at it.

### What is Expected?
It's fully hidden, does not take any space.

### What is actually happening?
It's taking some space, leaving a big blank.

### PR DESCRIPTION
**Pull request by KawaiiZapic**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

File: packages/components/input/src/input.vue [hunk 1]
```diff
@@ -6,6 +6,7 @@
       {
         'is-disabled': inputDisabled,
         'is-exceed': inputExceed,
+        'is-hidden': type === 'hidden',
```
Comment (JeremyWuuuuu) [inline packages/components/input/src/input.vue:9]: **Suggestion:** use `v-show` to keep the change minimal.

Comment (KawaiiZapic) [reply packages/components/input/src/input.vue]: Thank you for your suggestion, I hear someone said `v-show` is going to be deprecated, but I find no description in the doc of Vue.  
Now using `v-show` instead of CSS class.

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic Thank you for making Element Plus better! :pray:
