### PR TITLE
fix(components): [table-column] column miss update due to key (#8528)

### LINKED ISSUE #8528: [Component] [table-column, table] 使用 v-for 循环生成列，在 el-table-column 组件加上 key属性时，无法修改列的顺序
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table-column`
- `el-table`

### Reproduction Link

[CodePen](https://codepen.io/shibin-cli/pen/yLKLxgG)

### Steps to reproduce

点击按钮 change columns order  后，table 列的顺序没有改变
* 给一个 columns 数组用来表示 table 的列，v-for 来 循环el-table-column，通过调整columns 数组的顺序来改变列的顺序
* 当没有给 el-table-column 组件加上 key属性时，修改columns时，列的顺序是可以改变的
* 给 el-table-column 组件加上key 属性时，修改columns时，列的顺序没法改变

### What is Expected?

 el-table-column 组件加上key 属性时，table 列的顺序可以改变

### What is actually happening?

 el-table-column 组件加上key 属性时，table 列的顺序没办法改变

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by MrWeilian**
Fix: [[Component] [table-column, table] 使用 v-for 循环生成列，在 el-table-column 组件加上 key属性时，无法修改列的顺序 #8528](https://github.com/element-plus/element-plus/issues/8528)

Specific analysis of the problem: [为什么v-for key导致table无法修改列顺序](https://juejin.cn/post/7168308855623909406/)

### CODE REVIEW

File: packages/components/table/src/store/index.ts [hunk 1]
```diff
@@ -99,6 +99,17 @@ function useStore<T>() {
       }
     },
 
+    updateColumnOrder(states: StoreStates, keyList: Array<string>) {
+      const array = unref(states._columns)
+      states._columns.value = array.sort((a, b) => {
+        return keyList.indexOf(a.key) - keyList.indexOf(b.key)
```
[the remark this answers is not in the document]
Comment (MrWeilian) [reply packages/components/table/src/store/index.ts:105]: 大佬你好，十分感谢review和反馈的bug还有修改建议。根据你的建议和留意到有个mentioned的issue，我这2天重新改了实现方式，为了兼容多级表头时候的列切换问题，可能需要你重新大规模review一哈～

**Comment by MrWeilian** [comment]
大佬你好，由于改动比较大，而且节约一下你们的review时间，我把大致的想法和代码的实现描述一下。

这个pr主要针对vue3 diff算法对有 `key` 的同级列表更新的影响，因为跨级更新即使有key也会触发table的重渲染。可以参照当然版本的 [PlayGround](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDgnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA3JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuXVxuXG5jb25zdCBjb2x1bW5UcmVlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBsYWJlbDogJ0RhdGUnLFxuICAgIHByb3A6ICdkYXRlJyxcbiAgICB3aWR0aDogMTIwXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0RlbGl2ZXJ5IEluZm8nLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTmFtZScsXG4gICAgICAgIHByb3A6ICduYW1lJyxcbiAgICAgICAgd2lkdGg6IDEyMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdBZGRyZXNzIEluZm8nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgbGFiZWw6ICdTdGF0ZScsIHByb3A6ICdzdGF0ZScsIHdpZHRoOiAxMjAgfSxcbiAgICAgICAgICB7IGxhYmVsOiAnQ2l0eScsIHByb3A6ICdjaXR5Jywgd2lkdGg6IDEyMCB9LFxuICAgICAgICAgIHsgbGFiZWw6ICdBZGRyZXNzJywgcHJvcDogJ2FkZHJlc3MnIH1cbiAgICAgICAgXVxuICAgICAgfVxuICAgIF1cbiAgfVxuXSlcblxuY29uc3QgY2hhbmdlVHJlZUNvbHVtbnMgPSAoKSA9PiB7XG4gIFtjb2x1bW5UcmVlRGF0YS52YWx1ZVswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMV1dID0gW2NvbHVtblRyZWVEYXRhLnZhbHVlWzFdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVswXV07XG59XG5cbmNvbnN0IGNoYW5nZVRyZWVDb2x1bW5zMiA9ICgpID0+IHtcbiAgW2NvbHVtblRyZWVEYXRhLnZhbHVlWzBdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblswXV0gPSBbY29sdW1uVHJlZURhdGEudmFsdWVbMV0uY2hpbGRyZW5bMF0sIGNvbHVtblRyZWVEYXRhLnZhbHVlWzBdXTtcbn1cblxuY29uc3QgY2hhbmdlVHJlZUNvbHVtbnMzID0gKCkgPT4ge1xuICBbY29sdW1uVHJlZURhdGEudmFsdWVbMF0sIGNvbHVtblRyZWVEYXRhLnZhbHVlWzFdLmNoaWxkcmVuWzFdLmNoaWxkcmVuWzBdXSA9IFtjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMF1dO1xufVxuXG5jb25zdCBjaGFuZ2VUcmVlQ29sdW1uczQgPSAoKSA9PiB7XG4gIFtjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMV0uY2hpbGRyZW5bMV0uY2hpbGRyZW5bMV1dID0gW2NvbHVtblRyZWVEYXRhLnZhbHVlWzFdLmNoaWxkcmVuWzFdLmNoaWxkcmVuWzFdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXV07XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlVHJlZUNvbHVtbnNcIj7mm7TmlLnnrKzkuIDlsYLpobrluo88L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNoYW5nZVRyZWVDb2x1bW5zMlwiPuabtOaUuei3qOS4gOOAgeS6jOWxgumhuuW6jzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlVHJlZUNvbHVtbnMzXCI+5pu05pS56Leo5LiA44CB5LiJ6aG65bqPPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VUcmVlQ29sdW1uczRcIj7mm7TmlLnmnIDlkI7lsYLpobrluo88L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHYtZm9yPVwiZmlyc3QgaW4gY29sdW1uVHJlZURhdGFcIiA6a2V5PVwiZmlyc3QucHJvcFwiIDpwcm9wPVwiZmlyc3QucHJvcFwiIDpsYWJlbD1cImZpcnN0LmxhYmVsXCIgOndpZHRoPVwiZmlyc3Qud2lkdGhcIj5cbiAgICAgIDx0ZW1wbGF0ZSB2LWlmPVwiZmlyc3QuY2hpbGRyZW5cIj5cbiAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiB2LWZvcj1cInNlY29uZCBpbiBmaXJzdC5jaGlsZHJlblwiIDprZXk9XCJzZWNvbmQucHJvcFwiIDpwcm9wPVwic2Vjb25kLnByb3BcIiA6bGFiZWw9XCJzZWNvbmQubGFiZWxcIiA6d2lkdGg9XCJzZWNvbmQud2lkdGhcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgdi1pZj1cInNlY29uZC5jaGlsZHJlblwiPlxuICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiB2LWZvcj1cInRoaXJkIGluIHNlY29uZC5jaGlsZHJlblwiIDprZXk9XCJ0aGlyZC5wcm9wXCIgOnByb3A9XCJ0aGlyZC5wcm9wXCIgOmxhYmVsPVwidGhpcmQubGFiZWxcIiA6d2lkdGg9XCJ0aGlyZC53aWR0aFwiIC8+XG4gICAgICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ6aXBcIiBsYWJlbD1cIlppcFwiIHdpZHRoPVwiMTIwXCIgLz5cbiAgICAgICAgICA8L3RlbXBsYXRlPlxuICAgICAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gIDwvZWwtdGFibGU+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

根据table之前的源码：

`columns`的`render`函数：
image

`insertColumn`：
image

其实上述代码的效果会产生一对一一对应的`dom`和`store.states._columns`的结构，以demo案例的结果如下：

`dom`的：
image

`store.states._columns`的：
image

大致实现：根据这种现状，最新提交的大致的实现思路就是监测 `hidden-columns` 这个 `div` 下的 `dom` 变化，然后在每个 `column` 的组件实例中拿到自己的`el`，也就是`div`，求出当前`div`在`hidden-columns`的`dom树`中的路径，同理求出当前`column`组件的`columnConfig`在`store.states._columns`中的路径，如果路径不一样的话就调整`store.states._columns`的路径。

具体实现：
1. `table.vue`：通过 `useKeyRender` 开启对 dom树 的监测。dom树 改变通过 `store.states.updateOrderFns` 通知所有 column 组件检查更新顺序（观察者模式）。
2. `table-column/index.ts`：每个column组件提供 `updateColumnOrder` 方法，在 mounted 时候插入，unmount 时候删除（对应上述观察者模式）。
3. `table-column/render-helper.ts`：`updateColumnOrder` 具体实现。其实就是计算当前el在dom树中的路径，再调用 store里面的 `updateColumnOrder`。其中 `getTreePath` 的实现在这里，和 `updateColumnOrder` 这里都有用到，主要就是通过回溯计算当前项在树的路径
4. `store/index.ts`：实现 `updateColumnOrder`。计算 `columnConfig`在`store.states._columns`中的路径，然后进行换位以更新源columns数据。

其实大量代码都在处理树形数据上面，如果只处理一层数据的话代码不会这么复杂...主要还是为了兼顾多级表头的情况吧，避免用户直接在多级表头的table中切换第N层的带key的列表无效。table的代码比较复杂，辛苦帮忙review的大佬们了～

**Comment by MrWeilian** [comment]
[切换多级表头带key的PlayGround](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAxJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTYtMDUtMDgnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIHN0YXRlOiAnQ2FsaWZvcm5pYScsXG4gICAgY2l0eTogJ0xvcyBBbmdlbGVzJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICB6aXA6ICdDQSA5MDAzNicsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgc3RhdGU6ICdDYWxpZm9ybmlhJyxcbiAgICBjaXR5OiAnTG9zIEFuZ2VsZXMnLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIHppcDogJ0NBIDkwMDM2JyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTA3JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBzdGF0ZTogJ0NhbGlmb3JuaWEnLFxuICAgIGNpdHk6ICdMb3MgQW5nZWxlcycsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gICAgemlwOiAnQ0EgOTAwMzYnLFxuICB9LFxuXVxuXG5jb25zdCBjb2x1bW5UcmVlRGF0YSA9IHJlZihbXG4gIHtcbiAgICBsYWJlbDogJ0RhdGUnLFxuICAgIHByb3A6ICdkYXRlJyxcbiAgICB3aWR0aDogMTIwXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0RlbGl2ZXJ5IEluZm8nLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTmFtZScsXG4gICAgICAgIHByb3A6ICduYW1lJyxcbiAgICAgICAgd2lkdGg6IDEyMFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdBZGRyZXNzIEluZm8nLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgbGFiZWw6ICdTdGF0ZScsIHByb3A6ICdzdGF0ZScsIHdpZHRoOiAxMjAgfSxcbiAgICAgICAgICB7IGxhYmVsOiAnQ2l0eScsIHByb3A6ICdjaXR5Jywgd2lkdGg6IDEyMCB9LFxuICAgICAgICAgIHsgbGFiZWw6ICdBZGRyZXNzJywgcHJvcDogJ2FkZHJlc3MnIH1cbiAgICAgICAgXVxuICAgICAgfVxuICAgIF1cbiAgfVxuXSlcblxuY29uc3QgY2hhbmdlVHJlZUNvbHVtbnMgPSAoKSA9PiB7XG4gIFtjb2x1bW5UcmVlRGF0YS52YWx1ZVswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMV1dID0gW2NvbHVtblRyZWVEYXRhLnZhbHVlWzFdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVswXV07XG59XG5cbmNvbnN0IGNoYW5nZVRyZWVDb2x1bW5zMiA9ICgpID0+IHtcbiAgW2NvbHVtblRyZWVEYXRhLnZhbHVlWzBdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblswXV0gPSBbY29sdW1uVHJlZURhdGEudmFsdWVbMV0uY2hpbGRyZW5bMF0sIGNvbHVtblRyZWVEYXRhLnZhbHVlWzBdXTtcbn1cblxuY29uc3QgY2hhbmdlVHJlZUNvbHVtbnMzID0gKCkgPT4ge1xuICBbY29sdW1uVHJlZURhdGEudmFsdWVbMF0sIGNvbHVtblRyZWVEYXRhLnZhbHVlWzFdLmNoaWxkcmVuWzFdLmNoaWxkcmVuWzBdXSA9IFtjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMF1dO1xufVxuXG5jb25zdCBjaGFuZ2VUcmVlQ29sdW1uczQgPSAoKSA9PiB7XG4gIFtjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXSwgY29sdW1uVHJlZURhdGEudmFsdWVbMV0uY2hpbGRyZW5bMV0uY2hpbGRyZW5bMV1dID0gW2NvbHVtblRyZWVEYXRhLnZhbHVlWzFdLmNoaWxkcmVuWzFdLmNoaWxkcmVuWzFdLCBjb2x1bW5UcmVlRGF0YS52YWx1ZVsxXS5jaGlsZHJlblsxXS5jaGlsZHJlblswXV07XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGgyPlxuICAgIOeUseS6jmRlbW/mjaLliJfmlbDmja7lhpnmrbvvvIzms6jmhI/mm7TmlLnot6jnuqfmlbDmja7ml7bkv53mjIHliJ3lp4vljJbml7blgJnnmoTmoJHlvaLooajlpLTnu5PmnoRcbiAgPC9oMj5cbiAgPGRpdj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNoYW5nZVRyZWVDb2x1bW5zXCI+5pu05pS556ys5LiA5bGC6aG65bqPPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjaGFuZ2VUcmVlQ29sdW1uczJcIj7mm7TmlLnot6jkuIDjgIHkuozlsYLpobrluo88L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNoYW5nZVRyZWVDb2x1bW5zM1wiPuabtOaUuei3qOS4gOOAgeS4iemhuuW6jzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiY2hhbmdlVHJlZUNvbHVtbnM0XCI+5pu05pS55pyA5ZCO5bGC6aG65bqPPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiB2LWZvcj1cImZpcnN0IGluIGNvbHVtblRyZWVEYXRhXCIgOmtleT1cImZpcnN0LmxhYmVsXCIgOnByb3A9XCJmaXJzdC5wcm9wXCIgOmxhYmVsPVwiZmlyc3QubGFiZWxcIiA6d2lkdGg9XCJmaXJzdC53aWR0aFwiPlxuICAgICAgPHRlbXBsYXRlIHYtaWY9XCJmaXJzdC5jaGlsZHJlblwiPlxuICAgICAgICA8ZWwtdGFibGUtY29sdW1uIHYtZm9yPVwic2Vjb25kIGluIGZpcnN0LmNoaWxkcmVuXCIgOmtleT1cInNlY29uZC5sYWJlbFwiIDpwcm9wPVwic2Vjb25kLnByb3BcIiA6bGFiZWw9XCJzZWNvbmQubGFiZWxcIiA6d2lkdGg9XCJzZWNvbmQud2lkdGhcIj5cbiAgICAgICAgICA8dGVtcGxhdGUgdi1pZj1cInNlY29uZC5jaGlsZHJlblwiPlxuICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiB2LWZvcj1cInRoaXJkIGluIHNlY29uZC5jaGlsZHJlblwiIDprZXk9XCJ0aGlyZC5sYWJlbFwiIDpwcm9wPVwidGhpcmQucHJvcFwiIDpsYWJlbD1cInRoaXJkLmxhYmVsXCIgOndpZHRoPVwidGhpcmQud2lkdGhcIiAvPlxuICAgICAgICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiemlwXCIgbGFiZWw9XCJaaXBcIiB3aWR0aD1cIjEyMFwiIC8+XG4gICAgICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgICAgPC9lbC10YWJsZS1jb2x1bW4+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICA8L2VsLXRhYmxlPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTA2NzktZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMDY3OS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMDY3OS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMDY3OS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

File: packages/components/table/src/store/index.ts [hunk 2]
```diff
@@ -99,10 +101,77 @@ function useStore<T>() {
...
+          continue
+        }
+        if (typeof sourceTreePath[i] !== 'undefined')
+          sourceStr += `.children[${sourceTreePath[i]}]`
+        if (typeof targetTreePath[i] !== 'undefined')
+          targetStr += `.children[${targetTreePath[i]}]`
+      }
+
+      try {
+        eval(`[${sourceStr},${targetStr}]=[${targetStr},${sourceStr}];`)
```
Comment (tolking) [inline packages/components/table/src/store/index.ts:162]: 使用 eval 函数应该不算是一个好主意吧

Comment (MrWeilian) [reply packages/components/table/src/store/index.ts:162]: > 使用 eval 函数应该不算是一个好主意吧

hh我改一下，骚等

Comment (MrWeilian) [reply packages/components/table/src/store/index.ts]: > 使用 eval 函数应该不算是一个好主意吧

大佬你好，这次的 commit 应该更稳了～之前陷进树形的数据，这个函数 `getColumnIndex` 只计算同层index，也许在跨级计算中会有问题，一开始就被我忽视了。
image

但是昨晚再次改动的时候突然想明白了，**改变跨级的数据时`column组件`会重新渲染**，观测到 dom 变化的时候已经重新完成 `patch` 了，所以这个函数并不会处理到 `instance.vnode.el` 已经不在原层级的 `children` 里的情况。所所所以，只用兼顾同级的情况，当新旧的 index 计算不一样的时候再重新 sort 就好了。还可以用回之前的function，改动小了很多，感觉pr的风险也降低了～就很尴尬......😅麻烦大佬再次review
image

**Comment by tolking** [comment]
@MrWeilian 你能够增加一些测试吗？

File: packages/components/table/src/store/watcher.ts [hunk 3]
```diff
@@ -60,6 +60,7 @@ function useWatcher<T>() {
   const leafColumns: Ref<TableColumnCtx<T>[]> = ref([])
   const fixedLeafColumns: Ref<TableColumnCtx<T>[]> = ref([])
   const rightFixedLeafColumns: Ref<TableColumnCtx<T>[]> = ref([])
+  const updateOrderFns: Ref<(() => void)[]> = ref([])
```
Comment (tolking) [inline packages/components/table/src/store/watcher.ts:63]: 感觉 updateOrderFns 可以不需要定义为一个响应式值，直接使用 [] 应该也不会影响代码运行

**Comment by MrWeilian** [comment]
> @MrWeilian 你能够增加一些测试吗？

okok 这几天我找多点案例去测试

**Comment by tolking** [comment]
我的意思是向 table.test.ts 中增加一些测试

**Comment by MrWeilian** [comment]
> 我的意思是向 table.test.ts 中增加一些测试

ok

**Comment by MrWeilian** [comment]
> 我的意思是向 table.test.ts 中增加一些测试

大佬你好，我加了一个 test 例，顺便把 updateOrderFns 的 ref 给干掉了

File: packages/components/table/src/store/watcher.ts [hunk 4]
```diff
@@ -60,7 +60,7 @@ function useWatcher<T>() {
   const leafColumns: Ref<TableColumnCtx<T>[]> = ref([])
   const fixedLeafColumns: Ref<TableColumnCtx<T>[]> = ref([])
   const rightFixedLeafColumns: Ref<TableColumnCtx<T>[]> = ref([])
-  const updateOrderFns: Ref<(() => void)[]> = ref([])
+  const updateOrderFns: () => void[] = []
```
[the remark this answers is not in the document]
Comment (MrWeilian) [reply packages/components/table/src/store/watcher.ts]: > 

已处理～

[the remark this answers is not in the document]
Comment (tolking) [reply packages/components/table/src/store/watcher.ts]: 你改错了，应该是二选一

[the remark this answers is not in the document]
Comment (MrWeilian) [reply packages/components/table/src/store/watcher.ts]: > 你改错了，应该是二选一

对～新的提交已经处理了

**Review by tolking — APPROVED** [review]

File: packages/components/table/src/store/watcher.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (MrWeilian) [reply packages/components/table/src/store/watcher.ts]: 大佬，这个pr还有望合并吗

[the remark this answers is not in the document]
Comment (tolking) [reply packages/components/table/src/store/watcher.ts]: 还需要另外经过至少一位的成员审核通过后才能够合并。

[the remark this answers is not in the document]
Comment (MrWeilian) [reply packages/components/table/src/store/watcher.ts]: 好吧。谢谢

File: packages/components/table/src/table/key-render-helper.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
+// @ts-nocheck
```
Comment (btea) [inline packages/components/table/src/table/key-render-helper.ts:1]: This line can be removed.

File: packages/components/table/src/table/key-render-helper.ts [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+import { onMounted, onUnmounted, ref } from 'vue'
+import type { Ref } from 'vue'
+import type { Table } from './defaults'
+
+export default function useKeyRender(table: Table<[]>) {
+  const observer: Ref = ref(null)
```
Comment (btea) [inline packages/components/table/src/table/key-render-helper.ts:7]:
```suggestion
  const observer = ref<MutationObserver>()
```

File: packages/components/table/src/table/key-render-helper.ts (hunk 5 above)
Comment (MrWeilian) [reply packages/components/table/src/table/key-render-helper.ts:1]: - -大佬改了，但是本地跑 `test` 好像好多用例过不了，代码已经 `reabse` 过最新的 `dev` 了，这是啥情况

Comment (MrWeilian) [reply packages/components/table/src/table/key-render-helper.ts:1]: 😂没事了，可能用了v19的node导致的

File: packages/components/table/src/table/key-render-helper.ts (hunk 6 above)
Comment (MrWeilian) [reply packages/components/table/src/table/key-render-helper.ts]: 已修正

**Review by btea — APPROVED** [review]
