### PR TITLE
fix(components):  [table] row has rowspan when hover it only has background on the first row of this rowspan

### LINKED ISSUE #15384: [Style] [table] el-table表合并之后，鼠标移动上去样式错误
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.9`
- Element Plus Version: `2.4.4`
- Browser / OS: ` Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuXG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDIsXG4gICAgICAgIGNvbHNwYW46IDEsXG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZGl2PlxuXG5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

按照官网步骤合并表格

### What is Expected?

1.合并表格
2.鼠标移动到第一行，左边合并的列不高亮

### What is actually happening?

1.合并表格
2.样式出现错误，鼠标移动到第一行，左边合并的列高亮

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by dowinweb**
table row has rowspan when hover it only has background on the first row of this rowspan
the other rows of which share the rowspan should also give the background of this cell when hover the other rows
Please make sure these boxes are checked before submitting your PR, thank you!

fix #15384
- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by dowinweb** [comment]
fixed [Style] [table] el-table表合并之后，鼠标移动上去样式错误 #15384

**Comment by dowinweb** [comment]
image

**Comment by dowinweb** [comment]
#15384

**Comment by dowinweb** [comment]
> 🧪 Playground Preview: https://element-plus.run/?pr=15529 Please comment the example via this playground if needed.

hover row when it has rowspan the background problem fixed

**Comment by btea** [comment]
cc @element-plus/backers

**Comment by dowinweb** [comment]
cc @kooriookami

**Comment by dowinweb** [comment]
[example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgYXJyYXlTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAocm93SW5kZXggJSAyID09PSAxKSB7XG4gICAgaWYgKGNvbHVtbkluZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4gWzEsIDJdXG4gICAgfSBlbHNlIGlmIChjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgICAgcmV0dXJuIFswLCAwXVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDEgfHwgY29sdW1uSW5kZXggPT09IDMpIHtcbiAgICBpZiAocm93SW5kZXggJSAyID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAyLFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAnMTI5ODcxMjInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICcyMzQnLFxuICAgIGFtb3VudDI6ICczLjInLFxuICAgIGFtb3VudDM6IDEwLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzMyNCcsXG4gICAgYW1vdW50MjogJzEuOScsXG4gICAgYW1vdW50MzogOSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjUnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc2MjEnLFxuICAgIGFtb3VudDI6ICcyLjInLFxuICAgIGFtb3VudDM6IDE3LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzUzOScsXG4gICAgYW1vdW50MjogJzQuMScsXG4gICAgYW1vdW50MzogMTUsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICczMjQnLFxuICAgIGFtb3VudDI6ICcxLjknLFxuICAgIGFtb3VudDM6IDksXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI1JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNjIxJyxcbiAgICBhbW91bnQyOiAnMi4yJyxcbiAgICBhbW91bnQzOiAxNyxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjYnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc1MzknLFxuICAgIGFtb3VudDI6ICc0LjEnLFxuICAgIGFtb3VudDM6IDE1LFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTU1MjktZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by dowinweb** [comment]
> 感谢你的贡献，我认为鼠标悬浮在合并的单元格的时候，应该将合并的单元格所在的行都填充背景色，这样更符合直觉一些。
> 
> Thank you for your contribution, I think when hovering over merged cells, it is more intuitive to fill the rows of merged cells with background color.



> 感谢你的贡献，我认为鼠标悬浮在合并的单元格的时候，应该将合并的单元格所在的行都填充背景色，这样更符合直觉一些。
> 
> Thank you for your contribution, I think when hovering over merged cells, it is more intuitive to fill the rows of merged cells with background color.

You are right. I have fixed this.

**Comment by dowinweb** [comment]
@FrontEndDog  At first i finish this by writing code in the watch hoverRow method, but when you move your mouse from the first row of the cell, to the cell who has rowSan > 1, it didnot trigger the watch method. so i have to do this in the cell event listeners.
image

**Comment by dowinweb** [comment]
@FrontEndDog bro, can this be merged ? any more suggestions?

File: packages/components/table/src/table-body/events-helper.ts [hunk 1]
```diff
@@ -143,7 +160,9 @@ function useEvents<T>(props: Partial<TableBodyProps<T>>) {
   const handleCellMouseLeave = (event) => {
     const cell = getCell(event)
     if (!cell) return
-
+    if (cell.rowSpan > 1) {
+      toggleRowClassByCell(cell.rowSpan, event, removeClass)
```
Comment (btea) [inline packages/components/table/src/table-body/events-helper.ts:164]: You may need to import `addClass` and `removeClass`, otherwise an error will occur.

Comment (dowinweb) [reply packages/components/table/src/table-body/events-helper.ts:164]: OKOK

Comment (dowinweb) [reply packages/components/table/src/table-body/events-helper.ts:164]: @btea  fixed this

**Comment by dowinweb** [comment]
@btea  anything else need to fix

File: packages/components/table/src/table-body/events-helper.ts [hunk 2]
```diff
@@ -60,6 +60,20 @@ function useEvents<T>(props: Partial<TableBodyProps<T>>) {
...
+    event: MouseEvent,
+    toggle: (el: Element, cls: string) => void
+  ) => {
+    let node = event.target.parentNode
+    while (rowSpan > 1) {
+      node = node?.nextSibling
+      toggle(node, 'hover-row')
+      rowSpan--
+    }
+  }
```
Comment (FrontEndDog) [inline packages/components/table/src/table-body/events-helper.ts:75]: [test link](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6c3Bhbi1tZXRob2Q9XCJvYmplY3RTcGFuTWV0aG9kXCIgYm9yZGVyIHN0eWxlPVwid2lkdGg6IDEwMCU7IG1hcmdpbi10b3A6IDIwcHhcIj5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImlkXCIgbGFiZWw9XCJJRFwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MVwiIGxhYmVsPVwiQW1vdW50IDFcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50MlwiIGxhYmVsPVwiQW1vdW50IDJcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiYW1vdW50M1wiIGxhYmVsPVwiQW1vdW50IDNcIiAvPlxuICAgIDwvZWwtdGFibGU+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB0eXBlIHsgVGFibGVDb2x1bW5DdHggfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmludGVyZmFjZSBVc2VyIHtcbiAgaWQ6IHN0cmluZ1xuICBuYW1lOiBzdHJpbmdcbiAgYW1vdW50MTogc3RyaW5nXG4gIGFtb3VudDI6IHN0cmluZ1xuICBhbW91bnQzOiBudW1iZXJcbn1cblxuaW50ZXJmYWNlIFNwYW5NZXRob2RQcm9wcyB7XG4gIHJvdzogVXNlclxuICBjb2x1bW46IFRhYmxlQ29sdW1uQ3R4PFVzZXI+XG4gIHJvd0luZGV4OiBudW1iZXJcbiAgY29sdW1uSW5kZXg6IG51bWJlclxufVxuXG5jb25zdCBhcnJheVNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICBpZiAoY29sdW1uSW5kZXggPT09IDApIHtcbiAgICAgIHJldHVybiBbMSwgMl1cbiAgICB9IGVsc2UgaWYgKGNvbHVtbkluZGV4ID09PSAxKSB7XG4gICAgICByZXR1cm4gWzAsIDBdXG4gICAgfVxuICB9XG59XG5cbmNvbnN0IG9iamVjdFNwYW5NZXRob2QgPSAoe1xuICByb3csXG4gIGNvbHVtbixcbiAgcm93SW5kZXgsXG4gIGNvbHVtbkluZGV4LFxufTogU3Bhbk1ldGhvZFByb3BzKSA9PiB7XG4gIGlmIChjb2x1bW5JbmRleCA9PT0gMCkge1xuICAgIGlmIChyb3dJbmRleCAlIDIgPT09IDApIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDIsXG4gICAgICAgIGNvbHNwYW46IDEsXG4gICAgICB9XG4gICAgfSBlbHNlIHtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIHJvd3NwYW46IDAsXG4gICAgICAgIGNvbHNwYW46IDAsXG4gICAgICB9XG4gICAgfVxuICB9XG59XG5cbmNvbnN0IHRhYmxlRGF0YTogVXNlcltdID0gW1xuICB7XG4gICAgaWQ6ICcxMjk4NzEyMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzIzNCcsXG4gICAgYW1vdW50MjogJzMuMicsXG4gICAgYW1vdW50MzogMTAsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTIzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMTY1JyxcbiAgICBhbW91bnQyOiAnNC40MycsXG4gICAgYW1vdW50MzogMTIsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNTUyOS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xNTUyOS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsKHN0eWxlcylcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNTUyOS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

在上面的例子中，把鼠标移入最后一行第一个单元格，控制台会报错。原因是最后一行的第一个单元格的rowSpan是2，但是总的数据是5条。导致执行71行代码的时候，node变成了undefined。

In the above example, moving the mouse into the first cell of the last row will cause the console to report an error. The reason is that the rowSpan of the first cell in the last row is 2, but the total data is 5. When executing 71 lines of code, the node became undefined.

**Review by FrontEndDog — CHANGES_REQUESTED** [review]

File: packages/components/table/src/table-body/events-helper.ts (hunk 2 above)
Comment (dowinweb) [reply packages/components/table/src/table-body/events-helper.ts]: i am sorry, didnot test this boundary condition. I think i have fixed, take a look if you are free, thanks

**Comment by FrontEndDog** [comment]
如果可以加一下相关的测试用例，就更好了

**Comment by dowinweb** [comment]
> 如果可以加一下相关的测试用例，就更好了
> 
> It would be even better if you could add a test case!
OK already added test case

**Comment by dowinweb** [comment]
tell me if there is anything else to change @btea @FrontEndDog

File: packages/components/table/__tests__/table.test.ts [hunk 3]
```diff
@@ -492,6 +492,104 @@ describe('Table.vue', () => {
...
+              },
+              {
+                id: '12987126',
+                name: 'Tom',
+                amount1: '539',
+                amount2: '4.1',
+                amount3: 15,
+              },
+            ],
+          }
```
Comment (FrontEndDog) [inline packages/components/table/__tests__/table.test.ts:554]: Is it better to use `getTestData`?

**Review by FrontEndDog — CHANGES_REQUESTED** [review]

File: packages/components/table/__tests__/table.test.ts (hunk 3 above)
Comment (dowinweb) [reply packages/components/table/__tests__/table.test.ts]: @FrontEndDog what happened，were these unit test failed is my fault ? see it exist in other files

Comment (dowinweb) [reply packages/components/table/__tests__/table.test.ts]: @FrontEndDog I think its ok now

**Review by FrontEndDog — APPROVED** [review]
Thank you for your contribution!

File: packages/components/table/src/table-body/index.ts [hunk 4]
```diff
@@ -28,15 +28,52 @@ export default defineComponent({
...
+        e?.classList.contains(`${ns.e('row')}`)
+      )
+
+      // hover rowSpan > 1 choose the whole row
+      const childNodes = rows[newVal]?.childNodes
+      if (childNodes?.length) {
+        const indexes = Array.from(childNodes).reduce((acc, item, index) => {
+          // drop colsSpan
+          const pre = childNodes[index - 1]?.colSpan > 1
+          const next = childNodes[index + 1]?.colSpan > 1
```
Comment (btea) [inline packages/components/table/src/table-body/index.ts:44]: I'm a little confused, why is `colSpan` being judged here? 🤔

**Comment by dowinweb** [comment]
@btea can this be merged? [捂脸]

File: packages/components/table/src/table-body/index.ts (hunk 4 above)
Comment (btea) [reply packages/components/table/src/table-body/index.ts:44]: I tested your code and it works satisfactorily. But I have some questions about the code, can you explain it? @dowinweb

Comment (dowinweb) [reply packages/components/table/src/table-body/index.ts:44]: yeah sorry i forget submit the comments , it was pending last week🤣

File: packages/components/table/src/table-body/index.ts [hunk 5]
```diff
@@ -28,15 +28,52 @@ export default defineComponent({
...
+            ) {
+              addClass(preChildNodes[rowIndex], 'hover-cell')
+              hoveredCellList.push(preChildNodes[rowIndex])
+              break
+            }
+            newVal--
+          }
+        })
+      } else {
+        hoveredCellList.forEach((item) => removeClass(item, 'hover-cell'))
```
Comment (btea) [inline packages/components/table/src/table-body/index.ts:67]: After removing the class, the value of `hoveredCellList` should probably be cleared.

File: packages/components/table/src/table-body/index.ts [hunk 6]
```diff
@@ -28,15 +28,52 @@ export default defineComponent({
...
       rAF(() => {
         // just get first level children; fix #9723
-        const el = instance?.vnode.el as HTMLElement
-        const rows = Array.from(el?.children || []).filter((e) =>
-          e?.classList.contains(`${ns.e('row')}`)
-        )
+        // const el = instance?.vnode.el as HTMLElement
+        // const rows = Array.from(el?.children || []).filter((e) =>
+        //   e?.classList.contains(`${ns.e('row')}`)
+        // )
```
Comment (btea) [inline packages/components/table/src/table-body/index.ts:76]: The commented code here may be removed.

File: packages/components/table/src/table-body/index.ts (hunk 5 above)
Comment (dowinweb) [reply packages/components/table/src/table-body/index.ts:67]: OK

File: packages/components/table/src/table-body/index.ts (hunk 6 above)
Comment (dowinweb) [reply packages/components/table/src/table-body/index.ts:76]: OKOK

**Review by btea — APPROVED** [review]

**Comment by tolking** [comment]
当表格包含固定列同时 rowspan>2 时，样式会出错

鼠标在**非** ID 的列上下移动 [BUG](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgYXJyYXlTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAocm93SW5kZXggJSAzID09PSAxKSB7XG4gICAgaWYgKGNvbHVtbkluZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4gWzEsIDJdXG4gICAgfSBlbHNlIGlmIChjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgICAgcmV0dXJuIFswLCAwXVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDEpIHtcbiAgICBpZiAocm93SW5kZXggJSA0ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiA0LFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAnMTI5ODcxMjInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICcyMzQnLFxuICAgIGFtb3VudDI6ICczLjInLFxuICAgIGFtb3VudDM6IDEwLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzMyNCcsXG4gICAgYW1vdW50MjogJzEuOScsXG4gICAgYW1vdW50MzogOSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjUnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc2MjEnLFxuICAgIGFtb3VudDI6ICcyLjInLFxuICAgIGFtb3VudDM6IDE3LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzUzOScsXG4gICAgYW1vdW50MjogJzQuMScsXG4gICAgYW1vdW50MzogMTUsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICczMjQnLFxuICAgIGFtb3VudDI6ICcxLjknLFxuICAgIGFtb3VudDM6IDksXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI1JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNjIxJyxcbiAgICBhbW91bnQyOiAnMi4yJyxcbiAgICBhbW91bnQzOiAxNyxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjYnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc1MzknLFxuICAgIGFtb3VudDI6ICc0LjEnLFxuICAgIGFtb3VudDM6IDE1LFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTU1MjktZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by dowinweb** [comment]
> 当表格包含固定列同时 rowspan>2 时，样式会出错
> 
> 鼠标在**非** ID 的列上下移动 [BUG](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtdGFibGVcbiAgICAgIDpkYXRhPVwidGFibGVEYXRhXCJcbiAgICAgIDpzcGFuLW1ldGhvZD1cIm9iamVjdFNwYW5NZXRob2RcIlxuICAgICAgYm9yZGVyXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDAlOyBtYXJnaW4tdG9wOiAyMHB4XCJcbiAgICA+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJpZFwiIGxhYmVsPVwiSURcIiB3aWR0aD1cIjE4MFwiIGZpeGVkIC8+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDFcIiBsYWJlbD1cIkFtb3VudCAxXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDJcIiBsYWJlbD1cIkFtb3VudCAyXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFtb3VudDNcIiBsYWJlbD1cIkFtb3VudCAzXCIgLz5cbiAgICA8L2VsLXRhYmxlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgdHlwZSB7IFRhYmxlQ29sdW1uQ3R4IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbnRlcmZhY2UgVXNlciB7XG4gIGlkOiBzdHJpbmdcbiAgbmFtZTogc3RyaW5nXG4gIGFtb3VudDE6IHN0cmluZ1xuICBhbW91bnQyOiBzdHJpbmdcbiAgYW1vdW50MzogbnVtYmVyXG59XG5cbmludGVyZmFjZSBTcGFuTWV0aG9kUHJvcHMge1xuICByb3c6IFVzZXJcbiAgY29sdW1uOiBUYWJsZUNvbHVtbkN0eDxVc2VyPlxuICByb3dJbmRleDogbnVtYmVyXG4gIGNvbHVtbkluZGV4OiBudW1iZXJcbn1cblxuY29uc3QgYXJyYXlTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAocm93SW5kZXggJSAzID09PSAxKSB7XG4gICAgaWYgKGNvbHVtbkluZGV4ID09PSAwKSB7XG4gICAgICByZXR1cm4gWzEsIDJdXG4gICAgfSBlbHNlIGlmIChjb2x1bW5JbmRleCA9PT0gMSkge1xuICAgICAgcmV0dXJuIFswLCAwXVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCBvYmplY3RTcGFuTWV0aG9kID0gKHtcbiAgcm93LFxuICBjb2x1bW4sXG4gIHJvd0luZGV4LFxuICBjb2x1bW5JbmRleCxcbn06IFNwYW5NZXRob2RQcm9wcykgPT4ge1xuICBpZiAoY29sdW1uSW5kZXggPT09IDEpIHtcbiAgICBpZiAocm93SW5kZXggJSA0ID09PSAwKSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiA0LFxuICAgICAgICBjb2xzcGFuOiAxLFxuICAgICAgfVxuICAgIH0gZWxzZSB7XG4gICAgICByZXR1cm4ge1xuICAgICAgICByb3dzcGFuOiAwLFxuICAgICAgICBjb2xzcGFuOiAwLFxuICAgICAgfVxuICAgIH1cbiAgfVxufVxuXG5jb25zdCB0YWJsZURhdGE6IFVzZXJbXSA9IFtcbiAge1xuICAgIGlkOiAnMTI5ODcxMjInLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICcyMzQnLFxuICAgIGFtb3VudDI6ICczLjInLFxuICAgIGFtb3VudDM6IDEwLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzE2NScsXG4gICAgYW1vdW50MjogJzQuNDMnLFxuICAgIGFtb3VudDM6IDEyLFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzMyNCcsXG4gICAgYW1vdW50MjogJzEuOScsXG4gICAgYW1vdW50MzogOSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjUnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc2MjEnLFxuICAgIGFtb3VudDI6ICcyLjInLFxuICAgIGFtb3VudDM6IDE3LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzUzOScsXG4gICAgYW1vdW50MjogJzQuMScsXG4gICAgYW1vdW50MzogMTUsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI0JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnMzI0JyxcbiAgICBhbW91bnQyOiAnMS45JyxcbiAgICBhbW91bnQzOiA5LFxuICB9LFxuICB7XG4gICAgaWQ6ICcxMjk4NzEyNScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYW1vdW50MTogJzYyMScsXG4gICAgYW1vdW50MjogJzIuMicsXG4gICAgYW1vdW50MzogMTcsXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI2JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNTM5JyxcbiAgICBhbW91bnQyOiAnNC4xJyxcbiAgICBhbW91bnQzOiAxNSxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjQnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICczMjQnLFxuICAgIGFtb3VudDI6ICcxLjknLFxuICAgIGFtb3VudDM6IDksXG4gIH0sXG4gIHtcbiAgICBpZDogJzEyOTg3MTI1JyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhbW91bnQxOiAnNjIxJyxcbiAgICBhbW91bnQyOiAnMi4yJyxcbiAgICBhbW91bnQzOiAxNyxcbiAgfSxcbiAge1xuICAgIGlkOiAnMTI5ODcxMjYnLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFtb3VudDE6ICc1MzknLFxuICAgIGFtb3VudDI6ICc0LjEnLFxuICAgIGFtb3VudDM6IDE1LFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTU1MjktZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1NTI5LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

不得不说行固定的时候 执行的有点奇怪，我去标记了固定时候的行，以避免被清空行样式，我觉得修复好了 可以测试下
I have to say that row with fixed works a little bit strange with the code process , i have to mark the row with fixed class to avoid the remove of the row background class， i think this is fixed, you can test it.

**Comment by dowinweb** [comment]
@tolking what do i need to do now

**Review by tolking — APPROVED** [review]
LGTM.

Thank for your contribution
