### PR TITLE
fix(components): [table-v2] keep hover state after expanded

### LINKED ISSUE #21471: [Style] [table-v2] el-table-v2: Hover effect lost on parent row after expanding when using fixed columns ![](https://s1.ezgif.com/tmp/ezgif-10896da52f6963.gif)
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.17`
- Element Plus Version: `2.10.4`
- Browser / OS: ` Chrome 138.0.7204.158`
- Build Tool: `Other`

### Related Component

- `el-table-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUtdjJcbiAgICA6Y29sdW1ucz1cImNvbHVtbnNcIlxuICAgIDpkYXRhPVwiZGF0YVwiXG4gICAgOndpZHRoPVwiNzAwXCJcbiAgICBleHBhbmQtY29sdW1uLWtleT1cImlkXCJcbiAgICA6aGVpZ2h0PVwiNDAwXCJcbiAgICBmaXhlZFxuXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJztcbmltcG9ydCB7IEVsVGFibGVWMiB9IGZyb20gJ2VsZW1lbnQtcGx1cyc7XG5cbmNvbnN0IGNvbHVtbnMgPSByZWYoW1xuICB7IGtleTogJ2lkJywgZGF0YUtleTogJ2lkJywgdGl0bGU6ICdGaXhlZCBsZWZ0Jywgd2lkdGg6IDEwMCwgZml4ZWQ6ICdsZWZ0JyB9LFxuICB7IGtleTogJ25hbWUnLCBkYXRhS2V5OiAnbmFtZScsIHRpdGxlOiAnTmFtZScsIHdpZHRoOiAyMDAgfSxcbiAgeyBrZXk6ICdpbmZvJywgZGF0YUtleTogJ2luZm8nLCB0aXRsZTogJ0luZm8nLCB3aWR0aDogMjAwIH0sXG4gIHsga2V5OiAnb3AnLCB0aXRsZTogJ0ZpeGVkIHJpZ2h0Jywgd2lkdGg6IDEyMCwgZml4ZWQ6ICdyaWdodCcgfSxcbl0pO1xuXG5jb25zdCBkYXRhID0gcmVmKFxuICBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMCB9KS5tYXAoKF8sIGkpID0+ICh7XG4gICAgaWQ6IGksXG4gICAgbmFtZTogYE5hbWUgJHtpfWAsXG4gICAgaW5mbzogYEluZm8gJHtpfWAsXG4gICAgZml4ZWRSaWdodDogYCR7aX1gLFxuICAgIGNoaWxkcmVuOiBpICUgMyA9PT0gMCA/IFt7IGlkOiBpICsgJy0xJywgbmFtZTogYENoaWxkICR7aX1gLCBpbmZvOiAnU3ViJyB9XSA6IG51bGwsXG4gIH0pKVxuKTtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG5cbjwvc3R5bGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMC40L3RoZW1lLWNoYWxrL2RhcmsvY3NzLXZhcnMuY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGxTZXR0bGVkKHN0eWxlcylcbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQDMuNS4xNy9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy41LjE3L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjEwLjQvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnsidnVlVmVyc2lvbiI6IjMuNS4xNyIsImVwVmVyc2lvbiI6IjIuMTAuNCJ9fQ==)

### Steps to reproduce

1. Create a table with fixed columns and expandable rows.
2. Hover over a parent row — it is fully highlighted (has is-hovered class).
3. Click the expand arrow to open child rows. The parent row loses hover effect on the non-fixed part, while the fixed part still has it.
4. Click the expand arrow again to collapse the row:
The hover effect is lost entirely, even if the mouse is still over the parent row.

### What is Expected?

After expanding the row:

-The hover effect should remain on the parent row if the cursor is still over it.
-The is-hovered class should apply to both fixed and non-fixed sections of the row.
-When collapsing the row again (by clicking the expand arrow a second time), the hover effect should still persist if the mouse hasn't left the parent row.

### What is actually happening?

After expanding or collapsing a row, the non-fixed part of the parent row loses its hover state, even if the cursor never left the row.

### Additional comments

When using el-table-v2 with:
-Fixed columns
-Expandable rows

the hover effect on the parent row disappears right after clicking the expand arrow.
It only remains on the fixed section of the row, making it look broken or inconsistent.

### PR DESCRIPTION
**Pull request by rzzf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Before:

https://github.com/user-attachments/assets/710f51f3-0261-4ef4-89a2-7d0cf1b322cd

After:

https://github.com/user-attachments/assets/94b8247e-1b02-4c98-9645-4ca7a460a780

fix: #21471

### CODE REVIEW

File: packages/components/table-v2/src/composables/use-row.ts [hunk 1]
```diff
@@ -98,6 +105,22 @@ export const useRow = (
...
+      nextTick(() => {
+        onRowHovered({
+          hovered: true,
+          rowKey,
+          event: new MouseEvent('hover'),
+          rowData,
+          rowIndex,
+        })
+      })
+    }
```
Comment (Dsaquel) [inline packages/components/table-v2/src/composables/use-row.ts]: I agree with the logic change, perhaps these fields can be optional https://github.com/element-plus/element-plus/blob/dev/packages/components/table-v2/src/row.ts#L18-L20 and pass it only the require params ?

File: packages/components/table-v2/src/composables/use-row.ts [hunk 2]
```diff
@@ -98,6 +105,22 @@ export const useRow = (
     })
     // If this is not controlled, then use this to notify changes
     props.onExpandedRowsChange?.(_expandedRowKeys)
+
+    const tableRoot = tableInstance!.vnode.el as HTMLElement
+    const hoverRow = tableRoot.querySelector(
+      `[rowkey="${String(rowKey)}"].${ns.is('hovered')}`
+    )
+    if (hoverRow) {
```
Comment (Dsaquel) [inline packages/components/table-v2/src/composables/use-row.ts]: Is there any situation when we are not in hover while clicking the expand element?

File: packages/components/table-v2/src/composables/use-row.ts (hunk 1 above)
Comment (rzzf) [reply packages/components/table-v2/src/composables/use-row.ts]: I agree, I will update it later.

File: packages/components/table-v2/src/composables/use-row.ts (hunk 2 above)
Comment (rzzf) [reply packages/components/table-v2/src/composables/use-row.ts]: I think there does not exist, since `querySelector` is selecting the row that is currently in the hover state — and as far as I know, that state is only applied via the `mouseenter` event.

Comment (Dsaquel) [reply packages/components/table-v2/src/composables/use-row.ts]: Yes, it's just at this moment `hoverRow` will be always truthy because we already in the hovered row as we already triggered previously `mouseenter`.

But maybe i'm missing something :thinking: ?

Comment (rzzf) [reply packages/components/table-v2/src/composables/use-row.ts]: There might be some special considerations when `expand` programmatically, but currently, we don't have any public APIs for this. If you think of anything, please let me know. Thank you.

Comment (Dsaquel) [reply packages/components/table-v2/src/composables/use-row.ts]: Ok, considering this case we may not hover the row :+1:.

**Review by Dsaquel — APPROVED** [review]
LGTM

**Review by btea — APPROVED** [review]
Thanks!
