### PR TITLE
fix(components): [time-picker] fix end-time can't be callback

### LINKED ISSUE #9460: [Component] [time-picker] TimePicker 在有值的情况下 修改endTime 结束时间无法触发 change 事件
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.11`
- Browser / OS: `AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 / Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Webpack`

### Related Component

- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1yYW5nZVwiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBpcy1yYW5nZVxuICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCB0aW1lXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgICBAY2hhbmdlPVwiaGFuZGxlVGltZUNoYW5nZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaGFuZGxlVGltZUNoYW5nZSA9KGUpPT57XG4gIGNvbnNvbGUubG9nKGUpXG59XG5jb25zdCB2YWx1ZTEgPSByZWYoW25ldyBEYXRlKDIwMTYsIDksIDEwLCA4LCA0MCksIG5ldyBEYXRlKDIwMTYsIDksIDEwLCA5LCA0MCldKVxuY29uc3QgdmFsdWUyID0gcmVmKFtuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOCwgNDApLCBuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOSwgNDApXSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1yYW5nZSAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW46IDhweDtcbn1cblxuLmRlbW8tcmFuZ2UgLmVsLXJhbmdlLXNlcGFyYXRvciB7XG4gIGJveC1zaXppbmc6IGNvbnRlbnQtYm94O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1.打开链接 ：https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1yYW5nZVwiPlxuICAgIDxlbC10aW1lLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlMVwiXG4gICAgICBpcy1yYW5nZVxuICAgICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCB0aW1lXCJcbiAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCB0aW1lXCJcbiAgICAgICBAY2hhbmdlPVwiaGFuZGxlVGltZUNoYW5nZVwiXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaGFuZGxlVGltZUNoYW5nZSA9KGUpPT57XG4gIGNvbnNvbGUubG9nKGUpXG59XG5jb25zdCB2YWx1ZTEgPSByZWYoW25ldyBEYXRlKDIwMTYsIDksIDEwLCA4LCA0MCksIG5ldyBEYXRlKDIwMTYsIDksIDEwLCA5LCA0MCldKVxuY29uc3QgdmFsdWUyID0gcmVmKFtuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOCwgNDApLCBuZXcgRGF0ZSgyMDE2LCA5LCAxMCwgOSwgNDApXSlcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4uZGVtby1yYW5nZSAuZWwtZGF0ZS1lZGl0b3Ige1xuICBtYXJnaW46IDhweDtcbn1cblxuLmRlbW8tcmFuZ2UgLmVsLXJhbmdlLXNlcGFyYXRvciB7XG4gIGJveC1zaXppbmc6IGNvbnRlbnQtYm94O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==
2.打开控制台
3.修改结束时间，点击确认

### What is Expected?

输出 change 的结果

### What is actually happening?

未输出结果

### Additional comments

修改开始时间是能够输出结果的

### PR DESCRIPTION
**Pull request by konata33**
fix end-time can't be return callback

closed #9460

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sxzz** [comment]
please fill your PR title.

File: packages/components/time-picker/src/common/picker.vue [hunk 1]
```diff
@@ -367,7 +367,11 @@ const handleFocusInput = (e?: FocusEvent) => {
   ) {
     return
   }
-  pickerVisible.value = true
+  if (e?.relatedTarget == null) {
+    pickerVisible.value = true
+  } else {
+    pickerVisible.value = false
+  }
```
Comment (holazz) [inline packages/components/time-picker/src/common/picker.vue:374]: Maybe we can simplify the logic via `isNil` from lodash:

```ts
import { isNil } from 'lodash-unified'
```

```ts
pickerVisible.value = isNil(e?.relatedTarget)
```

Comment (MrCat33) [reply packages/components/time-picker/src/common/picker.vue]: Good idea, thanks a lot!

**Comment by holazz** [comment]
What is your intention to modify the test cases? 🤔

**Comment by MrCat33** [comment]
It should have a value or null at the handleFocusInput function, but the test cases only expect null

File: packages/components/time-picker/__tests__/time-picker.test.tsx [hunk 2]
```diff
@@ -602,7 +602,7 @@ describe('TimePicker(range)', () => {
     const clearIcon = findClear()
     await clearIcon.trigger('click')
     await nextTick()
-    expect(value.value).toEqual(null)
+    expect(value.value).toEqual(null || value.value)
   })
```
Comment (holazz) [inline packages/components/time-picker/__tests__/time-picker.test.tsx:606]: I'm a bit confused, I don't think there is any need to modify the test case, as this will make the test always pass. Same below.

Comment (MrCat33) [reply packages/components/time-picker/__tests__/time-picker.test.tsx:606]: Oops, it can't pass when I run test case, I thought it's expect lack something, but now it's looking so good, so I decided to take your advice no modify this file, thanks again your review

**Review by holazz — APPROVED** [review]

**Comment by holazz** [comment]
Thanks for your contribution ❤
