### PR TITLE
fix(components): [time-picker] allow clearing time via keyboard when using `is-range`

### LINKED ISSUE #23865: [Component] [date-picker] The range selector does not allow deleting selected values using the keyboard
Bug Type: **`Component`**

## Environment

- Vue Version: `3.6.0-beta.8`
- Element Plus Version: `2.13.6`
- Browser / OS: `win`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/date-picker)

### Steps to reproduce

开始结束时间搜索框，选择时间后，光标到时间的最后，然后长按键盘删除按钮，这时会一直重复显示

### What is Expected?

可以清空

### What is actually happening?

开始结束时间搜索框，选择时间后，光标到时间的最后，然后长按键盘删除按钮，这时会一直重复显示

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by IceMooncake**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fixed #23865 

## Summary by CodeRabbit

* **Bug Fixes**
  * Range time-picker preserves intentionally empty values (e.g., empty strings) and only treats a range as cleared when all parts are empty; single-value clearing behavior unchanged.

* **Tests**
  * Added a test confirming keyboard/manual clearing of a date-range emits a single change and resets the model to null.

### CODE REVIEW

**Comment by IceMooncake** [comment]
Here's a [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICAgIHR5cGU9XCJkYXRlcmFuZ2VcIlxuICAgICAgICB1bmxpbmstcGFuZWxzXG4gICAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCBkYXRlXCJcbiAgICAgICAgZW5kLXBsYWNlaG9sZGVyPVwiRW5kIGRhdGVcIlxuICAgICAgLz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoJycpXG48L3NjcmlwdD5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM4NzgvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzg3OC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3Jhdy5lc20uc2gvcHIvZWxlbWVudC1wbHVzQDIzODc4L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9yYXcuZXNtLnNoL3ByL2VsZW1lbnQtcGx1c0AyMzg3OC9cIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcmF3LmVzbS5zaC9wci9lbGVtZW50LXBsdXNAMjM4NzgvZGlzdC9pbmRleC5jc3MifX0=) for this PR

**Review by keeplearning66 — COMMENTED** [review]
When `type` is `daterange`, it seems that the selected dates can't be truly cleared, which is inconsistent with the behavior when `type` is `date`. 🤔 

https://github.com/user-attachments/assets/7b8bb025-d2cc-464b-bcc1-cc1b8baba080

**Comment by laybrid** [comment]
> When `type` is `daterange`, it seems that the selected dates can't be truly cleared, which is inconsistent with the behavior when `type` is `date`. 🤔
> 
>  20260323_202515.mp4

After fixing this bug, a new interaction problem arises: when the mouse loses focus, the input value deleted by the keyboard will be re-rendered. This issue has already been resolved in my PR https://github.com/element-plus/element-plus/pull/23880

**Comment by IceMooncake** [comment]
> > When `type` is `daterange`, it seems that the selected dates can't be truly cleared, which is inconsistent with the behavior when `type` is `date`. 🤔
> > 20260323_202515.mp4
> 
> After fixing this bug, a new interaction problem arises: when the mouse loses focus, the input value deleted by the keyboard will be re-rendered. This issue has already been resolved in my PR #23880

thanks for review, I have resolved this issue in the latest commit

**Review by keeplearning66 — COMMENTED** [review]
If possible, could you add a related test case? 🙏

**Comment by IceMooncake** [comment]
> If possible, could you add a related test case? 🙏

Just submitted a new commit and added the corresponding unit test. Thanks for your review 😄

File: packages/components/time-picker/src/common/picker.vue [hunk 1]
```diff
@@ -527,7 +527,9 @@ onBeforeUnmount(() => {
 const handleChange = () => {
   if (isTimePicker.value && !props.saveOnBlur) return
 
-  if (userInput.value) {
+  const isRangeEmpty =
+    isArray(userInput.value) && userInput.value.every((v) => v === '')
+  if (userInput.value && (isRangeInput.value ? !isRangeEmpty : true)) {
```
Comment (patienry) [inline packages/components/time-picker/src/common/picker.vue]:
```suggestion
  if (userInput.value && !isRangeEmpty) {
```

File: packages/components/time-picker/src/common/picker.vue [hunk 2]
```diff
@@ -536,7 +538,7 @@ const handleChange = () => {
       userInput.value = null
     }
   }
-  if (userInput.value === '') {
+  if (isRangeInput.value ? isRangeEmpty : userInput.value === '') {
```
Comment (patienry) [inline packages/components/time-picker/src/common/picker.vue]:
```suggestion
  if (userInput.value === '' || isRangeEmpty) {
```

File: packages/components/time-picker/src/common/picker.vue (hunk 1 above)
Comment (patienry) [reply packages/components/time-picker/src/common/picker.vue]: Wouldn't this make the judgment a bit simpler? 🤔 WDYT?

**Review by keeplearning66 — COMMENTED** [review]
This is actually an issue with `time-picker`. The same phenomenon occurs when using `is-range` prop in `time-picker`. So, we could consider adding test cases in `time-picker.test.tsx` instead of `date-picker.test.ts`.

File: packages/components/time-picker/src/common/picker.vue (hunk 1 above)
Comment (IceMooncake) [reply packages/components/time-picker/src/common/picker.vue]: Ah, you're right — my mistake 😄 I've fixed it.

File: packages/components/time-picker/__tests__/time-picker.test.tsx [hunk 3]
```diff
@@ -736,6 +736,50 @@ describe('TimePicker(range)', () => {
...
+      <TimePicker v-model={value.value} is-range onChange={changeHandler} />
+    ))
+
+    const [startInput] = wrapper.findAll('input')
+
+    await startInput.setValue('')
+    expect(startInput.element.value).toBe('')
+
+    await startInput.trigger('blur')
+    await nextTick()
```
Comment (patienry) [inline packages/components/time-picker/__tests__/time-picker.test.tsx:755]:
```suggestion
    await nextTick()
    expect(changeHandler).not.toHaveBeenCalled()
```

**Review by keeplearning66 — APPROVED** [review]
Thank you!

**Review by rzzf — APPROVED** [review]

**Review by Dsaquel — APPROVED** [review]
