### PR TITLE
fix(components): [date-picker] add missing data slot

### LINKED ISSUE #13535: [Component] [date-picker] Custom Content for date picker not working for month type
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.3`
- Element Plus Version: `2.3.7`
- Browser / OS: `chrome, in element plus edit in playground`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cImRlbW8tZGF0ZS1waWNrZXJcIj5cbiAgICA8ZWwtZGF0ZS1waWNrZXJcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICB0eXBlPVwibW9udGhcIlxuICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgbW9udGhcIlxuICAgICAgZm9ybWF0PVwiWVlZWS9NTVwiXG4gICAgICB2YWx1ZS1mb3JtYXQ9XCJZWVlZLU1NXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJjZWxsXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjZWxsXCIgOmNsYXNzPVwieyBjdXJyZW50OiBjZWxsLmlzQ3VycmVudCB9XCI+XG4gICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0ZXh0XCI+e3sgY2VsbC50ZXh0IH19PC9zcGFuPlxuICAgICAgICAgIDxzcGFuIHYtaWY9XCJpc0hvbGlkYXkoY2VsbClcIiBjbGFzcz1cImhvbGlkYXlcIiAvPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignMjAyMS0xMCcpXG5jb25zdCBob2xpZGF5cyA9IFtcbiAgJzIwMjEtMTAnLFxuICAnMjAyMS0xMSdcbiAgLy8gQWRkIG90aGVyIG1vbnRoIGhvbGlkYXkgdmFsdWVzIGhlcmVcbl1cblxuY29uc3QgaXNIb2xpZGF5ID0gKHsgZGF5anMgfSkgPT4ge1xuICByZXR1cm4gaG9saWRheXMuaW5jbHVkZXMoZGF5anMuZm9ybWF0KCdZWVlZLU1NJykpXG59XG48L3NjcmlwdD5cblxuPHN0eWxlIHNjb3BlZD5cbi5jZWxsIHtcbiAgaGVpZ2h0OiAzMHB4O1xuICBwYWRkaW5nOiAzcHggMDtcbiAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbn1cbi5jZWxsIC50ZXh0IHtcbiAgd2lkdGg6IDI0cHg7XG4gIGhlaWdodDogMjRweDtcbiAgZGlzcGxheTogYmxvY2s7XG4gIG1hcmdpbjogMCBhdXRvO1xuICBsaW5lLWhlaWdodDogMjRweDtcbiAgcG9zaXRpb246IGFic29sdXRlO1xuICBsZWZ0OiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgtNTAlKTtcbiAgYm9yZGVyLXJhZGl1czogNTAlO1xufVxuLmNlbGwuY3VycmVudCAudGV4dCB7XG4gIGJhY2tncm91bmQ6ICM2MjZhZWY7XG4gIGNvbG9yOiAjZmZmO1xufVxuLmNlbGwgLmhvbGlkYXkge1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIHdpZHRoOiA2cHg7XG4gIGhlaWdodDogNnB4O1xuICBiYWNrZ3JvdW5kOiB2YXIoLS1lbC1jb2xvci1kYW5nZXIpO1xuICBib3JkZXItcmFkaXVzOiA1MCU7XG4gIGJvdHRvbTogMHB4O1xuICBsZWZ0OiA1MCU7XG4gIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgtNTAlKTtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

try to change the type to month, then the indicator is not coming

### What is Expected?

like for date type where we are able to see the red dot indicators for the given dates, for month calender also, we should see the red dot indicator for the given months

### What is actually happening?

when type is changed to month, no red dot indicator is shown for the date/months in the holiday array

### Additional comments

_(empty)_

### LINKED ISSUE #19260: [Component] [date-picker] Date picker custom content for months and years does not return date or dayjs object.
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.0`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIDxlbC1kYXRlLXBpY2tlclxuICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgIHR5cGU9XCJtb250aFwiXG4gICAgICBwbGFjZWhvbGRlcj1cIlBpY2sgYSBkYXlcIlxuICAgICAgZm9ybWF0PVwiWVlZWS9NTS9ERFwiXG4gICAgICB2YWx1ZS1mb3JtYXQ9XCJZWVlZLU1NLUREXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJjZWxsXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjZWxsXCIgOmNsYXNzPVwieyBjdXJyZW50OiBjZWxsLmlzQ3VycmVudCB9XCI+XG4gICAgICAgICAgPHNwYW4gY2xhc3M9XCJ0ZXh0XCI+e3sgY2VsbC50ZXh0IH19PC9zcGFuPlxuICAgICAgICAgIDxzcGFuIHYtaWY9XCJpc0hvbGlkYXkoY2VsbClcIiBjbGFzcz1cImhvbGlkYXlcIiAvPlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZignMjAyMS0xMC0yOScpXG5jb25zdCBob2xpZGF5cyA9IFtcbiAgJzIwMjEtMTAtMDEnLFxuICAnMjAyMS0xMC0wMicsXG4gICcyMDIxLTEwLTAzJyxcbiAgJzIwMjEtMTAtMDQnLFxuICAnMjAyMS0xMC0wNScsXG4gICcyMDIxLTEwLTA2JyxcbiAgJzIwMjEtMTAtMDcnLFxuXVxuXG5jb25zdCBpc0hvbGlkYXkgPSAoeyBkYXlqcyB9KSA9PiB7XG4gIHJldHVybiBob2xpZGF5cy5pbmNsdWRlcyhkYXlqcy5mb3JtYXQoJ1lZWVktTU0tREQnKSlcbn1cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuLmNlbGwge1xuICBoZWlnaHQ6IDMwcHg7XG4gIHBhZGRpbmc6IDNweCAwO1xuICBib3gtc2l6aW5nOiBib3JkZXItYm94O1xufVxuLmNlbGwgLnRleHQge1xuICB3aWR0aDogMjRweDtcbiAgaGVpZ2h0OiAyNHB4O1xuICBkaXNwbGF5OiBibG9jaztcbiAgbWFyZ2luOiAwIGF1dG87XG4gIGxpbmUtaGVpZ2h0OiAyNHB4O1xuICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpO1xuICBib3JkZXItcmFkaXVzOiA1MCU7XG59XG4uY2VsbC5jdXJyZW50IC50ZXh0IHtcbiAgYmFja2dyb3VuZDogIzYyNmFlZjtcbiAgY29sb3I6ICNmZmY7XG59XG4uY2VsbCAuaG9saWRheSB7XG4gIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgd2lkdGg6IDZweDtcbiAgaGVpZ2h0OiA2cHg7XG4gIGJhY2tncm91bmQ6IHZhcigtLWVsLWNvbG9yLWRhbmdlcik7XG4gIGJvcmRlci1yYWRpdXM6IDUwJTtcbiAgYm90dG9tOiAwcHg7XG4gIGxlZnQ6IDUwJTtcbiAgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpO1xufVxuPC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Run the playground example.  Click on the date input, the following error will occur -

Cannot read properties of undefined (reading 'format')

### What is Expected?

cell in template should contain a dayjs object, and date property

### What is actually happening?

cell contains following properties, but no date property or dayjs object

column: 1
disabled: false
end: false
inRange: false
renderText: "Feb"
row: 0
start: false
text: 1
type: "normal"

### Additional comments

This applies to either the month or year date picker type.  

I need the date in the template for context.  All date pickers should be consistent with the object returned.

### LINKED ISSUE #21373: [Component] [date-picker] DatePicker
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.16`
- Element Plus Version: `2.9.7`
- Browser / OS: `Chrome 137.0.7151.122`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZGVtby1kYXRlLXBpY2tlclwiPlxuICAgIFxuICAgIDxkaXYgY2xhc3M9XCJibG9ja1wiPlxuICAgICAgPHNwYW4gY2xhc3M9XCJkZW1vbnN0cmF0aW9uXCI+V2l0aCBxdWljayBvcHRpb25zPC9zcGFuPlxuICAgICAgPGVsLWRhdGUtcGlja2VyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgIFxuICAgICAgICB1bmxpbmstcGFuZWxzXG4gICAgICAgIHJhbmdlLXNlcGFyYXRvcj1cIlRvXCJcbiAgICAgICAgc3RhcnQtcGxhY2Vob2xkZXI9XCJTdGFydCBtb250aFwiXG4gICAgICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBtb250aFwiXG4gICAgICAgIDpzaG9ydGN1dHM9XCJzaG9ydGN1dHNcIlxuICAgICAgICA6Y2VsbC1jbGFzcy1uYW1lPVwidGVzdFwiXG4gICAgICAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlMSA9IHJlZignJylcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcblxuY29uc3Qgc2hvcnRjdXRzID0gW1xuICB7XG4gICAgdGV4dDogJ1RoaXMgbW9udGgnLFxuICAgIHZhbHVlOiBbbmV3IERhdGUoKSwgbmV3IERhdGUoKV0sXG4gIH0sXG4gIHtcbiAgICB0ZXh0OiAnVGhpcyB5ZWFyJyxcbiAgICB2YWx1ZTogKCkgPT4ge1xuICAgICAgY29uc3QgZW5kID0gbmV3IERhdGUoKVxuICAgICAgY29uc3Qgc3RhcnQgPSBuZXcgRGF0ZShuZXcgRGF0ZSgpLmdldEZ1bGxZZWFyKCksIDApXG4gICAgICByZXR1cm4gW3N0YXJ0LCBlbmRdXG4gICAgfSxcbiAgfSxcbiAge1xuICAgIHRleHQ6ICdMYXN0IDYgbW9udGhzJyxcbiAgICB2YWx1ZTogKCkgPT4ge1xuICAgICAgY29uc3QgZW5kID0gbmV3IERhdGUoKVxuICAgICAgY29uc3Qgc3RhcnQgPSBuZXcgRGF0ZSgpXG4gICAgICBzdGFydC5zZXRNb250aChzdGFydC5nZXRNb250aCgpIC0gNilcbiAgICAgIHJldHVybiBbc3RhcnQsIGVuZF1cbiAgICB9LFxuICB9LFxuXVxuXG5mdW5jdGlvbiB0ZXN0KGRhdGUpe1xuICBjb25zb2xlLmxvZyhkYXRlKVxuICByZXR1cm4gXCJkc2ZcIlxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZHNme1xuICBjb2xvcjogI2ZmMDAwMDtcbn1cbi5kZW1vLWRhdGUtcGlja2VyIHtcbiAgZGlzcGxheTogZmxleDtcbiAgd2lkdGg6IDEwMCU7XG4gIHBhZGRpbmc6IDA7XG4gIGZsZXgtd3JhcDogd3JhcDtcbn1cbi5kZW1vLWRhdGUtcGlja2VyIC5ibG9jayB7XG4gIHBhZGRpbmc6IDMwcHggMDtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBib3JkZXItcmlnaHQ6IHNvbGlkIDFweCB2YXIoLS1lbC1ib3JkZXItY29sb3IpO1xuICBmbGV4OiAxO1xufVxuLmRlbW8tZGF0ZS1waWNrZXIgLmJsb2NrOmxhc3QtY2hpbGQge1xuICBib3JkZXItcmlnaHQ6IG5vbmU7XG59XG4uZGVtby1kYXRlLXBpY2tlciAuZGVtb25zdHJhdGlvbiB7XG4gIGRpc3BsYXk6IGJsb2NrO1xuICBjb2xvcjogdmFyKC0tZWwtdGV4dC1jb2xvci1zZWNvbmRhcnkpO1xuICBmb250LXNpemU6IDE0cHg7XG4gIG1hcmdpbi1ib3R0b206IDIwcHg7XG59XG48L3N0eWxlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

当type 不是date  

### What is Expected?

当type 不是date  比如 month monthrange是 cell-class-name无法触发，自定义插槽 cell数据格式不统一

### What is actually happening?

当type 无论那种类型 cell数据格式统一为官网文档 interface DateCell {
  column: number
  customClass: string
  disabled: boolean
  end: boolean
  inRange: boolean
  row: number
  selected: Dayjs
  isCurrent: boolean
  isSelected: boolean
  start: boolean
  text: number
  timestamp: number
  date: Date
  dayjs: Dayjs
  type: 'normal' | 'today' | 'week' | 'next-month' | 'prev-month'
} 

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Dsaquel**
close https://github.com/element-plus/element-plus/issues/19260
close #21373
close #13535
context pr #19481

### CODE REVIEW

**Comment by btea** [comment]
There is a code conflict that needs to be resolved.

File: packages/components/date-picker/src/date-picker-com/basic-month-table.vue [hunk 1]
```diff
@@ -49,6 +51,11 @@ type MonthCell = {
   text: number
   type: 'normal' | 'today'
   inRange: boolean
+  isSelected: boolean
+  date?: Date
+  dayjs?: Dayjs
+  timestamp?: number
+  customClass?: string
 }
```
Comment (btea) [inline packages/components/date-picker/src/date-picker-com/basic-month-table.vue]: It appears that the `DateCell` type has 16 properties; perhaps `MonthCell` and `YearCell` should be synchronized.

Comment (Dsaquel) [reply packages/components/date-picker/src/date-picker-com/basic-month-table.vue]: I will checkout it tomorrow :+1: .

Comment (Dsaquel) [reply packages/components/date-picker/src/date-picker-com/basic-month-table.vue]: Sorry for late response, i will work on this when date-picker-panel get merged to avoid potential annoying conflicts.

Comment (Dsaquel) [reply packages/components/date-picker/src/date-picker-com/basic-month-table.vue]: Done, i changed also this notation:
```diff
- property?: string
+ property: string | undefined
```
In order to always return 16 properties instead of missing keys from pickers to pickers.

File: docs/en-US/component/date-picker.md [hunk 2]
```diff
@@ -134,14 +134,15 @@ For data details, please refer:
 ```ts
 interface DateCell {
   column: number
-  customClass: string
+  customClass?: string
```
Comment (btea) [inline docs/en-US/component/date-picker.md]:
```suggestion
  customClass: string | undefined
```
Changing it to be the same as other type declarations? Anyway, is this considered a breaking change? 🤔

Comment (Dsaquel) [reply docs/en-US/component/date-picker.md]: I don't it should be a breaking change and now the change are additives, i'll update the doc.

Comment (Dsaquel) [reply docs/en-US/component/date-picker.md]: Just found this type was not exported in the previous version
https://github.com/element-plus/element-plus/blob/a985f511a0ca43d2e8972c4efa9ba69022491031/packages/components/date-picker-panel/src/types.ts#L18-L35

I update it accordingly with the doc.

**Review by btea — APPROVED** [review]

File: docs/en-US/component/date-picker.md (hunk 2 above)
Comment (Dsaquel) [reply docs/en-US/component/date-picker.md]: `DateCell` was taken to construct the picker table resulting with this type above, if we declare the DateCell like the type in the doc it throw many type errors.
I now understand the though behind the type declaration in the doc.
It will be good in the future to have two separates types (`DateCellConstructor` and `DateCell`).
We're good to merge we can do this later.
