### PR TITLE
fix(components): [el-popover] fix popover placement reactive

### LINKED ISSUE #5811: [Bug Report] popover placement初始化后再修改无效
### Element Plus version
1.3.0-beta.9

### OS/Browsers version
windows/chrome 版本 97.0.4692.99（正式版本） （64 位）

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/wangahui/pen/PoObVWX

### Steps to reproduce
1：给popover组件绑定属性placemnt，默认值bottom
2:点击按钮修改placment为right，
3：鼠标重新放到按钮上，popover弹出，位置placement仍为bottom

### What is Expected?
修改placement后重新显示popover时候位置为新值

### What is actually happening?
2:点击按钮修改placment为right，
3：鼠标重新放到按钮上，popover弹出，位置placement仍为bottom

### PR DESCRIPTION
**Pull request by 0xshellming**
Please make sure these boxes are checked before submitting your PR, thank you!

- fix: [[Bug Report] popover placement初始化后再修改无效 (#5811)](https://github.com/element-plus/element-plus/issues/5811)
- create new Popper Instance when  props.placement change  

---
- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by qeaonet** [comment]
牛啊！赞一个，解决啦

File: packages/components/popper/src/content.vue [hunk 1]
```diff
@@ -84,17 +84,23 @@ export default defineComponent({
...
+                popperInstanceRef.value?.destroy()
+                const newInstance = createPopperInstance({
+                  referenceEl: val,
+                  popperContentEl: unref(popperContentRef)!,
+                  arrowEl,
+                })
+                popperInstanceRef.value = newInstance
+              },
+              { immediate: true }
+            )
```
Comment (JeremyWuuuuu) [inline packages/components/popper/src/content.vue:103]: For fixing this issue, I think we should update the instance, instead of creating a new one which could introduces additional overhead.

Comment (QuXiaoMing) [reply packages/components/popper/src/content.vue]: You're right, this solution is better. 

We update the instance when the buildPopperOptions changed.

```js
 watch(() =>
    buildPopperOptions(props, {
        arrowEl: unref(arrowRef),
        arrowOffset: unref(arrowOffset),
    }),
    (option) => popperInstanceRef.value?.setOptions(option)
)
```

File: packages/components/popper/src/content.vue [hunk 2]
```diff
@@ -113,6 +113,15 @@ export default defineComponent({
...
       )
+
+      watch(
+        () =>
+          buildPopperOptions(props, {
+            arrowEl: unref(arrowRef),
+            arrowOffset: unref(arrowOffset),
+          }),
+        (option) => popperInstanceRef.value?.setOptions(option)
+      )
```
Comment (JeremyWuuuuu) [inline packages/components/popper/src/content.vue:124]: I think this is smart, this should work just fine.

Have you tested this in your local machine with the test test case?

Comment (QuXiaoMing) [reply packages/components/popper/src/content.vue:124]: Of course~

image
image

**Review by jw-foss — COMMENTED** [review]
Let's get this merged then.

**Review by jw-foss — APPROVED** [review]

File: packages/components/popper/src/content.vue (hunk 2 above)
Comment (QuXiaoMing) [reply packages/components/popper/src/content.vue:124]: I had tested the case #5838. It worked.
