### PR TITLE
fix(components): [el-date-picker] panel position error after view switch

### LINKED ISSUE #5269: [Bug Report] el-dialog uses el-date-picker internally ZIndex Error
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
Mac OS/ Chrome 版本 97.0.4692.71（正式版本） (arm64)

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-wqbsw?file=/src/App.vue

### Steps to reproduce
1. open dialog
2. select date-picker
3. close dialog
4. reopen dialog
5. reselect date-picker

### What is Expected?
el-date-picker Hierarchy should be above / 日期选择层级应高于 dialog 层级

### What is actually happening?
Hierarchy should be below / 日期选择层级低于 dialog 层级

### LINKED ISSUE #5274: [Bug Report] 关闭dialog再次打开时，select下拉面板在dialog中消失
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
macOS

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/lemonade1/pen/BawObJW

### Steps to reproduce
第一次打开弹窗，下拉正常显示，关闭后第二次打开弹窗，下拉面板消失

### What is Expected?
下拉面板显示

### What is actually happening?
下拉面板消失

### PR DESCRIPTION
**Pull request by msidolphin**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/date-picker/src/date-picker-com/panel-date-pick.vue [hunk 1]
```diff
@@ -182,6 +182,7 @@ import {
   DArrowRight,
   ArrowRight,
 } from '@element-plus/icons-vue'
+import { TOOLTIP_INJECTION_KEY } from '@element-plus/components/tooltip/src/tokens'
```
Comment (JeremyWuuuuu) [inline packages/components/date-picker/src/date-picker-com/panel-date-pick.vue:185]: I thin we can skip the `src/tokens` part, with only `@element-plus/components/tooltip` should be fine.

**Review by jw-foss — APPROVED** [review]

**Comment by msidolphin** [comment]
@JeremyWuuuuu done

**Review by jw-foss — APPROVED** [review]
