### PR TITLE
fix(components): [el-autocomplete] fix popper position

### LINKED ISSUE #4216: [Bug Report] Position of AutoComplete popper is not correctly calculated
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
Windows 10 / Chrome 95.0.4638.69

### Vue version
3.2.21

### Reproduction Link
https://jsfiddle.net/h9frjea6/31/

### Steps to reproduce
1. click on the auto-complete component
2. check the position of its popper 

### What is Expected?
the popper of this auto-complete component should be displayed at the top of the component

### What is actually happening?
image
popper  position of auto-complete is not correclty calculated

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #4216

### CODE REVIEW

File: packages/components/popper/src/use-popper/build-modifiers.ts [hunk 1]
```diff
@@ -37,7 +37,10 @@ export default function buildModifier(
       name: 'flip',
       options: {
         padding: 5,
-        fallbackPlacements: fallbackPlacements ?? [],
+        fallbackPlacements:
```
Comment (msidolphin) [inline packages/components/popper/src/use-popper/build-modifiers.ts:40]: I think it is not the reason here, refer to the other components

Comment (btea) [reply packages/components/popper/src/use-popper/build-modifiers.ts:40]: I see. Adding a `fallback-placements` attribute value to the `autocomplete` component can fix this problem.

**Review by msidolphin — APPROVED** [review]
