### PR TITLE
fix(components): [menu] expand active menu item

### LINKED ISSUE #9066: [Component] [menu, menu-item] v2.2.11版本，el-menu 的 default-active 不起效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-menu`
- `el-menu-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cImlzQ29sbGFwc2VcIiBzdHlsZT1cIm1hcmdpbi1ib3R0b206IDIwcHhcIj5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIDpsYWJlbD1cImZhbHNlXCI+ZXhwYW5kPC9lbC1yYWRpby1idXR0b24+XG4gICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCJ0cnVlXCI+Y29sbGFwc2U8L2VsLXJhZGlvLWJ1dHRvbj5cbiAgPC9lbC1yYWRpby1ncm91cD5cbiAgPGVsLW1lbnVcbiAgICBkZWZhdWx0LWFjdGl2ZT1cIjEtM1wiXG4gICAgY2xhc3M9XCJlbC1tZW51LXZlcnRpY2FsLWRlbW9cIlxuICAgIDpjb2xsYXBzZT1cImlzQ29sbGFwc2VcIlxuICAgIEBvcGVuPVwiaGFuZGxlT3BlblwiXG4gICAgQGNsb3NlPVwiaGFuZGxlQ2xvc2VcIlxuICA+XG4gICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMVwiPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5cbiAgICAgICAgPGVsLWljb24+PGxvY2F0aW9uIC8+PC9lbC1pY29uPlxuICAgICAgICA8c3Bhbj5OYXZpZ2F0b3IgT25lPC9zcGFuPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+PHNwYW4+R3JvdXAgT25lPC9zcGFuPjwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIxLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtbWVudS1pdGVtLWdyb3VwPlxuICAgICAgPGVsLW1lbnUtaXRlbS1ncm91cCB0aXRsZT1cIkdyb3VwIFR3b1wiPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMS0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1tZW51LWl0ZW0tZ3JvdXA+XG4gICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCIxLTRcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT48c3Bhbj5pdGVtIGZvdXI8L3NwYW4+PC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjEtNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPC9lbC1zdWItbWVudT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiLzJcIj5cbiAgICAgIDxlbC1pY29uPjxpY29uLW1lbnUgLz48L2VsLWljb24+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPk5hdmlnYXRvciBUd288L3RlbXBsYXRlPlxuICAgIDwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCIgZGlzYWJsZWQ+XG4gICAgICA8ZWwtaWNvbj48ZG9jdW1lbnQgLz48L2VsLWljb24+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPk5hdmlnYXRvciBUaHJlZTwvdGVtcGxhdGU+XG4gICAgPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjRcIj5cbiAgICAgIDxlbC1pY29uPjxzZXR0aW5nIC8+PC9lbC1pY29uPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5OYXZpZ2F0b3IgRm91cjwvdGVtcGxhdGU+XG4gICAgPC9lbC1tZW51LWl0ZW0+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBEb2N1bWVudCxcbiAgTWVudSBhcyBJY29uTWVudSxcbiAgTG9jYXRpb24sXG4gIFNldHRpbmcsXG59IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBpc0NvbGxhcHNlID0gcmVmKHRydWUpXG5jb25zdCBoYW5kbGVPcGVuID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG5jb25zdCBoYW5kbGVDbG9zZSA9IChrZXk6IHN0cmluZywga2V5UGF0aDogc3RyaW5nW10pID0+IHtcbiAgY29uc29sZS5sb2coa2V5LCBrZXlQYXRoKVxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5lbC1tZW51LXZlcnRpY2FsLWRlbW86bm90KC5lbC1tZW51LS1jb2xsYXBzZSkge1xuICB3aWR0aDogMjAwcHg7XG4gIG1pbi1oZWlnaHQ6IDQwMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. 切换 element-plus 版本到 2.1.11，点击“expand”，无法展开默认激活菜单
2. 切换 element-plus 版本到 2.1.10，点击“expand”，菜单可以正常展开

### What is Expected?

展开默认激活菜单

### What is actually happening?

无法展开默认激活菜单

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by holazz**
closes #9066

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/menu/src/menu.ts [hunk 1]
```diff
@@ -236,6 +236,8 @@ export default defineComponent({
       }
     )
 
+    watch(items.value, initMenu)
```
Comment (xiaoxian521) [inline packages/components/menu/src/menu.ts:239]: I think the following code will be more friendly, what do you think
```
watchEffect(() => {
     items.value && initMenu()
 })
```

**Review by xiaoxian521 — CHANGES_REQUESTED** [review]

File: packages/components/menu/src/menu.ts (hunk 1 above)
Comment (holazz) [reply packages/components/menu/src/menu.ts:239]: This seems incorrect, since the `initMenu` may also be executed when other deps change. For example, when switching the opening and closing of the sub menu, `initMenu` will be executed so that we can't close the sub menu.

Comment (holazz) [reply packages/components/menu/src/menu.ts:239]: Also, I think we no need to invoke the `initMenu ` in these places anymore.

https://github.com/element-plus/element-plus/blob/7da11bc2e6c912a32dad873d90660510284663d4/packages/components/menu/src/menu.ts#L210-L213

https://github.com/element-plus/element-plus/blob/7da11bc2e6c912a32dad873d90660510284663d4/packages/components/menu/src/menu.ts#L292-L297

WDYT?

Comment (xiaoxian521) [reply packages/components/menu/src/menu.ts:239]: Tested your idea is correct, please wait for more tests

Comment (holazz) [reply packages/components/menu/src/menu.ts:238]: Okay, I have updated a commit.

Comment (xiaoxian521) [reply packages/components/menu/src/menu.ts:238]: well down

**Review by xiaoxian521 — APPROVED** [review]
LGTM

**Review by xiaoxian521 — APPROVED** [review]

File: packages/components/menu/src/menu.ts (hunk 1 above)
Comment (holazz) [reply packages/components/menu/src/menu.ts:238]: Thanks for your careful review.
