### PR TITLE
fix(components): [el-message-box] add default value to button-size

### LINKED ISSUE #5610: [Bug Report]MessageBox.confirm [Vue warn]: Invalid prop: validation failed. Expected one of ["large", "default", "small", ], got value "".
### Element Plus version
1.3.0-beta.7

### OS/Browsers version
windows

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/frontyang/pen/VwrZOzX

### Steps to reproduce
调用MessageBox.confirm，没有加size的情况，就会出现警告[Vue warn]: Invalid prop: validation failed. Expected one of ["large", "default", "small", ], got value "". 

### What is Expected?
没有size的情况不出现警告

### What is actually happening?
调用MessageBox.confirm，没有加size的情况，就会出现警告[Vue warn]: Invalid prop: validation failed. Expected one of ["large", "default", "small", ], got value "".

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #5610

### CODE REVIEW

File: packages/components/message-box/src/index.vue [hunk 1]
```diff
@@ -170,6 +170,7 @@ export default defineComponent({
     buttonSize: {
       type: String as PropType<ComponentSize>,
       validator: isValidComponentSize,
+      default: 'default',
```
Comment (sxzz) [inline packages/components/message-box/src/index.vue:173]: required: false,

remove `default`, since we have ConfigProvider to provide default size.

File: packages/components/message-box/src/index.vue [hunk 2]
```diff
@@ -261,6 +261,8 @@ export default defineComponent({
         : ''
     })
 
+    const btnSize = useSize(computed(() => props.buttonSize))
```
Comment (sxzz) [inline packages/components/message-box/src/index.vue:264]:
```suggestion
    const btnSize = useSize()
```

File: packages/components/message-box/src/index.vue [hunk 3]
```diff
@@ -260,6 +261,8 @@ export default defineComponent({
         : ''
     })
 
+    const btnSize = useSize()
```
Comment (sxzz) [inline packages/components/message-box/src/index.vue:264]: Sooooory, it should be
```suggestion
    const btnSize = useSize(
      computed(() => props.buttonSize),
      { prop: true, form: true, formItem: true }
    )
```

Comment (btea) [reply packages/components/message-box/src/index.vue:264]: ok

**Review by sxzz — APPROVED** [review]
