### PR TITLE
fix(components): [cascader-panel] get the reactive proxy of `node` to trigger side effects

### LINKED ISSUE #16193: [Component] [cascader-panel] v-model is-active error after value change
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.1`
- Browser / OS: `Chrome 123.0.6312.59 / Windows 11`
- Build Tool: `Other`

### Related Component

- `el-cascader-panel`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNhc2NhZGVyLXBhbmVsIDpvcHRpb25zPVwib3B0aW9uc1wiIHYtbW9kZWw9XCJzZWxlY3RcIiByZWY9XCJwYW5lbFwiLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBzZWxlY3QgPSByZWYoWydndWlkZScsICdkaXNjaXBsaW5lcyddKTtcbmNvbnN0IHBhbmVsID0gcmVmKCk7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBzZWxlY3QudmFsdWUgPSBbJ2d1aWRlJywgJ25hdmlnYXRpb24nXTsgLy8gaW52YWxpZFxufSwgMjAwMCk7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBwYW5lbC52YWx1ZT8uY2xlYXJDaGVja2VkTm9kZXMoKTtcbiAgbmV4dFRpY2soKCkgPT4ge1xuICAgIHNlbGVjdC52YWx1ZSA9IFsnZ3VpZGUnLCAnbmF2aWdhdGlvbiddOyAvLyBDYW5cbiAgfSk7XG59LCA0MDAwKTtcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnZ3VpZGUnLFxuICAgIGxhYmVsOiAnR3VpZGUnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZGlzY2lwbGluZXMnLFxuICAgICAgICBsYWJlbDogJ0Rpc2NpcGxpbmVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbidcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

Element Plus Playground run code
1. variable initialization  `const select = ref(['guide', 'disciplines']);`
2. setTimeout `select.value = ['guide', 'navigation'];` invalid
3. After calling the clearCheckedNodes function
   `select.value = ['guide', 'navigation'];` Can

### What is Expected?

is-active class ok

### What is actually happening?

is-active class not found

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by makedopamine**
fixes #16193

[before](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNhc2NhZGVyLXBhbmVsIDpvcHRpb25zPVwib3B0aW9uc1wiIHYtbW9kZWw9XCJzZWxlY3RcIiByZWY9XCJwYW5lbFwiLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBzZWxlY3QgPSByZWYoWydndWlkZScsICdkaXNjaXBsaW5lcyddKTtcbmNvbnN0IHBhbmVsID0gcmVmKCk7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBzZWxlY3QudmFsdWUgPSBbJ2d1aWRlJywgJ25hdmlnYXRpb24nXTsgLy8gaW52YWxpZFxufSwgMjAwMCk7XG5cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnZ3VpZGUnLFxuICAgIGxhYmVsOiAnR3VpZGUnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZGlzY2lwbGluZXMnLFxuICAgICAgICBsYWJlbDogJ0Rpc2NpcGxpbmVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbidcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

[after](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNhc2NhZGVyLXBhbmVsIDpvcHRpb25zPVwib3B0aW9uc1wiIHYtbW9kZWw9XCJzZWxlY3RcIiByZWY9XCJwYW5lbFwiLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBuZXh0VGljaywgcmVmIH0gZnJvbSBcInZ1ZVwiO1xuXG5jb25zdCBzZWxlY3QgPSByZWYoWydndWlkZScsICdkaXNjaXBsaW5lcyddKTtcbmNvbnN0IHBhbmVsID0gcmVmKCk7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICBzZWxlY3QudmFsdWUgPSBbJ2d1aWRlJywgJ25hdmlnYXRpb24nXTsgLy8gaW52YWxpZFxufSwgMjAwMCk7XG5cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAnZ3VpZGUnLFxuICAgIGxhYmVsOiAnR3VpZGUnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnZGlzY2lwbGluZXMnLFxuICAgICAgICBsYWJlbDogJ0Rpc2NpcGxpbmVzJyxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbidcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNjE5OC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE2MTk4LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xNjE5OC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsKHN0eWxlcylcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNjE5OC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

### CODE REVIEW

File: packages/components/cascader-panel/src/index.vue [hunk 1]
```diff
@@ -268,7 +268,7 @@ export default defineComponent({
       if (props.props.multiple) {
         reactive(newNodes).forEach((node) => node.doCheck(true))
       } else {
-        newNodes.forEach((node) => node.doCheck(true))
+        reactive(newNodes).forEach((node) => node.doCheck(true))
```
Comment (btea) [inline packages/components/cascader-panel/src/index.vue:271]: Lines 269 and 271 can be combined into one line.

**Review by btea — CHANGES_REQUESTED** [review]
Could you add relevant test cases?

**Review by btea — APPROVED** [review]

File: packages/components/cascader-panel/src/index.vue (hunk 1 above)
Comment (makedopamine) [reply packages/components/cascader-panel/src/index.vue]: Done, please take a look.

**Review by kooriookami — APPROVED** [review]
