### PR TITLE
fix(components): [loading] Compatible with vue3.2.0~12

### LINKED ISSUE #12351: [Component] [loading] 升级2.2.34版本后ElLoading组件的service.ts异常(The service.ts of the ElLoading component is abnormal after the 2.2.34 upgrade)
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.4`
- Element Plus Version: `2.2.34`
- Browser / OS: `Chrome/111.0.5563.147`
- Build Tool: `Vite`

### Related Component

- `el-loading`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHsgRWxMb2FkaW5nIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBsb2FkaW5nID0gcmVmKHRydWUpXG5FbExvYWRpbmcuc2VydmljZSh7XG4gICAgbG9jazogdHJ1ZSxcbiAgICB0ZXh0OiAnTG9hZGluZycsXG4gICAgYmFja2dyb3VuZDogJ3JnYmEoMCwgMCwgMCwgMC43KScsXG4gIH0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIFxuICAgICAgXG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

初始进入页面控制台报异常
( en:
An exception is reported on the console when the page is initially accessed
)

### What is Expected?

控制台无报警，页面正常加载
( en:
The console has no alarm, and the page loads normally
)
### What is actually happening?

控制台报以下异常
未捕获（承诺）：无法解构“n.vm.zIndex”的属性“nextZIndex”，因为它未定义。
( en:
The console reports the following exception
Cannot destructure property 'nextZIndex' of "instance.vm,zIndex' as it is undefined.
)
### Additional comments

故障代码
```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
import { ElLoading } from 'element-plus'
const msg = ref('Hello World!')
const loading = ref(true)
ElLoading.service({
    lock: true,
    text: 'Loading',
    background: 'rgba(0, 0, 0, 0.7)',
  });
</script>
<template>
  <h1>{{ msg }}</h1>
  <el-input v-model="msg" />
  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>
```

### PR DESCRIPTION
**Pull request by chenxch**
close #12351 

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by huangzhongzhong** [comment]
image
image

File: packages/components/loading/src/service.ts [hunk 1]
```diff
@@ -94,7 +94,9 @@ const addStyle = async (
   parent: HTMLElement,
   instance: LoadingInstance
 ) => {
-  const { nextZIndex } = (instance.vm as any).zIndex as UseZIndexReturn
+  const { nextZIndex } =
+    ((instance.vm as any).zIndex as UseZIndexReturn) ||
+    (instance.vm as any)._.exposed.zIndex
```
Comment (btea) [inline packages/components/loading/src/service.ts:99]: Maybe we can add a comment here.

Comment (chenxch) [reply packages/components/loading/src/service.ts:99]: done.

**Review by btea — APPROVED** [review]
