### PR TITLE
fix(components): [dialog] fix el-dialog z-index bug

### LINKED ISSUE #14369: [Component] [dialog] el-dialog  set z-index:0  can't work properly
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.2.27`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-demo-forked-2g59hw?file=/src/App.vue)

### Steps to reproduce

Set z-index to 0

### What is Expected?

The element z-index is 0

### What is actually happening?

The element z-index is default setting

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by nothing-sy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 104d38f</samp>

Fixed a bug in `use-dialog.ts` that caused incorrect `zIndex` for dialog components with `props.zIndex` set to 0. Improved the robustness of the `zIndex` assignment and update logic.

## Related Issue

Fixes #14369 

### <samp>🤖 Generated by Copilot at 104d38f</samp>

*  Use nullish coalescing operator to assign `zIndex` ref from `props.zIndex` or `nextZIndex()` ([link](https://github.com/element-plus/element-plus/pull/14373/files?diff=unified&w=0#diff-99f04200ea4398c3bc7e40a15a806092a6511285f14a99a318d333a30fdade68L38-R38))
*  Update `zIndex` value only if `props.zIndex` is provided and not 0, otherwise call `nextZIndex()` ([link](https://github.com/element-plus/element-plus/pull/14373/files?diff=unified&w=0#diff-99f04200ea4398c3bc7e40a15a806092a6511285f14a99a318d333a30fdade68L164-R164))

### CODE REVIEW

File: packages/components/dialog/src/use-dialog.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ export const useDialog = (
         closed.value = false
         open()
         rendered.value = true // enables lazy rendering
-        zIndex.value = props.zIndex ? zIndex.value++ : nextZIndex()
+        zIndex.value = props.zIndex || props.zIndex === 0 ? zIndex.value++ : nextZIndex()
```
Comment (btea) [inline packages/components/dialog/src/use-dialog.ts:164]:
```suggestion
        zIndex.value = isUndefined(props.zIndex) ? nextZIndex() :  zIndex.value++ 
```

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]
Thanks!
