### PR TITLE
fix(table): fix bug caused by dynamic rendering

### LINKED ISSUE #1626: When dynamically generating el-table columns, some data will cause the website to fall into an infinite loop
### Element Plus version
1.0.2-beta.34

### OS/Browsers version
Mac Google Chrome 版本 89.0.4389.82

### Vue version
3.0.7

### Reproduction Link
https://github.com/chenkai0520/vue-element-plus-issue/blob/master/src/App.vue

### Steps to reproduce
动态生成el-table 列时某些数据会导致页面卡死
重现问题代码仓库文件
```html
<template>
    <el-table
      :data="dataInfo.rows"
      size='mini'
      border
      height="100%"
      style="width: 100%;">
      <el-table-column  v-for="(value, key) in dataInfo.columns" :key="key" :prop="key">
        <template #header>
          <div>{{key}}</div>
          <div>{{value}}</div>
        </template>
      </el-table-column>
    </el-table>
</template>
```
https://github.com/chenkai0520/vue-element-plus-issue/blob/master/src/App.vue

如果用slot的方式是正常的，
```html
<template #default="scope">
    <div>{{scope.row[key]}}</div>
</template>
```
此外如果不用单文件组件的方式是正常的
https://jsfiddle.net/aq4jfg19/

问题似乎是由`prop` 触发的

### What is Expected?
无

### What is actually happening?
动态生成el-table 列时某些数据会陷入某个死循环

### PR DESCRIPTION
**Pull request by justwiner**
fix #1626

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/table/src/table-column/render-helper.ts [hunk 1]
```diff
@@ -127,7 +128,7 @@ function useRender(props: TableColumnCtx, slots, owner: ComputedRef<any>) {
           }
         }
         checkSubColumn(children)
-        return h('div', props, [prefix, children])
+        return h('div', props, [prefix, cloneDeep(children)])
```
Comment (JeremyWuuuuu) [inline packages/table/src/table-column/render-helper.ts:131]: Will we have overhead when the children is large enough?

Comment (justwiner) [reply packages/table/src/table-column/render-helper.ts:131]: The data rendered here is the data of the cell. This data is not very large. This is mainly aimed at solving the problem caused by memory address reference.

**Review by jw-foss — APPROVED** [review]

**Review by Ryan2128 — APPROVED** [review]
