### PR TITLE
fix(components): [input-number] Improve modelValue prop type

### LINKED ISSUE #14848: [TypeScript] [input-number] el-input-number的value-on-clear会导致v-model的类型不正确
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.4.1`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IG4gPSByZWY8bnVtYmVyfHVuZGVmaW5lZD4oKVxuXG53YXRjaCgoKSA9PiBuLnZhbHVlLCAodmFsOiBudW1iZXJ8dW5kZWZpbmVkKSA9PiB7XG4gIGlmKHZhbCA9PT0gbnVsbCkge1xuICAgIC8vIC4uLlxuICB9XG59KVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbiB9fTwvaDE+XG4gIDxlbC1pbnB1dC1udW1iZXIgdi1tb2RlbD1cIm5cIiA6dmFsdWUtb24tY2xlYXI9XCJudWxsXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

创建一个响应式变量n: number|undefined（这是el-input-number的v-model要求的）。给el-input-number的v-model传递n，value-on-clear指定null值。在输入框填入数字，然后删除，并观察n.value的值变化。

### What is Expected?

v-model的类型会根据value-on-clear的参数进行变化，或者更改设计对typescript更友好

### What is actually happening?

n的类型必须指定为number|undefined（适应v-model的要求），但运行时的实际类型为number|null，导致对typescript编程不友好。

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by XL-YiBai**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### Description
The acceptable types for value-on-clear prop are: `'min' | 'max' | null | number`.
When clearing the input box, the value bound with the v-model may be modified to `number | null | undefined`. Therefore, modelValue should be allowed to accept `null` type.

### Related Issue
Fixes [#14848 ](https://github.com/element-plus/element-plus/issues/14848)

### CODE REVIEW

**Comment by btea** [comment]
Can you handle the code conflict?

**Comment by XL-YiBai** [comment]
Hi @btea , I have resolved the code conflict. Could you please review the PR again? Thanks.🍺

**Review by FrontEndDog — APPROVED** [review]

**Comment by FrontEndDog** [comment]
Thanks!

**Review by btea — APPROVED** [review]

**Comment by kooriookami** [comment]
All other props should accept `null` or `undefined`. Refer to doc of Vue. What do you think?

https://vuejs.org/guide/components/props.html#prop-validation

```
(`null` and `undefined` values will allow any type)
```

**Comment by XL-YiBai** [comment]
If prop fail Vue's verification, a warning will be thrown on the console: `[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Number with value 1, got String with value "1".`.
`null` and `undefined` can indeed pass Vue's validation, but in fact, if only the `modelValue` type is specified as `Number`, then when `n` is of type `number | null`, using `v-model="n"` will give the following prompt in VScode:
image

File: packages/components/input-number/src/input-number.ts [hunk 1]
```diff
@@ -45,7 +45,10 @@ export const inputNumberProps = buildProps({
   /**
    * @description binding value
    */
-  modelValue: Number,
+  modelValue: {
+    type: [Number, null],
+    validator: (val: number | null) => val === null || isNumber(val),
```
Comment (kooriookami) [inline packages/components/input-number/src/input-number.ts:50]:
```suggestion
```

Comment (kooriookami) [reply packages/components/input-number/src/input-number.ts:50]: No need to add a validator.

**Review by kooriookami — CHANGES_REQUESTED** [review]

**Comment by kooriookami** [comment]
Please resolve the conflicts, then this PR can be merged.

**Review by kooriookami — APPROVED** [review]

**Comment by XL-YiBai** [comment]
Thanks 🍻

**Comment by JCL206312** [comment]
However, ColorPicker also has the same problem, after clicking the clear, the value of v-model will also become null
