### PR TITLE
fix(components): date-picker add keydown events(#7506)

### LINKED ISSUE #7506: [Bug Report] [Component] [date-picker] plus版本日期组件不支持keyup、keydown等键盘事件，现在我想触发键盘事件，要自己打补丁吗？
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.22`
- Element Plus Version: `2.1.10`
- Browser / OS: `谷歌浏览器/mac`
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB0aW1lID0gcmVmKCcnKVxuY29uc3QgbWV0aG9kcyA9IHtcbiAgdGVzdCgpe1xuICAgIGNvbnNvbGUubG9nKCdlbnRlcuS6i+S7ticpXG4gIH0sXG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gICAgPGVsLWRhdGUtcGlja2VyXG5cdFx0XHR2LW1vZGVsPVwidGltZVwiXG5cdFx0XHRyZWY9XCJzZXR0YWdSZWZcIlxuICAgICAgdHlwZT1cImRhdGVcIlxuXHRcdFx0QGtleXVwLmVudGVyPVwibWV0aG9kcy50ZXN0XCJcblx0XHQ+PC9lbC1kYXRlLXBpY2tlcj5cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

```vue
<script setup>
import { ref } from 'vue'
const time = ref('')
const methods = {
  test(){
    console.log('enter事件')
  },
}
</script>
<template>
  <p>
    <el-date-picker v-model="time" ref="settagRef" type="date" @keyup.enter="methods.test"></el-date-picker>
  </p>
</template>
```

### What is Expected?

期望能触发keyup enter事件，或提供一个api来触发键盘事件

### What is actually happening?

keyup事件无任何反应，无打印

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by lily-elephant**
目前日期组件不支持键盘事件，所以emit了keyup事件，来满足项目需求中form表单日期元素的全键盘事件，全键盘事件对于用户还是很重要的一个需求和体验，如果我做的不合适，希望贵方能给日期组件开放一个键盘事件口子

### CODE REVIEW

File: packages/components/time-picker/src/common/picker.vue [hunk 1]
```diff
@@ -555,7 +564,7 @@ export default defineComponent({
 
     const handleKeydown = (event) => {
       const code = event.code
-
+      emitKeyup(event)
```
Comment (Giwayume) [inline packages/components/time-picker/src/common/picker.vue:567]: This is going to cause the keyup event to be emitted on keydown instead of keyup.

Comment (lily-elephant) [reply packages/components/time-picker/src/common/picker.vue:630]: > 

我想改一改

File: packages/components/time-picker/src/common/picker.vue [hunk 2]
```diff
@@ -348,6 +352,11 @@ export default defineComponent({
         _inputs[1].focus()
       }
     }
+
+    const onKeydown = (e) => {
```
Comment (Giwayume) [inline packages/components/time-picker/src/common/picker.vue:356]: You can remove this, it's unused.

File: packages/components/time-picker/src/common/picker.vue [hunk 3]
```diff
@@ -757,6 +765,7 @@ export default defineComponent({
       onMouseDownInput,
       onMouseLeave,
       onMouseEnter,
+      onKeydown,
```
Comment (Giwayume) [inline packages/components/time-picker/src/common/picker.vue:768]: Also remove this, unused in the template.

Comment (Giwayume) [reply packages/components/time-picker/src/common/picker.vue:768]: The `handleKeydownInput` callback already runs for the input keydown

Comment (lily-elephant) [reply packages/components/time-picker/src/common/picker.vue:768]: 如果不在这里emit keydown事件，日期组件上怎么执行键盘事件？我给el-date-picker添加keydown事件，会报警告的
<el-date-picker v-model="time" type="month" ref="dateRef" @keydown.enter="methods.handleEnter"></el-date-picker>

Comment (Giwayume) [reply packages/components/time-picker/src/common/picker.vue:768]: This lines already emit the keydown event:

https://github.com/element-plus/element-plus/pull/7536/files#diff-3d026a2d83f86f5dc2ce3aa7b95b77eff4a475e67c362841827e0e1bac7456abR326

https://github.com/element-plus/element-plus/pull/7536/files#diff-3d026a2d83f86f5dc2ce3aa7b95b77eff4a475e67c362841827e0e1bac7456abR630

I'm seeing it in my testing:

image

The `onKeydown` function is unused, update your local branch from `dev`. Maybe you're looking at older code?

Comment (Giwayume) [reply packages/components/time-picker/src/common/picker.vue:768]: > <el-date-picker v-model="time" type="month" ref="dateRef" @keydown.enter="methods.handleEnter">

Try changing to this?

```<el-date-picker v-model="time" type="month" ref="dateRef" @keydown.enter="handleEnter">```

**Comment by Giwayume** [comment]
Can you add unit tests for the new event?

File: packages/components/time-picker/src/common/picker.vue (hunk 3 above)
Comment (lily-elephant) [reply packages/components/time-picker/src/common/picker.vue]: 我懂了，我的代码写多余了，感谢指点。

**Comment by lily-elephant** [comment]
> @lily-elephant The coding change looks good. Can you add a unit test real quick? https://github.com/element-plus/element-plus/blob/dev/packages/components/time-picker/__tests__/time-picker.test.ts

加上单测了

File: packages/components/time-picker/__tests__/time-picker.test.ts [hunk 4]
```diff
@@ -243,6 +245,9 @@ describe('TimePicker', () => {
           onBlur(e) {
             return blurHandler(e)
           },
+          onKeydown(e) {
+            return keydownHandler(e)
+          },
         },
       }
     )
```
Comment (Giwayume) [inline packages/components/time-picker/__tests__/time-picker.test.ts:253]: Need to add some 'expect' statements to each of these tests, otherwise nothing is tested.

Something like this:

```
input.trigger('keydown')
await nextTick()
expect(keydownHandler).toHaveBeenCalledTimes(1)
```

**Comment by Giwayume** [comment]
Need to fix lint errors:

https://github.com/element-plus/element-plus/runs/6422960093?check_suite_focus=true#step:7:12

**Review by jw-foss — APPROVED** [review]

**Comment by Giwayume** [comment]
> LGTM /cc @Giwayume do you think this is ready?

Yes

**Review by Giwayume — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
✅ :rocket:
