### PR TITLE
fix(components): [el-collapse] watch modelValue invalid

### LINKED ISSUE #4587: [Bug Report] Collapse dont't watch v-model change when the model type of Array
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
chrome 96.0.4664.45

### Vue version
3.2.23

### Reproduction Link
https://codepen.io/liwenda/pen/XWeWYdy

### Steps to reproduce
ref model is array
then onMounted to pushed the model 
in html the model is changed 
but the Collapse don't to change 

### What is Expected?
ref model is array
then onMounted to pushed the model 
in html the model is changed 
and the Collapse to change 

### What is actually happening?
ref model is array
then onMounted to pushed the model 
in html the model is changed 
but the Collapse don't to change

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #4587

### CODE REVIEW

**Comment by Alanscut** [comment]
@msidolphin ok

**Review by jagoncalves14 — APPROVED** [review]

File: packages/components/collapse/src/collapse.vue [hunk 1]
```diff
@@ -57,6 +57,9 @@ export default defineComponent({
       () => props.modelValue,
       () => {
         activeNames.value = [].concat(props.modelValue)
+      },
+      {
+        deep: true,
       }
```
Comment (JeremyWuuuuu) [inline packages/components/collapse/src/collapse.vue:63]: Do you think it is possible to watch like this:

```ts
watch(() => props.modelValue.length, handler)
```

instead of adding `deep`?

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
I left a comment for you, but note that this is not a blocking comment, so you can merge this by yourself if you don't think the suggestions is good.

File: packages/components/collapse/src/collapse.vue (hunk 1 above)
Comment (Alanscut) [reply packages/components/collapse/src/collapse.vue:63]: Performance of `deep` is indeed not as good as `watch`.

When `length` is not changed but the item changed, it can't be monitoring, so should we watch both `props.modelVaule` and `props.modelValue.length`?

Comment (JeremyWuuuuu) [reply packages/components/collapse/src/collapse.vue:63]: Let's use deep here for now, if there is any perf concern we can try to fix it later.

**Comment by JeremyWuuuuu** [comment]
LGTM, merged!
