### PR TITLE
fix(components): [el-table] defaultSort not working

### LINKED ISSUE #6313: [Bug Report] [Component] [table] el-table中default-sort属性无效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.0.3`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IFVzZXIgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdGFibGVEYXRhID0gW1xuICAgICAge1xuICAgICAgICB1c2VybmFtZTogXCJUb21cIixcbiAgICAgICAgbW9uZXk6IFwiMSwwMDAsMDBcIixcbiAgICAgICAgb3BlcmF0aW9uOiBcIk5vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlc1wiLFxuICAgICAgICBkYXRlOiBcIjIwMTYtMDUtMDNcIixcbiAgICAgICAgc3RhdHVzOiAxLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdXNlcm5hbWU6IFwiVG9tXCIsXG4gICAgICAgIG1vbmV5OiBcIjEsMDAwLDAwXCIsXG4gICAgICAgIG9wZXJhdGlvbjogXCJOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXNcIixcbiAgICAgICAgZGF0ZTogXCIyMDE2LTA1LTAzXCIsXG4gICAgICAgIHN0YXR1czogMSxcbiAgICAgIH0sXG4gICAgXTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZVxuICAgIDpkZWZhdWx0LXNvcnQ9XCJ7IHByb3A6ICdkYXRlJywgb3JkZXI6ICdkZXNjZW5kaW5nJyB9XCJcbiAgICB0YWJsZS1sYXlvdXQ9XCJhdXRvXCJcbiAgICA6ZGF0YT1cInRhYmxlRGF0YVwiXG4gICAgc3RyaXBlXG4gICAgYm9yZGVyXG4gICAgbWF4LWhlaWdodD1cIjM1MFwiXG4gID5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJ1c2VybmFtZVwiIGxhYmVsPVwi55So5oi3SURcIiB3aWR0aD1cIlwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibW9uZXlcIiBsYWJlbD1cIuaPkOeOsOmHkeminVwiIHNvcnRhYmxlIHdpZHRoPVwiXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJvcGVyYXRpb25cIiBsYWJlbD1cIuaPj+i/sOaTjeS9nFwiIHdpZHRoPVwiXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJkYXRlXCIgbGFiZWw9XCLml7bpl7RcIiBzb3J0YWJsZSB3aWR0aD1cIlwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwic3RhdHVzXCIgbGFiZWw9XCLnirbmgIFcIiB3aWR0aD1cIlwiIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

配置el-plus版本2.0.3，vue 3.2以上均是这样

### What is Expected?

el-table设置default-sort默认排序好用

### What is actually happening?

el-table中设置了default-sort,默认排序仍然不好用

### Additional comments

el-plus版本2.0.2没问题，到2.0.3版本就有问题了

### PR DESCRIPTION
**Pull request by msidolphin**
fix #6313

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/table/src/table-header/index.ts [hunk 1]
```diff
@@ -63,12 +63,13 @@ export default defineComponent({
...
-        const init = true
-        parent?.store.commit('sort', { prop, order, init })
-      })
+    onMounted(async () => {
+      // Need double await, because udpateColumns is executed after nextTick for now
+      await nextTick()
+      await nextTick()
+      const { prop, order } = props.defaultSort
+      const init = true
+      parent?.store.commit('sort', { prop, order, init })
```
Comment (JeremyWuuuuu) [inline packages/components/table/src/table-header/index.ts:72]:
```suggestion
parent?.store.commit('sort', { prop, order, init: true })
```

**Review by jw-foss — APPROVED** [review]
