### PR TITLE
fix(table): fix: page resize event not monitor

### LINKED ISSUE #1691: [bug report] when the page is enlarged, the head and content of El table will be misplaced
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
windows Google Chrome 版本 89.0.4389.90（正式版本）

### Vue version
3.0.7

### Reproduction Link
https://codepen.io/yeyue1992/pen/mdReYaV

### Steps to reproduce
Chrome  ctrl     Zoom in page

浏览器放大页面

### What is Expected?
希望能够修复

### What is actually happening?
放大的使用不出现错位现象

### PR DESCRIPTION
**Pull request by justwiner**
Monitor the page size change event, update the table layout

fix #1691

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/table/src/table/style-helper.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { onMounted, onUnmounted, computed, ref, watchEffect, watch } from 'vue'
 import {
   addResizeListener,
   removeResizeListener,
+  ResizableElement,
```
Comment (JeremyWuuuuu) [inline packages/table/src/table/style-helper.ts:5]: import type standalone, instead of in the actual import statement, like this:
```ts
import type { ResizableElement } from '@element-plus/utils/resize-event'
```

Comment (justwiner) [reply packages/table/src/table/style-helper.ts]: OK

**Review by jw-foss — APPROVED** [review]
