### PR TITLE
fix(components): [virtual-list] prevent scroll from exceeding its bounds

### LINKED ISSUE #22756: [Component] [select-v2] selectV2 在火狐浏览器 144.0.2 (64 位）下滚动条滚动到底部之后还能滚动，滚动条超出最底部
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.11.7`
- Browser / OS: `firefox`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSByZWYoXG4gIEFycmF5LmZyb20oeyBsZW5ndGg6IDEwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICAgIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICAgIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbiAgfSkpXG4pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD5cbiAgICAgPGVsLXNlbGVjdC12MlxuICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICBtdWx0aXBsZVxuICAvPlxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开环境链接;打开下拉选择列表，将滚动条滚动到底部继续缓慢滚动。观察滚动条位置

### What is Expected?

滚动带底部不能滚动了，滚动条样式期望正常

### What is actually happening?

滚动条还能缓慢滚动

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by rzzf**
fix #22756

The default styles of the `<ul>` element cause its actual width to exceed the container, which results in scrolling beyond the allowed range when using a touchpad. I couldn’t reproduce the vertical scrolling issue mentioned in #22756, but it seems to be a related problem.

https://github.com/user-attachments/assets/cc397555-d552-4749-aef1-dc98129bffef

### CODE REVIEW

**Comment by patienry** [comment]
### Touchpad

https://github.com/user-attachments/assets/582fc286-c7e8-442a-bdb2-6066b9d8f9aa


### Mouse wheel

https://github.com/user-attachments/assets/7a846d11-b541-48a2-bfef-7241687f35ca

I found that when using **touchpad**, there is a flickering issue, but the scrollbar does not exceed the container in the end. However, when using **mouse wheel**, the scrollbar does eventually exceed the container. This was tested on **Windows**, and I'm not sure if it’s related to the operating system. I haven't come up with a suitable solution, but I hope this test result can help you troubleshoot the issue. 😂

**Comment by rzzf** [comment]
> I found that when using **touchpad**, there is a flickering issue, but the scrollbar does not exceed the container in the end. However, when using **mouse wheel**, the scrollbar does eventually exceed the container. This was tested on **Windows**, and I'm not sure if it’s related to the operating system. I haven't come up with a suitable solution, but I hope this test result can help you troubleshoot the issue. 😂

Oh, that's strange. Since I don’t have a Windows device with a mouse, I’m guessing it might be related to how the scroll event calculates positions, or perhaps it’s a [Firefox-specific](
https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html) behavior. Could you help me with this? Alternatively, you can open a new PR and close this one.

**Comment by patienry** [comment]
Compatibility issues like this are always quite troublesome. 😢 I haven't come up with a suitable solution yet, but I'll try to resolve it when I have time. If this PR fixes the issue on **macOS**, maybe we can merge it first and then wait for an appropriate PR to address the issue on **Windows**, which could take quite a long time. 😂

**Comment by rzzf** [comment]
> If this PR fixes the issue on **macOS**, maybe we can merge it first and then wait for an appropriate PR to address the issue on **Windows**, which could take quite a long time. 😂

Makes sense. Looking forward to your PR👍

**Comment by warmthsea** [comment]
This issue may be related to a change in version 2.11.4.

- https://github.com/element-plus/element-plus/pull/22153

screenshots


https://github.com/element-plus/element-plus/blob/dev/packages/components/select-v2/src/select-dropdown.tsx#L282

screenshots

**Comment by warmthsea** [comment]
It seems that clearing the `margin` of the `ul` resolves the issue.

## `div`
image

## `ul`
image

**Comment by rzzf** [comment]
> It seems that clearing the `margin` of the `ul` resolves the issue.

@warmthsea Thanks for your help! Please help me look into the Windows issue when you have a moment. 🙇

**Comment by patienry** [comment]
It works fine on my computer. 👍

File: packages/components/virtual-list/src/builders/build-list.ts [hunk 1]
```diff
@@ -143,6 +143,10 @@ const createList = ({
           height: horizontal ? '100%' : `${size}px`,
           pointerEvents: unref(states).isScrolling ? 'none' : undefined,
           width: horizontal ? `${size}px` : '100%',
+
+          // fix scrolling issues in Firefox.
+          margin: 0,
+          boxSizing: 'border-box',
```
Comment (warmthsea) [inline packages/components/virtual-list/src/builders/build-list.ts:149]: I recommend adding it only when `props.innerElement === 'ul'`.

image

Comment (rzzf) [reply packages/components/virtual-list/src/builders/build-list.ts:149]: In fact, any element with default browser styles that include margin or padding could potentially cause this issue. Although we're currently only using `<ul>` and `<div>`, I think it’s best to avoid similar situations in the future.

WDYT?

Comment (rzzf) [reply packages/components/virtual-list/src/builders/build-list.ts:149]: Additionally, I think `build-grid` should handle this as well.

Comment (warmthsea) [reply packages/components/virtual-list/src/builders/build-list.ts:149]: ok

**Review by warmthsea — APPROVED** [review]

**Review by Dsaquel — APPROVED** [review]
