### PR TITLE
fix: [image-viewer] two-finger zoom in and out

### LINKED ISSUE #3080: [Bug Report] bug el-image preview The browser is not disabled by default
### Element Plus version
1.1.0-beta.5

### OS/Browsers version
macos 11.4 chrome  92.0.4515.159

### Vue version
3.2.2

### Reproduction Link
https://codepen.io/CN-litai/pen/powJzPx

### Steps to reproduce
click image Zoom in and out using the touchpad

### What is Expected?
Only the picture size is changed

### What is actually happening?
The browser page size has also been changed

### PR DESCRIPTION
**Pull request by Alanscut**
fix [issue#3080](https://github.com/element-plus/element-plus/issues/3080)
stop the respond of brower about two-finger zoom in and out

Please make sure these boxes are checked before submitting your PR, thank you!

* [√ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [√ ] Make sure you are merging your commits to `dev` branch.
* [√ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/image/src/index.vue [hunk 1]
```diff
@@ -130,6 +130,18 @@ export default defineComponent({
...
+          if (e.deltaY < 0) {
+            e.preventDefault()
+            return false
+          }
+          if (e.deltaY > 0) {
+            e.preventDefault()
+            return false
+          }
+        }
+      }, { passive: false })
```
Comment (JeremyWuuuuu) [inline packages/components/image/src/index.vue:144]: Humm,
1. I don't think binding event in `computed` is a good idea
2. plus you didn't remove the listener since you are attaching this event to the `body` element

**Comment by CNlitai** [comment]
i fix this bug https://github.com/element-plus/element-plus/pull/3121
please review

**Comment by sxzz** [comment]
IMO it should be better to put the code in `packages/components/image-viewer/src/index.vue`

File: packages/components/image/src/index.vue (hunk 1 above)
Comment (Alanscut) [reply packages/components/image/src/index.vue:144]: ok, i will change it from computed the `chlickHandler()`, and remove the listenenr in `closeViewer()`

**Comment by Alanscut** [comment]
> IMO it should be better to put the code in `packages/components/image-viewer/src/index.vue`

you can see the issue, the problem is when image-viewer show , the page which include image is still show in the bottom(as the background). so if we want to zoom  in(out) image-viewer and at the same time dont't zoom the bottom page , it should be in `image/src/index.vue`

File: packages/components/image/src/index.vue (hunk 1 above)
Comment (Alanscut) [reply packages/components/image/src/index.vue]: @JeremyWuuuuu is this ok now

**Comment by sxzz** [comment]
@JeremyWuuuuu WDYT?

File: packages/components/image/src/index.vue [hunk 2]
```diff
@@ -246,18 +246,33 @@ export default defineComponent({
...
+        }
+      }
+    }
+
     function clickHandler() {
       // don't show viewer when preview is false
       if (!preview.value) {
         return
       }
+      document.body.addEventListener('wheel', _wheelHandler, { passive: false })
```
Comment (JeremyWuuuuu) [inline packages/components/image/src/index.vue:267]: use `on` and `off` in `@element-plus/utils/dom` for attaching/dettaching events. :bow:

Comment (JeremyWuuuuu) [reply packages/components/image/src/index.vue:267]: Also, would you mind adding tests against these changes? If you have trouble doing that I can guide you through it.

Comment (JeremyWuuuuu) [reply packages/components/image/src/index.vue:267]: Plus: please add this to co-responding file `el-image-viewer`, you can add it into the `onMounted` and `onBeforeUnmounted` hooks.

Comment (Alanscut) [reply packages/components/image/src/index.vue:267]: ok, i will change code to use `on` ( `off` ) and learn to add tests.

Comment (Alanscut) [reply packages/components/image/src/index.vue:267]: @JeremyWuuuuu i try to use `on` function but it's fourth parameter is `useCapture: boolean`, it can't be set as `{passive: false }

Comment (sxzz) [reply packages/components/image/src/index.vue:267]: You can use `addEventListener` first, and I will refactor it by using vueuse later

/cc @JeremyWuuuuu

**Review by sxzz — APPROVED** [review]

**Comment by Alanscut** [comment]
@sxzz do i need to bring up a new pr to add test case?

**Comment by sxzz** [comment]
> @sxzz do i need to bring up a new pr to add test case?

Well, that would be great.

**Comment by Alanscut** [comment]
> > @sxzz do i need to bring up a new pr to add test case?
> 
> Well, that would be great.

after read vue-test-utils documents, i was confusd how to test the position of image-viewer when mouse move .
i found that your image-viewer.spec.ts doesn't have test about mouse event before
