### PR TITLE
fix(components): [cascader] scrolls to the wrong active node

### LINKED ISSUE #23201: [Component] [cascader] 升级新版本后，Cascader无法自动定位到选中的叶子节点
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.26`
- Element Plus Version: `2.13.0`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0'`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXJcIj5cbiAgICA8ZWwtc3dpdGNoXG4gICAgICB2LW1vZGVsPVwic2hvd1ByZWZpeFwiXG4gICAgICBhY3RpdmUtdGV4dD1cInNob3cgcHJlZml4XCJcbiAgICAgIGluYWN0aXZlLXRleHQ9XCJoaWRlIHByZWZpeFwiXG4gICAgLz5cbiAgICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJtLTRcIj5cbiAgICAgICAgPHA+TXVsdGlwbGUgbW9kZTwvcD5cbiAgICAgICAgPGVsLWNhc2NhZGVyXG4gICAgICAgICAgdi1tb2RlbD1cInZhbHVlMlwiXG4gICAgICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgICAgICA6cHJvcHM9XCJwcm9wczJcIlxuICAgICAgICAgIGNsZWFyYWJsZVxuICAgICAgICAgIGNvbGxhcHNlLXRhZ3NcbiAgICAgICAgLz5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBjb21wdXRlZCwgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZTIgPSByZWYoKVxuY29uc3Qgc2hvd1ByZWZpeCA9IHJlZih0cnVlKVxuXG5jb25zdCBwcm9wczIgPSBjb21wdXRlZCgoKSA9PiAoe1xuICBtdWx0aXBsZTogdHJ1ZSxcbn0pKVxuXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdndWlkZScsXG4gICAgbGFiZWw6ICdHdWlkZScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdkaXNjaXBsaW5lcycsXG4gICAgICAgIGxhYmVsOiAnRGlzY2lwbGluZXMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnY29uc2lzdGVuY3knLFxuICAgICAgICAgICAgbGFiZWw6ICdDb25zaXN0ZW5jeScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAnbmF2aWdhdGlvbicsXG4gICAgICAgIGxhYmVsOiAnTmF2aWdhdGlvbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgdmFsdWU6ICdzaWRlIG5hdicsXG4gICAgICAgICAgICBsYWJlbDogJ1NpZGUgTmF2aWdhdGlvbicsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnY29tcG9uZW50JyxcbiAgICBsYWJlbDogJ0NvbXBvbmVudCcsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdiYXNpYycsXG4gICAgICAgIGxhYmVsOiAnQmFzaWMnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIHZhbHVlOiAnbGF5b3V0JyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGF5b3V0JyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdmb3JtJyxcbiAgICAgICAgbGFiZWw6ICdGb3JtJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICB2YWx1ZTogJ3JhZGlvJyxcbiAgICAgICAgICAgIGxhYmVsOiAnUmFkaW8nLFxuICAgICAgICAgIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgIF0sXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogJ3Jlc291cmNlJyxcbiAgICBsYWJlbDogJ1Jlc291cmNlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlJyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzJyxcbiAgICAgIH0sXG4gICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlMScsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50czEnLFxuICAgICAgfSxcbiAgICAgICB7XG4gICAgICAgIHZhbHVlOiAnYXh1cmUyJyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzMicsXG4gICAgICB9LFxuICAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZTMnLFxuICAgICAgICBsYWJlbDogJ0F4dXJlIENvbXBvbmVudHMzJyxcbiAgICAgIH0sXG4gICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlNCcsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50czQnLFxuICAgICAgfSxcbiAgICAgICB7XG4gICAgICAgIHZhbHVlOiAnYXh1cmU1JyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzNScsXG4gICAgICB9LFxuICAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZTYnLFxuICAgICAgICBsYWJlbDogJ0F4dXJlIENvbXBvbmVudHM2JyxcbiAgICAgIH0sXG4gICAgICAge1xuICAgICAgICB2YWx1ZTogJ2F4dXJlNycsXG4gICAgICAgIGxhYmVsOiAnQXh1cmUgQ29tcG9uZW50czcnLFxuICAgICAgfSxcbiAgICAgICB7XG4gICAgICAgIHZhbHVlOiAnYXh1cmU4JyxcbiAgICAgICAgbGFiZWw6ICdBeHVyZSBDb21wb25lbnRzOCcsXG4gICAgICB9LFxuICAgICAgIHtcbiAgICAgICAgdmFsdWU6ICdheHVyZTknLFxuICAgICAgICBsYWJlbDogJ0F4dXJlIENvbXBvbmVudHM5JyxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMS4yL2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuMTEuMi90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMS4yL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi4xMS4yL1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7ImVwVmVyc2lvbiI6IjIuMTEuMiJ9fQ==)

### Steps to reproduce

1. 选中Resource-Axure Components7、 Resource-Axure Components8 两个叶子节点，关闭下拉后重新打开，无法定位到选中的节点
2. 选中Resource-Axure Components7、 Resource-Axure Components8、Resource-Axure Components9 3个叶子节点，关闭下拉后重新打开，就可以定位到选中的节点

### What is Expected?

Cascader选中叶子节点后，重新打开可以定位到之前选择的叶子节点。

### What is actually happening?

如果选中了最后一个叶子节点可以定位，不选最后一个叶子节点无法定位。

### Additional comments

无

### PR DESCRIPTION
**Pull request by rzzf**
fix #23201

### CODE REVIEW

File: packages/components/cascader-panel/src/index.vue [hunk 1]
```diff
@@ -285,9 +285,8 @@ const scrollToExpandingNode = () => {
         `.${ns.namespace.value}-scrollbar__wrap`
       )
       const activeNode =
-        menuElement.querySelector(
-          `.${ns.b('node')}.${ns.is('active')}:last-child`
-        ) || menuElement.querySelector(`.${ns.b('node')}.in-active-path`)
+        menuElement.querySelector(`.${ns.b('node')}.in-active-path`) ||
+        menuElement.querySelector(`.${ns.b('node')}.${ns.is('active')}`)
```
Comment (rzzf) [inline packages/components/cascader-panel/src/index.vue]: I’m not sure why `in-active-path` has a lower priority than `active`, but intuitively, prioritizing `in-active-path` seems more reasonable. 
For example, in this case, the first panel scrolls to the last active node, while the second panel is actually still the one in the `in-active-path`. [play](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IG11bHRpcGx5IH0gZnJvbSAnbG9kYXNoJ1xuaW1wb3J0IHsgcmVmLCB2ZXJzaW9uIGFzIHZ1ZVZlcnNpb24gfSBmcm9tICd2dWUnXG5cbi8vIDEuIGNsaWNrIFwiMlwiIG5vZGVcbi8vIDIuIGNsb3NlIGRyb3Bkb3duXG4vLyAzLiBvcGVuIGRyb3Bkb3duXG5cbmNvbnN0IHNlbGVjdGVkID0gcmVmKFsnMTAtMScsJzEwLTInXSlcbmNvbnN0IHByb3BzID0ge1xuICBjaGVja1N0cmljdGx5OmZhbHNlLFxuICBlbWl0UGF0aDpmYWxzZSxcbiAgbXVsdGlwbGU6dHJ1ZSxcbn1cbmNvbnN0IG9wdGlvbnMgPSBbXG57XG4gIGxhYmVsOicxJyxcbiAgdmFsdWU6JzEnLFxuICBjaGlsZHJlbjpbXG4gICAge1xuICAgICAgbGFiZWw6JzEtMScsXG4gICAgICB2YWx1ZTonMS0xJyxcbiAgICB9LFxuICBdXG59LFxue1xuICBsYWJlbDonMicsXG4gIHZhbHVlOicyJyxcbiAgY2hpbGRyZW46W1xuICAgIHtcbiAgICAgIGxhYmVsOicyLTEnLFxuICAgICAgdmFsdWU6JzItMScsXG4gICAgfSxcbiAgXVxufSxcbntcbiAgbGFiZWw6JzMnLFxuICB2YWx1ZTonMycsXG4gIGNoaWxkcmVuOltcbiAgICB7XG4gICAgICBsYWJlbDonMy0xJyxcbiAgICAgIHZhbHVlOiczLTEnLFxuICAgIH1cbiAgXVxufSxcbntcbiAgbGFiZWw6JzQnLFxuICB2YWx1ZTonNCcsXG4gIGNoaWxkcmVuOltcbiAgICB7XG4gICAgICBsYWJlbDonNC0xJyxcbiAgICAgIHZhbHVlOic0LTEnLFxuICAgIH0sXG4gIF1cbn0sXG57XG4gIGxhYmVsOic1JyxcbiAgdmFsdWU6JzUnLFxuICBjaGlsZHJlbjpbXG4gICAge1xuICAgICAgbGFiZWw6JzUtMScsXG4gICAgICB2YWx1ZTonNS0xJyxcbiAgICB9XG4gIF1cbn0sXG57XG4gIGxhYmVsOic2JyxcbiAgdmFsdWU6JzYnLFxuICBjaGlsZHJlbjpbXG4gICAge1xuICAgICAgbGFiZWw6JzYtMScsXG4gICAgICB2YWx1ZTonNi0xJyxcbiAgICB9LFxuICBdXG59LFxue1xuICBsYWJlbDonNycsXG4gIHZhbHVlOic3JyxcbiAgY2hpbGRyZW46W1xuICAgIHtcbiAgICAgIGxhYmVsOic3LTEnLFxuICAgICAgdmFsdWU6JzctMScsXG4gICAgfSxcbiAgICB7XG4gICAgICBsYWJlbDonNy0yJyxcbiAgICAgIHZhbHVlOic3LTInLFxuICAgIH1cbiAgXVxufSxcbntcbiAgbGFiZWw6JzgnLFxuICB2YWx1ZTonOCcsXG4gIGNoaWxkcmVuOltcbiAgICB7XG4gICAgICBsYWJlbDonOC0xJyxcbiAgICAgIHZhbHVlOic4LTEnLFxuICAgIH0sXG4gICAge1xuICAgICAgbGFiZWw6JzgtMicsXG4gICAgICB2YWx1ZTonOC0yJyxcbiAgICB9XG4gIF1cbn0sXG57XG4gIGxhYmVsOic5JyxcbiAgdmFsdWU6JzknLFxuICBjaGlsZHJlbjpbXG4gICAge1xuICAgICAgbGFiZWw6JzktMScsXG4gICAgICB2YWx1ZTonOS0xJyxcbiAgICB9LFxuICAgIHtcbiAgICAgIGxhYmVsOic5LTInLFxuICAgICAgdmFsdWU6JzktMicsXG4gICAgfVxuICBdXG59LFxue1xuICBsYWJlbDonMTAnLFxuICB2YWx1ZTonMTAnLFxuICBjaGlsZHJlbjpbXG4gICAge1xuICAgICAgbGFiZWw6JzEwLTEnLFxuICAgICAgdmFsdWU6JzEwLTEnLFxuICAgIH0sXG4gICAge1xuICAgICAgbGFiZWw6JzEwLTInLFxuICAgICAgdmFsdWU6JzEwLTInLFxuICAgIH1cbiAgXVxufSxcblxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWNhc2NhZGVyIHYtbW9kZWw9XCJzZWxlY3RlZFwiIDpvcHRpb25zPVwib3B0aW9uc1wiIDpwcm9wcz1cInByb3BzXCIgY29sbGFwc2UtdGFncyBmaWx0ZXJhYmxlPjwvZWwtY2FzY2FkZXI+XG48L3RlbXBsYXRlPlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

related #20877

Comment (btea) [reply packages/components/cascader-panel/src/index.vue]: I've forgotten the reason, but this makes more sense.

```
menuElement.querySelector(`.${ns.b('node')}.${ns.is('active')}:last-child`)
```
This code has a problem with its logic, but the original purpose was to scroll to the bottom element. We could modify the code to retain the original logic.

Comment (rzzf) [reply packages/components/cascader-panel/src/index.vue]: I’m not quite sure what you mean. 
`:last-child` was the cause of #23201, and I’ve already removed it. 
Increasing the priority of `in-active-path` is intended to address #20873. 
Is there anything else I need to change?

Comment (btea) [reply packages/components/cascader-panel/src/index.vue]:
```ts
let activeNode = menuElement.querySelector(`.${ns.b('node')}.in-active-path`)
if (!activeNode) {
  const activeElements = menuElement.querySelectorAll(`.${ns.b('node')}.${ns.is('active')}`)
  activeNode = activeElements[activeElements.length - 1]
}
```
Perhaps it should be changed like this.

Comment (rzzf) [reply packages/components/cascader-panel/src/index.vue]: I see, thank you.

**Review by btea — APPROVED** [review]

**Review by Dsaquel — APPROVED** [review]
