### PR TITLE
[types.ts] Fixed Nullable type for RefElement

### LINKED ISSUE #2725: [Bug Report] Cannot find name "Nullable"
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
MacOS Big Sur 11.5 

### Vue version
3.1.5

### Reproduction Link
https://github.com/Oleksii14/element-plus-ts-bug

### Steps to reproduce
Sorry for the fake repro link!

I am not sure I can reproduce it locally in a new project.

The issue description:
There is a Vue 3 and TypeScript project set up via Vue CLI. We're using Element Plus v1.0.2-beta.63

We have started to get the TS error recently from the file: node_modules/element-plus/lib/utils/types.ts

`export type RefElement = Nullable<HTMLElement>` - for this line. I think TS does not see the types from declaration files. Can you advice something?

P.S. `skipLibCheck` property in `tsconfig.json` is set to `true`

### What is Expected?
No TS error

### What is actually happening?
TS throws an error from the library

**UPD**: repro link added

### PR DESCRIPTION
**Pull request by PxlBuzzard**
Fixed #2725. Confirmed to work with a local build.

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/utils/types.ts [hunk 1]
```diff
@@ -21,4 +21,4 @@ export type PartialReturnType<T extends (...args: unknown[]) => unknown> = Parti
 
 export type SFCWithInstall<T> = T & Plugin
 
-export type RefElement = Nullable<HTMLElement>
+export type RefElement = HTMLElement | undefined
```
Comment (JeremyWuuuuu) [inline packages/utils/types.ts:24]: Can we put a `null` here after `undefined` might be more accurate.

Comment (PxlBuzzard) [reply packages/utils/types.ts]: Sure, I changed it.

**Review by jw-foss — APPROVED** [review]
