### PR TITLE
fix(components): [dropdown-item] remove redundant attributes

### LINKED ISSUE #18337: [Component] [dropdown-item] Dropdown item duplicates id attribute when the divided flag is set
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.8`
- Element Plus Version: `2.8.3`
- Browser / OS: `Firefox 130 / Ubuntu 24.04`
- Build Tool: `Vite`

### Related Component

- `el-dropdown-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkcm9wZG93biA9IHJlZigpXG5sZXQgZGVidWdPdXRwdXQgPSByZWYoJycpXG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIGRyb3Bkb3duLnZhbHVlLmhhbmRsZU9wZW4oKVxuICBjb25zdCBzZWNvbmRJdGVtID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbChcIiNzZWNvbmRJdGVtXCIpXG4gIGZvciAoY29uc3Qgbm9kZSBvZiBzZWNvbmRJdGVtKSB7XG4gICAgZGVidWdPdXRwdXQudmFsdWUgKz0gbm9kZS5vdXRlckhUTUwgKyAnXFxuJ1xuICB9XG59KVxuXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1kcm9wZG93biByZWY9XCJkcm9wZG93blwiIHRyaWdnZXI9XCJjbGlja1wiIHN0eWxlPVwibWFyZ2luLWJvdHRvbTogMTUwcHg7XCI+XG4gICAgICA8ZWwtYnV0dG9uPk9wZW4gZHJvcGRvd248L2VsLWJ1dHRvbj5cbiAgICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAxPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGlkPVwic2Vjb25kSXRlbVwiIGRpdmlkZWQ+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1kcm9wZG93bj5cbiAgICA8aDM+RWxlbWVudHMgd2l0aCBpZCAjc2Vjb25kSXRlbTwvaDM+XG4gICAgPHByZT57eyBkZWJ1Z091dHB1dCB9fTwvcHJlPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMy9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0AyLjguMy90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUAzLjUuOC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAMy41LjgvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4zL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Render an `el-dropdown` with an `el-dropdown-item`, which has:
- The `divided` flag set
- An `id` attribute

### Example code

```vue
<el-dropdown ref="dropdown" trigger="click">
  <el-button>Open dropdown</el-button>
  <template #dropdown>
    <el-dropdown-menu>
      <el-dropdown-item>Action 1</el-dropdown-item>
      <el-dropdown-item id="secondItem" divided>Action 2</el-dropdown-item>
    </el-dropdown-menu>
  </template>
</el-dropdown>
```

### What is Expected?

There is a single DOM element with the provided `id`.

Example: There should be a single element with id `secondItem`.

### What is actually happening?

There are 2 DOM elements with the same `id`.

Example: There are 2 elements with id `secondItem`, one with class `el-dropdown-menu__item--divided`, and one with class `el-dropdown-menu__item`.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by betavs**
Please make sure these boxes are checked before submitting your PR, thank you!

close #18337 

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/dropdown/src/dropdown-item-impl.vue [hunk 1]
```diff
@@ -3,7 +3,6 @@
     v-if="divided"
     role="separator"
     :class="ns.bem('menu', 'item', 'divided')"
-    v-bind="$attrs"
```
Comment (btea) [inline packages/components/dropdown/src/dropdown-item-impl.vue:6]: Maybe we shouldn't delete directly, but just exclude the `id`.

Comment (betavs) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: It stands to reason that this would lead to destructive updates. But is it reasonable for `separator` and `menuiitem` to bind the same attributes?

Comment (btea) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: It has been so long that it is hard to clearly understand the considerations at that time. However, I personally think that binding the same attributes may facilitate the clear display of the grouping relationship between the item and the corresponding divider?

Comment (betavs) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: I have an idea: extend `divided` to support `Object` type for attribute configuration. Is it possible?

Comment (btea) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: To me, this seems feasible, but we could probably get more opinions.  cc @element-plus/backers

Comment (makedopamine) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: Removing this line looks good to me. I noticed [the test case](https://github.com/element-plus/element-plus/pull/5779/files#diff-fb8a1dec280aaa963d1509eac461358cc305563bdf74d743c58401ad6ee5745aR491) didn't cover this line of code, so the author might add the code no particular reason.

BTW, I can't receive a notification when you mentioned backers. @btea

Comment (tolking) [reply packages/components/dropdown/src/dropdown-item-impl.vue:6]: I also support deleting this line of code, and binding attributes to `item` and `divided` feels strange

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]
Although the impact may be small, this seems to be a breaking change. Should we mark it somewhere?
