### PR TITLE
fix(components): [select] iOS keyboard not appear when focus

### LINKED ISSUE #11415: [Component] [select, tree-select] EL-Select 不开多选，在IOS系统中获取焦点不会弹出软键盘
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome 109.0.5414.120`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-tree-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgOnJlc2VydmUta2V5d29yZD1cImZhbHNlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

在IOS 手机上，点击select

### What is Expected?

弹出软键盘

### What is actually happening?

未弹出软键盘

### Additional comments

和多选属性有关，开启则正常，不开则不正常

### PR DESCRIPTION
**Pull request by MrWeilian**
fix: [#11415](https://github.com/element-plus/element-plus/issues/11415)

问题原因：
iOS系统限制非用户行为的 `focus`，仅有用户行为直接触发 或者 用户行为后的 **回调函数同步触发 `.focus()`** 才能弹起键盘。当前 `el-input` 组件 `readonly` 属性当激活下拉框的时候会被改成 `false`，由于异步更新关系，再触发 `el.focus()` 就会被系统拦截。

参考链接：
1. https://github.com/ant-design/ant-design-mobile/issues/5256
2. https://stackoverflow.com/questions/6287478/mobile-safari-autofocus-text-field

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by MrWeilian** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgZmlsdGVyYWJsZVxuICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgOnJlc2VydmUta2V5d29yZD1cImZhbHNlXCJcbiAgICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gID5cbiAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgLz5cbiAgPC9lbC1zZWxlY3Q+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZjxzdHJpbmdbXT4oW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdIVE1MJyxcbiAgICBsYWJlbDogJ0hUTUwnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdDU1MnLFxuICAgIGxhYmVsOiAnQ1NTJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnSmF2YVNjcmlwdCcsXG4gICAgbGFiZWw6ICdKYXZhU2NyaXB0JyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTExNDk4LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTE0OTgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctMTE0OTgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTE0OTgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

**Comment by MrWeilian** [comment]
参考了设置 `multiple` 的情况，应该是让用户点了原生 `input` 先触发键盘弹起，等执行完 `readonly` 那个计算属性的更新时将焦点 `focus` 到 `el-input` 那里面的 `input` 中。

**Comment by chenxch** [comment]
键盘是弹出来了👍🏻，但是表现上存在一些问题哦

**Comment by MrWeilian** [comment]
> 键盘是弹出来了👍🏻，但是表现上存在一些问题哦

大佬好，什么问题，我跟进下😂

**Comment by chenxch** [comment]
https://user-images.githubusercontent.com/23251408/218263076-636eb2d2-039c-4d73-9afd-9bdb752afc65.MP4

一个是选择后回出现一个下拉框的抖动，类似收齐又展开；然后多选似乎出bug了

File: packages/components/select/src/select.vue [hunk 1]
```diff
@@ -30,13 +30,13 @@
           @mouseleave="inputHovering = false"
         >
           <div
-            v-if="multiple"
+            v-if="multiple || isIOS"
```
Comment (jw-foss) [inline packages/components/select/src/select.vue:33]: **Question:** I don't know why this is related with the platform, this is not even the dropdown field.

File: packages/components/select/src/select.vue [hunk 2]
```diff
@@ -30,13 +30,13 @@
...
             ref="tags"
             :class="nsSelect.e('tags')"
             :style="selectTagsStyle"
           >
             <span
-              v-if="collapseTags && selected.length"
+              v-if="collapseTags && selected.length && !isIOS"
```
Comment (jw-foss) [inline packages/components/select/src/select.vue:39]: Same here, you were just removing the selected tag 🤔 I suspect that you were barking up the wrong tree.

File: packages/components/select/src/select.vue (hunk 1 above)
Comment (MrWeilian) [reply packages/components/select/src/select.vue:33]: hello, this issue is cause by the iOS system that prohibits the `focus` event triggered by non-user actions or asynchronous triggered. You can get more info by these following: 
1. https://github.com/ant-design/ant-design-mobile/issues/5256
2. https://stackoverflow.com/questions/6287478/mobile-safari-autofocus-text-field
image

the `readonly` attribute like this picture1 is a `computed` that change by `visible` and other variable(like picture2).
image
image

if `readonly===true` that we can't focus the input element, so when we focus it must be a `false` value, as well as the framework is update async. So the focus will fail.

so, I just fix this problem by letting users click the native input to pull up the keyboard.

**Comment by MrWeilian** [comment]
> RPReplay_Final1676125311.MP4 
> 一个是选择后回出现一个下拉框的抖动，类似收齐又展开；然后多选似乎出bug了

@jw-foss @chenxch hello, I have solved this problem in the new commit. And I added a native input to trigger keyboard  instead of to use the `multiple native input` when device is iOS and select is `filterable`.

File: packages/components/select/src/useSelect.ts [hunk 3]
```diff
@@ -296,6 +297,7 @@ export const useSelect = (props, states: States, ctx) => {
         if (props.filterable) {
           states.filteredOptionsCount = states.optionsCount
           states.query = props.remote ? '' : states.selectedLabel
+          iOSInput.value?.focus()
```
Comment (MrWeilian) [inline packages/components/select/src/useSelect.ts:300]: this code is used to focus the native input when user click the suffix icon instead of directly clicking native input.

**Comment by MrWeilian** [comment]
https://user-images.githubusercontent.com/30046649/219687417-9ddc654a-7b3f-4327-ae5e-5d4813416115.MOV

File: packages/components/select/src/useSelect.ts (hunk 3 above)
Comment (jw-foss) [reply packages/components/select/src/useSelect.ts:300]: @MrWeilian we should use 

```ts
iOSInput.value?.focus?.()
```

here to prevent incorrect invocation.

File: packages/components/select/src/useSelect.ts [hunk 4]
```diff
@@ -772,6 +774,7 @@ export const useSelect = (props, states: States, ctx) => {
   const blur = () => {
     states.visible = false
     reference.value?.blur()
+    iOSInput.value?.blur()
```
Comment (jw-foss) [inline packages/components/select/src/useSelect.ts:777]: Same here.

**Review by jw-foss — APPROVED** [review]
The code LGTM, /cc @chenxch could you help verify this? Thanks :bow:

File: packages/components/select/src/useSelect.ts (hunk 3 above)
Comment (MrWeilian) [reply packages/components/select/src/useSelect.ts]: hh, thank you so much for your suggestion, I am fixed it

**Review by jw-foss — APPROVED** [review]

**Comment by MrWeilian** [comment]
@chenxch 大佬 cc 👀

**Comment by chenxch** [comment]
> @chenxch 大佬 cc 👀

晚点我看一下哈

**Review by chenxch — APPROVED** [review]
