### PR TITLE
chore(build): fix cdn process error

### LINKED ISSUE #16861: [Component] [tour] CDN 下使用el-tour 会报错aria.ts:22  Uncaught (in promise) ReferenceError: process is not defined
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.3`
- Browser / OS: ` Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1 Edg/124.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-tour`

### Reproduction Link

[Docs](https://element-plus.org/)

### Steps to reproduce

调试 发布均不能正常

### What is Expected?

正常运行

### What is actually happening?

控制台报错

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by warmthsea**
fix: https://github.com/element-plus/element-plus/issues/16861

# build dist file:

## Before: 
c6b0059dbe75e0b19673ef6fb96a31c4

## After:
31fc054e055fcd424c9763aa9c59cd06

### CODE REVIEW

File: internal/build/src/tasks/full-bundle.ts [hunk 1]
```diff
@@ -1,6 +1,7 @@
 import path from 'path'
 import { nodeResolve } from '@rollup/plugin-node-resolve'
 import { rollup } from 'rollup'
+import replace from '@rollup/plugin-replace'
```
Comment (plainheart) [inline internal/build/src/tasks/full-bundle.ts:4]: It seems the rollup replace plugin is a ghost dependency. It may be better to add it to the package.json.

**Review by plainheart — APPROVED** [review]

**Review by btea — APPROVED** [review]
