### PR TITLE
fix(components): [select] filter shake

### LINKED ISSUE #12099: [Component] [select] select框高度闪烁
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome 111.0.5563.64 / macOs 12.5`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJ0cnVlXCJcbiAgICAgID4gICAgXG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJ0ZWFjaGVyMVwiIHZhbHVlPVwiMVwiPjwvZWwtb3B0aW9uPlxuICAgICAgICBcbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cInRlYWNoZXJcIiB2YWx1ZT1cIjJcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PiAgICBcbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuICBpbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB2YWx1ZSA9IHJlZihbJzEnLCAnMiddKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

打开最小复现地址

### What is Expected?

选择框高度保持一致

### What is actually happening?

选择框高度发生跳动

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by chenxch**
close #12099 

[before](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiXG4gICAgICA+ICAgIFxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwidGVhY2hlcjJcIiB2YWx1ZT1cIjFcIj48L2VsLW9wdGlvbj5cbiAgICAgICAgXG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJ0ZWFjaGVyXCIgdmFsdWU9XCIyXCI+PC9lbC1vcHRpb24+XG4gICAgICA8L2VsLXNlbGVjdD4gICAgXG4gIDwvZGl2PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpc2FibGVkID0gIWRpc2FibGVkXCI+ZGlzYWJsZWQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZhbHVlID0gcmVmKFsnMScsICcyJ10pXG5jb25zdCBkaXNhYmxlZCA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

[after](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAgICAgICA6ZGlzYWJsZWQ9XCJkaXNhYmxlZFwiXG4gICAgICA+ICAgIFxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwidGVhY2hlcjJcIiB2YWx1ZT1cIjFcIj48L2VsLW9wdGlvbj5cbiAgICAgICAgXG4gICAgICAgIDxlbC1vcHRpb24gbGFiZWw9XCJ0ZWFjaGVyXCIgdmFsdWU9XCIyXCI+PC9lbC1vcHRpb24+XG4gICAgICA8L2VsLXNlbGVjdD4gICAgXG4gIDwvZGl2PlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImRpc2FibGVkID0gIWRpc2FibGVkXCI+ZGlzYWJsZWQ8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG4gIGltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHZhbHVlID0gcmVmKFsnMScsICcyJ10pXG5jb25zdCBkaXNhYmxlZCA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEyMTA2LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

The reason is that the input box is not canceled in the filter mode, and the width of the input box just triggers the threshold, which causes rezize to be triggered all the time. I think the input box should not exist in the disable mode.

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by HeftyKoo — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
@chenxch Can you provide a recording of the problem situation? Thanks!

**Comment by chenxch** [comment]
https://user-images.githubusercontent.com/23251408/226086249-9e1e167f-4a92-4a45-9ce3-4bd9c197a652.mov

/cc @ryuhangyeong

**Review by ryuhangyeong — APPROVED** [review]

**Comment by btea** [comment]
After the modification, there still seems to be a problem. Open the following [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LXdyYXBcIj5cbiAgICAgIDxlbC1zZWxlY3RcbiAgICAgICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICAgICAgZmlsdGVyYWJsZVxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBlbnRlciBhIGtleXdvcmRcIlxuICAgICAgPiAgICBcbiAgICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cInRlYWNoZXIyXCIgdmFsdWU9XCIxXCI+PC9lbC1vcHRpb24+XG4gICAgICAgIFxuICAgICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwidGVhY2hlcjFcIiB2YWx1ZT1cIjJcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PiAgICBcbiAgPC9kaXY+XG4gIDxlbC1idXR0b24gQGNsaWNrPVwiZGlzYWJsZWQgPSAhZGlzYWJsZWRcIj5kaXNhYmxlZDwvZWwtYnV0dG9uPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbiAgaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgdmFsdWUgPSByZWYoWycxJywgJzInXSlcbmNvbnN0IGRpc2FibGVkID0gcmVmKGZhbHNlKVxuPC9zY3JpcHQ+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMjEwNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMjEwNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMjEwNi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==) and you will see that it has been flashing.

**Comment by chenxch** [comment]
> link

image

I didn't show up here, could it have something to do with the platform, can I record the screen?

**Comment by btea** [comment]
win10 + chrome 111.0.5563.65
sel

**Comment by chenxch** [comment]
Received, I will use the window device to check tomorrow

**Comment by chenxch** [comment]
@btea Do you think it makes sense to use debounce here?

File: packages/components/select/src/select.vue [hunk 1]
```diff
@@ -141,7 +141,7 @@
               </span>
             </transition>
             <input
-              v-if="filterable"
+              v-if="filterable && !selectDisabled"
```
Comment (MrWeilian) [inline packages/components/select/src/select.vue:144]: hello啊xc大佬，我感觉这个问题应该是 `marginLeft` 的计算影响的，也就是代码的 `152-155` 行。
debug 多次发现是 `input` 的总体宽度变化问题。但是它的 `width` 值是固定的，我这边是 `0.126582%`，而真正宽度相关有变化的是 `marginLeft` 值，主要是受 `tagInMultiLine` 这个影响。 
image

我推测原本代码设计把 `width` 计算成 `0.xxx%` 是计算当前不换行的剩余空间，所以更确定问题应该就是 `marginLeft` 这边产生的。

看它的源码好像确实有点问题：
image
我认为 `input.style.height` 他是 inner 的值，所以如果要判断这个高度条件 `Number.parseFloat(input.style.height) >= sizeInMap` 是不是应该加上 2 呢？也就是 `Number.parseFloat(input.style.height) + 2 >= sizeInMap` 。这样改的话 demo 的问题（包括 `window` 环境）好像就解决了...

Comment (chenxch) [reply packages/components/select/src/select.vue:144]: 确实如你所说的，我也一直再找是哪里计算导致它在一个临界值范围出现这样的抖动的问题👍

Comment (MrWeilian) [reply packages/components/select/src/select.vue:144]: 感觉要么搞 `prefixWidth`，要么搞 `tagInMultiLine` 应该都可以解决。只是代码里很多直接用魔术数字去计算的，不敢随便改...

Comment (chenxch) [reply packages/components/select/src/select.vue:144]: marginLeft: `${prefixWidth}px` ,  直接固定这个，将prefixWidth值改为6好像也没啥问题了，感觉没必要去算

Comment (chenxch) [reply packages/components/select/src/select.vue:144]: 这个控件好像还有其他问题，prefix插槽也会有问题样式。。。

Comment (MrWeilian) [reply packages/components/select/src/select.vue:144]: hhh 我还在研究能不能完全用 `flex` 布局解决，把 `filterable` 的这个 `input`元素 自适应、换行的行为交给 `flex`。
[flex布局遇到input无法自适应的坑](https://zhuanlan.zhihu.com/p/59471707)

Comment (chenxch) [reply packages/components/select/src/select.vue:144]: 明天再研究吧，赶紧先睡觉了😴

File: packages/components/select/src/useSelect.ts [hunk 2]
```diff
@@ -577,7 +578,7 @@ export const useSelect = (props, states: States, ctx) => {
   const handleResize = () => {
     resetInputWidth()
     tooltipRef.value?.updatePopper?.()
-    if (props.multiple) resetInputHeight()
+    props.multiple && nextTick(() => resetInputHeight())
```
Comment (btea) [inline packages/components/select/src/useSelect.ts:581]: `resetInputHeight` has used nextTick internally, is it necessary to add nextTick here?

File: packages/components/select/src/select.vue (hunk 1 above)
Comment (MrWeilian) [reply packages/components/select/src/select.vue:144]: > 这个控件好像还有其他问题，prefix插槽也会有问题样式。。。

哈咯啊，你说的问题样式是这种吗？
image

[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCB2YWx1ZSA9IHJlZihbXSlcbmNvbnN0IHZhbHVlMSA9IHJlZihbJ+mAiemhuTEnLCAn6YCJ6aG5MicsICfpgInpobkzJ10pXG5jb25zdCB2YWx1ZTIgPSByZWYoWyfpgInpobkxJywgJ+mAiemhuTInLCAn6YCJ6aG5MycsICfpgInpobk0JywgJ+mAiemhuTUnXSlcblxuY29uc3Qgb3B0aW9ucyA9IFt7XG4gICAgdmFsdWU6ICfpgInpobkxJyxcbiAgICBsYWJlbDogJ+m7hOmHkeezlSdcbiAgfSwge1xuICAgIHZhbHVlOiAn6YCJ6aG5MicsXG4gICAgbGFiZWw6ICflj4znmq7lpbYnXG4gIH0sIHtcbiAgICB2YWx1ZTogJ+mAiemhuTMnLFxuICAgIGxhYmVsOiAn6Jq15LuU54WOJ1xuICB9LCB7XG4gICAgdmFsdWU6ICfpgInpobk0JyxcbiAgICBsYWJlbDogJ+m+memhu+mdoidcbiAgfSwge1xuICAgIHZhbHVlOiAn6YCJ6aG5NScsXG4gICAgbGFiZWw6ICfljJfkuqzng6TpuK0nXG4gIH1dXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8cD4xLiBwcmVmaXgg5Y2g5o2u56m66Ze077yMaW5wdXTpgJrov4forqHnrpcgbWFyZ2luIOWQjuenu+WKqCA8L3A+XG4gIDxlbC1zZWxlY3Qgdi1tb2RlbD1cInZhbHVlXCIgbXVsdGlwbGUgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIuivt+mAieaLqVwiPlxuICAgIDx0ZW1wbGF0ZSAjcHJlZml4PlxuICAgICAgPHNwYW4+cHJlZml4LXByZWZpeDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cbiAgPHA+Mi4g6YCJ5Lit5LiJ5Liq77yM5L2GIHRhZyDmsqHmjaLooYwgPC9wPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZTFcIiBtdWx0aXBsZSBmaWx0ZXJhYmxlIHBsYWNlaG9sZGVyPVwi6K+36YCJ5oupXCI+XG4gICAgPHRlbXBsYXRlICNwcmVmaXg+XG4gICAgICA8c3Bhbj5wcmVmaXgtcHJlZml4PC9zcGFuPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCI+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuICA8cD4zLiB0YWcg5o2i6KGMIDwvcD5cbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWUyXCIgbXVsdGlwbGUgZmlsdGVyYWJsZSBwbGFjZWhvbGRlcj1cIuivt+mAieaLqVwiPlxuICAgIDx0ZW1wbGF0ZSAjcHJlZml4PlxuICAgICAgPHNwYW4+cHJlZml4LXByZWZpeDwvc3Bhbj5cbiAgICA8L3RlbXBsYXRlPlxuICAgIDxlbC1vcHRpb25cbiAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgIDprZXk9XCJpdGVtLnZhbHVlXCJcbiAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiPlxuICAgIDwvZWwtb3B0aW9uPlxuICA8L2VsLXNlbGVjdD5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

应该是中间迭代被改没了，当时加 `tagInMultiLine` 这个判断条件的时候也处理了包裹 `el-tags` 的 `span` 的，可以看看：[#1682](https://github.com/element-plus/element-plus/pull/1682/files)

image

本地恢复了下之前的代码应该是好的：
image

然后我觉得如果是现在这个情况，要么就一起修了，要么就直接把 `tagInMultiLine` 这个先去掉，因为只要不在换行的时候动态改宽度就不会跳动了，应该可以保证大部分功能正常使用。剩下的再另外去搞 `prefix` 的问题。

File: packages/components/select/src/useSelect.ts (hunk 2 above)
Comment (chenxch) [reply packages/components/select/src/useSelect.ts]: done.

File: packages/components/select/src/select.vue (hunk 1 above)
Comment (Frank11223) [reply packages/components/select/src/select.vue:149]: @chenxch @MrWeilian 两位大佬，我感觉这个属性tagInMultiLine用宽度去计算还是比较合适的。我认为只有两种情况：第一种在一行显示，这种又分成两种情况：第一种（tags+input+margin(默认的)<=maxWidth），第二种（tags+input+margin(perfixWidth)<=maxWidth）。第二种同理。
所以我认为无论tagInMultiLine的值等于true/false,只要在一行显示那必然要满足（tagsWidth+inputWidth+inputMargin(默认的/prefixWidth)<=maxWidth），反之则必然换行。（手动狗头）

Comment (MrWeilian) [reply packages/components/select/src/select.vue:149]: 对，从准确度上来说计算宽度可能更直观准确，你这个方案也可以是解决这个闪烁的问题的。但是就像我之前 comment 的，恒定加默认`marginLeft: 15` 去计算是否换行可能会违背这个换行的设计。而且我也不知道会不会某个有临界值再次导致跳动的场景。

不过我觉得你这个修改理论上不会出现跳动的情况，因为有 prefix 的场景最小 marginLeft 是 30，恒定加 15 也不用怕因为换行的 margin 变小而又变成不换行了的这种情况，这一点是值得肯定的。

但是恒定加 15 确实有点问题，我搞了个刚好能触发 `tagInMultiLine` 为 `true` 的场景。（随便试了一个 demo，已经用了你那段改动的代码）：
image
这时候的表现形式是 `filter` 的 `input` 是没换行的（但其实应该换行）：
image
处于这样的情况下，由于 input 的宽度极小，用户的筛选输入会一点都看不见，最多看见光标在闪烁。（当然 element-ui 好像也有这个问题【手动狗头】）

我个人觉得，要改这个问题最好还是把换行行为完全交给 `flex` 去处理，不去动态改变一些影响宽度的属性导致 flex 在换行和不换之间变化。

Comment (Frank11223) [reply packages/components/select/src/select.vue:149]: @MrWeilian 大佬说的有理，如果交给`flex`感觉要修改布局，把那个`input`放到包裹`tags`的`span`里面，这样每次`input`都会在最后一个`tags`后面，但是如果这样写`input`就不能和其它的功能共用了。
 对于上面那个换行之后又折上去那个问题，我在测试的时候也发现了, 虽然`input`框很小，但是不影响，因为有提示框。
 从用户的角度去看，他们可能第一眼去注意下面那个醒目的提示框而忽略输入框里面的东西，这可能就是element-ui不去管这个问题的原因【再次狗头】
 如果感觉这是个问题，那么我感觉给这个`input`加个最小宽度就能解决。

Comment (Frank11223) [reply packages/components/select/src/select.vue:149]: @MrWeilian 大佬说的有理，如果交给`flex`感觉要修改布局，把那个`input`放到包裹`tags`的`span`里面，这样每次`input`都会在最后一个`tags`后面，但是如果这样写`input`就不能和其它的功能共用了。
 对于上面那个换行之后又折上去那个问题，我在测试的时候也发现了, 虽然`input`框很小，但是不影响，因为有提示框。
 从用户的角度去看，他们可能第一眼去注意下面那个醒目的提示框而忽略输入框里面的东西，这可能就是element-ui不去管这个问题的原因【再次狗头】
 如果感觉这是个问题，那么我感觉给这个`input`加个最小宽度就能解决。

Comment (MrWeilian) [reply packages/components/select/src/select.vue:149]: 😄 最小宽度我也觉得可以有

Comment (acyza) [reply packages/components/select/src/select.vue:149]: > marginLeft: `${prefixWidth}px` , 直接固定这个，将prefixWidth值改为6好像也没啥问题了，感觉没必要去算

没加prefix插槽的情况下，prefixWidth好像就是个固定值 https://github.com/element-plus/element-plus/blob/60ec38a69397a8d2dd6382d27880e27a13cf062a/packages/components/select/src/useSelect.ts#L60

Comment (chenxch) [reply packages/components/select/src/select.vue:149]: 是的

**Comment by lin52025i** [comment]
* 演示链接 [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwicG9zaXRpb246IHJlbGF0aXZlXCI+XG4gICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlOyBwb3NpdGlvbjogYWJzb2x1dGU7IHRvcDogMFwiPlxuICAgICAgc2hha2U6XG4gICAgICA8ZWwtc2VsZWN0XG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICAgIG11bHRpcGxlXG4gICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICAgIGRlZmF1bHQtZmlyc3Qtb3B0aW9uXG4gICAgICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlOyBwb3NpdGlvbjogYWJzb2x1dGU7IHRvcDogMTAwcHhcIj5cbiAgICAgIG5vIHNoYWtlOlxuICAgICAgPGVsLXNlbGVjdFxuICAgICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgIGFsbG93LWNyZWF0ZVxuICAgICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIkNob29zZSB0YWdzIGZvciB5b3VyIGFydGljbGVcIlxuICAgICAgICBjbGFzcz1cImZpeC1zaGFrZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcblxuY29uc3QgdmFsdWUgPSByZWY8c3RyaW5nW10+KFtcIkhUTUxcIiwgXCJDU1NcIiwgXCJKYXZhU2NyaXB0XCIsIFwiVnVlXCIsIFwiVnVleFwiXSk7XG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6IFwiSFRNTFwiLFxuICAgIGxhYmVsOiBcIkhUTUxcIixcbiAgfSxcbiAge1xuICAgIHZhbHVlOiBcIkNTU1wiLFxuICAgIGxhYmVsOiBcIkNTU1wiLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IFwiSmF2YVNjcmlwdFwiLFxuICAgIGxhYmVsOiBcIkphdmFTY3JpcHRcIixcbiAgfSxcbiAge1xuICAgIHZhbHVlOiBcIlZ1ZVwiLFxuICAgIGxhYmVsOiBcIlZ1ZVwiLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IFwiVnVleFwiLFxuICAgIGxhYmVsOiBcIlZ1ZXhcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmVsLXNlbGVjdCB7XG4gIHdpZHRoOiAxMDAlO1xufVxuLmZpeC1zaGFrZSAuZWwtc2VsZWN0X190YWdzIC5lbC1zZWxlY3RfX2lucHV0IHtcbiAgaGVpZ2h0OiAyOHB4O1xuICB3aWR0aDogMTAwJSAhaW1wb3J0YW50O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

> 这里对比 设置了上述的样式和没有设置样式的效果：

https://user-images.githubusercontent.com/87741822/230611491-fbdba813-669e-44f1-8b6c-50e72c6921e8.mov


> 这里面还出现了另一个 bug，我设置了 `default-first-option` 但是我并不能按照预期的方式在创建的时候选中默认的第一项。

**Comment by btea** [comment]
@lin52025iq Maybe you should use this [link](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwicG9zaXRpb246IHJlbGF0aXZlXCI+XG4gICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlOyBwb3NpdGlvbjogYWJzb2x1dGU7IHRvcDogMFwiPlxuICAgICAgc2hha2U6XG4gICAgICA8ZWwtc2VsZWN0XG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZVwiXG4gICAgICAgIG11bHRpcGxlXG4gICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgYWxsb3ctY3JlYXRlXG4gICAgICAgIGRlZmF1bHQtZmlyc3Qtb3B0aW9uXG4gICAgICAgIDpyZXNlcnZlLWtleXdvcmQ9XCJmYWxzZVwiXG4gICAgICAgIHBsYWNlaG9sZGVyPVwiQ2hvb3NlIHRhZ3MgZm9yIHlvdXIgYXJ0aWNsZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBzdHlsZT1cIndpZHRoOiAxMDAlOyBwb3NpdGlvbjogYWJzb2x1dGU7IHRvcDogMTAwcHhcIj5cbiAgICAgIG5vIHNoYWtlOlxuICAgICAgPGVsLXNlbGVjdFxuICAgICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgICBtdWx0aXBsZVxuICAgICAgICBmaWx0ZXJhYmxlXG4gICAgICAgIGFsbG93LWNyZWF0ZVxuICAgICAgICBkZWZhdWx0LWZpcnN0LW9wdGlvblxuICAgICAgICA6cmVzZXJ2ZS1rZXl3b3JkPVwiZmFsc2VcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIkNob29zZSB0YWdzIGZvciB5b3VyIGFydGljbGVcIlxuICAgICAgICBjbGFzcz1cImZpeC1zaGFrZVwiXG4gICAgICA+XG4gICAgICAgIDxlbC1vcHRpb25cbiAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAgIDpsYWJlbD1cIml0ZW0ubGFiZWxcIlxuICAgICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgICAvPlxuICAgICAgPC9lbC1zZWxlY3Q+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gXCJ2dWVcIjtcblxuY29uc3QgdmFsdWUgPSByZWY8c3RyaW5nW10+KFtcIkhUTUxcIiwgXCJDU1NcIiwgXCJKYXZhU2NyaXB0XCIsIFwiVnVlXCIsIFwiVnVleFwiXSk7XG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6IFwiSFRNTFwiLFxuICAgIGxhYmVsOiBcIkhUTUxcIixcbiAgfSxcbiAge1xuICAgIHZhbHVlOiBcIkNTU1wiLFxuICAgIGxhYmVsOiBcIkNTU1wiLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IFwiSmF2YVNjcmlwdFwiLFxuICAgIGxhYmVsOiBcIkphdmFTY3JpcHRcIixcbiAgfSxcbiAge1xuICAgIHZhbHVlOiBcIlZ1ZVwiLFxuICAgIGxhYmVsOiBcIlZ1ZVwiLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IFwiVnVleFwiLFxuICAgIGxhYmVsOiBcIlZ1ZXhcIixcbiAgfSxcbl07XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuLmVsLXNlbGVjdCB7XG4gIHdpZHRoOiAxMDAlO1xufVxuLmZpeC1zaGFrZSAuZWwtc2VsZWN0X190YWdzIC5lbC1zZWxlY3RfX2lucHV0IHtcbiAgaGVpZ2h0OiAyOHB4O1xuICB3aWR0aDogMTAwJSAhaW1wb3J0YW50O1xuICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG59XG48L3N0eWxlPlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEyMTA2LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTIxMDYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=) to test, that including the modification of this pr.

**Comment by hansonfang** [comment]
May I know the estimated time for this pull request to be merged?

**Review by btea — APPROVED** [review]

**Comment by Jibacat** [comment]
waiting for Merged
