### PR TITLE
fix(components): [select-v2] initial value compatibility

### LINKED ISSUE #10701: [Component] [select-v2] el-select-v2组件placeholder不显示
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.22`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.42`
- Build Tool: `Vite`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0LXYyXG4gICAgdi1tb2RlbD1cInZhbHVlXCJcbiAgICBmaWx0ZXJhYmxlXG4gICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgIFxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGluaXRpYWxzID0gWydhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJ11cblxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9KS5tYXAoKF8sIGlkeCkgPT4gKHtcbiAgdmFsdWU6IGBPcHRpb24ke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

当使用el-select-v2 组件时，无multiple属性时，placeholder不生效

### What is Expected?

placeholder 可显示

### What is actually happening?

placeholder 不显示

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by holazz**
closes #10701, closes #10705

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/select-v2/src/select.vue [hunk 1]
```diff
@@ -340,12 +348,29 @@ export default defineComponent({
...
-    const API = useSelect(props, emit)
+    const modelValue = computed(() =>
+      props.multiple
+        ? isArray(props.modelValue)
+          ? props.modelValue
+          : []
+        : isArray(props.modelValue)
+        ? undefined
+        : props.modelValue
+    )
```
Comment (jw-foss) [inline packages/components/select-v2/src/select.vue:359]: I think this can be simplified as:

```ts
const { modelValue, multiple } = props;
const fallback = multiple ? [] : undefined;
// When it is array, we check if this is multi-select.
// Based on the result we get
if (isArray(props.modelValue) {
  return multiple ? modelValue : fallback;
}
return modelValue;
```
I'd also like to suggest that we should not nest ternary operator inside a ternary operator just like the code here.

**Comment by jw-foss** [comment]
@holazz in general this change LGTM, I'd also like to ask you to write a test case for this 👍

File: packages/components/select-v2/src/select.vue (hunk 1 above)
Comment (holazz) [reply packages/components/select-v2/src/select.vue:359]: Thanks for your advice. 👍

**Comment by holazz** [comment]
> @holazz in general this change LGTM, I'd also like to ask you to write a test case for this 👍

I'll add a test case later.

**Comment by holazz** [comment]
@jw-foss I made a little modification based on https://github.com/element-plus/element-plus/pull/10759#discussion_r1032886040 to handle the single-selection case and added a test case, WDYT?

**Review by jw-foss — APPROVED** [review]
