### PR TITLE
fix(components): [image-viewer] avoid triggering scroll wheel events outside the preview area

### LINKED ISSUE #22720: [Component] [image-viewer] image-view 监听鼠标键盘事件绑定问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.23`
- Element Plus Version: `2.11.7`
- Browser / OS: `Chrome 141`
- Build Tool: `Vite`

### Related Component

- `el-image-viewer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIGVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpO1xuY29uc3QgdXJsID1cbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJ1xuY29uc3Qgc3JjTGlzdCA9IFtcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9hLzNmLzMzMDJlNThmOWExODFkMjUwOWYzZGMwZmE2OGIwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8xLzM0LzE5YWE5OGIxZmNiMjc4MWM0ZmJhMzNkODUwNTQ5anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8wLzZmL2UzNWZmMzc1ODEyZTZiMDAyMGI2YjRlOGY5NTgzanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS85L2JiL2UyNzg1OGU5NzNmNWQ3ZDM5MDQ4MzVmNDZhYmJkanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS9kL2U2L2M0ZDkzYTM4MDViM2NlM2YzMjNmNzk3NGU2Zjc4anBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8zLzI4L2JiZjg5M2Y3OTJmMDNhNTQ0MDhiM2I3YTdlYmYwanBlZy5qcGVnJyxcbiAgJ2h0dHBzOi8vZnVzczEwLmVsZW1lY2RuLmNvbS8yLzExLzY1MzViY2ZiMjZlNGM3OWI0OGRkZGU0NGY0YjZmanBlZy5qcGVnJyxcbl1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD5cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCB7XG4gIGZvbnQtc2l6ZTogMzBweDtcbn1cbi5kZW1vLWltYWdlX19lcnJvciAuaW1hZ2Utc2xvdCAuZWwtaWNvbiB7XG4gIGZvbnQtc2l6ZTogMzBweDtcbn1cbi5kZW1vLWltYWdlX19lcnJvciAuZWwtaW1hZ2Uge1xuICB3aWR0aDogMTAwJTtcbiAgaGVpZ2h0OiAyMDBweDtcbn1cbjpkZWVwKC5lbC1pbWFnZS12aWV3ZXJfX3dyYXBwZXIpe1xuICBsZWZ0OiA1MCU7XG4gIG92ZXJmbG93OiBoaWRkZW47XG59XG48L3N0eWxlPlxuPHRlbXBsYXRlPlxuICAgPGVsLWltYWdlXG4gICAgICBzdHlsZT1cIndpZHRoOiAxMDBweDsgaGVpZ2h0OiAxMDBweFwiXG4gICAgICA6c3JjPVwidXJsXCJcbiAgICAgIDp6b29tLXJhdGU9XCIxLjJcIlxuICAgICAgOm1heC1zY2FsZT1cIjdcIlxuICAgICAgOm1pbi1zY2FsZT1cIjAuMlwiXG4gICAgICA6cHJldmlldy1zcmMtbGlzdD1cInNyY0xpc3RcIlxuICAgICAgc2hvdy1wcm9ncmVzc1xuICAgICAgOmluaXRpYWwtaW5kZXg9XCI0XCJcbiAgICAgIGZpdD1cImNvdmVyXCJcbiAgICAvPlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC9kaXN0L2luZGV4LmNzcycsICdodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L1wiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

在页面左侧,预览区域外部滚动鼠标滚轮

### What is Expected?

预览区域内部的图像不响应鼠标滚轮

### What is actually happening?

预览区域内部的图像响应鼠标滚轮

### Additional comments

packages/components/image-viewer/src/image-viewer.vue

290   useEventListener(document, 'wheel', mousewheelHandler)  =>  useEventListener(wrapper.value, 'wheel', mousewheelHandler)

### PR DESCRIPTION
**Pull request by keeplearning66**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #22720

### CODE REVIEW

File: packages/components/image-viewer/src/image-viewer.vue [hunk 1]
```diff
@@ -287,7 +287,7 @@ function registerEventListener() {
 
   scopeEventListener.run(() => {
     useEventListener(document, 'keydown', keydownHandler)
-    useEventListener(document, 'wheel', mousewheelHandler)
+    useEventListener(wrapper.value, 'wheel', mousewheelHandler)
```
Comment (rzzf) [inline packages/components/image-viewer/src/image-viewer.vue]:
```suggestion
    useEventListener(wrapper, 'wheel', mousewheelHandler)
```

**Comment by patienry** [comment]
Updated, thank you for your suggestion. ❤️

**Review by warmthsea — APPROVED** [review]
LGTM

**Review by rzzf — APPROVED** [review]
