### PR TITLE
fix(components): [segmented] fire change event if option not checked

### LINKED ISSUE #16497: [Component] [segmented] Segmented Element
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.14`
- Element Plus Version: `2.7.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `el-segmented`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtc2VnbWVudGVkIHYtbW9kZWw9XCJ2YWx1ZVwiIDpvcHRpb25zPVwic2h1ZmZsZWRPcHRpb25zXCI+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ9XCJ7IGl0ZW0gfVwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiZmxleCBmbGV4LWNvbCBpdGVtcy1jZW50ZXIgZ2FwLTIgcC0yXCI+XG4gICAgICAgICAgPGVsLWljb24gc2l6ZT1cIjIwXCI+XG4gICAgICAgICAgICA8Y29tcG9uZW50IDppcz1cIml0ZW0uaWNvblwiIC8+XG4gICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgIDxkaXY+e3sgaXRlbS5sYWJlbCB9fTwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgPC9lbC1zZWdtZW50ZWQ+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgd2F0Y2ggfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBBcHBsZSxcbiAgQ2hlcnJ5LFxuICBHcmFwZSxcbiAgT3JhbmdlLFxuICBQZWFyLFxuICBXYXRlcm1lbG9uLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoJ0FwcGxlJylcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIGxhYmVsOiAnQXBwbGUnLFxuICAgIHZhbHVlOiAnQXBwbGUnLFxuICAgIGljb246IEFwcGxlLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdDaGVycnknLFxuICAgIHZhbHVlOiAnQ2hlcnJ5JyxcbiAgICBpY29uOiBDaGVycnksXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ0dyYXBlJyxcbiAgICB2YWx1ZTogJ0dyYXBlJyxcbiAgICBpY29uOiBHcmFwZSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnT3JhbmdlJyxcbiAgICB2YWx1ZTogJ09yYW5nZScsXG4gICAgaWNvbjogT3JhbmdlLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdQZWFyJyxcbiAgICB2YWx1ZTogJ1BlYXInLFxuICAgIGljb246IFBlYXIsXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ1dhdGVybWVsb24nLFxuICAgIHZhbHVlOiAnV2F0ZXJtZWxvbicsXG4gICAgaWNvbjogV2F0ZXJtZWxvbixcbiAgfSxcbl1cblxuY29uc3Qgc2h1ZmZsZWRPcHRpb25zID0gcmVmKFsuLi5vcHRpb25zXSlcblxud2F0Y2godmFsdWUsICgpID0+IHtcbiAgc2h1ZmZsZU9wdGlvbnMoKVxufSlcblxuZnVuY3Rpb24gc2h1ZmZsZU9wdGlvbnMoKSB7XG4gIHNodWZmbGVkT3B0aW9ucy52YWx1ZSA9IHNodWZmbGUoWy4uLm9wdGlvbnNdKVxufVxuXG5mdW5jdGlvbiBzaHVmZmxlKGFycmF5OiBhbnlbXSkge1xuICBsZXQgY3VycmVudEluZGV4ID0gYXJyYXkubGVuZ3RoLCByYW5kb21JbmRleFxuXG4gIHdoaWxlIChjdXJyZW50SW5kZXggIT09IDApIHtcbiAgICByYW5kb21JbmRleCA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIGN1cnJlbnRJbmRleClcbiAgICBjdXJyZW50SW5kZXgtLVxuXG4gICAgW2FycmF5W2N1cnJlbnRJbmRleF0sIGFycmF5W3JhbmRvbUluZGV4XV0gPSBbXG4gICAgICBhcnJheVtyYW5kb21JbmRleF0sIGFycmF5W2N1cnJlbnRJbmRleF1dXG4gIH1cblxuICByZXR1cm4gYXJyYXlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

When we clicked same index multiple time, it gets stuck

### What is Expected?

No stuck

### What is actually happening?

When dynamically options are loaded, the preiously clicked index is not being clicked

### Additional comments

I created date array in production, once the user select the date then it regenerates next and previous 3 days in array including today, the default value is the middle one, once the user clicked preios to preios then it gets stuck.

### LINKED ISSUE #19684: [Component] [segmented]The change event is triggered only the first time when I do not bind the selected value using model-value.
Bug Type: **`Component`**

## Environment

- Vue Version: `3.5.13`
- Element Plus Version: `2.9.3`
- Browser / OS: `Chrome 131.0.6778.265`
- Build Tool: `Vite`

### Related Component

- `el-segmented`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwicGxheS1jb250YWluZXJcIj5cbiAgICA8ZGl2PlxuICAgICAgPGVsLXNlZ21lbnRlZFxuICAgICAgICA6bW9kZWwtdmFsdWU9XCJ2YWx1ZVwiXG4gICAgICAgIDpvcHRpb25zPVwib3B0aW9uc1wiXG4gICAgICAgIHNpemU9XCJsYXJnZVwiXG4gICAgICAgIEBjaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIlxuICAgICAgLz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuLy8gY29kZSBoZXJlXG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCdNb24nKVxuXG5jb25zdCBvcHRpb25zID0gWydNb24nLCAnVHVlJywgJ1dlZCcsICdUaHUnLCAnRnJpJywgJ1NhdCcsICdTdW4nXVxuXG5mdW5jdGlvbiBoYW5kbGVDaGFuZ2UodmFsOiBzdHJpbmcpIHtcbiAgY29uc29sZS5sb2codmFsLCAndmFsJylcbn1cbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

1. Open the console. If there is a change event, it will be printed on the console. 
2. Select an unselected item and click twice

### What is Expected?

Because the value of the component binding does not change, the console print should appear for both clicks

### What is actually happening?

Print information appears only once in the console

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by ykcory**
fix: #19684 
fix: #16497

After selecting input, which triggers the change event, I do something: 
1. Determine whether the value bound by the current modelValue is the currently selected value (use getSelect) 
2. If no, cancel the check status of the current item first. 
3. Select the input corresponding to modelValue.

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/segmented/src/segmented.vue [hunk 1]
```diff
@@ -74,10 +74,21 @@ const state = reactive({
...
+  if (!getSelected(item)) {
+    evt.target && ((evt.target as HTMLInputElement).checked = false)
+    if (!segmentedRef.value) return
+    const selectedItemInput = segmentedRef.value.querySelector(
+      '.is-selected input'
+    ) as HTMLInputElement
+    if (selectedItemInput) {
+      selectedItemInput.checked = true
+    }
+  }
```
Comment (Dsaquel) [inline packages/components/segmented/src/segmented.vue]: It seems to follow the radio component on change.
https://github.com/element-plus/element-plus/blob/dev/packages/components/radio/src/use-radio.ts#L37

reason: By default clicking on a radio element will set checked=true without any restriction. Am i wrong ? @ykcory

I think it can be simplified:
```suggestion
  ;(evt.target as HTMLInputElement).checked = value === props.modelValue
```

File: packages/components/segmented/src/segmented.vue [hunk 2]
```diff
@@ -74,10 +74,21 @@ const state = reactive({
   focusVisible: false,
 })
 
-const handleChange = (item: Option) => {
+const handleChange = (item: Option, evt: Event) => {
```
Comment (Dsaquel) [inline packages/components/segmented/src/segmented.vue]:
```suggestion
const handleChange = (evt: Event, item: Option) => {
```

File: packages/components/segmented/src/segmented.vue [hunk 3]
```diff
@@ -21,7 +21,7 @@
           :name="name"
           :disabled="getDisabled(item)"
           :checked="getSelected(item)"
-          @change="handleChange(item)"
+          @change="handleChange(item, $event)"
```
Comment (Dsaquel) [inline packages/components/segmented/src/segmented.vue]:
```suggestion
          @change="handleChange($event, item)"
```

**Review by Dsaquel — COMMENTED** [review]
can you add a test case if possible ?

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]
