### PR TITLE
fix(components): [cascader-panel] lazy return children can't get value

### LINKED ISSUE #9157: [Component] [cascader] cascader级联组件懒加载的时候，如果同时返回子节点(children)，则无法选择值
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.12`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCB0eXBlID0gcmVmKG51bGwpXG5sZXQgaWQgPTBcbmNvbnN0IHByb3BzID0ge1xuICBsYXp5OiB0cnVlLFxuICBsYXp5TG9hZDogYXN5bmMgKG5vZGUsIHJlc29sdmUpID0+IHtcbiAgICBjb25zdCB7IGxldmVsIH0gPSBub2RlXG4gICAgc2V0VGltZW91dCgoKSA9PiB7XG4gICAgICBjb25zdCBub2RlcyA9IEFycmF5LmZyb20oeyBsZW5ndGg6IGxldmVsICsgMSB9KS5tYXAoKGl0ZW0pID0+ICh7XG4gICAgICAgIHZhbHVlOiArK2lkLFxuICAgICAgICBsYWJlbDogYE9wdGlvbiAtICR7aWR9YCxcbiAgICAgICAgbGVhZjogbGV2ZWwgPj0gMixcbiAgICAgIH0pKVxuICAgICAgaWYobGV2ZWw9PT0xKXtcbiAgICAgICAgbm9kZXMucHVzaCh7XG4gICAgICAgICAgdmFsdWU6ICdhYicsXG4gICAgICAgICAgbGFiZWw6ICfnm7TmjqXmlbDmja7niLYnLFxuICAgICAgICAgIGxlYWY6IGZhbHNlLFxuICAgICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgICB7dmFsdWU6ICdhJywgbGFiZWw6ICfnm7TmjqXmlbDmja5BJyxsZWFmOiB0cnVlfSxcbiAgICAgICAgICAgIHt2YWx1ZTogJ2InLCBsYWJlbDogJ+ebtOaOpeaVsOaNrkInLGxlYWY6IHRydWV9XVxuICAgICAgICB9KVxuICAgICAgfVxuICAgICAgcmVzb2x2ZShub2RlcylcbiAgICB9LCAxMDAwKVxuXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPnt7dHlwZX19PC9wPlxuICA8ZWwtY2FzY2FkZXIgdi1tb2RlbD1cInR5cGVcIiA6cHJvcHM9XCJwcm9wc1wiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

使用级联组件，使用lazy，直接返回本身及下级内容（children），会出现问题（参考复现代码）。
级联组件可以正常展示，直接返回的children内容也可以正常展示，但是选择之后值为空.
```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const type = ref(null)
let id =0
const props = {
  lazy: true,
  lazyLoad: async (node, resolve) => {
    const { level } = node
    setTimeout(() => {
      const nodes = Array.from({ length: level + 1 }).map((item) => ({
        value: ++id,
        label: `Option - ${id}`,
        leaf: level >= 2,
      }))
      // 演示在某个节点直接返回子节点
      if(level===1){
        nodes.push({
          value: 'ab',
          label: '直接数据父',
          leaf: false,
          //这里的子节点会导致问题
          children: [
            {value: 'a', label: '直接数据A',leaf: true},
            {value: 'b', label: '直接数据B',leaf: true}]
        })
      }
      resolve(nodes)
    }, 1000)

  }
}
</script>

<template>
  <p>{{type}}</p>
  <el-cascader v-model="type" :props="props" />

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>
```

### What is Expected?

正常返回对应的value

### What is actually happening?

返回空

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by coderchang0105**
fix #9157

closed #9157

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

File: packages/components/cascader-panel/src/store.ts [hunk 1]
```diff
@@ -50,14 +50,23 @@ export default class Store {
...
-    this.allNodes.push(node)
-    node.isLeaf && this.leafNodes.push(node)
+    this.append2AllNodesAndLeafNodes(node)
   }
 
   appendNodes(nodeDataList: CascaderOption[], parentNode: Node) {
     nodeDataList.forEach((nodeData) => this.appendNode(nodeData, parentNode))
   }
 
+  append2AllNodesAndLeafNodes(node: Node) {
```
Comment (btea) [inline packages/components/cascader-panel/src/store.ts:60]: Maybe the number 2 can be removed.

Comment (coderchang0105) [reply packages/components/cascader-panel/src/store.ts]: ok

**Review by btea — APPROVED** [review]
Thanks!

**Review by tolking — APPROVED** [review]
LGTM.

Thanks you for your contribution
