### PR TITLE
fix(components): [focus-trap] input selection

### LINKED ISSUE #10601: [Component] [input] InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `Firefox 106 / Chrome 107`
- Build Tool: `Webpack`

### Related Component

- `el-input`

### Reproduction Link

[Link]()

### Steps to reproduce

After upgrade to 2.2.21 we started getting these errors from clients - a dozen today already on random pages:
```
InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('checkbox') does not support selection.
or
"InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('radio') does not support selection.
```
Stack points to ElFocusTrap. At the moment I'm trying to figure out how to reproduce it. Maybe someone can help

It's definitely related to https://github.com/element-plus/element-plus/commit/d72fd34b58632dc011749b9393d93e12a5e160d5 :
```
      if (element.tagName === 'INPUT') {
        element.setSelectionRange(element.value.length, element.value.length)
        return
      }
```

### What is Expected?

no js errors

### What is actually happening?

js error

### Additional comments

_(empty)_

### LINKED ISSUE #10645: [Style] [select] el-select 无法选中文本
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.21`
- Browser / OS: `null`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJtc2dcIiBmaWx0ZXJhYmxlICAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1. 点击 select
2. 输入内容
3. ctrl + A 或手动选择输入的文本

### What is Expected?

选中的文本有选中样式

### What is actually happening?

选中文本没有任何样式

### Additional comments

2.2.19 版本正常
2.2.20 版本, el-input 和 el-select 都是不正常的
2.2.21 版本, el-input 可以正常选中, el-select 依然无法选中

类似的 el-input 的 issue 在 d72fd34b 已被修复
https://github.com/element-plus/element-plus/pull/10535
但是 el-select 依然有此问题

可能是这3个 git hash 的代码导致此问题
9c85ac73, 5830d076, f77716f1

### PR DESCRIPTION
**Pull request by holazz**
closes #10601

related to #10518, #10384

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by tolking — APPROVED** [review]

**Comment by chenxch** [comment]
The cursor is supposed to be at the end.

**Comment by holazz** [comment]
@chenxch This doesn't seem to be a problem caused by this change, I will investigate it. 🤔

File: packages/components/focus-trap/src/utils.ts [hunk 1]
```diff
@@ -88,10 +88,6 @@ export const tryFocus = (
       isSelectable(element) &&
       shouldSelect
     ) {
-      if (element.tagName === 'INPUT') {
-        element.setSelectionRange(element.value.length, element.value.length)
```
Comment (chenxch) [inline packages/components/focus-trap/src/utils.ts:92]: Because it was in the all-selected state before, it was impossible to judge the cursor position. When this version was optimized, this unit was processed. At that time, only the tag was judged as input, and the judgment of type was ignored.

Comment (holazz) [reply packages/components/focus-trap/src/utils.ts:92]: Hmmm... That does solve the problem, but I don't think we should manually control the cursor position in this case. Maybe we can save it from shifting focus by preventing the default event of `mousedown` of date table cell. I've updated a commit, WDYT?

**Comment by jw-foss** [comment]
Should we include @Giwayume for review this?

**Comment by holazz** [comment]
> Should we include @Giwayume for reviewing this?

That's great, I'd like to hear from Giwayume.

**Comment by Giwayume** [comment]
I can't really think of a problem with the PR in its current state. Whether or not the full text is selected or not when focus is returned to an element is more of a question of usability, not really an issue with accessibility.

**Review by chenxch — APPROVED** [review]
